- lib/jxl/passes_test.cc
The new testdata introduced a failing test in
`PassesTest.RoundtripMultiGroupPasses`
which we fix here.
> fix passes test

- lib/include/jxl/color_encoding.h
Fixes a copy/paste typo so JXL_TRANSFER_FUNCTION_PQ is
properly documented as coming from SMPTE ST 2084.
> jxl/color_encoding.h: fix documented PQ standard

- lib/jxl/dec_cache.cc
- lib/jxl/image.h
- lib/jxl/render_pipeline/low_memory_render_pipeline.cc
- lib/jxl/render_pipeline/render_pipeline_stage.h
- lib/jxl/render_pipeline/render_pipeline_test.cc
- lib/jxl/render_pipeline/stage_patches.cc
- lib/jxl/render_pipeline/stage_patches.h
This PR contains two related commits, one that fixes #1397:
Fix the patch stage when combined with noise.
The patch stage declared to affect the additional noise channels (which
it doesn't). Because of this, the pipeline execution got confused about
the amount of y axis padding that the stage required (as it assumes that
it is the same for all channels for which it matters), resulting in
bogus values for the y position and, thus, in patches being moved by 2
pixels up.
And one that hopefully improves clarity for the rendering pipeline and aids future debugging:
Refactor the low memory rendering pipeline.
The code should now hopefully be more clear and undestandable.
As a nice side effect, this remove a potential race condition and
optimizes rendering of frames partially outside the current …
> Refactor the low memory rendering pipeline and fix patch + noise combination.

- lib/extras/codec_test.cc
Older versions of gMock do not have the overload that does.
> Use the version of testing::Field that does not take the name of the field

- lib/jxl/enc_modular.cc
- lib/jxl/modular/transform/enc_palette.cc
- lib/jxl/modular/transform/palette.h
- lib/jxl/modular/transform/transform.cc
Fixes #1323 
Currently we're not allowing Palette when bitdepth is > 24, but this is a bit overly restrictive. Instead, let's not have such a restriction, but just don't do default delta scaling in this case.
With that restriction relaxed, the encoder can freely use channel palette also in case of float32 images. This PR adds an encode codepath for the case where the lookup table would be too large, doing it the slower way instead.
Also, RCTs are currently not tried in case of float32 (since bitdepth is 32 so there are no spare bits for it), but in case channel palette reduces the effective bitdepth, they can actually be used without issues.
Before, default speed:
Compressed to 16111054 bytes (52.445 bpp).
1920 x 1280, 0.56 MP/s [0.56, 0.56], 1 reps, 4 threads.
After, default speed: …
> relax high bitdepth palette restriction and improve lossless float compression

- doc/software_support.md
Updates the list of software that is using libjxl.
> add ffmpeg, krita, tachiyomi to list of software supporting jxl

- lib/include/jxl/encode.h
- lib/jxl/enc_modular.cc
- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
- lib/jxl/encode_test.cc
- lib/jxl/jpeg/jpeg_data.cc
- lib/jxl/jpeg/jpeg_data.h
- lib/jxl/test_utils.h
- tools/cjxl.cc
- tools/cjxl_ng_main.cc
~~Builds on top of https://github.com/libjxl/libjxl/pull/358 ~~
~~Adds an encoder api return code for the case where the `jbrd` cannot be stored (e.g. because there is too much tail data), but the jpeg image data itself can be recompressed. This is not a fatal error (can still produce a useful jxl that has all the image data and any exif/xmp if there was any), but it's also not just OK (the result is not bit-exact-reconstructible to the original jpeg file).~~
~~Applications that do not know this new return code will likely treat it as an (unknown) encoder error, which is fine (this is what would happen before, when failure to write the `jbrd` would be a fatal encode error).~~
Adds `JxlEncoderGetError` which can be used to check the reason why JXL_ENCODE_ERROR was returned: it could be …
> encoder api: error codes

- lib/include/jxl/decode.h
This PR will hyperlink functions included in the docs so you don't need to search them with Ctrl+F.
> Add Reference Links to Decoder Docs

- lib/jxl/decode.cc
- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
This PR tries to implement the "Part 2: File format" Frame Index Box,
aka 'jxli' box.
Likely it doesn't work yet correctly, but will allow trying to implement
a decoder for it.
> Attempt to implement the frame index box

- ci.sh
This makes sure that not only the last commit in a chain of commits is checked for authors.
At the moment this does not optimize by reducing the number of authors by removing duplicates before running the check; it basically runs the old check for each commit since the common ancestor commit.
> Update AUTHORS check

- lib/include/jxl/encode.h
- lib/jxl/encode.cc
- tools/cjxl.cc
- tools/cjxl_ng_main.cc
The valid range for the rct type is [0,41].
The spec also needs to be updated to require that range.
> fix range check for RCT

- .github/workflows/release.yaml
This might work around some of the issues seen with the built binaries.
> Pin the Windows version for release builds

- tools/djxl_ng_main.cc
This replaces the direct call to jxl::extras::EncodeImagePNM.
> Using jxl::extras::Encoder in djxl_ng

- tools/codec_config.h
Without the change libjxl build fails on this week's gcc-13 snapshot as:
In file included from /build/libjxl/tools/codec_config.cc:6:
/build/libjxl/tools/codec_config.h:17:31: error: 'uint32_t' was not declared in this scope
17 | std::string CodecConfigString(uint32_t lib_version);
|                               ^~~~~~~~
/build/libjxl/tools/codec_config.h:10:1: note: 'uint32_t' is defined in header '<cstdint>';
did you forget to '#include <cstdint>'?
9 | #include <string>
+++ |+#include <cstdint>
10 |
> tools: add missing <stdint.h> header to codec_config.h

- lib/jxl/libjxl.pc.in
- lib/threads/libjxl_threads.pc.in
Add Cflags.private field with proper defined flags. This
allows for the usage of $(pkgconf --static --cflags libjxl)
to produce the proper CFLAGS for static linking. Relies on
pkgconf rather than pkg-config. Otherwise, static libraries
export APIs with dllimport decorations. And it produces the
following errors while static linking:
ld.exe: decode_progressive.cc:(.text+0x1a): undefined reference to '__imp_JxlDecoderCreate'
ld.exe: decode_progressive.cc:(.text+0x53): undefined reference to '__imp_JxlResizableParallelRunnerCreate'
...
ld.exe: decode_progressive.cc:(.text+0x4f): undefined reference to '__imp_JxlResizableParallelRunnerCreate'
ld.exe: decode_progressive.cc:(.text+0x251): undefined reference to '__imp_JxlResizableParallelRunner'
...
Signed-off-by: Biswapriyo Nath …
> pkgconfig: Define JXL_STATIC_DEFINE for static linking

- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_params.h
This addresses another problem in Issue #330, namely if
resampling is selected based on butteraugli distance, then
the butteraugli distance is changed to reflect the expected
distortion on the smaller image. But in the AQ loop we
compare the full sized images, so there we have to use the
original butteraugli distance. For everything other than
the butteraugli comparison (initial quantization, etc.) we
still need to use the modified butteraugli distance.
```
BEFORE:
jxl:kitten:d25        13270   300537    0.1811767   0.161  17.280  14.90736198 …
```
> Fix butteraugli target in AQ loop for resampled images.

- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/jxl_test.cc
BEFORE:
```
Encoding                         kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
-------------------------------------------------------------------------------------------------------------------------------
jxl:tortoise:resampling=2:d1       13270  2561039    1.5439050   0.082  15.676  11.92454147   2.15506849  3.327220929853      0
jxl:tortoise:resampling=2:d4       13270   633621    0.3819741   0.104  15.105  11.97806740   2.75957457  1.054086053395      0
jxl:tortoise:resampling=2:d8       13270   291244    0.1755745   0.112  15.943  13.04184532   4.41013473  0.774307051378      0
jxl:tortoise:resampling=4:d8       13270   211605    0.1275646   0.202  20.137  24.62362862   6.61222334  0.843485865518      0 …
```
> Disable slow AQ search for low butteraugli target with resampling.

- lib/jxl/enc_ans.cc
When we do the float conversion earlier, we fix #1456.
> overflow in EstimateDataBitsFlat

- lib/include/jxl/types.h
- lib/jxl/dec_frame.cc
- lib/jxl/dec_frame.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
- lib/jxl/progressive_split.h
Added test with 4 intermediate passes, 2 for each downsampling
target. For this I had to fix a bug in progressive_splitter that
filled in the last_pass array of the frame header incorrectly.
> Implement kLastPasses progressive detail in the decoder.

- lib/jxl/fast_math_test.cc
This is currently causing errors when Cross-compiling i686-linux-gnu.
> slightly larger float error in a test

- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
After the commit https://github.com/libjxl/libjxl/commit/5a024e5bf5b9b93da698c7f6cb06abb874b73c4c, the jxl decoder in chrome goes into an infinite loop when trying to decoder a raw jxl image. 
This happens in `HandleBoxes` and more precisely this happens when `dec->avail_in == 0` and` dec->box_stage` switches back and forth between `BoxStage::kHeader` and `BoxStage::kCodestream`.
The proposed changed stops the infinite loop and makes the chrome jxl decoder work again. 
(I haven't run any tests yet..)
> prevent infinite loop in box decoding

- CHANGELOG.md
- lib/include/jxl/decode.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
- lib/jxl/frame_header.h
- tools/djxl_ng_main.cc
This commit implements the --downsampling flag from djxl.
Added a function to the public API that can retrieve info about
the downsampling / is_last arrays in the frame header.
Added a JxlDecoderSkipCurrentFrame function to the public API
that can jump to the next frame during progressive decoding.
> Implement partial decoding of progressive JXLs in djxl_ng.

- lib/include/jxl/codestream_header.h
- lib/include/jxl/decode.h
- lib/include/jxl/encode.h
Add note to uses_original_profile that it should not be used for
lossy compression.
Update the documentation of JxlDecoderAddImageFrame to reflect that
pixel buffer is always expected to be in the color profile that is
set by JxlEncoderSetColorEncoding or JxlEncoderSetICCProfile.
> Improve documentation of some API functions.

- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/encode_test.cc
While the checked condition would result in non-optimal compression
ratio, it is allowed by the API and should not crash the calling
application.
> Remove the JXL_CHECK from FindBestQuantizationMaxError.

- lib/jxl/dec_frame.cc
- lib/jxl/dec_frame.h
- lib/jxl/dec_params.h
- lib/jxl/decode.cc
- tools/djxl.cc
- tools/djxl.h
- tools/djxl_ng_main.cc
This change has the same effect as if setting --allow_progressive_steps
to the same value as --allow_partial_files.
If the --allow_partial_files is set to true, then we will always
decode and render as much detail as possible.
> Deprecate the --allow_progressive_steps flag from djxl.

- lib/jxl/enc_quant_weights.cc
- lib/jxl/quant_weights.cc
Fixes #1484.
As far as we are aware, no encoder today produces files with custom AFV
matrices, so this fix should be safe.
> Avoid reading DCT params for custom AFV matrices multiple times.

- lib/include/jxl/decode.h
- lib/jxl/dec_file.cc
- lib/jxl/dec_frame.cc
- lib/jxl/dec_frame.h
- lib/jxl/decode.cc
- lib/jxl/enc_cache.cc
- lib/jxl/enc_patch_dictionary.cc
- lib/jxl/frame_header.h
For JXL_DEC_NEED_MORE_INPUT events, we always consume everything,
except if we are in a signature, box header or the first 4 bytes of
brob/ftyp/jxlp boxes.
For JXL_DEC_BASIC info, we consume input until the end of ImageMetadata,
together with extensions, and we no longer return JXL_DEC_EXTENSIONS.
For JXL_DEC_COLOR_ENCODING, we consume input until end of all headers.
For JXL_DEC_PREVIEW_IMAGE, we consume input until end of preview frame.
For JXL_DEC_FRAME, we consume input until end of frame header.
Still missing is the input handling for the JXL_DEC_FRAME_PROGRESSION
events.
> Improved input handling in the decoder API implementation.

- AUTHORS
- README.md
Checked the link, the PDF is available via HTTPS as well:
http://ds.jpeg.org/whitepapers/jpeg-xl-whitepaper.pdf
vs.
https://ds.jpeg.org/whitepapers/jpeg-xl-whitepaper.pdf
> README.md: HTTP => HTTPS

- lib/jxl/dec_frame.cc
- lib/jxl/dec_frame.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
- lib/jxl/toc.cc
- lib/jxl/toc.h
- lib/jxl/toc_test.cc
This is a continuation of PR #1501.
For JXL_DEC_FRAME_PROGRESSION events, we stop at the end of the
section that was required to produce the progression event.
If the caller of the API does not subscribe to the full image output,
the decoder now stops and returns JXL_DEC_SUCCESS at the last event
that was produced from all of the subscribed ones.
Added tests for input handling for one-shot and streaming input.
The decoder now clears the codestream_copy when it advances the
codestream, so we now only use it as a temporary buffer instead of
the copy of the whole codestream.
> Improved input handling in the decoder API (part 2).

- lib/jxl/dec_frame.cc
- lib/jxl/dec_modular.cc
This fixes the debug test failure.
> Clear render pipeline state before finalizing modular decoding.

- tools/cjxl_ng_main.cc
`JxlEncoderSetICCProfile` was accidentally called twice.
> Fix cjxl_ng for inputs with an ICC profile

- lib/include/jxl/decode.h
- lib/jxl/dec_file.cc
- lib/jxl/dec_frame.h
- lib/jxl/dec_xyb.cc
- lib/jxl/dec_xyb.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_cache.cc
- lib/jxl/enc_patch_dictionary.cc
- lib/jxl/render_pipeline/stage_from_linear.cc
- lib/jxl/render_pipeline/stage_tone_mapping.cc
- lib/jxl/render_pipeline/stage_tone_mapping.h
- lib/jxl/test_utils.h
- tools/djxl_ng_main.cc
This change enables JxlDecoderSetPreferredColorProfile in cases
where the image is xyb encoded and the original color encoding
is not given by an ICC profile.
Added tests for converting back to original profile and to convert
between color profiles given by enums.
Implemented the --color_space flag in djxl_ng using this new functionality.
> Broader application of JxlDecoderSetPreferredColorProfile.

- lib/extras/enc/encode.cc
This is a fix for https://github.com/libjxl/libjxl/issues/1517, at least for `djxl_ng`.
> djxl_ng: allow apng extension

- lib/extras/codec.cc
- lib/extras/enc/encode.h
- lib/extras/enc/pnm.cc
- lib/extras/enc/pnm.h
- lib/extras/packed_image.h
- tools/djxl_ng_main.cc
Extra channels (other then first alpha) are written as separate
images. This is currently implemented only for the pnm encoder.
> Handle extra channels and metadata boxes in djxl_ng.

- .github/ISSUE_TEMPLATE/bug_report.md
This modifies the issue templates to encourage users to
upload .jxl images as .jxl.jpg, in order to be able to upload them
(and viewing them) instead of uploading them as .jxl.gz, where
viewing is not possible.
> Add explantion about uploading .jxl images

- tools/CMakeLists.txt
- tools/args.h
- tools/cmdline.h
- tools/codec_config.cc
- tools/djxl_ng_main.cc
- tools/speed_stats.cc
- tools/speed_stats.h
This change implements the --quiet and --print_read_bytes flag from
djxl and in case of missing output filename it calls the decoder
loop but discards the results.
> Add informative flags to djxl_ng and make output file optional.

- lib/include/jxl/encode.h
- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
- lib/jxl/encode_test.cc
Change the codestream level mechanics in the Codestream API to
allow the encoder to automatically choose level 10 codestreams
based on the information in the basic info. This should be ABI
compatible with the previous behavior, as explicitly setting the
level to 10 should still work, and letting it default to 5 will
work in every case it did before.
> encode: use -1 to let encoder decide level automatically

- tools/CMakeLists.txt
This should fix libvips' CIFuzz and OSS-Fuzz integration. See:
https://oss-fuzz-build-logs.storage.googleapis.com/log-3e7b1372-e642-4766-8b82-58e70c3cd9c6.txt
Resolves: https://github.com/libjxl/libjxl/issues/1564.
> Fix build with `-DJPEGXL_ENABLE_TOOLS=0`

- lib/jxl/enc_frame.cc
- tools/benchmark/benchmark_codec_jxl.cc
Additionally, activate lossless mode in benchmark for d0.0.
Fixes #1568
> Set a minimum butteraugli distance in vardct mode.

- lib/jxl/aux_out.h
- lib/jxl/enc_ans.cc
- lib/jxl/enc_bit_writer.h
- lib/jxl/enc_cache.cc
- lib/jxl/enc_context_map.cc
- lib/jxl/enc_context_map.h
- lib/jxl/enc_file.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_patch_dictionary.cc
- lib/jxl/enc_patch_dictionary.h
- lib/jxl/jxl_test.cc
- lib/jxl/modular/encoding/encoding.cc
- tools/benchmark/benchmark_stats.cc
The whole DC frame is added to kLayerDC, the whole patch reference
frame is added to kLayerDictionary, the padding bits between frames
are added to kLayerHeader, and the context map encoding is added
to the layer it was called from.
With these changes now the sum of layer bits is equal the sum of
compressed bits, and there is a warning added to benchmark stats
if it breaks again in the future.
The number and order of layers is also changed to reflect the current
state of the format.
Experiment on 31 images to see how much of bitsream is DC for some
bitrates:
```
Distance      BPP      DC%
--------------------------
d1.0        1.616    11.7%
d2.0        1.016    16.5%
d4.0        0.607    22.9%
d6.0        0.432    26.3%
d8.0        0.342    29.8%
d12.0       0.230    37.3%
d16.0 …
```
> Fix bit cost accounting in AuxOut.

- lib/jxl/dec_frame.cc
- lib/jxl/frame_header.cc
- lib/jxl/frame_header.h
This can speed up debugging issues with images containing
dc or patch reference frames.
> Add one-line frame header description to decoder on debug level 2.

- lib/jxl/encode.cc
- lib/jxl/roundtrip_test.cc
Legacy `cjxl` already does this. This brings this behavior to the API and `cjxl_ng` as well.
> Replace ICC profiles with an enum representation when appropriate

- lib/extras/dec/jxl.cc
- lib/include/jxl/decode.h
- lib/jxl/dec_xyb.cc
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
- lib/jxl/jxl_test.cc
Removed the limitation from JxlDecoderSetPreferredColorProfile
that the "grayscaleness" of the original and requested colorspaces
must match. Instead we check that the requested output format has
enough channels for color output.
DecodeImageJXL now sets the ppf.info.num_color_channels to match
the requested output color space (which is the original color space
by default), and clears ppf.info.alpha_bits if the accepted formats
can not handle an alpha channel.
> Allow conversion between RGB and Grayscale in djxl.

- lib/jxl/dec_frame.cc
- lib/jxl/dec_group.cc
- lib/jxl/dec_modular.cc
- lib/jxl/dec_modular.h
- lib/jxl/frame_header.cc
- lib/jxl/modular/encoding/encoding.cc
- lib/jxl/modular/modular_image.cc
- lib/jxl/modular/modular_image.h
- lib/jxl/render_pipeline/low_memory_render_pipeline.cc
- lib/jxl/render_pipeline/render_pipeline.cc
- lib/jxl/render_pipeline/simple_render_pipeline.cc
- lib/jxl/render_pipeline/stage_epf.cc
- lib/jxl/render_pipeline/stage_from_linear.cc
- lib/jxl/render_pipeline/stage_noise.cc
- lib/jxl/render_pipeline/stage_to_linear.cc
- lib/jxl/render_pipeline/stage_tone_mapping.cc
- lib/jxl/render_pipeline/stage_write.cc
- lib/jxl/sanitizers.h
* Initialize full image area with RenderPadding if frame is outside image
* Use unaligned store/load in all stages
* Only run per-group render pipeline if modular could decode something
> Fixes for fuzzer bugs.

- lib/jxl/decode.cc
Return JXL_DEC_SUCCESS if requested color space is the same as original,
even if the image is not XYB encoded.
Fixes #1578
> Fix return value of JxlDecoderSetPreferredColorProfile.

- lib/jxl/enc_frame.cc
```
jxl:1:d4.5      13270  1264112    0.7620613  18.634   8.117   4.83199263   1.71316856  1.305539512384      0
jxl:1:d8        13270   856537    0.5163575  20.078   8.037   6.49864912   2.45349616  1.266881165285      0
jxl:1:d16       13270   574334    0.3462333  20.631   8.217  11.38341045   3.64709596  1.262746248261      0
jxl:2:d4.5      13270  1217573    0.7340056  17.392   7.963   4.83199263   1.71316856  1.257475335028      0
jxl:2:d8        13270   813016    0.4901212  18.448   8.291   6.49864912   2.45349616  1.202510408162      0
jxl:2:d16 …
```
> Disable progressive dc for the fastest modes.

- lib/jxl/enc_color_management.cc
The fallback is what the skcms branch does in all cases.
Also align the white point detection logic with the skcms version.
> lcms2: add a fallback for determining primaries

- lib/jxl/dec_modular.cc
This is a no-op becuase if we have global transforms pushed to the
group level, then we also drop the full image and there is no
FinalizeDecoding stage.
> Don't undo per-group global transforms in modular FinalizeDecoding.

- lib/jxl/frame_header.cc
- lib/jxl/frame_header.h
See the discussion in https://github.com/libjxl/libjxl/issues/1401
This makes libjxl follow the spec regarding minshift/maxshift for modular passes, bringing the modular part of a pass in sync with the vardct part.
It also adds checks to require that the downscale sequence is strictly decreasing, so [8, 4, 2, 1] is allowed but not [2, 4] or [4, 4]. Also the last_pass sequence is required to be strictly increasing.
These constraints should ensure that all shifts are always covered exactly once (modulo brainos on my end), and should be added to the spec too.
This should not break any bitstreams encoded with "normal" cjxl options (i.e. the ones available in the non-verbose help screen).  It also does not break any bitstreams encoded with "advanced" cjxl options (the ones available in the …
> follow spec regarding shift brackets in multi-pass modular

- tools/cjxl_ng_main.cc
We change the default effort to match what is currently done in cjxl.
There it is speed tier "squirrel", which corresponds to effort 7.
> cjxl_ng: change default effort

- lib/include/jxl/encode.h
- lib/jxl/encode.cc
- tools/cjxl_ng_main.cc
This change widens the type of the `value` argument
of `JxlEncoderFrameSettingsSetOption`, from
`int32_t` to `long long`. This allows setting the
center_x and center_y arguments.
> JxlEncoderFrameSettingsSetOption to take int64_t

- tools/cjxl_ng_main.cc
This unifies the two boolean "container" and the "strip" into a three-state flag "container".
We move the `PrintMode` to a place after the state of container is known and also print this information in the end.
> cjxl_ng: improve container handling

- CHANGELOG.md
- lib/include/jxl/encode.h
- lib/jxl/encode.cc
- lib/jxl/encode_test.cc
- tools/cjxl_ng_main.cc
Some of the values that are currently set via
`JxlEncoderFrameSettingsSetOption` are floats, which are cast back and
forth to int64_t in between. We add a way of letting them be floats at
all times.
> add `JxlEncoderFrameSettingsSetFloatOption`

- lib/extras/dec/jxl.h
- lib/include/jxl/decode.h
- lib/jxl/codec_in_out.h
- lib/jxl/dec_external_image.h
- lib/jxl/decode.cc
- lib/jxl/image_bundle.cc
- lib/jxl/image_bundle.h
- lib/jxl/jxl_test.cc
This is generally bad idea to have alpha premultiplied (in storage format).
Unpremultiplying can cause very low precision results, and the result for
pixels with alpha == 0 is a separate discussion topic.
> Do not unpremultiply-alpha by default

- tools/cjxl_main.cc
cjxl should correctly report that it is using modular mode when a
user specifies distance=0 or quality=100. It already uses modular,
but until this commit it reported VarDCT incorrectly.
Fixes #1627.
> tools/cjxl_main: correctly report modular mode for lossless

- lib/jxl/modular/transform/enc_palette.cc
- lib/jxl/modular/transform/palette.h
This is analogous to how implicit delta palette value scaling is
defined for float32 palette.
This fixes an integer overflow bug found by oss-fuzz that was
introduced by #1341.
> Fix float32 small/large cube implicit palette value scaling.

- lib/jxl/dec_patch_dictionary.cc
- lib/jxl/dec_patch_dictionary.h
- lib/jxl/enc_patch_dictionary.cc
- lib/jxl/enc_patch_dictionary.h
The vector of patch positions is broken up into three
vectors: reference positions, patch positions (with indexes into
the reference positions vector) and blending infos. Each vector's
size is limited in the decoder, giving a combined upper bound on
the memory usage (currently 1.5GB).
I will fix the memory usage of the structures used for looking up
patches that insersect a certain row in a separate PR.
> Add tighter memory usage limits on patch dictionary.

- lib/jxl/aux_out.cc
- lib/jxl/aux_out.h
- lib/jxl/enc_cache.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_heuristics.cc
- lib/jxl/enc_params.h
- lib/jxl/enc_quant_weights.cc
- lib/jxl/enc_quant_weights.h
- lib/jxl/quantizer.cc
- lib/jxl/quantizer.h
- tools/benchmark/benchmark_codec.cc
- tools/benchmark/benchmark_codec_jxl.cc
This is currently rather slow (about 5x slowdown), but it is only used in the
benchmark. There is a new jxl codec param 'nr' for "normalize bitrate" and it
sets a bitrate target for each image by looking at the jpeg:95 compressed size
of the image and the target butteraugli distance.
The target bitrate it achieved by scaling the AC quantization interval lengths
by setting a custom global_scale in the quantizer. This way all other heuristic
choices are preserved.
> Implement compressing to a specific bitrate.

- AUTHORS
- lib/jxl/ans_common.cc
- lib/jxl/ans_common.h
- lib/jxl/base/random.h
- lib/jxl/dec_ans.cc
- lib/jxl/dec_modular.cc
- lib/jxl/enc_chroma_from_luma.cc
- lib/jxl/enc_coeff_order.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_modular.cc
- lib/jxl/epf.cc
- lib/jxl/modular/encoding/enc_encoding.cc
- lib/jxl/modular/encoding/enc_ma.cc
- lib/jxl/modular/encoding/enc_ma.h
- lib/jxl/modular/transform/palette.h
- lib/jxl/quantizer.cc
- lib/jxl/quantizer.h
- lib/jxl/render_pipeline/stage_noise.cc
Fixing #1534
arm-none-eabi-g++ declares "int32_t" as "long int" which makes it incompatible with "int" in C++ so the code using template classes does not compile. This pull request fixes those incompatibilities by changing some "int" types to "int32_t". It is just a minimum change to make the static library compile and link. Not all "int" are changed to "int32_t". Examples and tools are not touched either. Tools can't be cross-compiled as such anyway.
Important local modification required: Highway library does not have a bare-metal ARM support so it guesses the target is a POSIX system and uses "clock_gettime" function. That won't compile. So "hwy/nanobenchmark.cc" and "hwy/nanobenchmark.h" have to be commented out from the "third_party\highway\CMakeLIsts.txt".
Exact used compiler: [Arm …
> Make JXL library build for arm-none-eabi

- .github/workflows/build_test.yml
- lib/jxl/decode_test.cc
- lib/jxl/enc_ac_strategy.h
- lib/jxl/enc_heuristics.cc
- lib/jxl/encode_test.cc
- lib/jxl/jxl_test.cc
- lib/jxl/quantizer.cc
- lib/jxl/quantizer_test.cc
0.22% improvement in BPP*pnorm for squirrel:d1.
```
jxl:d1          13270  2680179    1.6157277   2.512  20.071   1.68695998   0.60068375  0.970541376851      0
jxl:d2          13270  1685303    1.0159735   2.642  19.665   2.98979163   0.94922260  0.964384967681      0
jxl:d4          13270  1006113    0.6065284   2.546  12.674   4.82071018   1.50046479  0.910074488374      0
jxl:d8          13270   567359    0.3420285   2.433  12.211  12.11405659   2.41911848  0.827407508324      0
jxl:5:d1        13270  2666994    1.6077792   4.184  17.521   1.82699859 …
```
> Tweak quant field quantization heuristics.

- lib/jxl/data_parallel_test.cc
- lib/jxl/decode_test.cc
- lib/jxl/jxl_test.cc
- lib/jxl/passes_test.cc
- tools/djxl_fuzzer_test.cc
Drive-by: fix typo
Drive-by: actually test 4-channels in `DecodeProgressiveTest`
> Parametrize slowest tests

- lib/profiler/tsc_timer.h
`wingdi.h` defines `ERROR` to `0`, which would conflict with the `ERROR`
enum member in `SerializationStatus`. Fix this by defining `NOGDI`
prior including `windows.h`, to avoid the GDI defines and routines.
---
This fixes compilation on Windows when building with 
`-DJPEGXL_ENABLE_PROFILER=ON`. Here's a simple Dockerfile to
reproduce this issue:
<details>
<summary>Dockerfile</summary>
```Dockerfile
FROM mstorsjo/llvm-mingw:latest
ARG ARCH=x86_64
RUN apt-get update -qq && \
apt-get install -qqy --no-install-recommends git && \
apt-get clean -y && \
rm -rf /var/lib/apt/lists/*
WORKDIR /build
RUN git clone --depth 1 --recursive https://github.com/libjxl/libjxl.git
ENV \
CFLAGS="-O3 -fdata-sections -ffunction-sections" \
CXXFLAGS="-O3 -fdata-sections -ffunction-sections" \ …
```
> tsc_timer.h: avoid conflict with SerializationStatus::ERROR on Windows

- lib/jxl/enc_cache.cc
- lib/jxl/enc_modular.cc
- lib/jxl/enc_modular.h
- lib/jxl/modular/modular_image.h
This occurs currently in dc frames where we have a (g>0)
top-level split, but the only non-empty stream is
the modular global (for small enough images).
```
jxl:d1          13270  2680680    1.6160297   2.527  20.140   1.68643689   0.59921594  0.968350771923      0
jxl:d5          13270   827864    0.4990722   2.378  11.477   8.16946983   1.76535380  0.881038980710      0
jxl:d8          13270   564527    0.3403213   2.488  11.155  11.99684238   2.41556748  0.822068981129      0
Aggregate:      13270  1078027    0.6498811   2.464  13.712   5.48795203 …
```
> Ignore empty stream images while learning modular tree.

- ci.sh
Some shells does not like "unbound variable"s.
> Fix shell script

- lib/jxl/dec_patch_dictionary.cc
- lib/jxl/dec_patch_dictionary.h
- lib/jxl/enc_patch_dictionary.cc
- lib/jxl/enc_patch_dictionary.h
This fixes a potential OOM attack by reducing the memory usage of
the patch dictionary from ```O(N*ysize)``` to ```O(N)``` where ```N``` is the number
of patches. Since ```N``` is restricted to be at most ```O(xsize*ysize)``` by
the decoder, the worst-case memory usage decreases from ```O(xsize*ysize^2)```
to ```O(xsize*ysize)```.
> Use an interval tree for looking up patches that intersect a row.

- lib/jxl/enc_ans.cc
- lib/jxl/enc_cluster.cc
- lib/jxl/enc_cluster.h
- lib/jxl/jxl_test.cc
The slow clustering will just attempt to merge some more clusters from the
output of the fast clustering. This seemingly works better than trying to
produce more clusters with a lower minimum distance parameter and then trying
to merge those.
Drive-by: simplify the implementation of fast clustering.
```
jxl:d1          13270  2680680    1.6160297   1.935  14.626   1.68643689   0.59921594  0.968350771923      0
jxl:d4          13270  1001875    0.6039735   1.915   8.464   5.01221323   1.50586670  0.909503632879      0
jxl:9:d1        13270  2609859 …
```
> Use the same minimum distance parameter for slow and fast clustering.

- lib/jxl/dec_frame.cc
- lib/jxl/decode.cc
This has the side-effect that JxlDecoderFlushImage will output the
extra channels as well.
> Use the same code-path for preview and image output and flush.

- lib/jxl/decode_test.cc
- lib/jxl/enc_file.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_params.h
- lib/jxl/encode_test.cc
- lib/jxl/progressive_split.cc
- lib/jxl/progressive_split.h
- tools/cjxl_main.cc
The custom saliency map support was removed since it is not possible
to set through the API (and there are no tests for it either).
> Move progressive splitter setup to EncodeFrame.

- lib/jxl/enc_group.cc
Benchmark results with all 8x8 blocks:
Before
```
jxl:d1          13270  2723911    1.6420912   1.810  16.222   1.74343252   0.65861527  1.081506359483      0
jxl:d2          13270  1706943    1.0290190   1.857  14.973   2.94722962   1.08186301  1.113257580031      0
jxl:d4          13270  1000052    0.6028746   1.782   9.602   5.04913187   1.77373730  1.069341081351      0
```
After:
```
--------------------------------------------------------------------------------- …
```
> Increase quantization in flat 8x8 blocks.

- tools/CMakeLists.txt
In some cases user may set CMAKE_SKIP_RPATH:BOOL=ON in which case we
must indicate explicitly where to find libjxl dynamic library.
> tests: Make sure libjxl0.7 can still be found

- tools/CMakeLists.txt
- tools/ssimulacra2.cc
- tools/ssimulacra2.h
- tools/ssimulacra2_main.cc
Major new version of the SSIMULACRA metric.
Changes compared to the original version:
- works in XYB color space
- uses 1-norm and 4-norm (instead of 1-norm and max-norm-after-downscaling)
- penalizes both smoothing and ringing artifacts (instead of only penalizing ringing but not smoothing)
- removed specific blockiness detection
The score weights were obtained by running Nelder-Mead simplex search, optimizing to minimize MSE and maximize Kendall and Pearson correlation for training data consisting of 17611 subjective quality scores, validated on separate validation data consisting of 4292 scores.
Results for the full dataset (almost 22k subjective scores):
Metric | Kendall correlation | Spearman | Pearson |
-- | -- | -- |-- 
PSNR | 0.34677 | 0.49926 | 0.48178
SSIM | 0.41612 | 0.58939 | …
> SSIMULACRA 2

- lib/extras/codec.cc
- lib/extras/enc/pnm.cc
- lib/jxl/base/file_io.h
- tools/benchmark/benchmark_args.cc
- tools/benchmark/benchmark_codec_custom.cc
- tools/benchmark/benchmark_codec_custom.h
- tools/benchmark/benchmark_utils.cc
- tools/benchmark/benchmark_utils.h
Add options to prepare input of custom codec in arbitrary file
format and colorspace.
Add option to suppress custom codec stdin/stdout.
Fix endianness of pfm headers and check correct endianness
of ppf when encoding into ppm/pgm.
> Improve 'custom' codec in benchmark.

- AUTHORS
- doc/software_support.md
The user needs to download and install a plugin for JPEG XL support.
> Add Paint.NET to the supported image editors list

- third_party/CMakeLists.txt
This PR adds a missing check for `JPEGXL_BUNDLE_LIBPNG` for the wasm build. This now results in this error message when `-DJPEGXL_BUNDLE_LIBPNG=OFF` is used:
```
CMake Error at third_party/CMakeLists.txt:105 (message):
Please run /workspaces/libjxl/deps.sh to fetch the build dependencies.
```
This error doesn't happen during the normal ci build but can be reproduced in the ci build with the following patch (tested in a codespace from #1725):
```patch
diff --git a/ci.sh b/ci.sh
index 06b73fd8..bca1052c 100755
--- a/ci.sh
+++ b/ci.sh
@@ -384,6 +384,7 @@ cmake_configure() {
-DSJPEG_ENABLE_SIMD=OFF
-DBUILD_SHARED_LIBS=OFF
+        -DJPEGXL_BUNDLE_LIBPNG=OFF
)
fi
args+=(
```
> Added missing check for JPEGXL_BUNDLE_LIBPNG in wasm build.

- lib/extras/enc/jpg.cc
- lib/jxl/color_encoding_internal.cc
- lib/jxl/color_management.cc
- lib/jxl/color_management.h
- lib/jxl/color_management_test.cc
- lib/jxl/dec_cache.cc
- lib/jxl/dec_xyb.cc
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
- lib/jxl/enc_xyb.cc
- lib/jxl/enc_xyb.h
- lib/jxl/opsin_params.h
- lib/jxl/render_pipeline/stage_xyb.cc
- lib/jxl/render_pipeline/stage_xyb.h
- lib/jxl/test_utils.h
Add the XYB profile created by sboukortt@ and veluca93@ that describes
a transformed version of the XYB space that is inside the unit cube for
sRGB colors.
Implement decoding into this modified XYB space by the API and thus
enable saving JXL files to XYB jpegs or PNGs.
> Implement decoding to a scaled XYB space.

- lib/extras/encode_jpeg.cc
- lib/extras/encode_jpeg.h
- lib/jxl/jpeg/dec_jpeg_data_writer.cc
- lib/jxl/jpeg/dec_jpeg_data_writer.h
- lib/jxl/jpeg/dec_jpeg_serialization_state.h
- lib/jxl_extras.cmake
- lib/lib.gni
- tools/benchmark/benchmark_codec_jpeg.cc
The quantization matrix and zero-bias logic is influenced by the adaptive quant field, based on the work of veluca93@.
```
jpeg:q95              13270  7112433    4.2876819  17.799  45.441   1.72006321   0.48375988  2.074208483263      0
jpeg:q82              13270  3405650    2.0530730  21.529  54.414   3.46519852   0.93051614  1.910417529264      0
jpeg:libjxl:d1.0      13270  3444711    2.0766206   4.408  31.047   2.07481623   0.65874454  1.367962491749      0
jpeg:libjxl:d0.6      13270  4708255    2.8383395   4.028  20.722   1.50057375 …
```
> Add a function to create XYB jpegs and add it to benchmark_xl.

- lib/jxl/base/byte_order.h
- lib/jxl/dec_cache.cc
- lib/jxl/dec_cache.h
- lib/jxl/dec_frame.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
- lib/jxl/render_pipeline/stage_write.cc
- lib/jxl/render_pipeline/stage_write.h
This enables low memory code-path for all image buffer cases with the exception of extra channels.
> Unify the pixel callback and image buffer write stages.

- lib/extras/encode_jpeg.cc
- lib/extras/encode_jpeg.h
- tools/benchmark/benchmark_args.cc
- tools/benchmark/benchmark_args.h
- tools/benchmark/benchmark_codec_jpeg.cc
- tools/benchmark/benchmark_xl.cc
```
Encoding                   kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
-------------------------------------------------------------------------------------------------------------------------
jpeg:q80                     13270  3185957    1.9206325  46.057 124.259   3.88049626   0.98219334  1.886432478371      0
jpeg:libjxl:d1.0:nr:q80      13270  3185856    1.9205716   1.553  55.073   2.05721784   0.71286332  1.369105080770      0
```
Images can be viewed at the following links:
https://storage.googleapis.com/jxl-quality/eval/61297ec/index.jpeg_q80.html 
https://storage.googleapis.com/jxl-quality/eval/61297ec/index.jpeg_libjxl_d1.0_nr_q80.html
> Add target-bitrate mode to the xyb-jpeg encoder.

- lib/extras/encode_jpeg.cc
- lib/jxl/image.cc
- lib/jxl/image_ops.h
```
Encoding                   kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
-------------------------------------------------------------------------------------------------------------------------
jpeg:libjxl:d1.0:nr:q80      13270  3185856    1.9205716   0.836  31.438   2.05721784   0.71286332  1.369105080770      0
```
Images:
https://storage.googleapis.com/jxl-quality/eval/61297ec/index.jpeg_libjxl_d1.0_nr_q80.html
```
Encoding                   kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
-------------------------------------------------------------------------------------------------------------------------
jpeg:libjxl:d1.0:nr:q80      13270  3185255 …
```
> Subsample the blue channel in XYB jpegs.

- tools/cjxl_main.cc
We change a detail in the calculation going from quality to distance: now it is continous near the value 30, corresponding to distance 6.4.
> cjxl: improve quality to distance calculation

- tools/cjxl_main.cc
Fixes #1755 both for --resampling and --ec_resampling.
> cjxl: fix check for resampling flag

- lib/extras/enc/jxl.cc
- lib/extras/enc/jxl.h
- lib/jxl_extras.cmake
- lib/lib.gni
- tools/cjxl_main.cc
The encoder API calls are moved to extras/enc/jxl.cc so that they can be reused in tests.
> Split cjxl implementation into flag parsing and encoder API calls.

- plugins/gdk-pixbuf/CMakeLists.txt
These changes are important for MSYS2 (Windows).
gdk-pixbuf plugins are built as modules in other projects too. For example:
https://github.com/AOMediaCodec/libavif/blob/2e8fe112b97ea9b7a0f00e7ae67ba53128f5ee99/contrib/gdk-pixbuf/CMakeLists.txt#L11
> build pixbufloader-jxl as module

- lib/extras/enc/jxl.cc
- lib/jxl/jxl_test.cc
- lib/jxl/test_image.h
- lib/jxl/test_utils.h
The new test framework detected a bug in cjxl where we would ignore the 16-bit alpha bit-depth and fall back to 8 bit precision.
> Convert more tests to use ppf input + alpha bit depth bugfix.

- tools/benchmark/benchmark_codec_jpeg.cc
- tools/butteraugli_main.cc
The hf_assymetry of the butteraugli_main tool was changed to match that of benchmark_xl.
```
Encoding           kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
-----------------------------------------------------------------------------------------------------------------
jpeg:q95             13270  7112433    4.2876819  18.423  45.517   1.72006321   0.48375988  2.074208483263      0
jpeg:q95:djxl8       13270  7112433    4.2876819  17.420   2.787   1.62978482   0.45445552  1.948560710939      0
jpeg:q95:djxl16      13270  7112433    4.2876819  14.434   2.842   1.62876725   0.44648875  1.914401746589      0
```
> Add jxl-roundtrip based jpeg decoder to benchmark.

- tools/benchmark/benchmark_codec_jpeg.cc
```
Encoding           kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
-----------------------------------------------------------------------------------------------------------------
jpeg:q95:djxl8       13270  7112433    4.2876819  17.679   2.856   1.62978482   0.45445552  1.948560710939      0
jpeg:q95:djxl16      13270  7112433    4.2876819  16.533   2.858   1.62876725   0.44648875  1.914401746589      0
```
```
Encoding           kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
-----------------------------------------------------------------------------------------------------------------
jpeg:q95:djxl8       13270  7112433    4.2876819  18.117   3.494 …
```
> Don't use chroma-from-luma for jxl-roundtrip jpeg decoding.

- lib/jxl/jpeg/enc_jpeg_data_reader.cc
- lib/jxl/jpeg/jpeg_data.cc
- lib/jxl/jpeg/jpeg_data.h
Errors during reading jpeg bitstreams caused both a debug string to be printed and an error code enum to be set. However, these error codes are not used anywhere, and I don't think we will want to expose that kind of granularity in the api (if it fails for some reason, it fails, but we don't really need to know why exactly). So this PR gets rid of the error codes in jpeg_data (while keeping the debug strings, of course only in builds that do print them).
Also gets rid of `kBrunsliMaxNumBlocks` which I think was a technical limitation in Brunsli but it no longer applies now (obviously memory will be a problem when trying to recompress a jpeg that large, but any valid jpeg dimensions are also valid jxl dimensions so I don't think we should enforce a lower limit).
> remove detailed error codes from jpeg data reader; remove max size limit

- lib/jxl/decode_test.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_cache.cc
- lib/jxl/encode_test.cc
- lib/jxl/jxl_test.cc
Currently we use a different approach for DC at d >= 2 than at d < 2. Most metrics don't notice this, but according to ssimulacra2, this causes a discontinuity at d2; effectively the DC precision in slow gradients drops a bit at d2-epsilon since the effective deadzone doubles when extra_levels goes from 1 to 0 and we switch from 'near-lossless' DC encoding with half-sized quantization buckets to losslessly encoding DC coefficients with full-sized quantization buckets.
This pull request proposes to remove the discontinuity by using the d >= 2 approach also at d < 2, and adjusting the dc quantization factors accordingly to stay close to the original behavior.
Butteraugli 3-norm slightly doesn't like this (small regression in bpp*pnorm of ~0.5%) though max-norm does like it. I have no idea …
> remove discontinuity in DC approach at d2

- lib/extras/decode_jpeg.cc
- lib/extras/decode_jpeg.h
- lib/jxl/enc_quant_weights.cc
- lib/jxl/enc_quant_weights.h
- lib/jxl_extras.cmake
- lib/lib.gni
- tools/benchmark/benchmark_codec_jpeg.cc
This is now equivalent to the lossless-jpeg roundtrip version, but is faster because we do not create the actual jxl bitstream.
> Add a jpeg decoding function that is based on libjxl internals.

- lib/include/jxl/encode.h
In the PR #834 the version header file was added to `decode.h` because `decode.cc` uses these defines. Can this also be added to the `encode.h` header file since `encode.cc` also uses these defines?
> Also include version.h in the encode header file.

- tools/cjxl_main.cc
Clarifying the error message, which is for example triggered in #1804.
> cjxl: correct error message

- lib/extras/packed_image_convert.cc
- lib/jxl/decode_test.cc
- lib/jxl/enc_external_image.cc
- lib/jxl/enc_external_image.h
- lib/jxl/enc_external_image_gbench.cc
- lib/jxl/enc_external_image_test.cc
- lib/jxl/roundtrip_test.cc
- lib/jxl/test_utils.h
- tools/benchmark/benchmark_codec_avif.cc
- tools/benchmark/benchmark_codec_webp.cc
- tools/fuzzer_corpus.cc
This is a preparation to accept buffers with zero-padding in most significant bits.
By default the bit depth is the full bit depth of the format data type, so the behavior is unchanged.
> Add separate data type and bit depth argument to image converter.

- tools/benchmark/benchmark_codec_custom.cc
Adding the options succeeds since there are none to add.
> Custom codec on Windows: adding the command-line options should return true, not false

- CHANGELOG.md
- lib/extras/dec/jxl.cc
- lib/extras/dec/jxl.h
- lib/extras/decode_jpeg.cc
- lib/extras/enc/jxl.cc
- lib/extras/enc/jxl.h
- lib/include/jxl/decode.h
- lib/include/jxl/encode.h
- lib/include/jxl/types.h
- lib/jxl/dec_cache.h
- lib/jxl/dec_frame.h
- lib/jxl/decode.cc
- lib/jxl/enc_external_image.cc
- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
- lib/jxl/jxl_test.cc
- lib/jxl/render_pipeline/stage_write.cc
- lib/jxl/test_image.h
- lib/jxl/test_utils.h
This addresses part of the issue in #1763.
For the encoder the two choices are using the bit depth of the pixel format (a.k.a. repeating higher bits in lower bits), or to use the bit deth from basic info (a.k.a. zero-padding higher bits). For the decoder there is an additional option to use a custom bit depth.
> Add API functions for setting input/output bit depth.

- lib/extras/enc/jpg.cc
- tools/benchmark/benchmark_codec_jpeg.cc
The progressive modes are numbered p1 - p5 in order of decreasing decoding speed.
Benchmark results (single-threaded):
```
Encoding       kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
-------------------------------------------------------------------------------------------------------------
jpeg:q95         13270  7112433    4.2876819  45.396 115.778   1.72006321   0.48375988  2.074208483263      0
jpeg:q95:p1      13270  6971047    4.2024483  38.270  76.232   1.72006321   0.48375988  2.032975892303      0
jpeg:q95:p2      13270  6909946    4.1656140  29.992  59.312   1.72006321   0.48375988  2.015156924794      0
jpeg:q95:p3      13270  6879637    4.1473424  26.299  50.730   1.72006321   0.48375988  2.006317870013      0
jpeg:q95:p4 …
```
> Add popular JPEG progressive modes to benchmark_xl.

- lib/jxl/butteraugli/butteraugli.cc
- lib/jxl/modular_test.cc
Butteraugli-only change. Makes the metric slightly more sensitive to DC errors.
Before, with `--progressive_dc=0`:
```
jxl:d0.5        13270  4230132    2.5501063   6.833  71.506   1.07251453   0.37361494  0.952757824848      0
jxl:d1          13270  2695661    1.6250609   7.499  71.163   1.69329262   0.60141074  0.977329093760      0
jxl:d2          13270  1682981    1.0145737   8.544  69.546   3.01595855   0.94927374  0.963108133887      0
jxl:d3          13270  1253173    0.7554668   7.188  65.433   3.69493628   1.24221990  0.938455926169      0
jxl:d4          13270 …
```
> make butteraugli slightly more sensitive to low freq errors

- lib/jxl/encode.cc
- plugins/gimp/file-jxl-save.cc
- tools/cjxl_main.cc
Fixes #1741
This slighlty changes how qualities below 30 are mapped to distance. Now we use a quadratic map with two properties:
- 0 is mapped to 25
- the first derivative at 30 agrees with the linear map for values above 30.
> cjxl: modify quality-to-distance map

- tools/jxl_from_tree.cc
when using in cmake,
tools\jxl_from_tree.cc(470,56): error C2668: 'jxl::make_unique': ambiguous call to overloaded function
> fix jxl_from_tree ambiguous call to make_unique

- lib/jxl/butteraugli/butteraugli.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_cache.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_params.h
- lib/jxl/encode_test.cc
- lib/jxl/jxl_test.cc
- lib/jxl/modular_test.cc
- lib/jxl/passes_test.cc
Butteraugli numbers are with a butteraugli as in https://github.com/libjxl/libjxl/pull/1822.
Currently, `progressive_dc=1` has somewhat lower DC precision than `progressive_dc=0`, causing a discontinuity at d4.5:
```
jxl:d0.5        13270  4230132    2.5501063   6.500  50.978   1.07075775   0.37354307  0.952574538746      0
jxl:d1          13270  2695661    1.6250609   7.318  65.233   1.69066322   0.60121030  0.977003367091      0
jxl:d2          13270  1682981    1.0145737   7.896  64.650   3.01102424   0.94896466  0.962794548686      0
jxl:d3          13270  1253173 …
```
> Disable progressive dc by default; adjust DC/AC balance and progressive DC precision

- lib/extras/codec_test.cc
- lib/jxl/jxl_test.cc
- tools/cjxl_main.cc
- tools/djxl_main.cc
- tools/roundtrip_test.sh
If a PNM file is compressed by cjxl / produced by djxl, the JXL_BIT_DEPTH_FROM_CODESTREAM option is set by default.
Additionally, djxl now implements the --bits_per_sample option for choosing an arbitrary bit depth for unsigned output types.
Added unit tests and end-to-end roundtrip tests for bit-exact pnm file reconstruction for lossless mode.
> Use zero-padded input/output buffers by default for PNM files.

- tools/jxl_from_tree.cc
Two minor tweaks to jxl_from_tree:
- reset manual noise between frames (otherwise there is no way to get rid of noise in overlays)
- don't clamp alpha — allowing out of range alpha allows interesting artistic effects, so it's nicer to disable clamping (we could also add an option to select what to do)
> jxl_from_tree: reset manual noise between frames, don't clamp alpha

- lib/extras/dec_group_jpeg.cc
- lib/extras/dec_group_jpeg.h
- lib/extras/decode_jpeg.cc
Based on article by J. R. Price and M. Rabbani from 2000.
```
Encoding                 kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
-----------------------------------------------------------------------------------------------------------------------
jpeg:q95:djxl8             13270  7112433    4.2876819  54.804 104.038   1.63272071   0.44628983  1.913548813406      0
jpeg:q95:yuv420:djxl8      13270  5230427    3.1531274  81.308 140.788   6.06236982   0.78961033  2.489741937504      0
jpeg:libjxl:djxl8          13270  3197015    1.9272988  19.081  84.911   2.19547820   0.70263982  1.354196861688      0
```
```
Encoding                 kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm …
```
> Compute optimal dequant biases assuming Laplacian AC distribution.

- lib/jxl/frame_header.cc
- lib/jxl/render_pipeline/stage_blending.cc
This prevents e.g. blending against a smaller preview frame.
> Check the sizes of extra channel backgrounds in blending stage.

- AUTHORS
- lib/extras/dec/apng.cc
- lib/extras/dec/jxl.cc
- lib/extras/enc/apng.cc
- lib/extras/enc/jxl.cc
- lib/extras/enc/jxl.h
- lib/include/jxl/encode.h
- lib/jxl/enc_params.h
- lib/jxl/encode.cc
- tools/cjxl_main.cc
This brings back a cjxl feature from before cjxl_ng: Exif/XMP/IPTC/JUMBF metadata from the input will be preserved as corresponding ISO BMFF boxes in the output.
Without this change, cjxl reads the metadata, reports that it has read the metadata, and forces the JXL container format... but never actually writes any boxes.
Tested with Exif and XMP metadata. `./ci.sh release` ran with no issues.
(This is my first ever PR. Hopefully I'm doing this right!)
> Make cjxl output Exif/xml/jumb boxes

- lib/include/jxl/decode.h
No implementation yet, just an API proposal.
The aim is to make uint8 output more useful by allowing applications to let libjxl do the color conversion before conversion to uint8. That way, the uint8 output can be guaranteed to be in display space, and it's no longer necessary to use the float pixel callback and manually do the color management and conversion to uint8.
Open question: in the encode API there's a default cms available, but I guess that here it also has to work in the lightweight decode-only `libjxl_dec` which doesn't include a default cms. We could perhaps allow calling JxlDecoderSetColorEncoding or JxlDecoderSetICCProfile when no explicit cms was set, but only in `libjxl` builds where we can have a default cms (i.e. if you do that when linking with `libjxl_dec`, it will …
> API only (proposal): set CMS and desired output color encoding in decoder

- lib/include/jxl/types.h
This feature about row stride has been implemented so the TODO can be removed.
Signed-off-by: Leo Izen <leo.izen@gmail.com>
> lib/include/jxl/types.h: remove implemented TODO

- ci.sh
- lib/extras/dec_group_jpeg.cc
- lib/extras/dec_group_jpeg.h
- lib/extras/decode_jpeg.cc
- lib/extras/decode_jpeg.h
- lib/extras/decode_jpeg_test.cc
- lib/jxl_tests.cmake
```
Encoding                  kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
------------------------------------------------------------------------------------------------------------------------
jpeg:q90                    13270  4838710    2.9169834  66.220 167.328   2.40070152   0.68663652  2.002907346396      0
jpeg:q90:djxl8              13270  4838710    2.9169834  65.773 117.422   2.17603183   0.62092407  1.811225220808      0
jpeg:q90:djxl16             13270  4838710    2.9169834  65.796 113.217   2.16807723   0.61567343  1.795909190468      0
jpeg:yuv420:q90             13270  3660915    2.2069577  99.355 250.723   6.07282543   0.95039908  2.097490592679      0
jpeg:yuv420:q90:djxl8       13270  3660915 …
```
> Add first version of streaming JPEG decoder.

- lib/extras/decode_jpeg.cc
```
Encoding                 kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
-----------------------------------------------------------------------------------------------------------------------
jpeg:q90:djxl8             13270  4838710    2.9169834  65.817 112.747   2.17603183   0.62092407  1.811225220808      0
jpeg:yuv420:q90:djxl8      13270  3660915    2.2069577  96.322 164.534   6.05725956   0.91959307  2.029503031911      0
jpeg:libjxl:djxl8          13270  3197015    1.9272988  19.046  79.233   2.25490046   0.70510193  1.358942071174      0
```
```
Encoding                 kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs …
```
> Dont save MCU coding state if there are enough bytes in buffer.

- tools/libjxl_test.c
Avoid declaring int main() without a prototype as this is deprecated in all versions of C.
> tools/libjxl_test.c: avoid function declaration without prototype

- lib/include/jxl/codestream_header.h
- lib/jxl/encode.cc
- lib/jxl/encode_test.cc
This makes the encoder store the `intrinsic_xsize` and `intrinsic_ysize` from JxlBasicInfo. Setting these previously had no effect.
Tests:
Encoded the same 80x30 image using several different settings for intrinsic_xsize and intrinsic_ysize:
```
Intrinsic dimensions       Encoder error
----------------------------------------
0x0 (unset)                None
80x30 (= xsize/ysize)      None
123x111                    None
123x0                      ./lib/jxl/headers.cc:66: JXL_FAILURE: Empty image
./lib/jxl/encode.cc:773: Invalid intrinsic dimensions
80x1073741824 (1<<30)*     None
80x1073741825              ./lib/jxl/encode.cc:773: Invalid intrinsic dimensions
```
(*There's an explicit check for this maximum, because otherwise it doesn't fail until JxlEncoderProcessOutput.)
Output files: …
> Encode intrinsic dimensions

- lib/extras/encode_jpeg.cc
```
jpeg:libjxl:d1.0      13270  3197015    1.9272988   5.469  29.993   2.19093180   0.70477101  1.358304300765      0
```
```
jpeg:libjxl:d1.0      13270  3163678    1.9072018   4.031  25.939   2.19093180   0.70477101  1.344140529099      0
```
> XYB-jpeg: jpeg-specific clustering and more progression.

- AUTHORS
- experimental/fast_lossless/fast_lossless.cc
- experimental/fast_lossless/fast_lossless.h
- experimental/fast_lossless/fast_lossless_main.cc
Adding a "Jxl" prefix disambiguates it when combining it with e.g. a fast PNG encoder or fast WebP encoder. Some lines were subsequently re-formatted to fit within 80 columns.
Also wrap an "extern C" around that function.
Also wrap an anonymous namespace around the implementation, so that the fjxl BitWriter doesn't conflict with e.g. fpnge's BitWriter.
Also fix some -Wunknown-pragmas and -Wsign-compare g++ warnings.
Fixes #1855
> fast_lossless: rename FastLosslessEncode

- lib/extras/encode_jpeg.cc
```
jpeg:libjxl:d0.5      13270  4804698    2.8964795   3.723  22.242   1.56636882   0.47385977  1.372525138424      0
jpeg:libjxl:d0.8      13270  3636329    2.1921362   4.089  25.696   1.87652230   0.61543190  1.349110553678      0
jpeg:libjxl:d0.9      13270  3378595    2.0367630   3.790  23.042   2.17102480   0.66006343  1.344392804990      0
jpeg:libjxl:d1.0      13270  3163678    1.9072018   4.064  24.490   2.19093180   0.70477101  1.344140529099      0
jpeg:libjxl:d1.1      13270  2984772    1.7993495   3.966  26.363   2.11484838 …
```
> Simplex-search optimized xyb-jpeg quantization matrix parameters.

- lib/jxl/enc_modular.cc
There is debug code to print an MA tree, but this is not supposed to be called at all (should require manually changing the code to get it compiled in). This broke benchmark_xl when setting --debug_image_dir and encoding VarDCT images.
> don't compile debug print tree code

- lib/extras/decode_jpeg.cc
- lib/extras/decode_jpeg.h
- lib/extras/decode_jpeg_test.cc
Modify ReadHeaders() to read until SOS marker as in libjpeg.
Add a StartDecompress() API function that will read whole input for progressive images. This is the same behaviour as in libjpeg's jpeg_start_decompress() for non-buffered-image mode.
> Make jpeg decoder's API more similar to libjpeg's API.

- AUTHORS
- lib/jxl/dec_xyb.cc
Changed OR to AND. In WASM, images that were not XYB encoded would fail to decode, as `CanOutputToColorEncoding(c_desired)` is never called.
> Update dec_xyb.cc to fix wasm decode issue

- tools/benchmark/benchmark_codec_custom.cc
- tools/benchmark/benchmark_codec_jpeg.cc
- tools/benchmark/benchmark_utils.cc
- tools/benchmark/benchmark_utils.h
With this addition, one can benchmark against a decoder-only libpeg implementation by setting a custom LD_LIBRARY_PATH and using a statically built cjpeg in the benchmark.
> Add option to run custom cjpeg command in jpeg benchmark.

- lib/jpegli/decode_api.cc
- lib/jpegli/decode_api_test.cc
- lib/jpegli/decode_internal.h
- lib/jpegli/decode_marker.cc
- lib/jpegli/decode_scan.cc
- lib/jpegli/render.cc
This can be enabled by the application by setting
```
cinfo.quantize_colors = FALSE;
cinfo.desired_number_of_colors = 65536;
```
In this case a scanline buffer should be twice as long.
Other changes in the commit:
* Remove code duplication between input reading API functions.
* Use the existing cinfo fields for marker parsing and keeping internal state, remove redundant fields from ```jpeg_decomp_master```.
* Add trivial implementation of ```jpeg_calc_output_dimensions``` and use ```cinfo->output_{width,height}```, 
and ```cinfo->out_color_components``` where appropiate.
> Support 16 bit output buffer in libjpegli decoder.

- lib/extras/codec_test.cc
- lib/extras/dec/apng.cc
Since the PNG encoder goes to the trouble of writing them, this allows the PNG decoder to read them.
This means that converting a JXL with an encoded (non-ICC) profile to PNG, and then back to JXL, will in many cases produce a JXL with the original encoded profile instead of a generated ICC, resulting in a smaller file.
- This changes the default rendering intent for PNGs that don't specify one from Perceptual to Relative, to be consistent with the API's default sRGB profile (`JxlColorEncodingSetToSRGB`). Relative was also the default in cjxl classic.
- The existing code was (mistakenly?) overriding the rendering intent from an sRGB chunk to Perceptual after decoding it. It now uses whatever the sRGB chunk specifies.
- cICP doesn't store a rendering intent, so we always use the default …
> Read cICP chunks from PNGs

- lib/jxl/modular/transform/enc_palette.cc
- lib/jxl/modular/transform/palette.h
- lib/jxl/modular/transform/squeeze.cc
Metachannels (i.e. channels representing palettes) have `hshift == -1`, but theoretically Squeeze can be applied on them which would make them have `hshift == 0`. This currently never happens because no jxl encoder does that, but it could cause somewhat weird/unexpected things to happen in very contrived cases.
This change makes Squeeze only increment the values of hshift/vshift if they are not -1.
It also makes Squeeze return error when trying to apply it to an empty channel — this is needed to prevent malicious bitstreams from doing an unbounded number of Squeeze steps (this was prevented before by hshift/vshift eventually getting too large, but now we can no longer count on that).
Also it makes Palette set `vshift = -1` (previously both spec and code didn't really define what the …
> fix hshift/vshift of metachannels

- lib/include/jxl/decode.h
- lib/jxl/alpha.cc
- lib/jxl/alpha.h
- lib/jxl/dec_external_image.cc
- lib/jxl/dec_external_image.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
- lib/jxl/enc_params.h
- lib/jxl/speed_tier_test.cc
- tools/benchmark/benchmark_codec_jxl.cc
Remove the deprecated DCOutBuffer stuff from the decode API — this was deprecated a long time ago and didn't work anymore anyway, so no need to keep it in.
Also remove some code that is no longer used. Move the speed tier name parsing to benchmark_xl (which is the only thing that still uses that). The function to convert speed settings to animal name strings was only used to produce pretty names for the tests in `speed_tier_test.cc`, so removing that too. Some overloads of `UnpremultiplyAlpha` and `ConvertToExternal` are not used by anything anymore, so removing them too.
> remove deprecated or dead code

- lib/jpegli/decode_api.cc
- lib/jpegli/decode_api_test.cc
- lib/jpegli/decode_internal.h
- lib/jpegli/decode_marker.cc
- lib/jpegli/decode_marker.h
- lib/jpegli/decode_scan.cc
- lib/jpegli/decode_scan.h
- lib/jpegli/render.cc
Added tests for suspending source manager use-case, and tests for consuming input ahead of the output processing.
> jpegli: implement jpeg_consume_input()

- ci.sh
No need to have these in the report, they are not part of libjxl itself.
> don't include *_gbench.cc in code coverage report

- lib/jpegli/decode_api.cc
- lib/jpegli/decode_api_test.cc
- lib/jpegli/decode_internal.h
- lib/jpegli/render.cc
The implementation is not yet optimal, it just calls jpeg_read_scanlines and discards the output that is not needed.
> jpegli: implement decoding to cropped output.

- .github/workflows/release.yaml
- AUTHORS
This PR adds Ubuntu 22.04 to the existing list of Ubuntu 18.04 and 20.04 for which a package is generated for releases.
> Build release package for Ubuntu 22.04

- lib/jpegli.cmake
- lib/jpegli/common_api.cc
- lib/jpegli/decode_api.cc
- lib/jpegli/decode_api_test.cc
- lib/jpegli/decode_internal.h
- lib/jpegli/decode_marker.cc
- lib/jpegli/decode_scan.cc
- lib/jpegli/memory_manager.h
- lib/jpegli/source_manager.cc
* implemented jpeg_abort(), jpeg_destroy()
* implemented jpeg_alloc_quant_table(), jpeg_alloc_huff_table()
* implemented jpeg_set_marker_processor()
* implemented jpeg_stdio_src()
* added jpeg_resync_to_restart() that throws an error
* added dummy jpeg_new_colormap()
* added dummy jpeg_read_coefficients()
> jpegli: Add rest of the decoder API functions.

- lib/jxl_tests.cmake
- tools/CMakeLists.txt
- tools/wasm_demo/index.html
- tools/wasm_demo/jxl_decoder_test.js
- tools/wasm_demo/jxl_decompressor.cc
- tools/wasm_demo/no_png.cc
- tools/wasm_demo/no_png.h
Drive-by:
* fix WASM test
* do not preallocate memory (1.5GiB) in tests
* allow memory growth in WASM-compiled tools
> Add CICP to no-png

- experimental/fast_lossless/build-android.sh
- experimental/fast_lossless/build.sh
- experimental/fast_lossless/cross_compile_aarch64.sh
- lib/jxl/enc_fast_lossless.cc
Do not assume little-endianness, use dynamic dispatch for AVX2.
> fast-lossless: portability improvements

- lib/jxl/enc_ac_strategy.cc
- lib/jxl/jxl_test.cc
DZgas reported this problem on discord
There is no related bug
This is a partial mitigation (fixes about 30 % of the problem)
```
Encoding         kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm   PSNR   QABPP  SmallB  DCT4x8     AFV  DCT8x8    8x16    8x32      16   16x32      32   32x64      64       BPP*pnorm   Bugs
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
jxl:d0.5:epf0      18611  5404951    2.3232311   1.056   9.377   1.43458343   0.37487900  44.50   2.355  0.9432 29.2418  1.9765  7.4389 25.5920  0.0000 31.8696  1.1499  2.3933  0.0880  0.0880  0.870930556345      0
jxl:d1:epf0        18611 …
```
> Less red-green blurring/ringing

- lib/include/jxl/encode.h
- lib/jxl.cmake
- lib/jxl/enc_fast_lossless.cc
- lib/jxl/enc_fast_lossless.h
- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
- lib/jxl/jxl_test.cc
- tools/cjxl_fuzzer.cc
Before:
```
Compressed to 2148068 bytes (2.731 bpp).
3072 x 2048, geomean: 23.99 MP/s [21.01, 24.47], 100 reps, 0 threads.
```
After:
```
Compressed to 2166489 bytes (2.755 bpp).
3072 x 2048, geomean: 375.76 MP/s [175.02, 377.97], 100 reps, 0 threads.
```
> Use fast-lossless for effort 1.

- lib/jpegli/decode_api.cc
- lib/jpegli/decode_internal.h
- lib/jpegli/decode_marker.cc
- lib/jpegli/render.cc
This makes it unnecessary to use an internal variable for this, and will make applications that somehow rely on this field work.
> jpegli: use cinfo->quant_tbl_ptrs to store quant tables

- lib/jxl/jxl_test.cc
Some tests started failing in the Scalar build after https://github.com/libjxl/libjxl/pull/1971.
Trying to fix them...
> attempt to fix tests

- lib/jxl/encode.cc
Trying fast lossless on animations currently results in segfault (unless the animation uses cropped frames or something else that disables the fast path anyway), since it's trying to access durations from a variable that is a nullptr when using the fast path.
For now, this just disables the fast lossless path in case of animation.
To deal with all the multi-frame lossless stuff (cropped frames, duration, blend modes, frame names etc), it's probably best to use the general libjxl frame header writer and only keep the simpler fjxl frame header writer for standalone builds of fjxl. One blocker to do that atm, is that the fast path assumes that frame dimensions are a multiple of kChunkSize (which is 16), and it can do that by just making the frame larger than the image if needed. This trick …
> no fast lossless animation yet

- tools/cjxl_main.cc
This fixes #1968. We disallow the combination `--lossless_jpeg=1` with `-d` for non-zero distances or `-q` for qualities not equal to 100.
> disallow nonsensible lossless_jpeg settings

- lib/jpegli/encode_api_test.cc
- lib/jxl/decode_test.cc
- lib/jxl/enc_ac_strategy.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/encode_test.cc
- lib/jxl/jxl_test.cc
- lib/jxl/passes_test.cc
```
Before:
jxl:d0.1        18611 14241577    6.1215124   1.509   9.323   1.15476871  99.91401321   0.12222551  53.28   6.133  1.6289 55.5325  2.6894 15.0325 15.0910  0.0000  9.4921  0.8693  0.2476  0.1100  0.0880  0.748204948196      0
jxl:d0.5        18611  5479933    2.3554609   1.945  14.862   1.46929085  96.88926767   0.37647436  44.44 …
```
> less ringing for anime

- lib/jxl/decode_test.cc
- lib/jxl/jxl_test.cc
Some failures in the ci were caused by #1987, which is fixed here by updating the expections of the test.
> fix RoundtripSmallPatches et al.

- experimental/fast_lossless/cross_compile_aarch64.sh
- lib/jxl/enc_fast_lossless.cc
- lib/jxl/jxl_test.cc
Multiple changes:
- Unified SIMD implementation between NEON and x86
- AVX2 support for >8bit
- AVX512 support (by default not compiled, given the loss in compression density for nonphoto, the increase in compilation time and the marginal speed improvement)
Summary of results (all single core):
- Slight speedup for NEON (~5%)
- 1.5x-2x speedup for AVX2 for >8bit cases
- AVX512 seems ~10% faster for <=8bit, ~10% slower for 15+ bit, and ~same speed in between compared to AVX2.
Results may change on different CPUs.
```
Before, NEON:
40.340 MP/s
11.895 bits/pixel
After, NEON:
42.940 MP/s
11.895 bits/pixel
Before:
build/fast_lossless /tmp/noise-4.ppm
215.101 MP/s
14.997 bits/pixel
0 (0)
build/fast_lossless /tmp/noise-6.ppm
192.920 MP/s
21.155 bits/pixel
0 (0)
build/fast_lossless …
```
> x86 SIMD for fast-lossless

- lib/jxl/decode_test.cc
- lib/jxl/enc_ac_strategy.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/encode_test.cc
- lib/jxl/jxl_test.cc
- lib/jxl/passes_test.cc
inspired by a test image provided by DZgas, this PR seems to make a substantial improvement on that image, with some lesser degradation on synthetic.png in 'jyrki31' corpus -- broadly the results seem slightly better
0.26 % improvement on BPP * pnorm
```
Before:
jxl:d0.1        18611 14271779    6.1344943   1.475   9.685   1.12860060  99.91379988 …
```
> improvements for red/green in AC strategy

- experimental/fast_lossless/build.sh
- lib/jxl/enc_fast_lossless.cc
About 10% speedup across the board.
```
Before, NEON:
42.940 MP/s
11.895 bits/pixel
After, NEON:
48.943 MP/s
11.895 bits/pixel
Before, AVX2:
build/fast_lossless /tmp/noise-4.ppm
206.035 MP/s
14.999 bits/pixel
build/fast_lossless /tmp/noise-6.ppm
204.538 MP/s
21.155 bits/pixel
build/fast_lossless /tmp/noise-8.ppm
219.908 MP/s
27.231 bits/pixel
build/fast_lossless /tmp/noise-10.ppm
144.475 MP/s
33.225 bits/pixel
build/fast_lossless /tmp/noise-11.ppm
132.273 MP/s
36.248 bits/pixel
build/fast_lossless /tmp/noise-12.ppm
128.479 MP/s
39.271 bits/pixel
build/fast_lossless /tmp/noise-13.ppm
132.436 MP/s
42.286 bits/pixel
build/fast_lossless /tmp/noise-14.ppm
106.496 MP/s
48.830 bits/pixel
build/fast_lossless /tmp/noise-15.ppm
104.697 MP/s
62.045 bits/pixel
build/fast_lossless /tmp/noise-16.ppm …
```
> Explicitly SIMDfy prediction.

- lib/jxl/enc_fast_lossless.cc
- lib/jxl/jxl_test.cc
About 0.5-1% density improvement at no loss in speed.
Diffbase: #2009 
```
/data/jpeg_xl_data/imagecompression.info.rgb8/artificial.ppm
Compressed to 2166489 bytes (2.755 bpp).
3072 x 2048, geomean: 366.12 MP/s [310.05, 436.53], 10 reps, 1 threads.
/data/jpeg_xl_data/imagecompression.info.rgb8/big_building.ppm
Compressed to 58067912 bytes (11.895 bpp).
7216 x 5412, geomean: 245.42 MP/s [211.02, 256.70], 10 reps, 1 threads.
/data/jpeg_xl_data/imagecompression.info.rgb8/big_tree.ppm
Compressed to 49273739 bytes (14.230 bpp).
6088 x 4550, geomean: 243.80 MP/s [207.39, 259.60], 10 reps, 1 threads.
/data/jpeg_xl_data/imagecompression.info.rgb8/cathedral.ppm
Compressed to 9082250 bytes (12.077 bpp).
2000 x 3008, geomean: 231.05 MP/s [183.09, 242.56], 10 reps, 1 threads. …
```
> [fast-lossless] Use per-channel prefix codes; some refactoring

- .github/workflows/build_test.yml
- lib/jxl/enc_fast_lossless.cc
With the RLE improvements and the changes here, AVX512 is about 50% faster than AVX2 on a i7-11850H.
```
Before, AVX2:
build/fast_lossless /tmp/noise-4.ppm
245.864 MP/s
14.668 bits/pixel
build/fast_lossless /tmp/noise-6.ppm
236.304 MP/s
20.813 bits/pixel
build/fast_lossless /tmp/noise-8.ppm
241.526 MP/s
26.878 bits/pixel
build/fast_lossless /tmp/noise-10.ppm
164.410 MP/s
32.878 bits/pixel
build/fast_lossless /tmp/noise-11.ppm
161.683 MP/s
35.897 bits/pixel
build/fast_lossless /tmp/noise-12.ppm
159.196 MP/s
38.912 bits/pixel
build/fast_lossless /tmp/noise-13.ppm
159.249 MP/s
41.925 bits/pixel
build/fast_lossless /tmp/noise-14.ppm
141.446 MP/s
48.705 bits/pixel
build/fast_lossless /tmp/noise-15.ppm
117.555 MP/s
62.039 bits/pixel
build/fast_lossless /tmp/noise-16.ppm
119.843 MP/s
66.092 …
```
> [fast-lossless] Speedup and enable (if supported) AVX512 by default 

- lib/jxl/decode_test.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/encode_test.cc
- lib/jxl/jxl_test.cc
This seems to reduce other red-green border artefacts, too.
Butteraugli and ssimulacra2 don't agree that this is an improvement, but the red-green image becomes bearable after this PR and other main artefacts are reduced.
Butteraugli thinks this is a 0.3 % degradation
SSIMULACRA2 thinks something like 0.1 %
DZgas' test image at d1 gets ~7 % more bytes as adaptive quantization allocates more bits in red/green saturated areas. The additional bytes sharpen the blurry text and fix some other remaining artefacts.
```
Before: …
```
> DZgas' red-green test image correction

- lib/jpegli.cmake
- lib/jpegli/common.cc
- lib/jpegli/common.h
- lib/jpegli/decode.cc
- lib/jpegli/decode.h
- lib/jpegli/decode_api_test.cc
- lib/jpegli/decode_marker.cc
- lib/jpegli/destination_manager.cc
- lib/jpegli/encode.cc
- lib/jpegli/encode.h
- lib/jpegli/encode_api_test.cc
- lib/jpegli/error.cc
- lib/jpegli/libjpeg_wrapper.cc
- lib/jpegli/source_manager.cc
This way the jpegli-static library can be independently tested and it can be linked to applications that want to use 16-bit input/output.
The libjpeg.so library is built with a single additional libjpeg_wrapper.cc and it links to libjpeg-static.
> Build a separate jpegli-static library that libjpeg.so depends on.

- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/encode_test.cc
- lib/jxl/jxl_test.cc
flattens masking dynamics a bit, uses resulting bytes for usual ac quantization
reduces max-butteraugli by about 1 % while everything else is more or less unchanged
improved DZgas' image slightly (red pixelized symbols become more 'readable')
```
Before:
jxl:d0.1        18611 15065296    6.4755748   1.518   9.140   1.12765002  99.91226860 …
```
> minor masking adjustment

- lib/jxl/modular_test.cc
- lib/jxl/test_utils.h
The following commit allow the
`DecodeTest/DecodeTestParam.PixelTest/301x33*f16*` test family to pass on big-endian architectures.
> Fix big-endian test for float16

- lib/jxl/enc_modular.cc
- lib/jxl/modular/encoding/enc_ma.cc
Namely:
libjxl/lib/jxl/enc_modular.cc:685:28: runtime error: signed integer overflow: 1058273171 - -1373346182 cannot be represented in type 'int' libjxl/lib/jxl/enc_modular.cc:1372:26: runtime error: signed integer overflow: 1057915026 - -1419157404 cannot be represented in type 'int' libjxl/lib/jxl/modular/encoding/enc_ma.cc:980:35: runtime error: signed integer overflow: -1321495375 - 880855586 cannot be represented in type 'int'
Steps:
% tools/cjxl -d 0.0 /usr/share/libjxl-testdata/jxl/splines.pfm /tmp/test.jxl
> Fix a bunch of ubsan/signed integer overflow errors

- lib/jxl/enc_frame.cc
> Ensure that the number of palette colors is representable.

- lib/jxl/enc_fast_lossless.cc
Some bit concatenation was happening with 32 bits instead of 64.
Fixes #2039
> Fix RLE in fast-lossless.

- CHANGELOG.md
- lib/extras/enc/jxl.cc
- lib/extras/enc/jxl.h
- lib/include/jxl/encode.h
- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
- tools/cjxl_main.cc
```
tools/cjxl 211207159-817bc091-3110-48a1-ab60-63c8424e36e1.png -d 0 -e 10 x.jxl
JPEG XL encoder v0.8.0 31e38dae [AVX3,AVX2,SSE4,SSSE3,Unknown]
Invalid flag value for --effort: Valid range is {1, 2, ..., 9}.
tools/cjxl 211207159-817bc091-3110-48a1-ab60-63c8424e36e1.png -d 0 -e 10 x.jxl --allow_expert_options
JPEG XL encoder v0.8.0 31e38dae [AVX3,AVX2,SSE4,SSSE3,Unknown]
./lib/extras/dec/color_hints.cc:54: No color_space/icc_pathname given, assuming sRGB
Read 451x384 image, 1137 bytes, 145.2 MP/s
Encoding [Modular, lossless, effort: 10],
Compressed to 251 bytes (0.012 bpp).
451 x 384, 0.02 MP/s [0.02, 0.02], 1 reps, 72 threads.
tools/cjxl 211207159-817bc091-3110-48a1-ab60-63c8424e36e1.png -d 0 -e 11 x.jxl --allow_expert_options
JPEG XL encoder v0.8.0 31e38dae …
```
> Add an explicit flag to allow effort 10.

- lib/jxl/enc_fast_lossless.cc
Thanks to @Maximus- for pointing this out.
> Fix out-of-bounds vector access in fast_lossless.

- lib/extras/codec_test.cc
- lib/extras/enc/encode.cc
- lib/extras/enc/encode.h
- lib/extras/enc/jpegli.cc
- lib/extras/enc/jpegli.h
- tools/benchmark/benchmark_codec_jpeg.cc
- tools/cjpeg_hdr.cc
This is consistent with the extras::DecodeJpeg API as well as the rest of the codec APIs in lib/extras.
> Change extras::EncodeJpeg to take PackedPixelFile as input.

- lib/jxl/enc_color_management.cc
We change the order of evaluations in some if statements in order to avoid calling EnumValid when it is in fact not valid, e.g. when color_primaries==12.
> Avoid EnumValid as much as possible

- README.md
- doc/encode_effort.md
Some updates/additions to the main README, and a new documentation file explaining what encode effort actually means (which is not just "higher effort implies smaller files" as some people would expect), and what exactly the various effort settings are doing.
> update README.md and add description of encode effort settings

- lib/extras/dec/decode.cc
- lib/extras/dec/jpegli.cc
- lib/extras/dec/jpg.cc
- lib/extras/dec/jpg.h
- lib/jpegli/common.cc
- lib/jpegli/common.h
- lib/jpegli/decode.cc
- lib/jpegli/decode.h
- lib/jpegli/decode_api_test.cc
- lib/jpegli/decode_internal.h
- lib/jpegli/encode.h
- lib/jpegli/encode_api_test.cc
- lib/jpegli/render.cc
- tools/benchmark/benchmark_codec_jpeg.cc
- tools/cjxl_main.cc
This new API function replaces the previous and somewhat hacky way of setting the output bit depth through the libjpeg API.
> Add jpegli_set_output_format() API function to jpegli decoder.

- lib/jpegli/dct.cc
- lib/jpegli/encode_api_test.cc
This does not seem to help any more with the current quantization matrix and entropy coding.
Benchmark before (jpegli encoding libjpeg decoding):
```
jpeg:enc-jpegli:q95          13270  5794758    3.4933305   5.119  27.937   1.38596916  93.46103343   0.46287938  1.616990638243      0
jpeg:enc-jpegli:q90          13270  3936787    2.3732653   5.477  34.725   1.91680062  87.25703326   0.65623733  1.557425270742      0
jpeg:enc-jpegli:q85          13270  3057394    1.8431292   5.516  37.937   2.62046552  82.52436872 …
```
> Remove the AQ-based drop of the LSB in jpegli quantization.

- lib/extras/jpegli_test.cc
- lib/jpegli/dct.cc
- lib/jpegli/dct.h
- lib/jpegli/encode.cc
- lib/jpegli/encode_api_test.cc
- tools/optimizer/update_jpegli_global_scale.py
Add python script to update global scale to match libjpeg quality 90 pnorm.
```
jpeg:enc-jpegli:q95          13270  5370748    3.2377189   4.330  27.512   1.50571752  93.15828805   0.48245202  1.562044043045      0
jpeg:enc-jpegli:q90          13270  3625700    2.1857286   5.520  33.601   2.15366292  86.57551788   0.68660493  1.500732036613      0
jpeg:enc-jpegli:q85          13270  2804097    1.6904308   5.355  35.518   2.48398638  82.22072505   0.87241299  1.474753809926      0
jpeg:enc-jpegli:xyb:q95 …
```
> Tweak jpegli adaptive zeroing parameters.

- lib/extras/enc/jpegli.cc
- lib/extras/enc/jpegli.h
- lib/jpegli/dct.cc
- lib/jpegli/encode.cc
- lib/jpegli/encode.h
- lib/jpegli/encode_api_test.cc
- lib/jpegli/encode_internal.h
- lib/jpegli/quant.cc
- lib/jpegli/quant.h
- tools/benchmark/benchmark_codec_jpeg.cc
```
Encoding                           kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs
----------------------------------------------------------------------------------------------------------------------------------------------
jpeg:enc-jpegli:q90                  13270  3594661    2.1670170   4.955  33.316   2.19617844  86.24572089   0.68664849  1.487978923693      0
jpeg:enc-jpegli:q90:p0               13270  3679628    2.2182387  12.169  94.790   2.19617844  86.24572089   0.68664849  1.523150280661      0
jpeg:enc-jpegli:q90:p0:noaq          13270  3980121    2.3993889  16.038  84.961   2.46895504  88.28771516   0.68333374  1.639583394752      0
jpeg:enc-jpegli:q90:p0:noaq:std      13270  4794182 …
```
> Add jpegli_use_standard_quant_tables() API function.

- lib/jpegli.cmake
- lib/jpegli/bitstream.cc
- lib/jpegli/bitstream.h
- lib/jpegli/common_internal.h
- lib/jpegli/dct.cc
- lib/jpegli/dct.h
- lib/jpegli/decode_internal.h
- lib/jpegli/decode_marker.cc
- lib/jpegli/decode_scan.cc
- lib/jpegli/encode.cc
- lib/jpegli/encode.h
- lib/jpegli/encode_api_test.cc
- lib/jpegli/encode_internal.h
- lib/jpegli/entropy_coding.cc
- lib/jpegli/entropy_coding.h
- lib/jpegli/huffman.h
- lib/jpegli/quant.cc
- lib/jpegli/quant.h
This also simplifies the code a bit since we don't need bit-exact reconstruction and we can store most things we need in cinfo instead of jpeg_data.
> jpegli encoder: remove dependence on lib/jxl/jpeg

- lib/extras/jpegli_test.cc
- lib/jpegli/render.cc
Since apparently sqrt(x * x) - x can be negative for some floats we now explicitly skip bias computation for all-zero blocks.
Fixes #2094
> Fix dequantization bias computation for all-zero-AC blocks.

- lib/extras/jpegli_test.cc
- lib/jpegli.cmake
- lib/jpegli/adaptive_quantization.cc
- lib/jpegli/adaptive_quantization.h
- lib/jpegli/color_transform.cc
- lib/jpegli/color_transform.h
- lib/jpegli/dct.cc
- lib/jpegli/encode.cc
- lib/jpegli/encode_api_test.cc
- lib/jpegli/encode_internal.h
This works for Y channel of both YUV and XYB colorspaces.
```
jpeg:enc-jpegli:q90          13270  3594661    2.1670170   6.487  35.901   2.19617844  86.24572089   0.68664849  1.487978923693      0
jpeg:enc-jpegli:xyb:q90      13270  3170952    1.9115869   7.518  44.012   1.90134680  84.71284882   0.68652196  1.312346361599      0
Aggregate:                   13270  3376166    2.0352988   6.983  39.750   2.04345219  85.47584872   0.68658522  1.397406070777      0
```
```
Encoding …
```
> Use Y-channel-only adaptive quantization in jpegli encoder.

- tools/benchmark/benchmark_codec.h
- tools/benchmark/benchmark_codec_jxl.cc
- tools/benchmark/benchmark_xl.cc
`benchmark_xl` has this specific optimization to convert the input image to linear RGB at load time when all tested codecs don't care about the input colorspace (i.e. are going to do jxl in xyb space), so some time can be saved on color conversions (since it only needs to be converted once per image, instead of once per encode and then again to compute the metrics).
This optimization currently causes some trouble on images with alpha: the ssimulacra2 scores are completely wrong in this case:
Before:
```
./OwlAlpha.png
Encoding      kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs
-------------------------------------------------------------------------------------------------------------------------
jxl              1228   107314 …
```
> remove all_color_aware optimization in benchmark_xl

- cmake/FindBrotli.cmake
- third_party/CMakeLists.txt
Commit google/brotli@641bec0 ensures that Brotli honors the `BUILD_SHARED_LIBS` option in CMake, making commit 43323c0 and 6f20853 redundant.
Resolves #1694.
> CMake: clean-up after Brotli update

- lib/jpegli/adaptive_quantization.cc
- lib/jpegli/bitstream.cc
- lib/jpegli/common_internal.h
- lib/jpegli/dct.cc
- lib/jpegli/decode_internal.h
- lib/jpegli/encode.cc
- lib/jpegli/encode_api_test.cc
- lib/jpegli/encode_internal.h
- lib/jpegli/entropy_coding.cc
- lib/jpegli/render.cc
Remove internal Image3F storage, replace with an array of RowBuffers.
Add test cases for invalid number of channels and unsupported color transforms.
> jpegli encoder: support 4-channel input images

- lib/jpegli/bitstream.cc
- lib/jpegli/common_internal.h
- lib/jpegli/decode_marker.cc
- lib/jpegli/encode.cc
- lib/jpegli/encode_api_test.cc
Add tests that custom component ids work
> jpegli encoder: sanity check component id/index and data precision

- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/encode_test.cc
- lib/jxl/jxl_test.cc
This adds dc quality everywhere, but more on high quality images
It looks like we could detect if the image is 'grainy' by character and quantize DC more for images that have no polished slow gradients. That could creates 1-5 % more savings. Before that, let's quantize less, so that great worst case performance is quaranteed.
```
Before:
jxl:d0.1 …
```
> more dc values to fix DZgas' latest findings

- lib/jxl/enc_group.cc
- lib/jxl/encode_test.cc
- lib/jxl/jxl_test.cc
This with jyrki31 test corpus + one 1024x1024 chessboard image (with many 64x64 chessboards of various colors and intensities)
Notably, at d2.0 the maximum error goes down from 30 to 3.5. That is mostly indicative how poorly pixel chessboards worked before.
Afterwards, the pixel chessboards look mostly good, with the exception of chessboards with X or B channel only -- because this heuristic only looks at Y channel.
```
Before:
----------------------------------------------------------------------------------------------------------------------------------------------- …
```
> Quantization mitigation for pixel chessboards

- lib/extras/enc/jpegli.cc
- lib/extras/enc/jpegli.h
- tools/benchmark/benchmark_codec_jpeg.cc
Example benchmark output:
```
Encoding                      kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs
-----------------------------------------------------------------------------------------------------------------------------------------
jpeg:q80                        13270  3185957    1.9206325  42.855 110.438   3.87432337  83.66896084   0.98216786  1.886383532368      0
jpeg:enc-jpegli:Q80             13270  3186422    1.9209128   0.878  38.530   2.81853485  84.90585484   0.76798638  1.475234906282      0
jpeg:q80:yuv420                 13270  2479762    1.4949077  63.668 166.356   6.31123829  77.72421936   1.23785681  1.850481645598      0
jpeg:enc-jpegli:Q80:YUV420      13270  2477555    1.4935772   0.816  43.066 …
```
> Add "encode to same size as libjpeg" option to jpegli benchmark

- lib/jxl/enc_group.cc
- lib/jxl/jxl_test.cc
3-4 % better Max Norm, some improvement in BPP*pnorm, pnorm, while size is reduced.
The detrimental impact of previous heuristics greatly reduced at d0.1 and d0.5
```
Before:
jxl:d0.1        19660 15915521    6.4761682   1.511   9.198   3.23348093  98.99428664   0.17878710  51.72   7.029 38.2944 20.1303  0.5785 28.8039  6.3478  0.0000  2.8243 …
```
> some improvement in chessboard heuristics

- tools/jxl-eval.sh
Example output
Mozjpeg quality 90
https://storage.googleapis.com/jxl-quality/eval/szabadka/jyrki31/279ed6ad/base/index.jpeg_q90.html
Jpegli at the same size
https://storage.googleapis.com/jxl-quality/eval/szabadka/jyrki31/279ed6ad/base/index.jpeg_enc-jpegli_Q90.html
Mozjpeg quality 85 (added yuv422 since that is the default for mozjpeg's cjpeg binary for quality range 80-89): https://storage.googleapis.com/jxl-quality/eval/szabadka/jyrki31/279ed6ad/base/index.jpeg_q85_yuv422.html
Jpegli at the same size:
https://storage.googleapis.com/jxl-quality/eval/szabadka/jyrki31/279ed6ad/base/index.jpeg_enc-jpegli_Q85_YUV422.html
> Add shell script to generate quality eval pages for jxl/jpegli

- tools/djxl_main.cc
Currently having the verbosity 1 set for disable_output makes it impossible to get help for this flag, because we don't have a `-v` fla for djxl. The fix is to don't set a verbosity level for this flag.
> only 1 verbosity level for djxl

- CHANGELOG.md
- lib/extras/enc/jxl.cc
- lib/extras/enc/jxl.h
- lib/include/jxl/encode.h
- lib/jxl/enc_modular.cc
- lib/jxl/enc_params.h
- lib/jxl/encode.cc
- lib/jxl/jxl_test.cc
- tools/benchmark/benchmark_codec_jxl.cc
- tools/cjxl_main.cc
Adds an option to the API to set the distance for extra channels separately, addressing #2111 .
This e.g. allows doing lossless alpha while the color is lossy, or in general to set the alpha quality independently of the color quality. We might want to experiment with this and set more sensible defaults. (Note: we can't really rely on the metrics though, since they don't really look at alpha, they just use it to blend the image to a solid background.)
Adds a parameter `D` to benchmark_xl and `--alpha_distance` to cjxl.
Flyby fix: correct the modular quantization adjustment to compensate for the actual bitdepth of extra channels (instead of assuming that all channels have the same bitdepth).
```
Encoding       kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2 …
```
> Alpha distance

- lib/jxl/decode.cc
According to decode.h, `JxlDecoderRewind` should keep the previously subscribed decoder events, but it actually forgets them.  I think this fixes it.
> Decoder API: remember subscribed events after JxlDecoderRewind

- BUILDING.md
- BUILDING_Haiku.md
- BUILDING_OSX.md
- README.md
- plugins/gdk-pixbuf/README.md
- plugins/mime/README.md
Compilation instructions don't need to be on the front page — people who just want to try jxl will generally just want to get a cjxl/djxl they can run. This puts the compilation instructions in a separate file (BUILDING.md) and puts some installation info on the front page, including a bunch of badges for the more popular linux distros and some pointers for MacOS and Windows.
> update README to have installation info (moving build instructions to a separate file)

- plugins/gimp/file-jxl-save.cc
Lossless encoding fails without this patch because the basic info isn't set early enough in the encode process. This fixes that so the basic info is set before the distance so the distance and frame addition does not fail.
> plugins/gimp/file-jxl-save: set basic info earlier to fix lossless

- lib/jpegli/adaptive_quantization.cc
- lib/jpegli/encode.cc
- lib/jpegli/encode_api_test.cc
Fix a bug caused by too small AQ map with subsampled luma.
> jpegli: add tests for unusual sampling ratios.

- lib/jpegli/decode.cc
- lib/jpegli/decode.h
- lib/jpegli/decode_marker.cc
- lib/jpegli/encode.cc
- lib/jpegli/encode.h
- lib/jpegli/encode_api_test.cc
- lib/jpegli/libjpeg_wrapper.cc
- lib/jpegli/quant.cc
- lib/jpegli/test_utils.h
- lib/jpegli/transcode_api_test.cc
- lib/jxl_lists.bzl
- lib/jxl_lists.cmake
Added jpegli_read_coefficients() and jpegli_copy_critical_parameters()
Refactored the test config into input image and compression params, and added a transcode_api_test.cc which resuses the code for jpeg file generation with jpegli and jpeg file verification with libjpeg.
> Implement the rest of the transcoding functions in jpegli.

- plugins/gimp/file-jxl-save.cc
After the last patch, the JPEG XL exporter no longer crashes upon lossless exports but it converts sRGB images to linear before feeding them to libjxl, but it tells libjxl that they are sRGB, resulting in incorrect colors. This patch fixes that issue.
> plugins/gimp/file-jxl-save: dont submit sRGB-tagged linear samples

- AUTHORS
- lib/jxl/enc_xyb.cc
compiling v0.8.1 of libjxl for riscv64 is currently broken with:
```
[ 33%] Building CXX object lib/CMakeFiles/jxl_enc-obj.dir/jxl/jpeg/enc_jpeg_data.cc.o
/build/libjxl/src/libjxl/lib/jxl/enc_xyb.cc: In function ‘jxl::Image3F jxl::N_SCALAR::TransformToLinearRGB(const jxl::Image3F&, const jxl::ColorEncoding&, float, const JxlCmsInterface&, jxl::ThreadPool*)’:
/build/libjxl/src/libjxl/lib/jxl/enc_xyb.cc:223:21: error: variable ‘std::atomic<bool> ok’ has initializer but incomplete type
223 |   std::atomic<bool> ok{true};
|                     ^~
[ 33%] Building CXX object lib/CMakeFiles/jxl_dec-obj.dir/jxl/gauss_blur.cc.o
[ 33%] Building CXX object lib/CMakeFiles/jxl_dec-obj.dir/jxl/headers.cc.o
make[2]: *** [lib/CMakeFiles/jxl_enc-obj.dir/build.make:566: …
```
> Add missing <atomic> content to fix gcc compilation for RISCV architecture.

- lib/jpegli/bitstream.cc
- lib/jpegli/bitstream.h
- lib/jpegli/encode.cc
- lib/jpegli/encode_internal.h
- lib/jpegli/entropy_coding.cc
- lib/jpegli/entropy_coding.h
Instead of going over the coefficients twice (once for histogram generation, once for bitstream output), we first gather a list of (histo index, symbol, extra bits) tokens, then build histograms from the tokens and then output the tokens to the bitstream.
```
Encoding                  kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs
-------------------------------------------------------------------------------------------------------------------------------------
jpeg:enc-jpegli:p0:q90      13270  3679226    2.2179964  30.876 195.221   2.26414490  86.30366270   0.68598218  1.521506008833      0
```
```
Encoding                  kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm …
```
> Add a faster encoding code-path for sequential jpegli.

- lib/jpegli/adaptive_quantization.cc
- lib/jpegli/dct.cc
The adaptive quantization path got a little bit faster as well by precomputing the inverse of the quantization field.
```
jpeg:enc-jpegli:q90:p0           13270  3679226    2.2179964  36.226 191.392   2.26414490  86.30366270   0.68598218  1.521506008833      0
jpeg:enc-jpegli:q90:p0:noaq      13270  4054300    2.4441072  43.646 173.163   2.29879761  88.59430808   0.67347722  1.646050522326      0
Aggregate:                       13270  3862213    2.3283086  39.763 182.050   2.28140546  87.44148490 …
```
> Faster no-adaptive-quantization code-path in jpegli encoder.

- lib/jpegli/dct.cc
```
jpeg:enc-jpegli:q90:p0           13270  3679226    2.2179964  39.669 196.711   2.26414490  86.30366270   0.68598218  1.521506008833      0
jpeg:enc-jpegli:q90:p0:noaq      13270  4054300    2.4441072  51.526 178.543   2.29879761  88.59430808   0.67347722  1.646050522326      0
jpeg:q90                         13270  4838710    2.9169834  64.179 167.310   2.40070152  91.22219875   0.68663652  2.002907346332      0
Aggregate:                       13270  4163584    2.5099882  50.811 180.453 …
```
> Simdify extra block-transposition and non-AQ quantization.

- lib/jpegli/bitstream.cc
- lib/jpegli/bitstream.h
- lib/jpegli/dct.cc
- lib/jpegli/dct.h
- lib/jpegli/encode.cc
- lib/jpegli/encode_internal.h
- lib/jpegli/entropy_coding.cc
- lib/jpegli/entropy_coding.h
- lib/jpegli/memory_manager.cc
- lib/jpegli/memory_manager.h
Use aligned allocators instead of vector for quantized coefficients, this also removes an unnecessary memset in the vector constructor.
> Support aligned allocators in the jpegli memory manager.

- lib/jpegli/adaptive_quantization.cc
- lib/jpegli/color_transform.cc
- lib/jpegli/dct.cc
- lib/jpegli/encode.cc
Instead do the scaling before adaptive quantization and adjust the multipliers in the DCT stage.
```
jpeg:enc-jpegli:p0:q90           13270  3679250    2.2180109  44.912 200.397   2.26414490  86.30579721   0.68598112  1.521513573278      0
jpeg:enc-jpegli:p0:noaq:q90      13270  4054221    2.4440596  68.389 182.477   2.29879761  88.59588680   0.67347566  1.646014648716      0
jpeg:q90                         13270  4838710    2.9169834  67.079 169.634   2.40070152  91.22219875   0.68663652 …
```
> Remove input scaling for 8-bit input in jpegli_write_scanlines()

- lib/jxl/decode_test.cc
- lib/jxl/enc_group.cc
- lib/jxl/jxl_test.cc
This increases quantization precision for high-frequency patterns without low precision content. This doesn't completely solve the chessboard pattern issues since the 32x32 etc. quantization matrices quantize rather heavily in chromacity high-frequency area, but is more of a small mitigation.
max error is reduced by 11 %, BPP*pnorm aggregate 0.2 %
This test is with the jyrki31 corpus augmented with the chessboard pattern.
This doesn't quite fix the problem fully, but is a substantial improvement.
```
Before:
------------------------------------------------------------- …
```
> quantization improvement for chromacity checkboard

- .github/workflows/build_test.yml
- lib/jpegli/adaptive_quantization.cc
- lib/jpegli/common_internal.h
- lib/jpegli/render.cc
- lib/jpegli/simd.cc
- lib/jpegli/simd.h
- lib/jxl_lists.bzl
- lib/jxl_lists.cmake
Adaptive quantization was the last place where we used it, this change removes the need of one image copy and one image scaling. The input scaling factor is rolled into the various constants.
```
Encoding                  kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs
-------------------------------------------------------------------------------------------------------------------------------------
jpeg:enc-jpegli:p0:q90      13270  3679204    2.2179831  73.002 200.177   2.26414490  86.30231498   0.68598247  1.521497538051      0
jpeg:q90                    13270  4838710    2.9169834  68.118 171.392   2.40070152  91.22219875   0.68663652  2.002907346332      0
Aggregate:                  13270  4219313 …
```
> Remove the dependence on ImageF from the jpegli encoder.

- .github/workflows/debug_ci.yml
- ci.sh
- lib/extras/enc/jpegli.cc
- lib/jpegli/dct.cc
- lib/jpegli/encode.cc
- lib/jpegli/encode_api_test.cc
- lib/jpegli/encode_internal.h
- lib/jpegli/input.cc
- lib/jpegli/input.h
- lib/jpegli/test_utils.cc
- lib/jpegli/test_utils.h
- lib/jpegli/transcode_api_test.cc
- lib/jxl_lists.bzl
- lib/jxl_lists.cmake
drive-by: use DirectRow() instead of the (cyclical) Row() in dct.cc
```
Encoding                  kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs
-------------------------------------------------------------------------------------------------------------------------------------
jpeg:enc-jpegli:p0:q90      13270  3679204    2.2179831  78.468 200.201   2.26414490  86.30231498   0.68598247  1.521497538051      0
jpeg:q90                    13270  4838710    2.9169834  67.006 169.425   2.40070152  91.22219875   0.68663652  2.002907346332      0
Aggregate:                  13270  4219313    2.5435841  72.511 184.172   2.33142362  88.72816311   0.68630941  1.745685709510      0
```
```
Encoding …
```
> SIMDify input deinterleaving.

- lib/extras/jpegli_test.cc
- lib/jpegli/adaptive_quantization.cc
- lib/jpegli/encode.cc
- lib/jpegli/encode_api_test.cc
- lib/jpegli/encode_internal.h
- lib/jpegli/quant.cc
We write DQT and SOF in the first call to jpegli_write_scanlines() or jpegli_write_raw_data(). To make this work quant_field_max was removed from quant table calculation and the relevant constants were updated. The effect on size/quality seems to be neutral on all metrics.
```
jpeg:enc-jpegli:q90          13270  3592229    2.1655508  18.380  68.514   2.26414490  86.30231498   0.68598247  1.485529907995      0
jpeg:enc-jpegli:xyb:q90      13270  3108580    1.8739863  18.852  79.471   2.23073959  84.88789541 …
```
> Preparations for streaming encoder: write DQT and SOF earlier.

- third_party/CMakeLists.txt
This partially reverts commit b0f3014. 
---
The issue mentioned in that commit will be fixed with PR #2144 instead. Sorry for the confusion.
> CMake: allow bundling of shared Brotli libs

- lib/jpegli/downsample.cc
- lib/jpegli/downsample.h
- lib/jpegli/encode.cc
- lib/jpegli/encode_internal.h
- lib/jxl_lists.bzl
- lib/jxl_lists.cmake
```
Encoding                         kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs
--------------------------------------------------------------------------------------------------------------------------------------------
jpeg:enc-jpegli:p0:q90:yuv420      13270  3198546    1.9282217  67.487 270.751   6.51610565  77.44071666   1.02397616  1.974453078519      0
jpeg:q90:yuv420                    13270  3660915    2.2069577  96.409 246.624   6.07282543  84.48148665   0.95039908  2.097490592689      0
Aggregate:                         13270  3421930    2.0628873  80.662 258.406   6.29056215  80.88452801   0.98650190  2.035042200520      0
```
```
Encoding                         kPixels …
```
> SIMDify chroma subsampling in jpegli encoder.

- lib/extras/jpegli_test.cc
- lib/jpegli/adaptive_quantization.cc
- lib/jpegli/common_internal.h
- lib/jpegli/downsample.cc
- lib/jpegli/encode.cc
- lib/jpegli/encode_internal.h
Instead of comparing the quant field values to the quant field maximum, we compare it against a fixed constant. This changes the results slightly, but it looks neutral quality-wise.
```
jpeg:enc-jpegli:q90          13270  3587770    2.1628628  19.083  70.559   2.25433660  86.32254081   0.68681241  1.485480997421      0
jpeg:enc-jpegli:xyb:q90      13270  3108476    1.8739236  20.062  81.030   2.13027716  84.85884641   0.68753171  1.288381922542      0
jpeg:enc-jpegli:p0:q90       13270  3672874 …
```
> Streaming adaptive quantization field computation in jpegli.

- lib/jxl/decode_test.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_gaborish.cc
- lib/jxl/encode_test.cc
- lib/jxl/jxl_test.cc
- tools/optimizer/simplex_fork.py
10+ % improvement on max error
~7 % improvement for BPP * pnorm for high quality images ~3 % aggregate BPP * pnorm improvement
~0.5 improvement in SSIMULACRA2
This may be an improvement now mostly because the chessboard image is part of the test set now.
```
jxl:d0.1        19725 16002061    6.4897492   1.491   9.414   3.23409367  98.99529775 …
```
> reoptimized gaborish encoding

- lib/jpegli/bitstream.cc
- lib/jpegli/dct.cc
- lib/jpegli/encode.cc
- lib/jpegli/encode_internal.h
- lib/jpegli/entropy_coding.cc
- lib/jpegli/memory_manager.cc
This removes the need to copy the coefficient buffer when we do transcoding and we need one less data structure in jpeg_comp_master.
> Use the same type of coeff buffer for encoding and transcoding.

- lib/jpegli/adaptive_quantization.cc
- lib/jpegli/common_internal.h
- lib/jpegli/dct.cc
- lib/jpegli/downsample.cc
- lib/jpegli/encode.cc
- lib/jpegli/encode_internal.h
We now only need a ring-buffer of 3 iMCU rows. Similarly for the adaptive quantization map related structures we only allocate a ring-buffer of block rows.
> Don't allocate full input buffer in jpegli encoder.

- lib/jpegli/encode.cc
- lib/jpegli/encode_api_test.cc
- lib/jpegli/error.cc
- lib/jpegli/error.h
This change adds support for warning and trace messages, and an addon error message table that is used by eg. cjpeg/djpeg.
> Extend error manager support in jpegli.

- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_gaborish.cc
- lib/jxl/enc_group.cc
- lib/jxl/enc_heuristics.cc
- lib/jxl/jxl_test.cc
0.02 db better PSNR
0.24 % improved BPP*pnorm
Max norm reduced by 38 % and BPP*pnorm by 8 % at d0.1 
Max norm reduced by 7 % and BPP*pnorm by 0.37 % at d1
```
Before
jxl:d0.1        19791 16033582    6.4810008   1.444   8.938   1.38181531  99.69665288   0.13035467  52.68   6.539 40.0026 19.5743  0.4252 28.2471  5.4191  0.0000  2.9013  0.9261 …
```
> more optimizations for difficult images

- lib/jpegli/decode.cc
- lib/jpegli/decode_api_test.cc
- lib/jpegli/input_suspension_test.cc
- lib/jpegli/test_utils.cc
This caught a bug in the IsInputReady() function of the decoder.
> Add more expectations for input/output progress in jpegli tests.

- lib/jpegli/decode.cc
- lib/jpegli/decode_api_test.cc
- lib/jpegli/decode_scan.cc
- lib/jpegli/input_suspension_test.cc
- lib/jpegli/test_utils.h
This caught two bugs in the main decoding function.
> Add decoder tests for scan header and restart intervals.

- lib/jxl/decode_test.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_frame.cc
- lib/jxl/encode_test.cc
- lib/jxl/jxl_test.cc
Heuristics for deciding chromacity quantization multipliers based on individual pixels in the image (the worst colorful pixel).
Average BPP * pnorm improvement of ~0.4 %
```
Before:
jxl:d0.1        19988 16523292    6.6132527   1.468   9.103   0.82352817  99.92358975   0.11904343  53.30   6.613 40.2246 19.6242  0.4403 27.7621  5.5246  0.0000 …
```
> Improving difficult images, max error -25 %

- lib/jpegli/decode.cc
The bug was caused by jpegli_calc_output_dimensions() setting the sampling factor fields incorrectly when called multiple times with different scaling factor settings.
> Fix YUV420 rendering bug.

- .github/workflows/conformance.yml
- lib/jxl/color_management.cc
- lib/jxl/enc_color_management.cc
Before:
```console
$ tools/cjxl adobench.png output.jxl && tools/jxlinfo output.jxl
JPEG XL encoder v0.9.0 f8c984d67 [AVX2,SSE4,SSSE3,SSE2]
Read 500x606 image, 694182 bytes, 94.6 MP/s
Encoding [VarDCT, d1.000, effort: 7], 
Compressed to 130817 bytes (3.454 bpp).
500 x 606, 4.25 MP/s [4.25, 4.25], 1 reps, 56 threads.
JPEG XL image, 500x606, lossy, 8-bit RGB
Color space: 888-byte ICC profile, CMM type: "lcms", color space: "RGB ", rendering intent: 0
```
After:
```console
$ tools/cjxl adobench.png output.jxl && tools/jxlinfo output.jxl
JPEG XL encoder v0.9.0 8b7a98417 [AVX2,SSE4,SSSE3,SSE2]
Read 500x606 image, 694182 bytes, 96.4 MP/s
Encoding [VarDCT, d1.000, effort: 7], 
Compressed to 130553 bytes (3.447 bpp).
500 x 606, 4.73 MP/s [4.73, 4.73], 1 reps, 56 threads.
JPEG XL image, 500x606, …
```
> Detect gamma when appropriate

- lib/jpegli/decode.cc
- lib/jpegli/decode_api_test.cc
- lib/jpegli/decode_scan.cc
- lib/jpegli/input_suspension_test.cc
- lib/jpegli/test_utils.cc
- lib/jpegli/test_utils.h
drive-by: fix previous asan/msan failures
> Support jpegli_read_coefficients() in buffered image mode.

- lib/extras/enc/jpegli.cc
- lib/jpegli/bitstream.cc
- lib/jpegli/decode.cc
- lib/jpegli/decode_api_test.cc
- lib/jpegli/decode_internal.h
- lib/jpegli/destination_manager.cc
- lib/jpegli/encode.cc
- lib/jpegli/encode.h
- lib/jpegli/encode_api_test.cc
- lib/jpegli/encode_internal.h
- lib/jpegli/quant.cc
- lib/jpegli/quant.h
- lib/jpegli/source_manager.cc
- lib/jpegli/test_utils.cc
- lib/jpegli/test_utils.h
To make this work, the quantization matrices have to be defined in the parameter setup phase, which means that we can not look at the ICC profile, so the CICP transfer function has to be communicated separately.
Moreover, to be more compatible with libjpeg API, we only define one chroma quantization table by default, but we define two chroma quant tables if the new jpegli_set_distance() API function was called.
> Support cinfo reuse in jpegli encoder and decoder.

- lib/jxl/decode_test.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_group.cc
- lib/jxl/encode_test.cc
- lib/jxl/jxl_test.cc
- tools/optimizer/simplex_fork.py
0.16 % improvement on bpp * pnorm
looks slightly better
is faster and removes a hairy goto
```
Before:
jxl:d0.1        19988 16558847    6.6274831   1.504   9.130   0.37474449  99.91563915   0.11897888  53.46   6.627 40.1468 19.6738  0.4364 27.7147  5.5886  0.0000  3.0380  0.9324  3.0124  0.1025  0.0820  0.788530544762      0
jxl:d0.5        19988 …
```
> quantization improvement

- lib/jpegli/decode.cc
- lib/jpegli/decode_marker.cc
- lib/jpegli/source_manager.cc
drive-by: add some more TODO's regarding marker processing
> Add default implementation for skip_input_data() callback.

- AUTHORS
- lib/jxl/enc_fast_lossless.cc
The previous check was incorrect for a few reasons:
- The definition is missing in all Clang versions older than 10, not just Apple's[[1]].
- The OS version doesn't determine which compiler is used; a Mojave system could be running the latest Clang release.
- Whether `__MAC_10_0` is defined doesn't tell you which OS version you are building on or for, so a conflicting definition was added on newer OS versions where the default compiler already has it.
Closes: #2291
[1]: https://github.com/llvm/llvm-project/commit/caac097fbf4e0883a675feb2ee38407def08b5a6
> Fix condition for defining _mm512_cvtsi512_si32

- lib/jxl/enc_fast_lossless.cc
- lib/jxl/image.cc
The `__clang_major__` macro provides a marketing version which is not required to be consistent between vendors[[1]]. And indeed, Apple uses a versioning scheme for its Clang releases that is unrelated to that of the llvm.org releases on which they are based. The correspondences between the versions can however be determined[[2]].
So, checking whether `__apple_build_version__` is defined is necessary to determine whether an Apple version of Clang is being used, so that the correct version check can be done. Checking the value of that macro is simpler for the purposes of this code than checking (a different value of) `__clang_major__`, because distinguishing between the relevant versions of Apple Clang would also require checking `__clang_minor__` and `__clang_patchlevel__`.
Closes: #2260 …
> Check version of Apple clang correctly

- lib/jpegli/bit_writer.cc
- lib/jpegli/bit_writer.h
- lib/jpegli/bitstream.cc
- lib/jpegli/color_quantize.cc
- lib/jpegli/common.cc
- lib/jpegli/common_internal.h
- lib/jpegli/decode.cc
- lib/jpegli/decode_internal.h
- lib/jpegli/decode_marker.cc
- lib/jpegli/encode.cc
- lib/jpegli/encode_internal.h
- lib/jpegli/entropy_coding.cc
- lib/jpegli/entropy_coding.h
- lib/jpegli/render.cc
This PR removes some std::vector, std::array, etc. based allocations and replaces them with the cinfo->mem based allocator.
> Use jpegli's own memory manager for heap allocations more often.

- lib/jxl/decode_test.cc
- lib/jxl/enc_ac_strategy.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/encode_test.cc
- lib/jxl/jxl_test.cc
try non-aligned 32x32 and 16x32 dcts, too
```
Before:
jxl:d0.1        19988 16631666    6.6566281   1.516   8.966   0.37648740  99.92763374   0.11894861  53.49   6.657 40.3459 19.5387  0.4390 27.7660  5.4849  0.0000  3.0136  0.9221  3.0328  0.1025  0.0820  0.791796646022      0
jxl:d0.5        19988  6314769    2.5274118   1.998  14.137 …
```
> small vardct quality improvement (0.1 %)

- lib/jpegli/decode.cc
- lib/jpegli/huffman.h
This fixes -Werror=class-memaccess an error introduced in https://github.com/libjxl/libjxl/commit/1112ef0e263600f9bc7f0cbc735fcd0d004af33d
assuming the constructor is not used anymore
> remove constructor for HuffmanTableEntry

- lib/jxl/splines.cc
fixes #2171
After having the new spline area estimate, we can remove this check to prevent CPU bombs.
> disable old spline area limit

- lib/jxl/decode_test.cc
- lib/jxl/enc_ac_strategy.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/jxl_test.cc
- tools/optimizer/simplex_fork.py
0.5 % improvement on image quality (BPP * pnorm)
close to 2 % improvement at d1
looks ok in manual viewing, too
```
Before:
jxl:d0.1        19988 16632798    6.6570812   1.524   8.861   0.37712332  99.92071497   0.11893726  53.50   6.657 40.3709 19.4916  0.4367 27.7628  5.4151  0.0000  2.7421  0.9221  3.4017  0.1025  0.0820  0.791774977142      0 …
```
> Adjust HfModulation in initial adaptive quant

- lib/jxl/decode_test.cc
- lib/jxl/enc_group.cc
- lib/jxl/jxl_test.cc
1.2 % improvement in BPP * pnorm
~2 % improvement on Max norm
looks nicer, especially text/graphics
```
Before:
jxl:d0.1        19988 16900604    6.7642674   1.516   9.094   0.37410482  95.47297329   0.11561354  53.54   6.764 41.8880 18.7084  0.4624 27.5303  5.0264  0.0000  2.4347  0.9017  3.5913  0.1025  0.0820  0.782040912825      0
jxl:d0.5 …
```
> Improve Adaptive Quantization after AC Strategy

- AUTHORS
- examples/decode_oneshot.cc
- examples/decode_progressive.cc
- lib/jxl/base/status.h
- lib/jxl/image_test_utils.h
- tools/speed_stats.cc
This is well-known error:
```
:info:build [ 71%] Building C object tools/CMakeFiles/jxlinfo.dir/jxlinfo.c.o
:info:build cd /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_graphics_libjxl/libjxl/work/build/tools && /opt/local/bin/gcc-mp-12 -DHWY_DISABLED_TARGETS="(HWY_SVE|HWY_SVE2|HWY_SVE_256|HWY_SVE2_128|HWY_RVV)" -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_graphics_libjxl/libjxl/work/libjxl-0.8.1/lib/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_graphics_libjxl/libjxl/work/build/lib/include -pipe -Os …
```
> Unbreak build on macOS with GCC: add __STDC_FORMAT_MACROS where needed

- lib/jxl/alpha.cc
Spec says `clamp` has to be conditionally applied also in kMulAdd (AlphaWeightedAdd) blending, but it looks like libjxl is just ignoring the condition and always doing clamping. This makes libjxl do it as in the spec instead.
> fix alpha clamping in kMulAdd blending

- lib/jpegli/adaptive_quantization.cc
- lib/jpegli/decode_api_test.cc
- lib/jpegli/encode.cc
- lib/jpegli/encode_internal.h
- lib/jpegli/quant.cc
- lib/jpegli/quant.h
This is because in some cases distance is not known becasue the quantization matrix got updated outside of a jpegli_set_quality() or jpegli_set_distance() call.
> Use quantization matrix values instead of distance in encoder.

- .github/workflows/release.yaml
This should add more tools (such as butteraugli_main and ssimulacra2) to the Windows and Linux binaries in the CI artifacts and future releases.
> add devtools to the artifacts

- lib/jpegli/adaptive_quantization.cc
- lib/jpegli/adaptive_quantization.h
- lib/jpegli/quant.cc
- tools/scripts/jpegli_tools_test.sh
Benchmarks on jyrki31 corpus:
```
Encoding                      kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs
-----------------------------------------------------------------------------------------------------------------------------------------
BEFORE:
jpeg:enc-jpegli:Q65:YUV420      13270  1430697    0.8624860   1.120  46.304   3.94868069  65.09968044   1.61473877  1.392689527227      0
jpeg:enc-jpegli:Q75:YUV420      13270  1776531    1.0709696   1.051  50.961   3.19333309  71.40137002   1.32800514  1.422253188587      0
jpeg:enc-jpegli:Q80:YUV420      13270  2086102    1.2575924   1.045  47.581   2.74619906  75.35488383   1.14550312  1.440576029150      0
jpeg:enc-jpegli:Q85:YUV420      13270  2455852    1.4804937   0.967 …
```
> Non-linear quantization matrix scaling in jpegli encoder.

- lib/extras/dec/apng.cc
See #2457
Prevents cjxl from crashing or producing crazy output when decoding a 16-bit PNG into an 8-bit buffer.
This still isn't completely correct (except in the specific case of a 16-bit PNG with sBIT=8 for all channels), because it can only discard 0 or 8 bits. Any remaining insignificant bits (as per sBIT) can still affect the color when they're not supposed to.
e.g. for 8-bit grayscale with sBIT = 4, the two samples 0x00 and 0x0F are currently passed along unmodified, so they produce different colors when converted to lossless JXL. If I understand correctly, the PNG decoder is supposed to turn them both into pure black.
> Partial fix for PNG sBIT handling in cjxl

- lib/extras/jpegli_test.cc
- lib/jpegli/adaptive_quantization.cc
- lib/jpegli/bitstream.cc
- lib/jpegli/dct-inl.h
- lib/jpegli/dct.cc
- lib/jpegli/dct.h
- lib/jpegli/decode_api_test.cc
- lib/jpegli/encode.cc
- lib/jpegli/encode_api_test.cc
- lib/jpegli/encode_internal.h
- lib/jpegli/input_suspension_test.cc
- lib/jpegli/quant.cc
- lib/jpegli/transpose-inl.h
- tools/optimizer/update_jpegli_global_scale.py
- tools/scripts/jpegli_tools_test.sh
Benchmark results on jyrki31 corpus:
```
Encoding                      kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs
-----------------------------------------------------------------------------------------------------------------------------------------
BEFORE:
jpeg:enc-jpegli:Q90             13270  4681116    2.8219790   0.598  26.349   1.27255321  88.00687122   0.53531399  1.510644830124      0
jpeg:enc-jpegli:Q85             13270  3573716    2.1543904   0.632  30.351   1.61245817  84.91516370   0.68812425  1.482488278521      0
jpeg:enc-jpegli:Q85:YUV422      13270  2856952    1.7222941   0.784  32.775   1.99105390  81.71974604   0.85125798  1.466116598017      0
jpeg:enc-jpegli:Q85:YUV420      13270  2455115    1.4800494 …
```
> Use frequency dependent dead zone multipliers.

- lib/jpegli/encode_api_test.cc
- lib/jpegli/entropy_coding.cc
- lib/jpegli/quant.cc
- lib/jpegli/test_utils.cc
- tools/scripts/jpegli_tools_test.sh
Benchmark on jyrki31 corpus:
```
Encoding                             kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs
------------------------------------------------------------------------------------------------------------------------------------------------
BEFORE:
jpeg:enc-jpegli:yuv420                 13270  3065816    1.8482063  14.104  54.140   3.22283839  76.87140839   1.02752502  1.899078256579      0
jpeg:enc-jpegli:yuv420:Q85:YUV420      13270  2454814    1.4798679   1.242  60.195   3.61167194  72.99267191   1.18053870  1.747041371858      0
jpeg:enc-jpegli:yuv420:Q75:YUV420      13270  1776259    1.0708057   1.506  70.731   4.30828297  65.92608268   1.48627252  1.591509038309      0
jpeg:enc-jpegli:yuv420:Q65:YUV420 …
```
> Use different quant matrices for 444 and 420 modes.

- lib/jpegli/bitstream.cc
- lib/jpegli/bitstream.h
- lib/jpegli/encode.cc
- lib/jpegli/encode_internal.h
- lib/jpegli/entropy_coding.cc
Memory benchmarking results:
```
cjpeg    per       djpeg    per
Input           Encode args          Pixels     peak mem  pixel    peak mem  pixel
----------------------------------------------------------------------------------
BEFORE:
tiny.ppm        -sample 2x2             256       295468             243923
tiny.ppm        -sample 2x2 -o          256       336785             243560
tiny.ppm        -sample 2x2 -p          256       598884             243708
stp2.ppm        -sample 2x2          960000      1574892   1.64      918424   0.96
stp2.ppm        -sample 2x2 -o       960000      7527369   7.84      918765   0.96
stp2.ppm        -sample 2x2 -p       960000      5947204   6.20     4869331   5.07
NC003.ppm       -sample 2x2        45441024      9203724   0.20     4212018   0.09 …
```
> Don't use full image buffer in optimized-code jpegli encoder.

- .github/workflows/build_test.yml
- .github/workflows/build_test_cross.yml
- .github/workflows/build_test_md.yml
- .github/workflows/conformance.yml
- .github/workflows/debug_ci.yml
- .github/workflows/fuzz.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- .github/workflows/test_new_highway.yml
Fixes #2484.
As described in the issue, this PR ensures workflows run with minimal permissions, protecting the project from supply-chain attacks.
> Add read-only token permissions

- lib/jpegli/decode.cc
- lib/jpegli/render.cc
Memory benchmark results:
```
cjpeg    per       djpeg    per
Input           Encode args          Pixels     peak mem  pixel    peak mem  pixel
----------------------------------------------------------------------------------
BEFORE:
tiny.ppm        -sample 2x2             256       295508             211923
tiny.ppm        -sample 2x2 -o          256       302713             211560
tiny.ppm        -sample 2x2 -p          256       583484             211708
stp2.ppm        -sample 2x2          960000      1574932   1.64      894104   0.93
stp2.ppm        -sample 2x2 -o       960000      3429281   3.57      894445   0.93
stp2.ppm        -sample 2x2 -p       960000      4747804   4.95     3714771   3.87
NC003.ppm       -sample 2x2        45441024      9203764   0.20     4182322   0.09 …
```
> Move horizontal upsampling after vertical upsampling.

- lib/jpegli/decode.cc
- lib/jpegli/decode_internal.h
- lib/jpegli/render.cc
Memory benchmark results:
```
cjpeg    per       djpeg    per
Input           Encode args          Pixels     peak mem  pixel    peak mem  pixel
----------------------------------------------------------------------------------
BEFORE:
tiny.ppm        -sample 1x1             256       272996             206739
tiny.ppm        -sample 1x1 -o          256       281913             206381
tiny.ppm        -sample 1x1 -p          256       561572             207314
stp2.ppm        -sample 1x1          960000      1090276   1.14      760958   0.79
stp2.ppm        -sample 1x1 -o       960000      2947513   3.07      761577   0.79
stp2.ppm        -sample 1x1 -p       960000      7143764   7.44     6462516   6.73
NC003.ppm       -sample 1x1        45441024      5962308   0.13     3287009   0.07 …
```
> Don't use context rows for non-chroma-subsampled images.

- lib/jpegli/bitstream.cc
- lib/jpegli/encode.cc
- lib/jpegli/entropy_coding.cc
Benchmark results (encoding speed only):
```
Encoding               kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs
----------------------------------------------------------------------------------------------------------------------------------
BEFORE:
jpeg:enc-jpegli:q90      13270  3540894    2.1346039  18.780  71.479   0.99999997   0.00000000   0.00000000  0.000000000000      0
AFTER:
jpeg:enc-jpegli:q90      13270  3540894    2.1346039  19.722  71.590   0.99999997   0.00000000   0.00000000  0.000000000000      0
```
> Compute zig-zag order only once for progressive jpegli.

- lib/jpegli/bitstream.cc
- lib/jpegli/dct-inl.h
- lib/jpegli/quant.cc
This PR just adds the placeholders for the constants, it is now a no-op.
> Add support for adaptive DC dead-zone quantization.

- lib/jxl/decode_test.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_adaptive_quantization.h
- lib/jxl/enc_heuristics.cc
- lib/jxl/jxl_test.cc
- tools/optimizer/simplex_fork.py
0.16 % improvement in BPP * pnorm
```
Before:
jxl:d0.1        19988 16571766    6.6326538   1.429   9.556   0.35375724  95.48140318   0.11566954  53.18   6.633 42.0702 18.3139  0.4611 27.5998  4.8720  0.0000  2.4001  0.8965  3.9294  0.1025  0.0820  0.767196019168      0
jxl:d0.5        19988  6400108    2.5615677   1.813  14.956   0.78447949 …
```
> merging adaptive quantization based on distance

- lib/jpegli/bitstream.cc
- lib/jpegli/encode_internal.h
- lib/jpegli/entropy_coding.cc
Benchmark results (encoder only):
```
Encoding               kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs
----------------------------------------------------------------------------------------------------------------------------------
BEFORE:
jpeg:enc-jpegli:q90      13270  3540894    2.1346039  19.456  70.956   0.99999997   0.00000000   0.00000000  0.000000000000      0
jpeg:enc-jpegli:q75      13270  2093320    1.2619437  22.268  91.640   0.99999997   0.00000000   0.00000000  0.000000000000      0
AFTER:
jpeg:enc-jpegli:q90      13270  3542281    2.1354400  21.752  67.721   0.99999997   0.00000000   0.00000000  0.000000000000      0
jpeg:enc-jpegli:q75      13270  2093148    1.2618400  25.933  91.867   0.99999997 …
```
> Accumulate refinement bits in fixed size array instead of vector.

- lib/jxl/decode_test.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_group.cc
- lib/jxl/jxl_test.cc
- lib/jxl/passes_test.cc
reduce quantization when large blocks are used with lots of quantization error, but not large coefficient values and the masking is low
```
Before:
jxl:d0.1        19988 16609463    6.6477416   1.360   9.336   0.35353178  95.48321280   0.11547700  53.20   6.648 42.2069 18.2557  0.4579 27.5521  4.8560  0.0000  2.3809  0.8991  3.9345  0.1025  0.0820 …
```
> 0.1 % quality improvement

- lib/jpegli/bitstream.cc
- lib/jpegli/bitstream.h
- lib/jpegli/encode.cc
- lib/jpegli/encode_api_test.cc
- lib/jpegli/encode_internal.h
- lib/jpegli/entropy_coding-inl.h
- lib/jpegli/entropy_coding.cc
- lib/jpegli/entropy_coding.h
- lib/jpegli/test_utils.h
- lib/jxl_lists.bzl
- lib/jxl_lists.cmake
With this change the progressive and multi-scan sequential code paths also go through tokenization first, and then we build histograms from the tokens and then encode the tokens using the Huffman codes built from the histograms.
This makes progressive encoding 50% faster while using 50% more memory.
```
Encoding                             kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs
-----------------------------------------------------------------------------------------------------------------------------------------
BEFORE:
jpeg:enc-jpegli:q90:p0:fix             13270  3805508    2.2941246 101.189 190.896   1.58508737  84.51521884   0.68271017  1.566222227305      0
jpeg:enc-jpegli:q90:p0 …
```
> Rewrite progressive part of jpegli encoder.

- lib/jxl/decode_test.cc
caused by #2503, this fixes a problem when cross-compiling
> fix PixelTestWithICCProfileLossy

- lib/jpegli/bitstream.cc
- lib/jpegli/bitstream.h
- lib/jpegli/encode.cc
- lib/jpegli/encode_api_test.cc
- lib/jpegli/encode_internal.h
- lib/jpegli/entropy_coding-inl.h
- lib/jpegli/entropy_coding.cc
- lib/jpegli/entropy_coding.h
- lib/jpegli/test_utils.cc
- lib/jpegli/test_utils.h
Define a context id for each component of each scan and gather histograms for each context. Clustering outputs a list of Huffman tables (JHUFF_TBL can be resued here), and a slot id for each together with a context map, then we build coding tables for each Huffman table and use the context map and coding tables for entropy coding. All Huffman tables and corresponding coding tables are built in advance for all scans, and the bitstream functions for writing DHT and SOS segments also use the context map and list of slot ids.
> Simplify Huffman coding data structures, more consistent naming.

- lib/jpegli/bitstream.cc
- lib/jpegli/encode.cc
- lib/jpegli/entropy_coding.cc
- lib/jpegli/entropy_coding.h
```
Encoding                  kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs
-------------------------------------------------------------------------------------------------------------------------------------
BEFORE:
jpeg:enc-jpegli:q90:p0      13270  3621255    2.1830490  87.032 203.926   0.99999997   0.00000000   0.00000000  0.000000000000      0
jpeg:enc-jpegli:q90         13270  3540894    2.1346039  40.410  71.981   0.99999997   0.00000000   0.00000000  0.000000000000      0
AFTER:
jpeg:enc-jpegli:q90:p0      13270  3621255    2.1830490  99.742 204.198   0.99999997   0.00000000   0.00000000  0.000000000000      0
jpeg:enc-jpegli:q90         13270  3540894    2.1346039  41.476  70.090   0.99999997 …
```
> Always use pre-shifted prefix code tables.

- lib/jxl/decode_test.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_group.cc
- lib/jxl/jxl_test.cc
0.13 % quality improvement
```
Before:
jxl:d0.1        19988 16168561    6.4712758   1.364   9.630   0.35357815  95.44301818   0.11810353  52.99   6.471 40.6501 19.1672  0.4425 27.6286  5.2825  0.0000  2.4847  0.9068  3.9704  0.1127  0.0820  0.764280538314      0
jxl:d0.5        19988  6327432    2.5324800   1.798  15.641   0.79171594  91.42061585 …
```
> vardct encoding heuristics improvements

- lib/jxl/enc_modular.cc
Fixes https://github.com/libjxl/libjxl/issues/2508
Make lossless more likely to use a palette, in particular if the original had at most 256 colors (which is quite common considering GIF and PNG8). Also do this at e2 and e3, to avoid having the weird behavior where e1 uses a palette, e2 and e3 don't, and then e4+ does use it again (which can lead to e2/e3 file sizes being significantly larger than e1).
Before (for a png8 input):
```
JPEG XL encoder v0.9.0 c81a5a46 [SSE4,SSSE3,Unknown]
Read 3526x358 image, 627101 bytes, 158.1 MP/s
Encoding [Container | Modular, lossless, effort: 3 | 14-byte Exif], 
Compressed to 2164034 bytes including container (13.715 bpp).
3526 x 358, geomean: 4.51 MP/s [3.43, 4.59], 10 reps, 0 threads.
```
After:
```
jon@macdeb:~/dev/libjxl/test-dev$ …
```
> do more palette

- lib/jxl/enc_butteraugli_pnorm.cc
- lib/jxl/enc_butteraugli_pnorm.h
- tools/benchmark/benchmark_stats.cc
- tools/benchmark/benchmark_stats.h
- tools/benchmark/benchmark_xl.cc
This is the behavior with p-norm and SSIMULACRA2 as well.
Compute the image PSNR as a 6:1:1 weighted average of Y-PSNR, U-PSNR and V-PSNR values.
> Aggregate PSNR in benchmark as size-weighted-average.

- lib/jxl/color_management.cc
- lib/jxl/color_management_test.cc
- lib/jxl/dec_tone_mapping-inl.h
- lib/jxl/enc_color_management.cc
The tone mapping can be via 1D curves (smaller profile) or a 3D look-up table (more flexible).
For PQ, the 1D version will significantly desaturate highlights whereas the 3D version will preserve their color better.
For HLG, the 1D version assumes a system gamma of 1 (which, in a reference environment, would be a ~300-cd/m² monitor), which is likely to result in an image that looks quite dark on many SDR monitors or viewing environments. The 3D version is able to perform the rendering corresponding to a lower gamma, thereby lifting the shadows and mid-tones, without distorting the colors as altering the 1D curves would.
> For PQ and HLG, make it possible to generate ICC profiles that perform tone mapping

- lib/jxl/decode_test.cc
Two tests were failing in the low precision case, probably as a side effect of changes in encoder heuristics. This makes them pass again.
> fix low precision tests

- lib/jxl/color_encoding_internal.cc
Since returning false from MaybeCreateProfile is not an error in some cases, this error message can cause some extra noise.
> Don't emit error message in CreateICC().

- lib/jpegli/dct-inl.h
- lib/jpegli/encode.cc
- lib/jpegli/quant.cc
```
BEFORE:
jpeg:enc-jpegli:q90:p0           13270  3621255    2.1830490  94.474 195.784   1.58508737  84.51521884   0.68271017  1.490389738174      0
jpeg:enc-jpegli:q90:p0:noaq      13270  4283894    2.5825164  96.507 173.256   1.51445576  87.30502011   0.63342515  1.635830838152      0
AFTER:
jpeg:enc-jpegli:q90:p0           13270  3620412    2.1825408  94.136 193.894   1.58508737  84.50913605   0.68283419  1.490313465273      0
jpeg:enc-jpegli:q90:p0:noaq      13270  4053215    2.4434531 …
```
> Use some fixed dead-zone quantization in :noaq mode as well.

- lib/extras/dec/jxl.cc
- lib/jxl/jpeg/dec_jpeg_data_writer.cc
Reconstruction of losslessly recompressed JPEG files was rather slow. A big reason for this was that a small initial output buffer size was used, leading to JXL_DEC_JPEG_NEED_MORE_OUTPUT, which with the current (non-streaming) implementation in `dec_jpeg_data_writer.cc` causes it to basically redo all of the work several times.
This gets particularly bad if the jpeg file is quite large — the initial buffer size was 16 kb and basically it would reconstruct the first 16 kb, then run out of output buffer, restart and reconstruct the first 32 kb, then 64 kb, and so on until the buffer size is large enough to store the entire jpeg file.
Besides the small change to set the initial output buffer size large enough to likely store the entire result on the first try, I also 'ported' some tricks …
> faster jpeg reconstruction

- lib/jxl/enc_modular.cc
- lib/jxl/encode_test.cc
- lib/jxl/modular/transform/enc_palette.cc
Use the luma * alpha palette sorting from e1 also at higher effort settings, as opposed to the lexicographic sorting that was there (which kind of makes sense for YCoCg pixels, but not really when there's alpha or when the data is still RGB).
Also use `unordered_set` to keep track of which colors have been seen (doesn't have to be ordered anymore since we're not using that order anymore anyway), and use an `unordered_map` to converts pixels to palette indices (instead of doing a naive linear search).
Net result is an encoder speedup and generally some density improvement, though that's not guaranteed on a per-image basis (palette ordering is weird).
On the jyrki31 corpus, converted to png8 with default pngquant:
Before:
```
Encoding      kPixels    Bytes          BPP  E MP/s  D MP/s …
```
> improve palette ordering and encode speed

- lib/extras/enc/exr.cc
The EXR encoder should not advertise support for FLOAT16 if it does not actually support it.
> Let djxl write OpenEXR again

- tools/djxl_main.cc
- tools/file_io.cc
Replaces https://github.com/libjxl/libjxl/pull/1958
As is the convention in many other tools, the filename `-` is treated as stdin/stdout. So `cjxl - - < input.png > output.jxl` will work. For djxl, `djxl - - < input.jxl > output.png` does not work since djxl needs to know what format to output.
So this adds syntax similar to what ImageMagick's tools do: besides communicating the output format via the filename extension (e.g. `output.png`) you can also communicate it with a prefix (e.g. `jpg:output`). This allows you to do `djxl - png:- < input.jxl > output.png`.
In the case where multiple output files would be generated (e.g. when decoding an animation to ppm, where it generates one output file per frame), it will simply concatenate everything to stdout. Tools like ffmpeg do take …
> allow using cjxl/djxl with stdin/stdout

- lib/extras/enc/jxl.cc
- lib/extras/enc/jxl.h
- tools/cjxl_main.cc
The cjxl option `--already_downsampled` was broken: it would produce an image with the non-upsampled size, and then pass it a buffer with that size, which is too large since the encoder is expecting to get an already-downsampled frame. So it would just cause an error:
```
./lib/jxl/enc_external_image.cc:84: JXL_FAILURE: Buffer size is too large
./lib/jxl/enc_external_image.cc:133: JXL_RETURN_IF_ERROR code=1: ConvertFromExternal(bytes, xsize, ysize, bits_per_sample, format, c, pool, &color.Plane(c))
./lib/jxl/encode.cc:1896: Invalid input buffer
JxlEncoderAddImageFrame() failed.
EncodeImageJXL() failed.
```
This fixes that by setting the nominal image dimensions correctly in the JxlBasicInfo (to the upsampled size), so the expected frame dimensions will correspond to the input.
> fix --already_downsampled

- .github/workflows/conformance.yml
This makes the `./ci.sh bump_version` script work again.
> fix spacing in version number

- tools/cjxl_main.cc
The `cjxl` help screen looked a bit messy. Line breaks and indentation were applied inconsistently. Also some of the phrasing/style could be improved, and choices of what options to show at each verbosity level could be improved.
Now all lines are less than 100 characters wide.
Before:
```
$ cjxl
JPEG XL encoder v0.9.0 2d05683c [SSE4,SSSE3,SSE2]
Usage: cjxl INPUT OUTPUT [OPTIONS...]
INPUT
the input can be PNG, APNG, GIF, JPEG, EXR, PPM, PFM, PGX, or JXL
OUTPUT
the compressed JXL output file
-d maxError, --distance=maxError
Max. butteraugli distance, lower = higher quality.
0.0 = mathematically lossless. Default for already-lossy input (JPEG/GIF).
1.0 = visually lossless. Default for other input.
Recommended range: 0.5 .. 3.0. Allowed range: 0.0 ... 25.0.
Mutually exclusive with --quality. …
```
> improve cjxl help

- tools/cjxl_main.cc
- tools/djxl_main.cc
Similar to how `cjxl` does it, make `djxl` a bit more user-friendly by not showing all the options but only the most important ones (and with more verbosity `-v -v -v` you get to see more options). Also improve the phrasing and layout a bit (e.g. making sure everything fits in a terminal width of 100 characters).
Before:
```
$ djxl
JPEG XL decoder v0.9.0 2d05683c [SSE4,SSSE3,SSE2]
Missing INPUT filename.
Use 'djxl -h' for more information
$ djxl -h
JPEG XL decoder v0.9.0 2d05683c [SSE4,SSSE3,SSE2]
Usage: djxl INPUT OUTPUT [OPTIONS...]
INPUT
The compressed input file.
OUTPUT
The output can be (A)PNG with ICC, JPG, or PPM/PFM.
-V, --version
Print version number and exit.
--num_reps=N
Sets the number of times to decompress the image. Used for benchmarking, the default is 1.
--disable_output …
```
> improve djxl help

- AUTHORS
- deps.sh
I've pulled libjxl as tarball inside a project which is managed by Git. When executing `deps.sh` the script detects `libjxl` is a Git repository, but because it's inside a parent Git repository. However, the provision of the submodules fails (tries to provision the submodules of the parent Git repository, which are none).
To correctly provision `libjxl` submodules the script should not only check libjxl is a Git repository but its toplevel directory is the absolute path of libjxl.
> Harden current directory is a Git repository

- CMakeLists.txt
When this flag is set, CMake will call script 'deps.sh' to provision dependencies.
The need of adding this new CMake flag comes from a real use case scenario. I've recently added libjxl to WebKitGTK and I had some trouble to build it as part of a JHBuild moduleset. 
https://github.com/webkit/webkit/pull/15132
JHBuild expects that CMake modules follow the standard CMake flow:
```
$ mkdir build
$ cd build
$ cmake <FLAGS> ..
$ make
```
There's no margin for executing steps before the build process. Libjxl requires to provision dependencies before running cmake so I added this new CMake flag to perform this task directly from `cmake`. Example:
```
cmake -DPROVISION_DEPENDENCIES=ON ...
```
> Add CMake flag PROVISION_DEPENDENCIES

- CHANGELOG.md
- examples/decode_oneshot.cc
- examples/decode_progressive.cc
- lib/extras/dec/jxl.cc
- lib/include/jxl/decode.h
- lib/include/jxl/encode.h
- lib/include/jxl/types.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
- lib/jxl/encode.cc
- lib/jxl/fast_dct-inl.h
- lib/jxl/render_pipeline/render_pipeline_test.cc
- lib/jxl/roundtrip_test.cc
- plugins/gdk-pixbuf/pixbufloader-jxl.c
- plugins/gimp/file-jxl-load.cc
- tools/codec_config.h
- tools/decode_basic_info_fuzzer.cc
- tools/djxl_fuzzer.cc
- tools/jni/org/jpeg/jpegxl/wrapper/decoder_jni.cc
- tools/jxlinfo.c
- tools/viewer/load_jxl.cc
There are quite a few API functions that have been deprecated for a while but were still in there.
I think we want to get rid of all those deprecated things before we release version 1.0, otherwise they will end up becoming part of the 1.0 API anyway.
So it's probably wise to do it now already, so the deprecated stuff will be gone in v0.9 when we release that, and applications that will break because they were still using deprecated stuff get a chance to fix things and get it working with v0.9 before v1.0 gets released.
The only annoying thing are the functions `JxlDecoderGetColorAsEncodedProfile`, `JxlDecoderGetICCProfileSize`, and `JxlDecoderGetColorAsICCProfile`, which have a deprecated unused argument, so applications using those functions will need to update their code. Better get …
> API: remove deprecated things

- lib/jxl/decode_test.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_group.cc
- lib/jxl/jxl_test.cc
0.1 % improvement in BPP * pnorm
```
before:
jxl:d0.1        19988 16262919    6.5090415   1.453   9.648   0.35504593  95.44944669   0.11776069  55.38   6.509 41.0113 18.9684  0.4505 27.6395  5.1307  0.0000  2.4680  0.9042  3.9704  0.1025  0.0820  0.766509194521      0
jxl:d0.5        19988  6328890    2.5330636   1.875  15.535   0.79249374 …
```
> adjust adaptive quantization for deadzone blocks

- lib/jxl/enc_color_management.cc
The code that reads the CICP tag exits the function if it succeeds, but it should not skip reading the rendering intent, so make sure to have already done it by that point.
> Make sure to read the rendering intent before the CICP tag

- lib/jxl/enc_color_management.cc
This reverts commit 970583df885f3313953130b51404b411542cf27e.
> Revert "JxlCmsInit: use enum representation if appropriate"

- tools/cjxl_main.cc
- tools/cmdline.cc
- tools/cmdline.h
- tools/djxl_main.cc
- tools/speed_stats.cc
Currently the help screens for cjxl/djxl are one long list and making the help more verbose shows more options in random places, which makes it hard to distinguish the basic options from the more advanced ones.
This reorders the options and adds some structure to it.
For `cjxl`, I made five tiers of options (so you need four `-v` to see them all). The first tier is always shown in the help screen and each additional `-v` 'unlocks' another tier.
- Basic options
- Advanced options
- Expert options
- Options for experimentation / benchmarking
- Modular mode options
Those last two tiers should not really be useful for normal users, they're intended more for encoder development than for actual use.
The full `cjxl` help looks like this then:
```
$ cjxl -v -v -v -v
JPEG XL encoder v0.9.0 …
```
> organize cjxl/djxl help a bit

- lib/jxl/enc_icc_codec.cc
- lib/jxl/jxl_test.cc
I think some code paths in jpeg recompression/reconstruction were not properly being tested. This should improve that a bit.
> add jpeg recompression roundtrip test for jpegs with icc/exif/xmp

- lib/jxl/decode_test.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_params.h
- lib/jxl/encode.cc
- tools/cjxl_main.cc
In the old cjxl (before it used the API) the modular group size was chosen depending on the image dimensions. This brings back that behavior, but now as a default setting for that option.
Also uses the frame dimensions rather than the image dimensions to make the choice, which makes more sense in case it is e.g. a 300x300 cropped frame in an animation or multi-layer image that is larger, or in case resampling is used.
On the jyrki31 images, resized with `convert -resize 400x400` to fit within a 400x400 box:
Before:
benchmark_xl v0.9.0 fb76c60b [SSE4,SSSE3,SSE2]
4 total threads, 31 tasks, 4 threads, 0 inner threads
```
Encoding      kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs …
```
> better default modular group size

- lib/jxl/dec_modular.cc
- lib/jxl/frame_header.cc
- lib/jxl/image_metadata.cc
- lib/jxl/modular/modular_image.cc
No need to compile the DebugString() functions if they're not going to be used anyway. Probably doesn't make any difference on the final binary size since link-time optimization will probably remove the unused functions anyway, but still, it should improve the code coverage reports and perhaps make compilation slightly faster.
> conditionally compile debug strings

- lib/jxl/dec_cache.cc
- lib/jxl/render_pipeline/stage_xyb.cc
Slightly reduces the binary size of `libjxl.so` for default (high-precision) builds.
> conditionally compile low-precision neon-only XYB to RGB code

- lib/extras/enc/jpegli.cc
- lib/extras/enc/jpegli.h
- lib/jxl_extras.cmake
- tools/benchmark/benchmark_codec_jpeg.cc
- tools/cjpegli.cc
First we define all the object libraries we need and then we put together the static/dynamic libraries from them. This also makes it clear that we have to compile some source files twice.
> Refactor jxl_extras.cmake

- lib/jxl/modular/encoding/encoding.cc
Probably doesn't make any difference on realistic examples, and it's a bit nitpicky, but in principle: if `size_t` is small (it can be only uint32) and the size of a local group is very large (e.g. because the image is a multispectral one with lots of channels), presumably the computation of the bound to use for the MA tree size could return failure while the bitstream was actually valid.
> simplify/fix local max MA tree size calculation

- lib/extras/tone_mapping_gbench.cc
- lib/jxl/color_management_test.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_cache.cc
- lib/jxl/enc_detect_dots.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_gaborish.cc
- lib/jxl/enc_heuristics.cc
- lib/jxl/enc_image_bundle.cc
- lib/jxl/image.cc
- lib/jxl/image_bundle.h
- lib/jxl/image_ops.h
- lib/jxl/modular/transform/palette.cc
- lib/jxl/opsin_inverse_test.cc
- lib/jxl/splines_test.cc
- tools/benchmark/benchmark_xl.cc
- tools/hdr/local_tone_map.cc
There are a bunch of functions in `image_ops.h` that are currently dead code — they were probably used at some point during the development of jxl, but they're now no longer used. Some functions like `ScaleImage()` or `AddTo()` had several variants for no good reason, so I simplified that a bit too.
The function `PadImageMirror()` is only used by `tools/hdr/local_tone_map.cc` so it makes more sense to move it there.
Some functions like `CopyImage()` were marked as "deprecated"; they were still used in some places (mostly in tests) so I replaced them with the alternative (e.g. `CopyImageTo()`).
> remove dead or deprecated image_ops functions

- lib/jxl/jxl_test.cc
- tools/cjxl_main.cc
We have an option to enable adaptive noise synthesis in the encode API, but it doesn't exist in `cjxl`. Even though it's still experimental, it's nice to expose it.
Also updating the test for noise to actually test noise by picking a different image. The image that was used was too clean to trigger the noise detection, so it ended up early-aborting and not signaling any noise on that image (which caused most of the code in `enc_noise.cc` to not be reached). This other image does lead to some noise being generated.
> add --noise to cjxl and make the noise test actually test noise

- lib/extras/dec/jxl.h
- lib/extras/enc/encode.cc
- lib/include/jxl/types.h
- lib/jxl/decode.cc
- lib/jxl/enc_external_image.cc
- lib/jxl/encode.cc
Partially fixes https://github.com/libjxl/libjxl/issues/2581
(it will still convert enum colorspace to icc, but at least the bit depth is preserved with this change)
On the API side, we currently don't allow JXL_BIT_DEPTH_FROM_CODESTREAM in combination with float buffers (we return "not implemented"), but I don't think there's a reason to disallow that. I think we can just define it to not have any impact on the interpretation of float buffers (they always use nominal range 0..1) and call it a day.
> preserve bitdepth when recompressing jxl

- .github/workflows/build_test_cross.yml
In the `Build/Test Cross` workflow, when pushing to `main`, it runs all tests on builds with `-DCMAKE_CROSSCOMPILING_EMULATOR=/usr/bin/qemu-aarch64-static`. This is pretty slow, and often time-outs. For some reason the time this takes fluctuates quite a lot, probably depending on the overall load the particular workflow runner has — on a good day these tasks complete in 2-3 hours, on a bad day they need more than the 6 hour default time-out. When they time-out, it does look like they are actually not that far from completing when they get killed (e.g. the two most recent time-outs happened at 5510/5946 tests completed and 5458/5946 tests completed).
Bumping up the time-out from 6h to 10h might help to avoid these time-out failures.
> bump up timeout for cross-compile

- lib/jxl/jpeg/jpeg_data.cc
Small cleanup/tweak: the correct bound for block_idx is `3 << 26` since the largest possible JPEG image has `1<<13` x `1<<13` blocks (e.g. for a 65535x65535 image) and we have at most 3 components (JPEG can do 4 but we don't support that).
Improving the bound also means that there is no need to check for integer overflow in the `block_idx + last_block_idx + 1` calculation since `block_idx` is at most 40+2^28 (`BitsOffset(28, 41)`) and `last_block_idx` is less than `3 << 26`, so the sum is certainly smaller than 2^29 and cannot cause overflow. (actually the overflow check was already redundant with the cruder bound)
> improve/simplify bound checking on block_idx

- CMakeLists.txt
According to https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam (see "Other Settings"), 99.18% of desktop hardware has SSE4 (and 100% has SSE2), so it is a bit unnecessary to have the highway target for SSSE3 enabled since it will only bring a small speedup to < 1% of people while the binary size bloat is for everyone.
Also in this survey we see 90% has AVX2 but less than 10% has AVX512. While of course AVX512 does give additional speedups over AVX2, the question is whether it is worth the binary size bloat (especially because there are two variants of this, the regular one and the Zen4 one). Also I'm assuming the steam survey will contain relatively more beefy gaming machines so it's likely an overestimate of the actual support for AVX512 in the …
> disable SSSE3 and AVX512 in default builds

- lib/jxl/enc_fast_lossless.cc
- lib/jxl/enc_fast_lossless.h
The code for using `enc_fast_lossless` in a standalone way to produce a complete jxl file does not have to be in libjxl. This is the high-level function that produces a full file, and also the code that produces an image header (which is unused in libjxl).
Also removing `JxlFastLosslessMaxRequiredOutput()` since it's not really needed imo.
Slightly reduces `libjxl.so` binary size.
> conditionally compile code for standalone-fjxl

- lib/extras/codec_test.cc
- lib/jxl/base/compiler_specific.h
- lib/jxl/base/status.h
- lib/jxl/blending.cc
- lib/jxl/butteraugli/butteraugli.cc
- lib/jxl/butteraugli/butteraugli.h
- lib/jxl/color_encoding_internal.cc
- lib/jxl/color_management.cc
- lib/jxl/dec_transforms-inl.h
- lib/jxl/dec_xyb-inl.h
- lib/jxl/decode_to_jpeg.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_ans.cc
- lib/jxl/enc_aux_out.cc
- lib/jxl/enc_bit_writer.cc
- lib/jxl/enc_modular.cc
- lib/jxl/enc_params.h
- lib/jxl/enc_patch_dictionary.cc
- lib/jxl/enc_transforms-inl.h
- lib/jxl/fields.cc
- lib/jxl/image_bundle.cc
- lib/jxl/jpeg/jpeg_data.h
- lib/jxl/render_pipeline/low_memory_render_pipeline.cc
- lib/jxl/render_pipeline/stage_blending.cc
- lib/jxl/render_pipeline/stage_epf.cc
- lib/jxl/render_pipeline/stage_from_linear.cc
- lib/jxl/render_pipeline/stage_upsampling.cc
- tools/benchmark/benchmark_codec_jxl.cc
Various cleanups all aimed at reducing the amount of unnecessary strings and debug code in libjxl.so:
1. JXL_ABORT() is often used in unreachable code paths that could only become reachable if the code would change (e.g. if the encoder would use a new blendmode for patches, or some programming error happened that caused a presumably unreachable path to become reachable). However, the compiler cannot know these are unreachable so even release builds still contain the code to print the abort message and to do the actual abort. This replaces these aborts with JXL_NOT_REACHABLE() which is a new macro that keeps the old behavior for debug builds (print message and abort), but in release builds it simply signals JXL_UNREACHABLE to inform the compiler that this is in fact an unreachable path.
2. …
> Various cleanups

- lib/jxl/enc_ac_strategy.cc
- lib/jxl/enc_ac_strategy.h
There is quite a bit of code in `enc_ac_strategy.cc` that is just there to produce a nice debug image that shows the ac strategy (dct block type selection). This functionality is not exposed via the library api, but it can still be accessed via `benchmark_xl`. Probably better not to compile this into `libjxl.so` — if we want to use this debugging aid, we can easily enough set `JXL_DEBUG_AC_STRATEGY=1` (just like there's e.g. `JXL_DEBUG_DOT_DETECT`).
> put code for ac strategy debug images behind a compile flag

- lib/BUILD
- lib/jpegli.cmake
- lib/jpegli/common.h
- lib/jpegli/decode_api_test.cc
- lib/jpegli/encode_api_test.cc
- lib/jpegli/error_handling_test.cc
- lib/jpegli/input_suspension_test.cc
- lib/jpegli/libjpeg_test_util.cc
- lib/jpegli/libjpeg_test_util.h
- lib/jpegli/streaming_test.cc
- lib/jpegli/test_params.h
- lib/jpegli/test_utils-inl.h
- lib/jpegli/test_utils.cc
- lib/jpegli/test_utils.h
- lib/jpegli/types.h
- lib/jxl_lists.bzl
- lib/jxl_lists.cmake
- tools/scripts/build_cleaner.py
This is preparation for using jpegli's own jpeg headers for compiling the jpegli-static library.
> Factor out the libjpeg-decoding parts of test_utils.cc

- lib/jxl/jpeg/dec_jpeg_data_writer.cc
The manual unroll did give a small speedup, but it comes at a cost of ~100kb binary size bloat, which I think is not really worth it.
> revert manual unroll of dct writing loop in jpeg reconstruction

- lib/extras/dec/jxl.cc
- lib/extras/dec/jxl.h
- tools/djxl_main.cc
Fixes https://github.com/libjxl/libjxl/issues/2581
Now converting lossless jxl to lossless jxl becomes a no-op (if done with the same settings), instead of e.g. converting Enum sRGB to an explicit synthesized ICC profile for sRGB, which then gets stored exactly in the new jxl file.
Lossless jxl to lossless jxl might seem like a silly thing to do, but it could be quite useful to do quick e1 encodes first and then spend more effort on it later.
> jxl-to-jxl conversion: don't use ICC if not needed

- lib/jxl/decode.cc
Currently there is no distinction in the decoder API between errors caused by bad API usage (e.g. calling the functions in the wrong order, or with arguments that make no sense) and errors caused by bad input (corrupt/invalid/unsupported bitstreams).
Since that is probably a useful distinction to make (the former is an application bug while the latter is something that can happen at runtime and needs to be handled by the application), as a start I'm adding a macro JXL_INPUT_ERROR in addition to the JXL_API_ERROR macro that already existed, and changed all instances where the error is not an API usage error to use this macro instead. For now they both still do the same thing (return JXL_DEC_ERROR) but this will make it easier if we later want to have some more fine-grained error mechanism. …
> preparation for distinguishing bad input from bad api usage

- lib/jxl/enc_ans.cc
There's some code in the ANS encoding to do fuzzer-friendly (but very bad) entropy coding. It can only be enabled via a non-exposed function that only works in debug builds, but since it's not guarded by `if (constexpr false)`, the actual code for fuzzer-friendly entropy coding could still end up in release builds.
> no fuzzer-friendly encoding in release builds

- lib/jxl/enc_modular.cc
- lib/jxl/jxl_test.cc
- lib/jxl/modular/encoding/context_predict.h
- lib/jxl/modular/encoding/enc_encoding.cc
- lib/jxl/modular/encoding/enc_ma.cc
- lib/jxl/modular_test.cc
The way things currently are, there's a big gap between lossless e3 and e4, where e4 is a _lot_ slower than e3. This makes the gap smaller, making e4 about twice as fast at the cost of some compression density.
All the lossless e4-e7 settings get faster, e8+ has roughly the same speed as before. Efforts 1-3 are not modified. Density of e4-e6 gets worse (but speed improves), density of e7+ is about the same or maybe slightly better. The new e5 is faster than the old e4 and also better; the new e4 does a better job at filling the gap between e3 and e5.
Decode speed also improves.
Obviously results are image-dependent and your mileage may vary.
Overview of the changes:
- Make the MA tree splitting heuristic threshold get lower gradually as effort goes up, instead of a big step
- Don't use …
> tweak lossless e4+

- .github/workflows/gitlab_mirror.yml
This adds a workflow running on every push to main or version branches, mirroring all the changes in those branches to gitlab.com/wg1/jpeg-xl/.
> workflow to mirror to gitlab

- lib/jxl_extras.cmake
- tools/djxl_main.cc
The -DJPEGXL_ENABLE_SJPEG=1 flag has to be added to the object library that contains lib/extras/enc/jpg.cc otherwise it has no effect.
The build flag from djxl_main.cc is removed because it is not possible to know when building the tool what the extras library has compiled in.
> Fix sjpeg build flag.

- lib/jxl/jxl_test.cc
- lib/jxl/modular/encoding/enc_ma.cc
Simplify the function EstimateBits a little bit: instead of first rounding up the non-zero counts that would otherwise end up getting a probability below 1/4096, just make all probabilities at least 1/4096 — that's wrong if the count was zero but it doesn't matter since we'll then multiply the number by zero anyway.
This gives a small (~2% or so) speedup at most of the lossless effort settings, but a ~20% speedup at e9.
Both ways of doing the estimate are not quite exact, and this approximation is slightly different from the previous one. The effect of this change on density is small but this way of doing it also seems slightly better for compression (but it's image-dependent and mostly just some fluctuation).
Before (jyrki31):
```
Encoding      kPixels    Bytes          BPP  E MP/s  D …
```
> simplify EstimateBits a bit

- lib/jxl/dec_ans.h
- lib/jxl/dec_context_map.cc
- lib/jxl/dec_group.cc
- lib/jxl/modular/encoding/encoding.cc
Some more decoding speedup by avoiding a function call in the hot loops, and by having a specialization in modular decoding for the no-lz77 case (which is quite common since only e1 and e8/e9 use lz77 at the moment).
Binary size goes up a bit because of this (by 100kb or so on x86), so we may want to be a bit more selective with the inlining and templating, but I think it's ok for now.
Modular decode speedup is 5-10%, also VarDCT decode gets some speedup (3% or so).
Before: (30 decode reps, single-core)
```
station.png …
```
> inline and specialize the symbol reading

- lib/jxl/enc_group.cc
- lib/jxl/jxl_test.cc
- tools/optimizer/simplex_fork.py
small degradation on metrics (except psnr)
improves chessboard patterns a lot at all distances
reduces the quality of a complex pixel graphic pattern
```
Before:
jxl:d0.1        19988 16285960    6.5182633   1.211  11.091   0.35751487  95.44402571  55.33   0.11858650  0.772978009094   6.518      0
jxl:d0.5        19988  6339424    2.5372797   1.616  16.782   0.79035681  91.38825397  46.40   0.34845275  0.884122066221   2.555      0
jxl:d0.8        19988  4701461    1.8817043   1.698  16.455   1.09826621  88.63624132 …
```
> improve on chess board images substantially

- lib/jxl/dec_ans.h
- lib/jxl/modular/encoding/encoding.cc
Minor tweaks to improve the modular decode speed and binary size.
Before: (single-core, only decode speed is measured accurately)
```
station.png
jxl:d0:2          987  1487163   12.0458779   9.497  21.502         -nan 100.00000000  99.99   0.00000000  0.000000000000  12.046      0
jxl:d0:3          987  1416083   11.4701367   5.772   8.072         -nan 100.00000000  99.99   0.00000000  0.000000000000  11.470      0
jxl:d0:4          987  1401819   11.3545996   1.489   6.190         -nan 100.00000000  99.99   0.00000000 …
```
> tweak modular decode speed vs binary size

- lib/jxl/decode_test.cc
- lib/jxl/enc_ac_strategy.cc
- lib/jxl/enc_ac_strategy.h
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/encode_test.cc
- lib/jxl/jxl_test.cc
- lib/jxl/render_pipeline/render_pipeline_test.cc
- tools/optimizer/simplex_fork.py
this PR reduces ringing at distance 3 and below
at high distances it is less clear if this is an improvement, more likely not
this simplifies the logic in entropy/information loss calculation and might make future improvements easier
all metrics show a degradation -- careful viewing shows an improvement however
```
Before:
jxl:d0.1        19988 16248290    6.5031864   1.207  10.666   0.36367235  95.40348953  55.31   0.12028512  0.782236544141   6.503      0
jxl:d0.5        19988  6352958    2.5426965   1.594  14.169 …
```
> reduces ringing near borders

- CHANGELOG.md
- lib/extras/dec/color_hints.cc
- lib/extras/dec/color_hints.h
- lib/extras/dec/decode.cc
- lib/extras/dec/jxl.cc
- lib/extras/enc/encode.cc
- lib/extras/enc/encode.h
- lib/extras/enc/jxl.cc
- lib/extras/enc/jxl.h
- lib/include/jxl/encode.h
- lib/jxl/enc_params.h
- lib/jxl/encode.cc
- lib/jxl/encode_test.cc
- lib/jxl/jxl_test.cc
- lib/jxl/test_utils.cc
- lib/jxl/test_utils.h
- tools/args.h
- tools/cjxl_main.cc
- tools/djxl_main.cc
This adds some functionality to improve metadata handling.
In djxl, 'metadata-only output formats' are added (`.exif`, `.xmp`, `.jumbf`) which can be used to extract the metadata embedded in a jxl file.
In cjxl, a new `--dec-hints` (`-x`) syntax is added so you can add a sidecar exif/xmp/jumbf file to the input file (e.g. `cjxl -x exif=input.exif`); this allows adding metadata to input formats like PPM, and it also allows overriding the metadata of the input file with something else. Specific metadata can also be stripped from the input file using the syntax `-x strip=exif`.
To make metadata stripping also work when losslessly recompressing JPEG images (assuming it is not needed to reconstruct the original JPEG file), some encode options were added to the API:
- …
> improve metadata handling

- lib/extras/enc/jxl.cc
See https://github.com/libjxl/libjxl/issues/2685, https://github.com/libjxl/libjxl/issues/2580, https://github.com/libjxl/libjxl/issues/2693
Instead of simply saying `JxlEncoderAddJPEGFrame() failed.`, cjxl will now give a more useful error message depending on why it failed.
> more detailed/useful error messages when jpeg recompression fails

- lib/extras/exif.cc
I think this fixes the djxl fuzzerbug in https://github.com/libjxl/libjxl/issues/2661 (though the asan trace suggests the issue is elsewhere). In any case this fixes _something_ in that example.
Since `offset` was uint32_t, the test `exif.size() < 12 + offset + 2` was not quite robust: in that fuzzer example, `offset` has the value 4294967287, so the right hand side evaluates to something that overflows (so the result is not 4294967301 but that number mod 2^32, which is 5). Doing the arithmetic in uint64_t avoids that problem.
We didn't catch this overflow before because this code is not called by libjxl (or djxl_fuzzer) but only by the `extras` encoders used by djxl.
> fix overflow in corrupt exif offset

- CHANGELOG.md
- lib/extras/enc/jxl.cc
- lib/extras/enc/jxl.h
- lib/include/jxl/encode.h
- lib/jxl/encode.cc
- tools/cjxl_main.cc
Currently the default upsampling weights are always used by the libjxl encoder. This adds a function to use custom upsampling weights. This is in particular useful when encoding pixel art with JXL_ENC_FRAME_SETTING_ALREADY_DOWNSAMPLED, since the default upsampling is great for photographic images but it's not what you typically want for pixel art.
For example, for this original image:
encoding with `cjxl -d 0 --already_downsampled --resampling 8` produces this:
while when setting the upsampling mode to nearest neighbor (`--upsampling_mode 0`), it will look like this:
Just for fun I also added another upsampling mode which I called "pixel dots" and it looks like this:
For truly customized upsampling we would need a function that allows you to set the actual weights as opposed to picking …
> add a way to do custom upsampling

- lib/jxl/decode_test.cc
This test was broken for low_precision by https://github.com/libjxl/libjxl/pull/2688
> fix broken test

- lib/jxl/decode_test.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_group.cc
- lib/jxl/jxl_test.cc
make large (16x16 and above) blocks with high error but not a lot of signal get higher adaptive quant
```
Before:
jxl:d0.1        19988 16856164    6.7464808   1.149   8.660   0.35450427  95.45846516  55.53   0.11510705  0.776567470265   6.746      0
jxl:d0.5        19988  6518150    2.6088126   1.638  15.463   0.78029452  91.40099532  46.62   0.34410685  0.897710301801   2.661      0
jxl:d0.8        19988  4794309    1.9188656   1.703  15.062   1.11216959  88.61554644  44.05   0.48290552  0.926630798371   2.241      0 …
```
> small heuristics tuning for adaptive quant

- .github/dependabot.yml
- .github/workflows/build_test.yml
- .github/workflows/build_test_cross.yml
- .github/workflows/conformance.yml
- .github/workflows/debug_ci.yml
- .github/workflows/fuzz.yml
- .github/workflows/gitlab_mirror.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- .github/workflows/test_new_highway.yml
Fixes #2683.
This PR hash-pins GitHub Actions to prevent supply-chain attacks. It also adds dependabot to help keep the GHAs up-to-date.
> Hash-pin workflow Actions, set up dependabot to keep them updated

- lib/extras/dec/decode.cc
- lib/extras/dec/jxl.cc
Folow-up: fix exrtas-jxl-codec-decode to decode just metadata
> Fix using uninitialized value

- .github/workflows/build_test.yml
- .github/workflows/build_test_cross.yml
- .github/workflows/conformance.yml
This removes the paths-ignores for ichange to .md and AUTHORS. This allows us to have required workflows. The ci is faster now and also we don't have many such pull requests.
> remove paths-ignore

- lib/jxl/jpeg/dec_jpeg_data_writer.cc
When AC coeff is -32768 the logic of "de-signization" does not work. Healthy JPEGs does not contain such values.
> Fix edge case in JPEG serialization

- AUTHORS
- doc/software_support.md
Older release notes are regularly moved to "archived release notes" in the Pale Moon project. Since this change was made in November 2022, it's no longer relevant for the main release notes page. The correct/permanent link at this point in time is https://www.palemoon.org/releasenotes-archived.shtml#v31.4.0 -- jumping directly to the related version.
> Correct link to Pale Moon release notes in doc/sofware-support.md

- lib/extras/metrics.cc
- lib/jxl/enc_color_management.cc
- lib/jxl/gauss_blur.cc
- tools/wasm_demo/jxl_decoder.cc
Drive-by: avoid nameless HWY_FULL(T) instantiations
> Fix WASM build

- lib/jxl/color_management.cc
- lib/jxl/dec_tone_mapping-inl.h
- lib/jxl/dec_xyb.cc
- lib/jxl/enc_color_management.cc
- lib/jxl/fast_math_test.cc
- lib/jxl/rational_polynomial-inl.h
- lib/jxl/render_pipeline/stage_from_linear.cc
- lib/jxl/render_pipeline/stage_to_linear.cc
- lib/jxl/tf_gbench.cc
- lib/jxl/transfer_functions-inl.h
Benchmarking with
```
build/lib/jxl_gbench --benchmark_filter=".*PQ.*"
```
showed that TF_PQ() was not made significantly slower by this change.
Drive-by: add `static_assert` when evaluating polynomials
> don't special case intensity target for pq

- doc/api.txt
- doc/sphinx/api.rst
- doc/sphinx/api_butteraugli.rst
- doc/sphinx/api_color.rst
- doc/sphinx/api_cpp.rst
- doc/sphinx/api_metadata.rst
- lib/include/jxl/cms_interface.h
- lib/include/jxl/codestream_header.h
- lib/include/jxl/color_encoding.h
- lib/include/jxl/decode.h
- lib/include/jxl/decode_cxx.h
- lib/include/jxl/encode_cxx.h
- lib/include/jxl/parallel_runner.h
- lib/include/jxl/resizable_parallel_runner_cxx.h
- lib/include/jxl/thread_parallel_runner_cxx.h
- lib/include/jxl/types.h
Cluster things a bit more by topic, so the API documentation will end up being a bit better organized.
Also move `JxlProgressiveDetail` from types.h to decode.h since it's not a common type (used in both encoder and decoder) but only relevant for the decoder.
For convenience: this is what the API documentation looks like after this PR:
https://libjxl--2706.org.readthedocs.build/en/2706/
> improve API documentation structure

- lib/include/jxl/stats.h
- lib/include/jxl/thread_parallel_runner.h
Declaring a function as foo(); is fine in C++ but produces a warning in C. Since these are C headers, we should declare them as foo(void). This has been the case since C89.
See: -Wstrict-prototypes
> lib/include/jxl: use void for strict C prototypes

- lib/jxl/butteraugli/butteraugli.cc
- lib/jxl/butteraugli/butteraugli.h
- lib/jxl/butteraugli/butteraugli_test.cc
- lib/jxl_lists.bzl
- lib/jxl_lists.cmake
The new in-place version can be used when the input images are not needed after the comparison and thus can be deallocated or reused within the butteraugli computation.
This version uses less than 1/3 of peak memory than the comparator-based one.
> Add low memory version of butteraugli.

- README.md
Adds a badge like this: [![OpenSSF Best Practices](https://www.bestpractices.dev/projects/7845/badge)](
https://www.bestpractices.dev/projects/7845)
> add badge for OpenSSF best practices

- .github/workflows/scorecard.yml
Added a fine-grained PAT so the scorecard action can check the branch protection settings.
> add PAT for branch protection check

- tools/djxl_main.cc
> Drop the suffix -ec0 from the color part of ppm output.

- tools/djxl_main.cc
Added separate flags for dumping all extra channels and frames into separate files.
Addresses Issue #2813
> By default output only a single file from djxl.

- lib/jxl/dec_cache.cc
- lib/jxl/dec_cache.h
- lib/jxl/dec_frame.cc
- lib/jxl/enc_adaptive_quantization.cc
At effort >= 8 in VarDCT mode, i.e. when adaptive quantization iterations are being done, if noise is enabled then this causes trouble:
- noise generation is not properly initialized or something in this code path (decoding-while-encoding), causing nondeterministic results (!) and probably also wildly wrong noise (haven't checked but this is what I would expect)
- BA scores will be lower because of the noise (possibly wildly lower if the noise is wildly wrong), causing adaptive quantization to bump up the quality a lot (so the file size will be a lot larger with --noise=1 than with --noise=0)
This simply disables noise rendering when doing decoding-while-encoding, which makes the resulting main image data identical whether noise is enabled or not, the only difference being the signaling …
> fix e8+ VarDCT with noise enabled

- lib/jxl/decode_test.cc
- lib/jxl/enc_ac_strategy.cc
- lib/jxl/enc_ac_strategy.h
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_adaptive_quantization.h
- lib/jxl/enc_cache.h
- lib/jxl/enc_chroma_from_luma.cc
- lib/jxl/enc_group.cc
- lib/jxl/enc_heuristics.cc
- lib/jxl/jxl_test.cc
- lib/jxl/passes_test.cc
- tools/optimizer/simplex_fork.py
measure the quality of an integral transform in the pixel space rather than dct coefficient base (as done before this PR)
some more ringing, better texture/subtle material fitting, some more details right, better performance on difficult images, cleaner architecture for further quality improvements, slower
```
Before:
jxl:d0.1        20315 17381585    6.8445662   2.475  20.374   0.35752780  95.38110842  55.31   0.11907606  0.815023950090   6.845      0
jxl:d0.5        20315  6840469    2.6936578   3.043  30.431 …
```
> back-and-forth dcts for ac strategy

- lib/jxl/jxl_test.cc
This tests for a problem that was fixed in https://github.com/libjxl/libjxl/pull/2842.
> Test `cjxl -e 1 -d 0` for images with few colors

- AUTHORS
- doc/software_support.md
Added 2 programs for Windows now supporting jxl: 
- the best (imho) picture viewer - jpegview
- duplicate image finder able to find similar images with different resolution, rotation, flipping - AntiDupl.NET
Also sorted image viewers alphabetically
> Added jpegview and antidupl.net to software_support.md

- lib/jxl/encode_test.cc
- lib/jxl/roundtrip_test.cc
Improve the encoder tests:
- Check that effort 10 can only be used when `JxlEncoderAllowExpertOptions` has been called
- There was only a test for 2x upsampling with the default upsampling mode, add tests for 4x and 8x and the other upsampling modes.
> improve tests (mainly upsampling modes)

- lib/jxl/jpeg/dec_jpeg_data_writer.cc
- lib/jxl/jpeg/dec_jpeg_serialization_state.h
Some JPEGs failed to decode, others produced not the same bytes (but, likely represented original image data)
Also this makes decoding faster and saves memory.
> Pick-up fix from Brunsli upstream

- lib/jxl/encode.cc
- lib/jxl/encode_test.cc
Fixes https://github.com/libjxl/libjxl/issues/2870
In case of non-XYB (e.g. lossless), we currently force applications to explicitly set a colorspace with `JxlEncoderSetColorEncoding` or `JxlEncoderSetICCProfile`, while in our documentation (https://github.com/libjxl/libjxl/blob/main/lib/include/jxl/encode.h#L645) we say that if it is not explicitly set, it has a default (which is sRGB, either linear or nonlinear depending on the pixel format).
This fixes the discrepancy by also allowing to use the default colorspace in the non-XYB case.
> allow non-XYB encoding with default colorspace

- .github/workflows/build_test_cross.yml
- ci.sh
Drive-by: cleanup cross-build workflow
> When cross-compiling propagate options to msan library

- lib/jxl/enc_fast_lossless.cc
Fixes #2841 (the new failing image).
> Fix fast-lossless on images with a palette larger than 256 colors.

- AUTHORS
- tools/butteraugli_main.cc
The raw distmap file created when using the `--rawdistmap` argument of butteraugli_main was opened in text mode. On Windows, this caused any occurrence of 0x0A in floats written to undergo newline correction and have a 0x0D inserted before it, resulting in incorrect output and an invalid PFM (file size after header > w x h x 4 bytes). This PR fixes that by opening the file in binary mode instead.
> Open rawdistmap in binary mode for writing

- lib/extras/dec/pnm.cc
- lib/extras/dec/pnm.h
- lib/extras/enc/jxl.cc
- lib/extras/packed_image.h
- tools/cjxl_main.cc
- tools/file_io.h
- tools/scripts/roundtrip_test.sh
This option works only for PPM and PGM for now, and it causes the encoder to not read the entire image file in memory but use the streaming input API of the encoder instead.
> Implement chunked file input in cjxl.

- .github/workflows/build_test.yml
This marks the expectance for the the build step in the two failing mingw tests as failures, so that they marked as green in the ci, even if they were failures.
> continue-on-error for step

- lib/extras/dec/pnm.cc
- lib/extras/dec/pnm.h
- lib/extras/packed_image.h
- lib/jxl/enc_fast_lossless.cc
- lib/jxl/enc_fast_lossless.h
- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
- lib/jxl/jxl_test.cc
- tools/cjxl_main.cc
Memory usage for a 45MP image went from 466 MB to 6.7 MB.
cjxl -d 0.0 -e 1 --streaming_input --streaming_output
BEFORE:
Compressed to 79443.2 kB (13.986 bpp).
8256 x 5504, 125.388 MP/s [125.39, 125.39], 1 reps, 8 threads.
AFTER:
Compressed to 79444.1 kB (13.986 bpp).
8256 x 5504, 105.129 MP/s [105.13, 105.13], 1 reps, 8 threads.
cjxl  -d 0.0 -e 1
BEFORE:
Compressed to 79443.2 kB (13.986 bpp).
8256 x 5504, 229.300 MP/s [229.30, 229.30], 1 reps, 8 threads.
AFTER:
Compressed to 79443.2 kB (13.986 bpp).
8256 x 5504, 230.898 MP/s [230.90, 230.90], 1 reps, 8 threads.
> Reduce memory usage of streaming fast-lossless code-path.

- plugins/gdk-pixbuf/pixbufloader-jxl.c
The "icc-profile" gdk-pixbuf option accepts a base64-encoded string, so we can just pass that instead of relying on lcms2 to convert the pixels to sRGB. This saves most of the time on load.
> plugins/pixbufloader-jxl: pass ICC profile instead of converting to sRGB

- lib/jxl/decode_test.cc
- lib/jxl/enc_cache.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_frame.h
- lib/jxl/enc_heuristics.cc
- lib/jxl/enc_modular.cc
- lib/jxl/enc_params.h
- lib/jxl/enc_patch_dictionary.cc
- lib/jxl/encode.cc
- lib/jxl/gradient_test.cc
- lib/jxl/jxl_test.cc
- lib/jxl/passes_test.cc
- lib/jxl/render_pipeline/render_pipeline_test.cc
- lib/jxl/test_utils.cc
- lib/jxl/test_utils.h
- tools/djxl_fuzzer_corpus.cc
- tools/jxl_from_tree.cc
The relevant custom structs used in tests and jxl_from_tree are passed via cparams instead.
> Remove PassesEncoderState parameter from EncodeFrame.

- tools/cjxl_main.cc
Also slightly reduce the number of 0-initializations by avoiding to shrink the vector buffer.
> Fix streaming output with multiple repetitions.

- lib/jxl/decode.cc
- tools/djxl_fuzzer.cc
This fixes the case when API contract is broken - next `JXL_DEC_FRAME` arrives without `JXL_DEC_FULL_IMAGE`.
However it is unlikely that normal users will face it - that fires on a complex mixture: boxes + lossless jpeg + preview? + multi-frame
> Fix dead-end in jpeg-transcode flow

- lib/jxl/ans_test.cc
- lib/jxl/dec_ans.cc
- lib/jxl/enc_ans.cc
- lib/jxl/enc_ans.h
- lib/jxl/enc_ans_params.h
- lib/jxl/enc_bit_writer.cc
- lib/jxl/enc_bit_writer.h
- lib/jxl/enc_cache.cc
- lib/jxl/enc_cache.h
- lib/jxl/enc_cluster.cc
- lib/jxl/enc_cluster.h
- lib/jxl/enc_coeff_order.cc
- lib/jxl/enc_coeff_order.h
- lib/jxl/enc_context_map.cc
- lib/jxl/enc_entropy_coder.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_group.cc
- lib/jxl/enc_heuristics.cc
- lib/jxl/enc_heuristics.h
- lib/jxl/enc_icc_codec.cc
- lib/jxl/enc_modular.cc
- lib/jxl/enc_modular.h
- lib/jxl/enc_patch_dictionary.cc
- lib/jxl/enc_splines.cc
- lib/jxl/modular/encoding/enc_encoding.cc
- lib/jxl/passes_state.h
All the internal images are now limited to the 2048x2048 DC group size, and the maximum memory usage is around 500 MB.
```
Encoding           kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2   PSNR        pnorm       BPP*pnorm   QABPP   Bugs
---------------------------------------------------------------------------------------------------------------------------------------------
jxl:d0.1:1          156870 125499004    6.4001333   2.883  17.712   0.33339094  93.97017505  55.04   0.11910771  0.762305231867   6.400      0
jxl:d0.1:3          156870 118196370    6.0277173   1.342  14.221   0.33339094  93.97017505  55.04   0.11910771  0.717947620036   6.028      0
jxl:d0.1:4          156870 117892031    6.0121968   1.501  14.289   0.33382890 …
```
> Implement streaming encoder mode with constant memory usage.

- lib/extras/dec/pnm.cc
- lib/extras/dec/pnm.h
- lib/extras/mmap.cc
- lib/extras/mmap.h
- lib/extras/packed_image.h
- lib/jxl_lists.bzl
- lib/jxl_lists.cmake
- tools/cjxl_main.cc
This PR recovers most of the low-core speed loss from using streaming input/output for fast lossless.
Memory usage may be increased, depending on OS choices. However, in case of out of memory, the OS should always unmap pages loaded because of this change.
```
Before:
7216 x 5412, geomean: 76.994 MP/s [76.29, 79.14], 20 reps, 2 threads.
3.67user 9.16system 0:10.18elapsed 126%CPU (0avgtext+0avgdata 8936maxresident)k
680inputs+223752outputs (4major+319857minor)pagefaults 0swaps
After:
7216 x 5412, geomean: 327.330 MP/s [296.45, 338.47], 20 reps, 2 threads.
3.28user 0.83system 0:02.47elapsed 166%CPU (0avgtext+0avgdata 123000maxresident)k
0inputs+111872outputs (10major+309603minor)pagefaults 0swaps
Non-streaming:
7216 x 5412, geomean: 369.804 MP/s [258.03, 371.21], 20 reps, 2 threads. …
```
> mmap-backed implementation of PNM streaming input.

- lib/jxl/enc_patch_dictionary.cc
- lib/jxl/jxl_test.cc
> Stop using opsin.xsize() and opsin.ysize() in patch search.

- lib/extras/dec/jxl.h
In #1823 djxl got `bits_per_sample` argument.
It is said, that default behavior is to export with full bit depth of output format. But #2591 has broken this contract to save with with depth of input format. After that change it become impossible to fulfill the contract (`bits_per_sample` both `-1` and `0` meant the same).
> Fixes #3018 - can't save 32-bit float JXL to PNG

- lib/jxl/cms/jxl_cms.cc
- lib/jxl_cms.cmake
- third_party/skcms.cmake
This ensures that when libjxl_cms is built statically and installed system-wide (which skcms won’t be), its users are able to link to it.
Fixes #3021.
> When building with skcms, incorporate it into libjxl_cms

- lib/jxl/enc_fast_lossless.cc
- lib/jxl/enc_fast_lossless.h
- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
This should reduce the amount of input requests significantly.
Size in streaming mode increases by up to ~5% depending on image content.
```
Before:
artificial.ppm: Compressed to 2105.3 kB (2.677 bpp).
big_building.ppm: Compressed to 57276.8 kB (11.733 bpp).
big_tree.ppm: Compressed to 48669.9 kB (14.056 bpp).
cathedral.ppm: Compressed to 9031.3 kB (12.010 bpp).
fireworks.ppm: Compressed to 5973.9 kB (6.479 bpp).
flower_foveon.ppm: Compressed to 3130.9 kB (7.304 bpp).
hdr.ppm: Compressed to 6949.5 kB (8.837 bpp).
leaves_iso_1600.ppm: Compressed to 10643.3 kB (14.153 bpp).
leaves_iso_200.ppm: Compressed to 9060.4 kB (12.048 bpp).
nightshot_iso_100.ppm: Compressed to 7719.1 kB (8.372 bpp).
nightshot_iso_1600.ppm: Compressed to 12916.3 kB (14.009 bpp).
spider_web.ppm: Compressed to 9820.6 kB …
```
> Modify the sampling algorithm in fast-lossless streaming mode.

- lib/jxl/enc_aux_out.cc
Fixes: https://github.com/libjxl/libjxl/issues/3091
See also: https://github.com/libjxl/libjxl/commit/97ec970d06ad04254f2cdcbe0bf8bba3166372b6
Some platforms need `__STDC_FORMAT_MACROS` defined prior to including `inttypes.h`, otherwise all PRI* defines are unavailable, which breaks the build. See the issue.
Perhaps CLA is signed, since I contributed earlier.
> enc_aux_out.cc: define `__STDC_FORMAT_MACROS` if undefined

- lib/jxl/convolve.h
- lib/jxl/convolve_separable5.cc
- lib/jxl/convolve_separable7.cc
- lib/jxl/convolve_slow.cc
- lib/jxl/convolve_symmetric5.cc
- lib/jxl/convolve_test.cc
This is for now only implemented for the slow mode and the symmetric5 mode, others are not needed for the streaming encoder.
> Make convolution work for arbitrary input/output rectangles.

- lib/include/jxl/encode.h
- lib/jxl/enc_ac_strategy.cc
- lib/jxl/enc_ac_strategy.h
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_adaptive_quantization.h
- lib/jxl/enc_ar_control_field.cc
- lib/jxl/enc_ar_control_field.h
- lib/jxl/enc_cache.cc
- lib/jxl/enc_cache.h
- lib/jxl/enc_chroma_from_luma.cc
- lib/jxl/enc_chroma_from_luma.h
- lib/jxl/enc_frame.cc
- lib/jxl/enc_gaborish.cc
- lib/jxl/enc_gaborish.h
- lib/jxl/enc_gaborish_test.cc
- lib/jxl/enc_group.cc
- lib/jxl/enc_group.h
- lib/jxl/enc_heuristics.cc
- lib/jxl/enc_heuristics.h
- lib/jxl/enc_modular.cc
- lib/jxl/image.h
```
Encoding         kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2   PSNR        pnorm       BPP*pnorm   QABPP   Bugs
-------------------------------------------------------------------------------------------------------------------------------------------
BEFORE:
jxl:d1:1:buf3     156870 30083811    1.5341986  10.752  38.434   1.43588506  86.14940783  43.59   0.58841531  0.902745969086   2.236      0
jxl:d1:3:buf3     156870 28045193    1.4302342   9.866  36.601   1.43588506  86.14940783  43.59   0.58841531  0.841571732152   2.083      0
jxl:d1:4:buf3     156870 28554209    1.4561928   9.028  26.851   1.43953718  86.43275684  43.61   0.58675396  0.854426882480   2.124      0
jxl:d1:5:buf3     156870 23633360    1.2052419   3.013  39.530 …
```
> Enable Gaborish for streaming mode.

- lib/jxl/enc_adaptive_quantization.cc
This makes the streaming and non-streaming versions of the adaptive quantization map the same.
Benchmark results for non-streaming mode:
```
BEFORE
jxl:d1:1       156870 30373676    1.5489810   8.015  34.055   1.43588506  86.14940783  43.59   0.58841531  0.911444150987   2.257      0
jxl:d1:3       156870 27841570    1.4198500   6.669  30.050   1.43588506  86.14940783  43.59   0.58841531  0.835461474297   2.068      0
jxl:d1:4       156870 28110273    1.4335532   5.963  28.523   1.43953718  86.43275684  43.61 …
```
> Use border pixels of tiles in streaming adaptive quantization.

- lib/include/jxl/encode.h
- lib/jxl/enc_frame.cc
- lib/jxl/enc_heuristics.cc
- lib/jxl/enc_params.h
- lib/jxl/encode.cc
- tools/benchmark/benchmark_codec_jxl.cc
This will be used for testing equivalence of streaming and non-streaming modes. This change is a no-op by default.
> Add encoder option to disable full image based heuristics.

- lib/jxl/enc_ar_control_field.cc
- lib/jxl/enc_gaborish.cc
- lib/jxl/image.h
With this change the streaming mode and non-streaming mode produce the same pixels up to effort 6 (with the no-full-image-heuristic mode).
```
Encoding               kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2   PSNR        pnorm       BPP*pnorm   QABPP   Bugs
-------------------------------------------------------------------------------------------------------------------------------------------------
BEFORE:
jxl:d0.1:fi0:6          156870 139354770    7.1067425   1.335  19.288   0.34056786  93.91142399  57.02   0.10183740  0.723732157417   7.107      0
jxl:d0.1:fi0:6:buf3     156870 140549699    7.1676808   1.491  21.354   0.34056786  93.91142399  57.02   0.10183740  0.729937962522   7.168      0
jxl:d1:fi0:6            156870 25205202 …
```
> Use borders for EPF field in streaming mode.

- AUTHORS
- tools/djxl_main.cc
djxl was not doing anything if `--disable_output` is set, due to the changes introduced in v0.9.0 (presumably #2686) that decodes only image metadata when the list of accepted pixel format is empty.
> djxl: Request float pixel formats if --disable_output is set

- plugins/gdk-pixbuf/CMakeLists.txt
Fix for https://github.com/gentoo/gentoo/pull/34799#issuecomment-1892391058
> plugins: use JPEGXL_TEST_DATA_PATH instead of hard-coded path.

- lib/jxl/enc_chroma_from_luma.cc
- lib/jxl/enc_chroma_from_luma.h
- lib/jxl/enc_heuristics.cc
This is a global image heuristics that could introduce pixel differences in streaming mode, but it does not make a difference in practice.
Benchmark results on small images:
```
BEFORE:
jxl:d0.1        13270 12575672    7.5811584   0.688  16.435   0.31300673  95.34879620  55.43   0.10223163  0.775034177620   7.581      0
jxl:d1          13270  2923926    1.7626689   0.946  26.249   1.36367276  86.74409296  41.97   0.58689168  1.034495722999   2.443      0
jxl:d2          13270  1760918    1.0615574   1.046  25.471 …
```
> Remove custom DC chroma-from luma heuristics.

- lib/jxl/decode_test.cc
- lib/jxl/enc_heuristics.cc
- lib/jxl/jxl_test.cc
- tools/scripts/jxl-eval.sh
This change removes the non-streamable heuristics for quantizing the adaptive quantization field that depends on global statistics.
Benchmark on 31 images:
```
BEFORE:
jxl:d0.1:6      13270 12626327    7.6116954   0.800  16.867   0.31356426  95.36709772  55.37   0.10249605  0.780168699734   7.612      0
jxl:d0.5:6      13270  4762922    2.8712952   1.031  27.333   0.79376823  91.31835271  45.82   0.34330964  0.985743308245   2.902      0
jxl:d1:6        13270  2929121    1.7658007   1.097  28.909   1.37083528 …
```
> Simplify adaptive quantization field quantization.

- lib/jxl/enc_frame.cc
```
BEFORE
jxl:d0.1:6      16460 14855553    7.2201252   0.734  14.748   0.32632550  95.55052636  55.98   0.10797757  0.779611600960   7.220      0
jxl:d1:6        16460  3619784    1.7592946   1.003  22.865   1.33882102  86.96879756  42.79   0.56881514  1.000713393425   2.388      0
jxl:d2:6        16460  2224826    1.0813143   1.009  23.328   2.30537368  79.11047984  39.21   0.95280424  1.030280878257   2.555      0
jxl:d8:6        16460   742198    0.3607245   1.086  14.263   6.53787903 …
```
> Use pixel stats based chromacity adjustment from effort 7.

- lib/extras/packed_image_convert.cc
(This failed for >8-bit formats.)
> Fix stride in ConvertImage3FToPackedPixelFile

- lib/jxl/base/status.h
This is a small tweak in the definition of `JXL_DEBUG_V_LEVEL` that removes the `JXL_DEBUG` blocks when `JXL_DEBUG_V_LEVEL` is `0`.
> Change definition of JXL_DEBUG_V when JXL_DEBUG_V_LEVEL is zero.

- lib/include/jxl/encode.h
Adds additional documentation to JxlEncoderAddJPEGFrame to make it clear that this function can only be used for lossless JPEG transcoding.
This PR resolves the [issue I raised here.](https://github.com/libjxl/libjxl/issues/3210) It adds an extra sentence to the `JxlEncoderAddJPEGFrame` function doc comment to make it clear that it can only be used for lossless JPEG transcoding.
> Add documentation to JxlEncoderAddJPEGFrame indicating it's for lossless compression only

- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
- plugins/gdk-pixbuf/pixbufloader-jxl.c
**plugins/gdk-pixbuf: consider stride when passing buffer to libjxl**
This change uses gdk_pixbuf_get_pixels_with_length to get the actual
size of the buffer, with stride taken into account. The previous code
just multiplies width by height and ignores stride.
Signed-off-by: Leo Izen <leo.izen@gmail.com>
**lib/jxl/decode.cc: deduplicate and correct min_size calculation**
Code to calculate the proper size of the buffer exists in three places
in this function - one for the standard buffer, one for the extra
channel buffer, and one for the preview buffer. However, only the code
for the preview buffer correctly took into account the last row size
possibly being slightly smaller than the remaining rows.
This commit separates the code out into a separate function to remove
duplicate code, and …
> GDK Pixbuf Loader Fixes

- lib/extras/enc/jxl.h
- lib/jxl/enc_frame.cc
- lib/jxl/enc_modular.cc
- lib/jxl/enc_params.h
- lib/jxl/encode.cc
- lib/jxl/encode_test.cc
- lib/jxl/jxl_test.cc
- tools/cjxl_main.cc
This is in preparation to adding support for streaming-mode extra channel coding.
> Do not encode alpha lossily by default in VarDCT mode.

- lib/jxl/cms/jxl_cms.cc
Closes #1973.
Because there appear to be images with faulty rendering intent in their ICC profiles in the wild, we relax the check for valid rendering intent to a warning if we are able to deduce a plausible value for the rendering for the last byte of the rendering intent of the ICC profiles, i.e. the byte at offset 67, even if the other bytes (at offsets 64, 65 and 66) are non-zero. In that case we print a warning.
> relax rendering intent check

- lib/extras/dec/apng.cc
- lib/extras/dec/color_hints.cc
- lib/extras/dec/jpegli.cc
- lib/extras/dec/jpg.cc
- lib/extras/dec/jxl.cc
- lib/extras/dec/jxl.h
- lib/extras/enc/apng.cc
- lib/extras/enc/jpegli.cc
- lib/extras/enc/jxl.cc
- lib/extras/packed_image.h
- lib/extras/packed_image_convert.cc
- lib/jxl/blending_test.cc
- lib/jxl/jxl_test.cc
- tools/djxl_main.cc
Always produce the ICC profile, but also indicate whether it’s the primary colorspace representation or not.
This lets `enc/jxl` ignore it if it’s not, and `enc/apng` include it for compatibility, helping with #2289.
> Fix #2581 in a different way

- lib/jxl/enc_frame.cc
- lib/jxl/enc_modular.cc
- lib/jxl/enc_params.h
- lib/jxl/encode.cc
- lib/jxl/encode_test.cc
- lib/jxl/modular_test.cc
- tools/cjxl_main.cc
```
Before:
Encoding [Modular, lossless, effort: 7]
Compressed to 137.9 kB (9.629 bpp).
444 x 258, geomean: 0.370 MP/s [0.35, 0.52], 20 reps, 72 threads.
7.69user 3.43system 0:06.12elapsed 181%CPU (0avgtext+0avgdata 96460maxresident)k
Encoding [Modular, lossless, effort: 8]
Compressed to 137.6 kB (9.606 bpp).
444 x 258, geomean: 0.148 MP/s [0.15, 0.15], 5 reps, 72 threads.
4.05user 0.87system 0:03.84elapsed 128%CPU (0avgtext+0avgdata 36848maxresident)k
Encoding [Modular, lossless, effort: 9]
Compressed to 137.3 kB (9.586 bpp).
444 x 258, geomean: 0.038 MP/s [0.04, 0.04], 5 reps, 72 threads.
15.46user 0.88system 0:14.99elapsed 109%CPU (0avgtext+0avgdata 67496maxresident)k
Encoding [Modular, lossless, effort: 7]
Compressed to 47974.1 kB (9.827 bpp).
7216 x 5412, geomean: 0.255 MP/s [0.25, …
```
> Update modular efforts to faster settings.

- plugins/gdk-pixbuf/pixbufloader-jxl.c
djxl and libjxl already silently ignore garbage trailing data at end of file for otherwise-valid JXL files, so there's no reason the gdk pixbuf loader should refuse to decode these files.
> plugins/gdk-pixbuf: allow trailing data at end of file

- lib/jxl/enc_frame.cc
This prevents the encoder crashing with some configurations.
> Set a minimum epf for modular if doing EPF in modular lossy.

- lib/jxl/common.h
- lib/jxl/enc_ans.cc
- lib/jxl/enc_ans_params.h
- lib/jxl/enc_cluster.h
- lib/jxl/enc_context_map.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_icc_codec.cc
- lib/jxl/enc_modular.cc
- lib/jxl/enc_params.h
- lib/jxl/jxl_test.cc
- lib/jxl/modular/encoding/enc_encoding.cc
- lib/jxl/modular/options.h
```
/home/veluca/libjxl/testdata/jxl/flower/flower.png
Encoding         kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2   PSNR        pnorm       BPP*pnorm   QABPP   Bugs
-------------------------------------------------------------------------------------------------------------------------------------------
jxl:2:d0:buf3       3429  3196707    7.4575810  55.181 161.038         -nan 100.00000000  99.99   0.00000000  0.000000000000   7.458      0
jxl:2:d0            3429  3304063    7.7080312  32.291 112.184         -nan 100.00000000  99.99   0.00000000  0.000000000000   7.708      0
jxl:3:d0:buf3       3429  2971057    6.9311633  17.053  30.484         -nan 100.00000000  99.99   0.00000000  0.000000000000   6.931      0
jxl:3:d0            3429  2975615 …
```
> Fix effort2/3 streaming vs nonstreaming

- lib/jxl/enc_frame.cc
As this happens only when weird combinations of options were requested, this is simpler than trying to fix all the corner cases and should not affect most sensible usages.
> Switch to Thunder mode if fjxl cannot handle Lightning.

- lib/include/jxl/encode.h
- lib/jxl/enc_frame.cc
- lib/jxl/enc_params.h
- lib/jxl/encode.cc
- lib/jxl/encode_test.cc
- lib/jxl/jxl_test.cc
- tools/cjxl_main.cc
- tools/streaming_fuzzer.cc
Moves the cjxl logic to decide what kind of buffering to use to the library itself.
This makes the default libjxl behavior significantly faster for large images.
> have default buffering mode as in cjxl

- lib/jxl/jxl_test.cc
- lib/jxl/modular/encoding/enc_encoding.cc
The total number of pixels was being incorrectly set to 0.
> Fix the usage of fixed trees with streaming mode.

- lib/jxl/enc_modular.cc
Ensure that the group ID is always avaliable as a property if doing modular lossy.
> Fix non-squeeze modular on small images.

- examples/CMakeLists.txt
- lib/CMakeLists.txt
- lib/jxl.cmake
- lib/jxl/libjxl.pc.in
- lib/jxl/libjxl_cms.pc.in
- lib/jxl_cms.cmake
This ensures that if libjxl is built statically, C programs that use it will still link properly.
> Include `-lm` and the C++ standard library in pkgconfig “Libs” as appropriate

- lib/jxl/enc_heuristics.cc
- lib/jxl/enc_modular.cc
Fixes the passing of splines from jxl_from_tree to the encoder.
> fix jxl_from_tree splines passing

- lib/jxl/enc_modular.cc
This is a pessimization for photographic content with local trees.
Fixes #3323.
> Do not use Variable predictor by default at e9.

- README.md
Update README.md to state that cjxl/djxl can also read/write jxl files themselves, and be more explicit about the file formats supported. Also use code backticks for file extensions.
Closes #3349.
> README.md: update and clarify input/output file extensions

- lib/jxl/enc_fast_lossless.cc
Fixes #3357 
There was a bug in the lossless e1 encoder in the specific case that
- a palette could be used
- the palette does _not_ contain the color black (all-zeroes)
In the original palette detection code, we would write a palette without the color black in this particular case, but that was changed to make the palette detection faster and now we simply always have the color black in the palette even if it is not actually used in the image. However the code that writes the palette itself was not properly updated to reflect that, so it wrote a wrong palette, which caused all palette indices to be off-by-one. This fixes that.
> fix bug in lossless e1 palette writing

- lib/jxl/enc_detect_dots.cc
- lib/jxl/enc_detect_dots.h
- lib/jxl/enc_dot_dictionary.cc
- lib/jxl/enc_dot_dictionary.h
- lib/jxl/enc_patch_dictionary.cc
> Fix roundtrip failure for images with dots near the border.

- lib/extras/enc/jpegli.cc
- lib/jxl/color_encoding_internal.h
- lib/jxl/color_management_test.cc
- lib/jxl/enc_image_bundle.cc
- lib/jxl/enc_xyb.cc
- lib/jxl/render_pipeline/stage_cms.cc
Also transform only as many pixels as needed.
Fixes #3348.
> Fix assert in CMS stage

- .github/workflows/release.yaml
- ci.sh
Drive-by: fix linkage (before that pkgconfig was not working!)
And now we have evidence that "Release" build is slower than MSYS2 / nix.
> Benckmark release windows binaries

- lib/extras/dec/decode.cc
Otherwise it defaults to taking the bitdepth from the pixel format, which is always float32.
> preserve bitdepth when taking jxl input

- .github/workflows/build_test.yml
- .github/workflows/build_test_bazel.yml
- .github/workflows/build_test_cross.yml
- .github/workflows/build_test_md.yml
- .github/workflows/build_test_msys2.yml
- .github/workflows/build_test_wasm.yml
- .github/workflows/codeql.yml
- .github/workflows/conformance.yml
- .github/workflows/dependency-review.yml
- .github/workflows/fuzz.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
With label 'CI:none' most workflows will be disabled; new/debugged workflows could be enabled manually.
Obviously, PR could not be landed while until this label is removed.
> Add possibility to skip most worflows (for debugging)

- lib/jxl.cmake
- lib/jxl_cms.cmake
- lib/jxl_extras.cmake
When building a local git version of libjxl on a system that already has libjxl headers system-installed, the build can fail because the system headers might be outdated. This should fix that (at least it does for me).
> include local jxl headers before system headers

- lib/jpegli/color_transform.cc
Use extended `J_COLOR_SPACE` enum values behind the `#ifdef`.
This PR does not change where build system looks for `jpeglib` headers.
> Partially fix #2320

- doc/developing_in_github.md
At least for me, "git clone git https://github.com/libjxl/libjxl --recursive" causes an error "fatal: repository git does not exist".
I believe the extra "git" is a typo.
> Corrected the checkout instruction in developing_in_github.md.

- lib/jxl/enc_modular.cc
- lib/jxl/enc_modular.h
- lib/jxl/encode_test.cc
- lib/jxl/modular/transform/enc_palette.cc
- lib/jxl/modular/transform/palette.h
- lib/jxl/modular_test.cc
Some tweaks to the modular palette heuristics:
- Refactored some code (there was some near-duplicate code between global and group encoding)
- Change the max_colors heuristic to make it less likely to use palette when the image/group has low entropy already anyway (e.g. the group is only a smooth gradient, which has few enough colors for doing a palette but also palette doesn't help)
- Actually use the implicit palette if these colors happen to occur in the image (but still make them explicit if they are frequent)
- Tweak the palette ordering: still luma sorted, but first the 'common' colors and then the 'rare' colors
- Don't do palette if the whole group is just a single color (it's slightly cheaper not to)
Before:
benchmark_xl v0.10.0 453f1127 [NEON]
12 total threads, 17088 tasks, 6 …
> tweak palette heuristics

- tools/CMakeLists.txt
- tools/icc_simplify.cc
Adds a new tool called `icc_simplify` that can be used to simplify/rewrite/fix/normalize ICC profiles. It uses the libjxl encoder-side logic to interpret an input ICC profile and the decoder-side logic to synthesize an output ICC profile. For ICC profiles found in the wild, the effect is generally that the output profile is smaller than the input profile, sometimes substantially, since things like description strings in various languages or redundant transfer function tables will get stripped.
The tool also allows synthesizing profiles from a colorspace description string, as well as from an input image that might contain an ICC profile or some other way to signal the colorspace — in particular, PNG has various other ways to signal the colorspace.
> add tool to simplify ICC profiles

- lib/extras/dec/jxl.cc
- lib/jxl/jxl_test.cc
If jpeg bytes were requested, we returned success even if the stream was truncated, without filling in the jpeg bytes. This can cause djxl to return successfully without writing any output file.
> Return error in case of truncated streams for jpeg reconstruction.

- lib/extras/dec/apng.cc
Fixes #3430
Those files are valid:
https://wiki.mozilla.org/APNG_Specification#Chunk_Sequence_Numbers
> The `fcTL` chunk is an ancillary chunk as defined in the PNG Specification. It must appear before the `IDAT` or `fdAT` chunks of the frame to which it applies
> Revert "Reject IDAT after fcTL"

- lib/jpegli/color_transform.cc
- lib/jpegli/decode.cc
- lib/jpegli/decode_api_test.cc
- lib/jpegli/test_utils.cc
Add color transforms to the JCS_EXT_* color spaces, since it is used in Chrome.
> Support more color transforms in jpegli decoder.

- lib/jpegli/color_transform.cc
- lib/jpegli/encode.cc
- lib/jpegli/encode_api_test.cc
- lib/jpegli/test_utils.cc
Add color transforms from the JCS_EXT_* color spaces, since it is used in Chrome (for e.g. creating thumbnails on the "New Tab" page).
> Support more color transforms in jpegli encoder.

- lib/jpegli/encode.cc
In accordance with IJG JPEG, see:
https://github.com/libjpeg-turbo/ijg/blob/jpeg-9e/transupp.c#L1879-L1880
https://github.com/libjpeg-turbo/ijg/blob/jpeg-9e/transupp.c#L2145-L2150
Helps: https://github.com/libvips/libvips/pull/3924.
> jpegli: force samp factors to 1x1 for single-component images

- doc/developing_in_debian.md
fixes
```
error: ignoring \dot command because HAVE_DOT is not set (warning treated as error, aborting now)
```
which happens when graphviz is not present
> add graphviz in documentation

- lib/extras/dec/decode.cc
- lib/extras/dec/decode.h
- lib/extras/enc/encode.cc
- lib/extras/enc/encode.h
- tools/cjpegli.cc
- tools/cjxl_main.cc
- tools/djpegli.cc
- tools/djxl_main.cc
Fixes https://github.com/libjxl/libjxl/issues/3498
(btw why don't we support JXL as an output format? e.g. using fast lossless encoding it could perhaps be a good alternative to PNG or PPM...)
> de-duplicate list of supported input/output codecs for tool help screens

- lib/extras/dec/color_description.cc
- lib/extras/jpegli_test.cc
- lib/jxl/cms/jxl_cms_internal.h
- tools/cjxl_main.cc
Adds a few special values for the colorspace description strings: `sRGB`, `DisplayP3`, `Rec2100PQ`, and `Rec2100HLG`. These are probably the most commonly used and relevant color spaces right now and in the foreseeable future.
This makes it somewhat more convenient to manually specify these colorspaces when e.g. using `cjxl` on a ppm or pfm input, that is, you can now also do `-x color_space=sRGB` instead of having to do `-x color_space=RGB_D65_SRG_Per_SRG` which I find hard to remember.
It also has the effect of making the description string a little shorter (and arguably easier to understand) in the corresponding synthesized ICC profiles.
> add shorthand colorspace descriptions

- lib/jxl/decode_test.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_frame.cc
- lib/jxl/encode_test.cc
- lib/jxl/jxl_test.cc
- lib/jxl/passes_test.cc
- lib/jxl/render_pipeline/render_pipeline_test.cc
- lib/jxl/roundtrip_test.cc
This is done so that chromaticty related quality degradations are mitigated.
```
BEFORE
jxl:d0.1        20795 17954256    6.9068854   1.278  15.017   0.35805166  95.37202576  55.88   0.11725678  0.809879134700   6.907      0
jxl:d0.25       20795 11185575    4.3030179   1.378  17.422   0.47584089  93.97937085  51.22   0.19450189  0.836945112541   4.328      0
jxl:d0.5        20795  7260540    2.7930825   1.506  19.257   0.78400613  91.40084419  47.11   0.33293958  0.929927705908   2.898      0
jxl:d1 …
```
> Increase quality in chromacity planes.

- tools/comparison_viewer/image_loading.cc
`base/rect.h` was moved to `jxl/base/rect.h`, but the include was not updated in `tools/comparison_viewer/image_loading.cc`.
> Fix compile error caused by moved rect.h

- lib/extras/enc/jxl.cc
- lib/include/jxl/encode.h
- lib/jxl/enc_frame.cc
- lib/jxl/enc_heuristics.cc
- lib/jxl/enc_params.h
- lib/jxl/enc_patch_dictionary.cc
- lib/jxl/encode.cc
- lib/jxl/jxl_test.cc
- tools/benchmark/benchmark_codec_jxl.cc
- tools/cjxl_main.cc
There still likely is something off with the implementation, but this lays the groundwork.
> Add an option for disabling perceptual optimizations.

- lib/jxl/enc_ac_strategy.cc
- lib/jxl/enc_heuristics.cc
- lib/jxl/encode_test.cc
```
Before:
jxl:d0.1        20315 17771024    6.9979205   1.070  10.836   0.35756577  95.39413774  55.88   0.11792287  0.825214859523   6.998      0
jxl:d0.5        20315  7252143    2.8557679   1.261  15.667   0.78009917  91.43862540  47.13   0.33393541  0.953642033483   2.944      0
jxl:d0.8        20315  5355383    2.1088568   1.171  16.131   1.11966839  88.71172911  44.48   0.47360329  0.998761497683   2.496      0
jxl:d1          20315  4592636    1.8085003   1.165  16.544   1.34746867  86.90689460  43.25 …
```
> minimal enc_heuristics improvement

- lib/include/jxl/color_encoding.h
- lib/jxl/cms/jxl_cms_internal.h
- lib/jxl/color_encoding_internal.h
and using "white point" (with a space) consistently
closes #3553
> typos in color encoding

- lib/jxl/enc_frame.cc
- lib/jxl/jxl_test.cc
Set the flag --keep_invisible to default to 1 for lossless processing, and 0 for lossy.
Change the test target file size since the new default flag will create a smaller file.
Switched test comparison method to Butteraugli which handles the invisible pixels correctly.
> Fixed --keep_invisible defaults.

- lib/jxl/enc_linalg.cc
- lib/jxl/enc_linalg_test.cc
The bound was too tight, I encountered a case where it produced NaN output with that number equal to 1.13687e-12.
Haven't tested if this new bound is safe but it should at least be safer than the current one.
> fix arithmetic issue in dot detection

- tools/benchmark/benchmark_args.cc
- tools/benchmark/benchmark_args.h
- tools/benchmark/benchmark_xl.cc
Adds an option `--generations=N` to do simple generation loss testing (same encode settings in each generation).
This makes it easier to evaluate the impact of changes in encoder heuristics in multi-generation scenarios (which are of course often an indication of a poor workflow on the user end, but it happens in practice nonetheless), as well as to improve any inaccuracies in the encoder or decoder implementation (e.g. in color conversions, implementation of transforms, etc) that could lead to cumulative errors or some kind of drift.
For example (and also to demonstrate that this is in fact an issue):
Normal single-generation:
benchmark_xl v0.10.2 99663f9d [NEON]
12 total threads, 5 tasks, 5 threads, 0 inner threads
```
005.png
Encoding                          kPixels    Bytes …
```
> add option for generation loss testing in benchmark_xl

- lib/jxl/enc_heuristics.cc
```
Before:
jxl:d0.1        20315 17771024    6.9979205   1.072  10.153   0.35756577  95.39413774  55.88   0.11792287  0.825214859523   6.998      0
jxl:d0.5        20315  7252143    2.8557679   1.278  14.595   0.78009917  91.43862540  47.13   0.33393541  0.953642033483   2.944      0
jxl:d0.8        20315  5363198    2.1119342   1.180  15.134   1.11808133  88.71449750  44.49   0.47287594  0.998682857933   2.498      0
jxl:d1          20315  4603082    1.8126137   1.202  16.286   1.34310821  86.92441895  43.26 …
```
> minor optimization for enc_heuristics

- lib/jxl/enc_gaborish.cc
- lib/jxl/enc_heuristics.cc
- lib/jxl/passes_test.cc
- lib/jxl/roundtrip_test.cc
This greatly reduces generation loss, but other issues in generation loss remain.
```
Before:
jxl:d0.1        20315 17771024    6.9979205   1.083  10.777   0.35756577  95.39413774  55.88   0.11792287  0.825214859523   6.998      0
jxl:d0.5        20315  7252143    2.8557679   1.284  15.072   0.78009917  91.43862540  47.13   0.33393541  0.953642033483   2.944      0
jxl:d0.8        20315  5367111    2.1134751   1.174  15.958   1.11498186  88.72067125  44.51   0.47189587  0.997340150865   2.494      0
jxl:d1 …
```
> Gaborish adjustment, more precise for high quality

- tools/benchmark/benchmark_stats.cc
- tools/benchmark/benchmark_stats.h
- tools/benchmark/benchmark_xl.cc
Fixes https://github.com/libjxl/libjxl/issues/3585
Also adds more details when using the flag `--print_distance_percentiles`.
Also fixes the aggregate value for ssimulacra2: it was ignoring negative values and taking the geomean of just the positive ones; now it just takes the arithmetic mean of all ssimulacra2 values.
Before:
```
50th/90th percentile distance: 0.74641287  0.89263189
jxl:d0.5        13562  4936672    2.9119624   2.323  34.301   0.76519037  91.52246513  46.23   0.34268783  0.997894059218   2.913      0 …
```
> more benchmark_xl output

- lib/extras/dec/pnm.cc
- lib/extras/enc/pnm.cc
Fixes two issues in PAM handling:
- `pec.ec_info` was not initialized, causing bogus values in `exponent_bits` and failure the encode.
- maximum header size when writing a PAM file was too small for e.g. the multispectral use case with 21 channel images.
> fix issues in pam encode/decode

- lib/jxl/enc_frame.cc
- lib/jxl/enc_heuristics.cc
- lib/jxl/enc_modular.cc
- lib/jxl/jxl_test.cc
- lib/jxl/passes_test.cc
At very high quality / low distance settings, some of the default encoder choices are doing more harm than good, especially w.r.t. generation loss. In particular:
- VarDCT mode: Gaborish is causing more distortion than it is reducing it, and it accumulates badly over generations. This PR disables Gaborish by default at distances up to 0.5
- Disabling gaborish caused a reduction in both quality and filesize; this PR adjusts the calibration to get gab0 closer to gab1
- Modular integer quantization of XYB is too coarse to allow very high-precision encoding
- Modular additional quantization of B is not useful and causes additional cumulative errors
The rationale for these changes is as follows: at very low distances, it is more likely that additional editing/processing will still be done, …
> Reduce generation loss

- lib/extras/dec/apng.cc
Avoids getting
```
lib/extras/dec/apng.cc:795: JXL_FAILURE: PNG signature mismatch
```
whenever reading input files that happen to be not PNGs.
> don't print error when loading something that is not a PNG

- lib/jxl/enc_modular.cc
- lib/jxl/encode.cc
- lib/jxl/modular/encoding/enc_encoding.cc
- lib/jxl/modular/encoding/enc_encoding.h
- lib/jxl/modular/encoding/encoding.cc
- lib/jxl/modular/encoding/encoding.h
The cutoffs used in the predefined trees for e2 (and the fallback e1 path) and e3 lossless encoding were designed with 8-bit images (possibly up to 10-bit) in mind. For higher bit depth images, compression improves when scaling up the cutoff values according to the bit depth.
Also: when explicitly enabling the previous channel extra properties (as set by the `-E` option in cjxl), we can use a previous channel  gradient difference property as context (based on the decoded value of the previous channel at the current pixel position), instead of the usual MA tree property we use in e2. This adds some encode/decode slowdown and is not necessarily better, but it can improve compression. This can be useful in particular for multi-spectral images with many correlated channels, like this example …
> improve lossless e2/e3 for > 10-bit images and make -E 1 do something when doing -e 2

- lib/jxl/image.cc
- lib/jxl/image.h
- lib/jxl/memory_manager_internal.cc
- lib/jxl/memory_manager_internal.h
- lib/jxl/render_pipeline/low_memory_render_pipeline.cc
In the render pipeline, we promise 16 floats before the pointer passed to each stage to be readable.
Because of implementation details of the pre-memory-manager image allocation, that was always the case before. Once we started using the memory manager, this is no longer the case. This PR introduces the possibility to explicitly ask for such padding and uses it in the render pipeline.
> Allow to ask for memory with 0-side padding.

- lib/extras/dec/color_description.cc
When trying to pass custom primaries in a color space string, the current code always produces an error even if the primaries parsed correctly. This fixes that.
> allow passing custom primaries

- tools/CMakeLists.txt
Fixes https://github.com/libjxl/libjxl/issues/2670
I think it is not necessary to explicitly add `-Werror` to the `libjxl_test` target, because Werror is enabled/disabled globally via:
```
if (JPEGXL_WARNINGS_AS_ERRORS)
add_compile_options(-Werror)
endif ()
```
> Make -Werror optional

- lib/jxl/base/float.h
- lib/jxl/blending_test.cc
- lib/jxl/enc_external_image.cc
- lib/jxl/jxl_test.cc
- lib/jxl/modular_test.cc
- lib/jxl/speed_tier_test.cc
- tools/benchmark/benchmark_codec_jxl.cc
- tools/scripts/roundtrip_test.sh
When loading 8-bit images to float, we used to do `* 257 * (1.0f / 65535)` instead of just `* (1.0f / 255)`, which in floating point arithmetic is somehow not quite the same thing. For example, for the 8-bit value 254, the first formula produces the value 0.996078431606292724609375, while the second produces the value 0.996078491210937500000000, a difference of 5.96046e-08. This was basically a hack to ensure uint8 images decoded to uint16 buffers would still map all values to the same float32 values.
However, it only works for uint8 and uint16. For e.g. 10-bit or 12-bit images, this kind of trick doesn't work: while 65535 = 255*257, i.e. the uint16 maxval is an integer multiple of the uint8 maxval, so uint8 values can be represented exactly as uint16 values, but this is not the case for …
> don't do a funky conversion from uint8 to float

- plugins/gimp/file-jxl-load.cc
The Gimp plugin fails to load any image with a named frame...
```
file-jxl-loadError: JxlDecoderGetFrameName failed
```
...due to the name buffer being 1 byte too short.  This fixes it, and also makes sure the buffer is freed on return.
Drive-by: also avoid leaking the blend string(s), by not allocating them in the first place.
```
$ jxlinfo two_frames_with_names.jxl
JPEG XL animation, 32x32, (possibly) lossless, 8-bit RGB+Alpha
Color space: RGB, D65, sRGB primaries, sRGB transfer function, rendering intent: Relative
frame: full image size, duration: 1000.0 ms, name: "the first frame"
frame: 32x32 at position (10,20), duration: 1000.0 ms, name: "the second frame"
Animation length: 2.000 seconds (looping)
```
(Is the plugin here still going to be maintained now that Gimp has its own …
> Gimp plugin: fix loading files with named frames

- tools/benchmark/benchmark_utils.cc
Use a dedicated `environ` definition on macOS, which is supported on all macOS versions.
> benchmark_utils: use correct environ on macOS

- lib/jxl/encode.cc
Fixes https://github.com/libjxl/libjxl/issues/3729
https://github.com/libjxl/libjxl/pull/3661 accidentally caused FastLossless to never be used on PNG input, since `frame_settings->values.image_bit_depth.bits_per_sample` is always 0 (it's a value that gets ignored and that doesn't get set).
So the test was wrong before because it always succeeded on PNG input (which was bad because it can cause wrong results, when using --override_bitdepth), but the fix was also wrong because it always failed on PNG input (which is slightly less bad but causes e1 to be slower than expected).
Now it should be OK :)
(on PPM input, there was no issue)
> fix e1 condition again

- lib/jxl/decode_test.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/encode_test.cc
- tools/optimizer/simplex_fork.py
https://github.com/libjxl/libjxl/issues/414
0.08 % win on BPP * pnorm
small improvement on 'blue eyes' problem, perhaps fixes 15 % of the issue
```
Before:
104 images
jxl:d0.1        20315 17201092    6.7734912   0.877   9.400   0.27150021  95.71487004  56.45   0.09202106  0.623303827334   6.776      0
jxl:d0.5        20315  7097969    2.7950569   1.055  13.011   0.85951955  91.44716664  46.43   0.34549147  0.965668308615   2.933      0
jxl:d0.8        20315  5369188    2.1142929   0.956  11.795   1.10998495 …
```
> more bits and precision for small blue details

- lib/jxl/ans_test.cc
- lib/jxl/bit_reader_test.cc
- lib/jxl/decode_test.cc
- lib/jxl/enc_ans.cc
- lib/jxl/enc_bit_writer.cc
- lib/jxl/enc_bit_writer.h
- lib/jxl/enc_chroma_from_luma.cc
- lib/jxl/enc_context_map.cc
- lib/jxl/enc_fields.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_group.cc
- lib/jxl/enc_icc_codec.cc
- lib/jxl/enc_modular.cc
- lib/jxl/enc_noise.cc
- lib/jxl/enc_quant_weights.cc
- lib/jxl/enc_toc.cc
- lib/jxl/encode.cc
- lib/jxl/fields_test.cc
- lib/jxl/image_bundle_test.cc
- lib/jxl/modular_test.cc
- lib/jxl/test_utils.cc
- lib/jxl/toc_test.cc
This lets us detect and handle failure in initialisation without requiring that we make `Allotment` movable for use with `JXL_ASSIGN_OR_RETURN`.
> Expose a wrapper function instead of Allotment

- tools/file_io.h
Windows stdin and stdout default to text mode, but they can be changed to binary mode with _setmode from <io.h>. This is relevant because text mode enables LF <-> CRLF translation, and binary mode disables it, and it needs to be disabled for image reading/writing. This is technically also true on Unix-like operating systems, but text and binary do the same thing on macOS, Linux, etc.
Fixes #542
> tools/file_io.h: set binary mode for stdin and stdout on Windows

- lib/extras/dec/pnm.cc
- lib/extras/enc/pnm.cc
This allows you to have kUnknown and kOptional extra channels in PAM input/output.
For example, for 21-channel 16-bit multispectral images, where the first three are RGB and then there are 18 additional channels that are represented as extra channels of type kOptional, you could use a (somewhat nonstandard) PAM file with a header like this:
```
P7
WIDTH 4865
HEIGHT 4091
DEPTH 21
MAXVAL 65535
TUPLTYPE RGB
TUPLTYPE Optional
TUPLTYPE Optional
TUPLTYPE Optional
[...]
TUPLTYPE Optional
ENDHDR
```
Not the most beautiful way to deal with this type of data, but at least this provides a way to do it.
> add unknown and optional extra channels in PAM

- lib/jxl/enc_frame.cc
84 images, 20 threads:
```
bpp (mean)        unique mins            Mpx/s real (mean)
B        |         mins    |       Mpx/s CPU (mean)            best of
7318553  3.482824  73.81%  42.86%  0.003986642    0.02157361   cjxl_0.11.0-637806b1-p24t21-fix_d0e11
7325717  3.488910  57.14%  26.19%  0.00025005346  0.004543083  cjxl_0.11.0-637806b1_d0e11
```
> Fix e11 iterations

- lib/jxl/decode_test.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_heuristics.cc
- lib/jxl/jxl_test.cc
- tools/optimizer/simplex_fork.py
about 0.18 % improvement on image quality as measured by BPP*pnorm
```
Before:
104 images
jxl:d0.1        20315 17234055    6.7864714   0.795   8.565   0.26921220  95.72922587  56.47   0.09149990  0.620961464563   6.786      0
jxl:d0.5        20315  7112515    2.8007848   0.940  12.078   0.85998310  91.46395356  46.44   0.34487223  0.965912919133   2.941      0
jxl:d0.8        20315  5380024    2.1185600   0.861  11.031   1.10730124  88.87286260  44.43   0.46413467  0.983297134681   2.471      0
jxl:d1          20315 …
```
> encoding changes for more precise epf

- CMakeLists.txt
> In static builds, also link the MSVC runtime statically

- tools/benchmark/benchmark_codec_avif.cc
Fixes regression since 5df155d975bd8ecf091f2b808d41cdd1f37e09b8. This commit restores compatibility with these functions using libavif before major version 1, as they didn't return a result in those cases.
Fixes #3753.
> tools/benchmark_codec_avif.cc: restore compatability with libavif < 1

- lib/extras/enc/apng.cc
I did the thing.
Lowers the zlib compression level from the default 6 to 1, to lessen the impact of PNG writing on JXL decoding tests.
This results in a 20% density decrease and a 73% speed increase of djxl when outputting to PNGs.
> Faster PNG compression

- tools/streaming_fuzzer.cc
and only check approximate equality of pixels in those cases.
> re-activate streaming fuzzer for higher efforts

- lib/jxl/loop_filter.h
Floating-point overloads of `std::abs` come from `<cmath>`. Also use non-deprecated C++ forms of the other headers.
Without this, the build fails on at least macOS 10.15:
```
libjxl-0.11.0/lib/jxl/loop_filter.cc:31:11: error: call to 'abs' is ambiguous
if (std::abs(1.0f + (gab_x_weight1 + gab_x_weight2) * 4) < 1e-8) {
^~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:132:6: note: candidate function
int      abs(int) __pure2;
^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/stdlib.h:110:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/stdlib.h:112:44: note: candidate function
inline …
```
> loop_filter.{c,h}: Use correct header for std::abs

- CMakeLists.txt
I needed this to get it to work in my macos/homebrew environment. Without this, it would go into the MSYS2 branch where it doesn't call `a2x` directly but invokes the Python interpreter on it — except it doesn't use the right Python version for that, and it fails (while calling `a2x` directly works fine).
> fix cmake script for homebrew a2x

- tools/benchmark/benchmark_codec_jxl.cc
Accept parameters 'tectonic_plate' or '11' in combination with 'expert'.
> Allow e11 in benchmark_xl

- lib/extras/enc/jpg.cc
Fix the following error when building with MinGW-w64 and libjpeg instead of libjpeg-turbo:
```raw
lib/extras/enc/jpg.cc:277:34: error: cannot convert 'long unsigned int*' to 'size_t*' {aka 'long long unsigned int*'}
277 |   jpeg_mem_dest(&cinfo, &buffer, &size);
|                                  ^~~~~
|                                  |
|                                  long unsigned int*
```
> Fix jpg.cc for MinGW-w64

- lib/jxl/enc_bit_writer.cc
- tools/streaming_fuzzer.cc
drive-by: some typos in streaming fuzzer
> Don't abort in the destructor of allotment if allocation failed

- CMakeLists.txt
> Don’t set CMAKE_MSVC_RUNTIME_LIBRARY in debug builds

- tools/djxl_main.cc
Fix a simple typo in the documentation for the downsampling argument.
> tools/djxl_main.cc: fix typo in -s documentation

- lib/jpegli/huffman.h
- lib/jxl/jpeg/enc_jpeg_huffman_decode.h
See also: https://www.youtube.com/watch?v=_ACCK0AUQ8Q&t=696s
> Port the Huffman lookup table size fix from brunsli.

- doc/software_support.md
Remove the reference to my imlib2 plugin, as imlib2 / Enlightenment has had built-in support JPEG XL for years now.
The only remaining selling point of the plugin was that it forced everything to decode to sRGB... which while obviously wrong, is arguably less wrong than what imlib2 itself does, which is ignore the color space completely.  But that's how all the imlib2 loaders behave, so I think most users will be OK with it :).
> Remove reference to imlib2-jxl plugin

- lib/extras/dec/jxl.cc
- lib/extras/enc/apng.cc
Also fix the detection of the primary encoding.
> PNG: only create cICP chunk if ColorEncoding is primary

- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_butteraugli_comparator.cc
- lib/jxl/enc_butteraugli_comparator.h
- tools/butteraugli_main.cc
Previously, the Butteraugli loop would use an intensity of 80 even for HDR content, thereby lowering quality at efforts 8 and above.
butteraugli_main also did not handle the reference and actual images having different intensity_targets, meaning that it was not possible to compare a PQ PNG (which would automatically have an intensity_target of 10000) with a compressed JXL version using a lower intensity_target (reflecting the fact that the image doesn’t actually get that bright).
ClassE_LasVegasStore, before:
e1:  1.709 bpp, Butteraugli 1.9095990658, 3-norm 0.763096
e2:  1.709 bpp, Butteraugli 1.9095990658, 3-norm 0.763096
e3:  1.616 bpp, Butteraugli 1.9095990658, 3-norm 0.763096
e4:  1.631 bpp, Butteraugli 1.9226754904, 3-norm 0.761637
e5:  1.519 bpp, Butteraugli 2.5887553692, 3-norm …
> e8+ and butteraugli: better HDR behavior

- .github/workflows/build_test_md.yml
- .github/workflows/build_test_msys2.yml
Likely forever (with MSYS2 toolchain); perhaps we will get some other alternatives in the future.
> Disable cross-clang32 build

- AUTHORS
- lib/jxl/enc_adaptive_quantization.cc
This bug explains why e10 is faster than e9. It's only doing 2 iterations instead of 4!
> Fix e10 butteraugli iterations

- lib/extras/enc/apng.cc
https://w3c.github.io/png/#cLLI-chunk
Reading remains to be updated. (We might want to read both?)
> PNG: write cLLI instead of cLLi, per recent update

- CMakeLists.txt
Likely fixes #3855 
Based on CMake developers answer: https://gitlab.kitware.com/cmake/cmake/-/issues/26330
> Use "canonical" expression for static link on MSVC

- CMakeLists.txt
In NixOS, the shebang of the `a2x` script is `xxx/bash -e`, which doesn't match the current regex, causing the build to default to Python and fail. 
This PR updates the regex to correctly match such shebangs.
> fix cmake script for a2x

- tools/cjxl_main.cc
Formatted everything more consistently. Corrected or clarified some text, streamlined phrasing generally. Renamed "Expert options" to "More advanced options" to mitigate --allow_expert_options confusion.
> Improve help text formatting and clarity

- lib/extras/codec_test.cc
- lib/extras/dec/exr.cc
Newer versions of OpenEXR are doing "scratch" reads that can span befind end of file (and thus misuse exceptions)
This PR adjusts our InMemoryIStream to fit OpenEXR expectations.
> Fix for newer versions of OpenEXR

- ci.sh
That is gcov issue we can not work around.
> Make gcov parser "suspicious_hits" a warning, not error

- lib/jxl/convolve-inl.h
E.g. for kRadius == 2 and ysize == 3 -> line [1] would be convolved twice
> Fix double-convolution for very short planes

- lib/jxl/enc_frame.cc
- lib/jxl/render_pipeline/render_pipeline_test.cc
- lib/jxl/tf_gbench.cc
- tools/gauss_blur_gbench.cc
> Fix some clang-tidy findings

- lib/jxl/enc_modular.cc
- lib/jxl/modular/encoding/enc_encoding.cc
- lib/jxl/modular/encoding/enc_ma.cc
- lib/jxl/modular/encoding/encoding.cc
Before this PR 0px channels were "skipped" before the check. In some cases 1xK and Kx1 images are squeezed (for 420 subsampling) and thus 0xK / Kx0 channels appear.
> Make 0px channels eligible for "stop" check

- lib/jxl/dct-inl.h
Seems to be performance / binary size neutral on non-scalable arch.
BEFORE
----------------------------------------------------------------------------
Benchmark                 Time             CPU   Iterations items_per_second
----------------------------------------------------------------------------
DCT2x2/AVX2            8.65 ns         8.64 ns    163279224       462.812M/s
DCT2x2/SSE4            9.51 ns         9.51 ns    145840086       420.697M/s
DCT2x2/SSE2            10.2 ns         10.2 ns    137965038       393.798M/s
IDCT2x2/AVX2           12.4 ns         12.4 ns    110683707       322.803M/s
IDCT2x2/SSE4           12.5 ns         12.5 ns    111257180       320.209M/s
IDCT2x2/SSE2           12.5 ns         12.5 ns    110645291       320.963M/s
DCT4x4/AVX2            21.1 ns …
> Scalable-friendly dct-inl.h

- lib/jxl/modular/options.h
GCC does not like inline default vector initialization.
> More GCC-related fixes

- lib/extras/tone_mapping.cc
- lib/extras/tone_mapping.h
- lib/jxl/cms/tone_mapping-inl.h
- lib/jxl/cms/tone_mapping.h
- lib/jxl/render_pipeline/stage_tone_mapping.cc
- tools/args.h
std::pair<float,float> is ABI incompatible across different C++ standards on ARM
Switch to std::array<float, 2>.
That will cause minor API change: in header-only part of jxl_cms.
But google-search haven't found any public uses of that API.
> Prevent ABI incompatibility on GCC + Arm

- tools/ssimulacra2_main.cc
Old help text:
```
Usage: ssimulacra2 orig.png distorted.png
Returns a score in range -inf..100, which correlates to subjective visual quality:
30 = low quality (p10 worst output of mozjpeg -quality 30)
50 = medium quality (average output of cjxl -q 40 or mozjpeg -quality 40,
p10 output of cjxl -q 50 or mozjpeg -quality 60)
70 = high quality (average output of cjxl -q 70 or mozjpeg -quality 70,
p10 output of cjxl -q 75 or mozjpeg -quality 80)
90 = very high quality (impossible to distinguish from original at 1:1,
average output of cjxl -q 90 or mozjpeg -quality 90)
```
New help text:
```
Usage: ssimulacra2 original.png distorted.png
Returns a score in range -inf..100, which correlates to subjective visual quality:
negative scores: extremely low quality, very strong distortion
10 = very …
```
> update help text of ssimulacra2 tool to be more accurate

- .github/workflows/build_test.yml
- .github/workflows/codeql.yml
- .github/workflows/conformance.yml
- .github/workflows/release.yaml
- plugins/gdk-pixbuf/CMakeLists.txt
Before it was breaking build too late (because message parameter should have been FATAL_ERROR, not FATAL).
Now it skips test if required binary is not found.
Instead fix all packages list to contain xdg-utils.
> Fix pixbufloader test

- lib/jpegli/entropy_coding.cc
When the mode is not progressive, we allow more than 2 clusters only if the quantization tables require extended sequential mode.
This is because extended sequential mode (0xff 0xc1) is not universally supported by jpeg decoders.
> Disable extended baseline mode in clustering by default.

- AUTHORS
- lib/jxl/decode_test.cc
- lib/jxl/enc_ans.cc
- lib/jxl/jxl_test.cc
RLE encoding procedure has a bug that skips one symbol after each run. It provides still valid results for encoding further, just some unnecessary additional run stops appear in the sequence, reducing the ability to compress histogram. This fix corrects "off-by-1" bug and provides then slightly better compression: that is why hardcoded sizes of output in several tests are corrected down as well.
Example: 
```
{12, 12, 13, 14, 15, 15, 15, 15, 7, 8, 6} histogram
{2,  0,  0,  1,  0,  3,  0,  0,  0, 1, 1} current same with +1
{2,  0,  1,  1,  4,  0,  0,  0,  1, 1, 1} correct same without +1
```
> Fix for RLE encoding

- doc/debugging_workflows.md
Only actions in allow-list are allowed now.
tmate is a potential token/secrets leaker (by design)
> Add note about tmate

- .github/workflows/build_test_md.yml
- .github/workflows/build_test_wasm.yml
- .github/workflows/test_new_highway.yml
That will help gathering more statistics on mysterious failures
Drive-by: make all CI non-fail-fast; that won't waste much resources, but will make reports more consistent (i.e. no more confusion between failed and cancelled because other job failed)
> Make WASM CI non-fail-fast

- lib/jxl/decode_test.cc
- tools/scripts/build_stats.py
`typ` should have been `type` but it is reserved property in Python.
This PR includes changes from #4140 (fix tests after #4111)
> Replace typ->kind

- lib/jxl/enc_ans.cc
- lib/jxl/jxl_test.cc
The remark in the normalize histogram code by @robryk suggested that rescaling targets can provide a better histogram, and this is indeed the case - many test cases show file size reduction with application of that rescaling.
Additionally `SmallestIncrement` is simplified for the invocation with `count > 0` (that is the only case used), and `target` was chosen to be float instead of int. The latter is connected to the problem in current implementation that arizes on near-flat histograms with `inc = 1` due to the fact that then `inc / 2 = 0`.
To illustrate the problem, take a histogram of 2048 values of 2 and 2048 values of 0 with `inc = 1`, then in the current realization `target = 2/0` correspondingly, and for all 2 values `target >= counts[n] + inc / 2` is true, therefore first method …
> More precise histogram

- tools/jxl_from_tree.cc
For larger images (more than one LF group) the buffering-by-default was messing stuff up.
> fix jxl_from_tree

- tools/CMakeLists.txt
- tools/jxltran.cc
This tool, as described in #871 will perform operations on existing jxl files, like changing the orientation or packing a codestream in a container.
---
I aimed small for this PR, but I plan to add more features to the tool. It will probably not be every single one listed in #871, but at least a few.
I tried to be the more idiomatic as possible to the `libjxl` style, but I probably did a few things wrong. I will happily make any requested change.
Oh, and I didn't add a test, but I can surely add one with some hints on how to do it.
> Introduce the new jxltran tool

- lib/include/jxl/encode.h
Fixes the description of how extended box size is signaled in the container format.  Just a comment fix - the code in encode.cc and decode.cc already behaves correctly.
> Fix description of the box size field

- .github/workflows/build_test.yml
This runner was retired yesterday:
```
This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
```
> remove Ubuntu 20.04

- lib/jxl/ans_common.cc
- lib/jxl/ans_common.h
- lib/jxl/dec_frame.cc
- lib/jxl/enc_ans.cc
- lib/jxl/enc_ans.h
- lib/jxl/enc_ans_params.h
- lib/jxl/enc_cluster.cc
- lib/jxl/enc_cluster.h
- lib/jxl/frame_header.h
- lib/jxl/jxl_test.cc
- lib/jxl/modular/encoding/context_predict.h
This refactoring streamlines the usage of histograms and separates all operations on histograms for ANS encoding into a class. The only functional change introduced is returning the correct encoding costs for empty and single-bin histograms in accordance with former `EncodeCounts`, now `ANSEncodingHistogram::Encode` - it changes some choices of best histograms and shrinks several test files by a byte or two.
> Refactoring: More general Histogram and specialized ANSEncodingHistogram

- .github/workflows/conformance.yml
- CMakeLists.txt
There seems to be some issue with SVE_256 that is causing trouble, e.g. conformance testing fails with large errors.
For now, disable this highway target.
> disable highway target SVE_256 for now

- lib/jxl/ans_test.cc
- lib/jxl/enc_ans.cc
- lib/jxl/enc_ans.h
- lib/jxl/enc_ans_params.h
- lib/jxl/enc_cluster.cc
- lib/jxl/enc_coeff_order.cc
- lib/jxl/enc_context_map.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_group.cc
- lib/jxl/enc_icc_codec.cc
- lib/jxl/enc_lz77.cc
- lib/jxl/enc_modular.cc
- lib/jxl/enc_patch_dictionary.cc
- lib/jxl/enc_splines.cc
- lib/jxl/modular/encoding/enc_encoding.cc
I found out that `context_map`  is used almost exclusively with `EntropyEncodingData`, that allows to merge them.
In this PR I put `context_map` , `log_alpha_size` , and `ChooseUintConfigs` into `EntropyEncodingData`, rename `Histogram` fields per codestyle guide, remove `HistogramBuilder`, and move all `log_alpha_size`  handling into `EntropyEncodingData::ChooseUintConfigs`.
As a result `BuildAndEncodeHistograms` and `WriteTokens` interfaces and usage cleared a lot.
I'll prepare also another PR with corresponding changes on decoder side.
> Refactor: Interfaces clearing

- tools/hdr/local_tone_map.cc
Two changes to the `local_tone_map` tool:
1. Instead of producing SDR output in Rec2020 with the sRGB tf (which is too wide gamut for 8-bit formats, kind of defeating much the purpose of the tool), make the output DisplayP3 instead.
2. Add an optional argument to dump the HDR image in a format suitable for the libultrahdr example app `ultrahdr_app` (see https://github.com/google/libultrahdr). If a third filename is given on the command line, the input image will be converted to the P3 PQ space and stored as a raw little-endian rgba1010102 file which can be used as input for that tool. An example command line will also be provided, e.g. like this:
```
$ local_tone_map alps-sunset.png out_sdr.png out_hdr.raw
cjpegli out_sdr.png input_sdr.jpg
ultrahdr_app -m 0 -a 5 -t 2 -C 1 -w 840 -h 944 -c …
```
> output in DisplayP3, add option for producing ultrahdr_app input

- .devcontainer/Dockerfile
https://github.com/libjxl/libjxl/pull/4176 added a Dockerfile without the copyright/license blob, which makes bash_test fail.
> add copyright/license to example Dockerfile to stop bash_test from failing

- CHANGELOG.md
- lib/jxl/enc_ans.cc
- lib/jxl/enc_icc_codec.cc
- lib/jxl/jxl_test.cc
Currently only Effort 8 uses LZ77 and Effort 9+ use LZ77-Optimal, causing a large difference between 7 and 8 when `-P 0` is used. This has been present since a regression in v0.11.
This PR enables RLE for Efforts 5-7, with Predictor Zero enabling RLE at Effort 1-4, LZ77 for Effort 5-8 and LZ77-Optimal for Effort 9+. ICC compression is also higher for profiles up to 16KiB in size. This results in roughly a 5% encoding speed penalty but up to **25,000x** smaller filesize, when using a solid color image with `cjxl -d 0 -P 0 -g 3`. [Test Image](https://github.com/user-attachments/assets/95fab318-d072-432d-a6fa-9c4076d06b16)
Main
```
JPEG XL encoder v0.12.0 5e1e5530 [_AVX2_,SSE4,SSE2]
Encoding [Modular, lossless, effort: 7]
Compressed to 12583.2 kB (6.000 bpp).
4096 x 4096,  6.958 MP/s [6.96, …
```
> Allow more use of LZ77

- lib/jxl/enc_modular.cc
- lib/jxl/jxl_test.cc
The parameter `fast_decode_multiplier` for modular tree learning (which penalizes use of the WP property and of non-static properties in MA tree decision nodes) was set to a fixed value of 1.01 regardless of decode speed tier. This PR changes the parameter depending on decode speed tier, making fd0 and fd1 decode a bit slower than before while improving density by 0.5% or so at default effort (on photographic images), and making fd2 decode a bit faster at the cost of 0.3% or so worse density at default effort (on photographic images). On non-photo images the impact is typically smaller. On individual images, your mileage may vary, as usual.
There is no effect on fd3 and fd4, nor on e1-e3, since they don't do any tree learning.
Before: (on the jyrki31 corpus)
```
31 images
Encoding …
```
> lossless: finetune fast_decode_multiplier

- .github/workflows/gitlab_mirror.yml
- .github/workflows/release.yaml
Not sure if these two workflows actually need `contents: write` permissions to do their thing.
If they do, then the permission should be at the lowest level where it is needed, not at the top-level like it is now.
See also: 
https://securityscorecards.dev/viewer/?uri=github.com/libjxl/libjxl
https://github.com/ossf/scorecard/blob/cd152cb6742c5b8f2f3d2b5193b41d9c50905198/docs/checks.md#token-permissions
> try reducing workflow permissions from write to read

- lib/jxl/enc_cache.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_params.h
- lib/jxl/encode.cc
- lib/jxl/jxl_test.cc
Fixes https://github.com/libjxl/libjxl/issues/4234
After all, it was not modular mode + XYB that caused this (as I first thought), but bad API usage that ended up doing VarDCT at d0. The current code would translate that to d0.001, but that distance is too low: the DC quantization factors will be huge and the result is that the DC goes outside the `int16` range, which means it does not conform to Level 5 and we are producing technically invalid bitstreams since we don't set `modular_16bit_buffers` to false as we should.
While we could in principle go to arbitrarily low distances and just go outside Level 5, there is no real practical use for that so for now let's ignore that option.
This sets the minimum distance to 0.05 (instead of 0.001), which should be a safe limit to stay within …
> ensure we stay within Level 5, also avoid "lossy d0"

- lib/jxl/jxl_test.cc
- lib/jxl/modular/encoding/enc_ma.cc
This PR fixes a minor bug in the tree construction where the property index (`prop` in range `[0, num_properties)`) is compared with a property "value" `kNumStaticProperties`. I believe this comparison should be made using `tree_samples.PropertyFromIndex(prop)` instead, which gets the enum value associated with the property index.
This bug only affects a very specific scenario when not both of the static properties are used.  As far as I can tell, this only occurs when there are few groups (see [relevant line](https://github.com/libjxl/libjxl/blob/77cd542df9714955e35e4b1515682da651157cc7/lib/jxl/enc_modular.cc#L553)).
It seems to improve compression slightly in those cases, and I had to update the test values as a result. To further demonstrate this, I've ran the changes on a few of the …
> Fix minor bug in tree construction

- lib/jxl/splines.cc
- lib/jxl/splines_test.cc
- plugins/gimp/file-jxl-load.cc
Test is simplified: jxl crafting is covered by jxl_from_tree now
Drive-by: fix compilation problem in gimp plugin after #4243
> Revert #4242 and extend test to detect the problem

- lib/jxl/decode_test.cc
- lib/jxl/enc_heuristics.cc
slightly less smoothing
Before:
```
104 images
jxl:d0.1        20315 17262519    6.7976800   0.820  10.092   0.26883791  95.73059523  56.48   0.09126293  0.620376202833   6.798      0
jxl:d0.5        20315  7123032    2.8049262   0.993  14.348   0.85243591  91.46139586  46.45   0.34404012  0.965007169526   2.930      0
jxl:d0.8        20315  5392600    2.1235122   0.904  12.586   1.09959988  88.89283658  44.49   0.46026238  0.977372768155   2.466      0
jxl:d1          20315  4622687    1.8203338   0.911  12.955 …
```
> minor quality tweak

- lib/jxl/enc_frame.cc
The check for progressive lossless with faster decoding was incorrectly `> 1` instead of `>= 1` and missing the lossless condition.
Also consolidated both if statements and moved them into the existing block.
> Group size selection cleanup and fix

- lib/extras/dec/jxl.cc
E.g. size == 4, offset = 5 would cause string instantiation with start > end.
Drive-by: pick minimal valid EXIF limit from IsExif (12 bytes instead of 4).
> Fix possible underflow

- lib/jxl/enc_ac_strategy.cc
Building libjxl with clang 18 on illumos was failing due to being unable to resolve the `std::pow` overloading:
```
lib/jxl/enc_ac_strategy.cc:572:22: error: call to 'pow' is ambiguous
572 |       float weight = pow((5.0f - butteraugli_target) / 5.0f, 2.0);
|                      ^~~
/usr/include/iso/math_iso.h:175:15: note: candidate function
175 |         inline float pow(float __X, float __Y) { return __powf(__X, __Y); }
|                      ^
/usr/include/iso/math_iso.h:177:15: note: candidate function
177 |         inline float pow(float __X, int __Y) {
|                      ^
/usr/include/iso/math_iso.h:76:15: note: candidate function
76 | extern double pow(double, double);
|               ^
```
Adding type declarations for the constant arguments addresses this.
Please review the …
> Specify types for arguments to disambiguate calls to pow()

- lib/jxl/encode_test.cc
- tools/streaming_fuzzer.cc
In case of lossless we have to set `uses_original_profile`.
Drive-by: `MODULAR_MA_TREE_LEARNING_PERCENT` was limited (effectively) unconditionally.
> Fix streaming fuzzer encoder API usage.

- tools/cjxl_main.cc
When the `-p` flag is used, this PR allows decoding full-frame images/previews from files as soon as 0.16% loaded instead of 16% (For a 4K image) and loads centre-first by default. This is at the cost of 25% slower encoding and 2% filesize increase on average (efforts 1 and 2 are 20% larger, effort 3 is 5% and 2% for all other effort levels).
Disabling patches improves speeds by up to 50% compared to main for effort 7, but could impact density when lots of matches are found.
This makes files futureproof for decoders and web usage in the future with minimal density impact, while also making sure the progressive flag meets expectations of using the format's capabilities. The encode speed penalty is quite severe, but can be reverted with `--progressive_dc 0` and only applies when progressive …
> Make `-p` more progressive

- lib/jxl/enc_ac_strategy.cc
- lib/jxl/jxl_test.cc
```
104 images
jxl:d0.1        20315 17262466    6.7976592   0.679   8.830   0.26883791  95.73074691  56.48   0.09126293  0.620374290230   6.798      0
jxl:d0.5        20315  7123032    2.8049262   0.801  12.266   0.85243585  91.46070452  46.45   0.34404012  0.965007161729   2.930      0
jxl:d0.8        20315  5403007    2.1276103   0.734  11.521   1.09686460  88.90359100  44.49   0.45983938  0.978358992626   2.468      0
jxl:d1          20315  4635303    1.8253018   0.753  11.671   1.31577511  87.07023293  43.25 …
```
> reduce long-distance color ringing (red-green)

- tools/streaming_fuzzer.cc
(Modular) encoder actively uses 64-bit arithmetics. So, 32-bit build needs some komi.
> Further tune image size for fuzzer.

- lib/jxl/enc_fast_lossless.cc
The image header was always signaling 8-bit alpha even when it was actually a different bit depth. This did not affect libjxl, only the standalone version of fast-lossless.
> fix header in case of alpha with bitdepth > 8

- lib/extras/dec/decode.cc
- lib/extras/dec/decode.h
- lib/extras/dec/jxl.cc
- lib/extras/dec/jxl.h
- lib/extras/enc/apng.cc
- lib/extras/enc/encode.cc
- tools/cjxl_main.cc
- tools/djxl_main.cc
Should fix https://github.com/libjxl/libjxl/issues/4097
~Probably the new `--no_coalescing` option in djxl does not quite do the right thing; it works when outputting to .pam with `--output_frames` but for other output formats it may do bad things still. Anyway,~
default djxl will apply coalescing just like before, so nothing changes there.
When loading a layered jxl in cjxl, it will be loaded without coalescing now, so layers are preserved. This is probably what you want to do, e.g. to convert a lossless layered image to a better-compressed lossless layered image or a slightly-lossy one.
~Also other tools that can take jxl input will now get the layered image, not the coalesced one, which may or may not be a good idea.~
When outputting a layered image to PNG (or PAM) with …
> allow decoding without coalescing, and do that when doing jxl to jxl

- lib/jxl.cmake
See https://github.com/microsoft/vcpkg/pull/46177 for more context, but the vcpkg libjxl port was broken on MSVC due to consumers of the target attempting to link with `m.lib`, as libm is not a thing in MSVCRT. It was asked that my patch to the port also be upstreamed into libjxl itself.
> Remove libm dependency when building with MSVC

- .gitignore
- AUTHORS
- lib/extras/dec/exr.cc
- lib/extras/enc/jxl.cc
Improvements in handling EXR files when reading them in `cjxl`:
- No longer makes color channels always be FP16 (even for EXR files where they were FP32), fixing #465
- Support EXR files where color channel names are not strictly just `R`, `G`, `B` (`A`). Multi-layer files could have names like `Composite.Combined.R` etc. Now finds the first EXR "layer" (channel prefix ending with `.`) that contains channels `R`, `G`, `B` and uses that for color channels. Uses alpha with the same prefix.
- If no "color channels" are found, put first EXR channel as "grayscale", this makes it support luminance-only files like [Garden.exr](https://openexr.com/en/latest/test_images/LuminanceChroma/Garden.html) from EXR test suite.
- Read all other channels as "extra channels" to be encoded.
- Additionally, …
> cjxl: EXR improvements

- tools/streaming_fuzzer.cc
Large number of threads blows RSS (due to ASAN overhead) more than 4x live allocations size
> Limit number of threads in streaming fuzzer

- lib/extras/enc/jxl.cc
PackedExtraChannel name was being ignored when encoding JXL files, now it is set via JxlEncoderSetExtraChannelName. This makes cjxl preserve channel names coming from multi-layer EXR files better.
I noticed this while doing #4312 and a comment there said that fixing this issue separately is the way to go.
> cjxl: set extra channel names

- tools/cjxl_fuzzer.cc
- tools/decode_basic_info_fuzzer.cc
- tools/djxl_fuzzer.cc
- tools/icc_codec_fuzzer.cc
- tools/rans_fuzzer.cc
- tools/set_from_bytes_fuzzer.cc
- tools/streaming_fuzzer.cc
- tools/transforms_fuzzer.cc
Sometimes fuzzer stacktrace says nothing useful when check is triggered.
> Make Check more talkative in fuzzers

- lib/jxl/enc_ans.cc
That restores behaviour before #4340, not sure if it is 100% right, though.
Whats for sure - there are scenarios when ac[0].step_log is used as an index, and garbage is not welcome there.
> Initialize delta_log2/step_log for the first slot

- lib/jxl/encode.cc
Before it was "Codestream level verification for level -1 failed: Too large image dimensions".
-1 means both "auto select" and "maximal level (10) is not enough".
> Fix confusing error message

- .github/workflows/release.yaml
- ci.sh
- debian/control
Since Gimp3 has their own JXL plugin, we could just discontinue shipping ours (for distros that dropped Gimp2).
> Undisable trixie

- third_party/skcms.cmake
Fixes a CMake configuration error in `third_party/skcms.cmake` where malformed expressions caused build failures.
The original code attempted to combine boolean variables using `AND` directly in `set()` commands:
set(_use_avx2 ${CXX_MAVX2_SUPPORTED} AND ${CXX_MF16C_SUPPORTED})
When these variables were undefined/empty, this resulted in malformed if() statements like if(AND AND AND AND), causing
CMake Error at third_party/skcms.cmake:46 (if):
if given arguments:
"AND" "AND" "AND" "AND"
Unknown arguments specified
> fix malformed expressions

- CMakeLists.txt
Without this PR. Android build fails with `unable to find library -lpthread`.
This is because of this cmake statement:
```
set_target_properties(Threads::Threads PROPERTIES
INTERFACE_LINK_LIBRARIES
"-Wl,--whole-archive;-lpthread;-Wl,--no-whole-archive")
```
Android’s libc (bionic) has pthreads built-in. Trying to force `-lpthread` with `--whole-archive` can break build on Android, because there’s no libpthread.a in the NDK (threads are provided by libc).
> Fix "unable to find library -lpthread" error on Android
