libjxl/libjxl

lib/include/jxl/encode.h
lib/jxl/encode.cc
lib/jxl/encode_test.cc
lib/jxl/jpeg/enc_jpeg_data.cc
lib/jxl/jpeg/enc_jpeg_data.h
lib/jxl/roundtrip_test.cc

Made JxlEncoderAddJPEGFrame set basic info and color encoding if necessary.

Made JxlEncoderAddJPEGFrame set options.

---

lib/jxl.cmake

Fixes https://gitlab.com/wg1/jpeg-xl/-/issues/224.

Ensure pkg-config file is installed when -DJPEGXL_STATIC=1

---

tools/djxl_fuzzer.cc
tools/fuzzer_corpus.cc

* generate files with preview images
* toggle "keep orientation" Decoder API switch

Improve fuzzing

---

lib/jxl/dec_group.cc
lib/jxl/progressive_split.h

Ensure that Roundtrip() accounts for pass shift.

---

lib/extras/codec_pnm.cc

Drive-by:
* fix infinite loop (after reading space pos_ wasn't incremented)
* validate last digit in '444' subsampling case

Fuzz: fix read of undefined value

---

lib/extras/codec_jpg.cc

JPEG arithmetic coding could be used for CPU-zip bombing.

Fuzz: set_from_bytes timeout

---

deps.sh

This reverts commit d993cb642931d9d0c675f2820bd9f011d8ac1fbe.

Revert "Update Highway to 0.12.2"

---

lib/jxl/dec_xyb-inl.h

Fix build on aarch64 with GCC.

---

.gitlab-ci.yml

Otherwise JNI test will fail to load the "main".

List artifacts necessary for JNI test

---

lib/jxl/decode.cc

In decode.cc, when parsing a box that is being skipped, "consume" its
bytes, rather than passing them back to the user: it is more efficient
for the user if the decoder indicates more bytes as consumed, and when
skipping a box there's no reason to require keeping them around. This
can increase performance depending on the scenario in which the input is
being passed.

Use up all bytes of box to skip

---

lib/jxl/modular/transform/palette.h

Example results: https://docs.google.com/document/d/1mdvt5Q7987wfFwLypDFx7CslQMWmx7R8ytJKSMKKD80/edit?usp=sharing

Add colors that cover 1% of image to palette.

---

lib/jxl/dec_upsample.cc

Multiplication by 0 does not save from mixing-in undefined values,
because NaN is toxic. Added special "unlikely" case for the tail
of input in case X-repeat is in action (only 2x upsampling, and
vector size >4).

Fix use of undefined value in 2x upsampling.

---

lib/jxl/decode.cc
lib/jxl/decode_test.cc

This optimizes skipping frames in several cases, more cases are still
planned in next MRs based on the frames dependency graph known after
rewind.

Don't decode frame if skipped and not referenced

---

lib/jxl/modular/encoding/encoding.cc

Fixes https://github.com/libjxl/libjxl/issues/140

Fix UB integer overflow in gradient-only fast path.

---

lib/lib.gni
tools/build_cleaner.py

This matches the rest of the arrays in the file which are all relative
to the lib/ directory.

Make new lib.gni headers paths relative to that file

---

lib/jxl/blending.cc
lib/jxl/dec_frame.cc
lib/jxl/frame_header.cc

Verify the size of reference frames when saving them

---

tools/djxl_fuzzer.cc
tools/fuzzer_corpus.cc

Improve djxl_fuzzer

---

lib/extras/codec_pnm.cc
lib/jxl/jxl_test.cc

Adds a test for modular encoding of YCbCr 4:2:0 input.

add test for modular encoding of ycbcr 4:2:0

---

lib/jxl/enc_cluster.cc

Some speedup, especially for small images with faster_decoding=4.
16.63 MP/s -> 17.01 MP/s

Avoid extra computation for empty histograms in clustering.

---

lib/jxl/dec_upsample.cc

It is fine, if groups are processed left-to-right, but in multi-threaded case it is not guaranteed.
Write "tail" pixelwise to avoid touching alien pixels.

Upsampling: fix overwrite at right border

---

lib/jxl/dec_reconstruct.cc

Fixed condition to refrelct the comment.

Fuzz: undefiend values for images with upsampling with <=2 pixels in last group.

---

tools/CMakeLists.txt
tools/jni/org/jpeg/jpegxl/wrapper/Decoder.java
tools/jni/org/jpeg/jpegxl/wrapper/DecoderJni.java
tools/jni/org/jpeg/jpegxl/wrapper/DecoderTest.java
tools/jni/org/jpeg/jpegxl/wrapper/ImageData.java
tools/jni/org/jpeg/jpegxl/wrapper/Status.java
tools/jni/org/jpeg/jpegxl/wrapper/StreamInfo.java
tools/jni/org/jpeg/jpegxl/wrapper/decoder_jni.cc

* add pixel formats without alpha channel
* add "decodeInfo" to recognize the JXL / check existence of alpha channel

Extend JNI wrapper

---

lib/jxl/dec_modular.cc
lib/jxl/dec_modular.h
lib/jxl/modular/transform/rct.h
lib/jxl/modular/transform/transform.cc

Reverts libjxl/libjxl#198.
It seems that pipelines started to fail after this PR (benchmarks fail to decode file).

Revert "push global RCT to groups if possible, parallelize otherwise"

---

lib/jxl/enc_ac_strategy.cc

No quality change, possibly 1 % speedup at default speed, more at higher
speeds if the new ac strategy heuristic was used there.

Minor speedup to ac strategy for special case 8x8

---

lib/extras/codec_gif.cc
lib/extras/codec_jpg.cc
lib/jxl.cmake
lib/jxl/common.h
lib/jxl/dec_cache.h
lib/jxl/dec_frame.cc
lib/jxl/dec_reconstruct.cc
lib/jxl/filters.h
lib/jxl/image.cc
lib/jxl/sanitizers.h
lib/lib.gni
tools/benchmark/benchmark_codec_jpeg.cc
tools/benchmark/benchmark_codec_webp.cc

This will allow using functions without `ifdef` surroundings.

Pull sanitizer-specific code to sanitizers.h

---

lib/jxl/test_utils.h

Make the randomly generated image from GetSomeTestImage more varied:
before, it always had a quarter circle of the same size in the top left
corner, and random noise elsewhere.
Now, it has a circle with random radius at random location, a rectangle
with random noise, and a random colored gradient as background.
I needed this to generate a jxl image with blending that has the
blending visible (multiple circles at random locations overlaid, which
was not possible to see if circle was always the same), but
this is worth committing because it improves the tests in general.

Make GetSomeTestImage more varied

---

lib/jxl/dec_external_image.cc

Intermediate mul value for bpp=24..32 is bigger than expected due to limited float presision.
For bpp=32 it is bigger than MAX_INT. Use direct "cap" values for v >= 1.0

Fix: float-to-int-overflow

---

lib/jxl/dec_reconstruct.cc

Refactor code to extract common part. This allows to deal with MSAN in one place (instead of 6).

OssFuzz: Do not read/use undefined values in UndoXYB

---

lib/jxl/enc_ans.cc
lib/jxl/enc_frame.cc

Fixes -Wunused-but-set-variable in newer compilers.

Remove unused variables.

---

lib/jxl/enc_ac_strategy.cc

Preparation work for ac strategy improvements. This PR attempts to have no functional stages at this time.
This PR prepares the 16X16 ac strategy lookup so that it can soon be used for finding non-2-aligned positions for 16x8, 8x16 and 16x16 transforms within a 64x64 block.
Before and after are the same:
Before:
```
-------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```

Preparations for non-aligned 16x16 comparisons

---

lib/jxl/enc_ac_strategy.cc

Previously only faster_decoding=0 has been using the decision tree
reversal. This commit changes it for all decoding speed tiers.
About 3 % improvement in BPP * pnorm, significant improvement in
reduction on ringing, possibly about 50 %.
Reviewed jxl:d3:faster_decoding=4 very carefully, and results are very
good, especially on anime, graphics and screen captures.
Before:
```
Compr                              Input    Compr            Compr       Compr  Decomp  Butteraugli
Method                            Pixels     Size              BPP   #    MP/s    MP/s     Distance    Error p norm   PSNR   QABPP     DCT2     DCT4   DCT4X8      AFV     DCT8  DCT8X16  DCT8X32    DCT16 DCT16X32    DCT32           BPP*pnorm   Errors
------------------------------------------------------------------------ …
```

Turn on decision tree reversal for faster decoding

---

lib/jxl/enc_ac_strategy.cc

one more step towards removing the original (non-reversed) decision tree
jxl:5, 
12 % improvement on BPP * pnorm, 30 % slower, 
45 % reduction in max butteraugli score
before:
```
Compr              Input    Compr            Compr       Compr  Decomp  Butteraugli
Method            Pixels     Size              BPP   #    MP/s    MP/s     Distance    Error p norm   PSNR   QABPP     DCT2     DCT4   DCT4X8      AFV     DCT8  DCT8X16  DCT8X32    DCT16 DCT16X32    DCT32           BPP*pnorm   Errors
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
jxl:1           17972865  4033242    1.79525835197   1  13.789 …
```

adding speed 5 to tree reversal speed categories

---

tools/jxl_from_tree.cc

Example image (produces the same image as
`third_party/testdata/jxl/splines.png`):
Width 320
Height 320
XYB
Spline
0.03125 0.00625 0.003125 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
1 0.321875 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
1 0.24375 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0.3125 0 0 0.0625 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
9 54
118 159
97 3
10 40
150 25
120 300
EndSpline
- Set 0

Add spline support to `jxl_from_tree`

---

lib/jxl/enc_ac_strategy.cc

simplify EstimateEntropy
same results before and after

remove unnecessary computation

---

lib/jxl/dec_reconstruct.cc

Do not poison-unpoison when there is no alpha-channel

---

lib/jxl/enc_ac_strategy.cc

Removing discontinuous butteraugli-based heuristics from ac strategy
Looks ok in a visual comparison
Before:
```
jxl:d0.8:epf0      17972865  3941131    1.75425832220   1   2.434  14.947   1.57823062   0.52378479117  41.77   2.110 …
```

Removing discontinuous butteraugli-based heuristic

---

lib/jxl/enc_ac_strategy.cc

Before/After the same
Just cleanup

Simplification to FindBest16X16

---

lib/jxl/enc_ac_strategy.cc

Reduces ringing significantly in d16 and worse.
Some reduction in d8.
Finest qualities get changes only in smooth areas that already look
great.
0.13 % improvement on BPP*pnorm
0.58 % on butteraugli distance
0.016 % size reduction
Before:
```
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```

more balanced 16x32, 32x16 and 32x32 decisions

---

doc/building_and_testing.md
doc/building_wasm.md
doc/developing_in_debian.md
doc/developing_in_docker.md
doc/developing_in_windows.md

Paths are relative - files in doc/ directory should not use doc/ path prefix in links.

Fix md-links

---

lib/jxl/dec_external_image.cc

This uses Poison and Unpoison on the last portion of the last vector to
handle the case where we do NearestInt or DemoteTo on uninitialized
memory in dec_external_image.cc.

Use Poison/Unpoison instead of changing code behavior in msan.

---

lib/jxl/dec_reconstruct.cc

When the image right or bottom border is not in the currently processed
group but the required padding around the group would go past the image
border in the next group, we would not mirror the right column/row for
YCbCr upsampling algorithm. This patch fixes the logic when mirroring
the last row / column.

Fix YCbCrUpsampling handling of border.

---

lib/jxl/enc_ac_strategy.cc

Removes code, prepares codebase for 64x64 square splitting.
Before:
```
jxl:d0.8:epf0      17972865  3978806    1.77102804700   1   2.366  14.363   1.57902789   0.52086395504  41.78   2.105 0.000000 0.000911 0.229583 0.021543 0.060425 …
```

Generalising the 16x16 and 32x32 square splitting

---

lib/jxl/modular/transform/squeeze.cc

Previous shortcut logic created uninitialized images even for non-empty channels

Fuzz: use-of-uninitialized in unsqueeze

---

lib/jxl/enc_ac_strategy.cc

clang-tidy was complaining about this.

Remove unused "using" declarations.

---

lib/jxl/enc_ac_strategy.cc

Not better, not much worse, 0.02 % worse BPP * pnorm
Activates the use of large transforms where feasible.
Some nicer geometry interpolation at large distances, but this is more a
theoretical aspect and not relevant with the current test corpus and
smooth settings.
Before:
```
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ …
```

Split 64x64 squares fairly, more large transforms

---

lib/jxl/dec_reconstruct.cc

Set the image initialization expectations after YCbCrUpsampling so we
can catch bugs right after it instead of relying on something else
further down using the uninitialized value.
This changes (x0, x1, y0, y1) so that all the pixels in that range are
defined.

Add Image initialization expectations to YCbCrUpsampling

---

.github/workflows/build_test.yml

Building with gcc-8 from ubuntu-latest in PRs to check compatibility
with GCC.

Build with gcc-8 in release mode in PRs.

---

lib/jxl/dec_reconstruct.cc

`frame_rect` in YCbCrUpsampling is meant to be the input `rect` but in
the frame coordinates. We update the input rect offset and size
when frame_header.upsampling != 1 but didn't update the `frame_rect`
one.

Fix frame_rect parameter size in YCbCrUpsampling.

---

lib/jxl/dec_noise.cc

This gets rid of a significant fraction of noise's cost on the decoder
side. The remaining part is tied to the noise buffers, which are
image-sized but need not be.
~10^-9 variations in output, likely due to different order of
operations.
```
Before:
Compr              Input    Compr            Compr       Compr  Decomp  Butteraugli
Method            Pixels     Size              BPP   #    MP/s    MP/s     Distance    Error p norm           BPP*pnorm   Errors
--------------------------------------------------------------------------------------------------------------------------------
jxl:d0.7        13270449  3376300    2.03537951127   1   5.565  26.594   3.97672892   0.81331137439  1.6553973077103630        0
jxl:d1          13270449  2668722    1.60882092234   1   5.854  29.188 …
```

SIMD-fy noise generation.

---

lib/jxl/dec_noise.cc

Properly unpoison/poison memory in SIMDfied noise decoding.

---

AUTHORS
lib/extras/codec_apng.cc

Fixes #308
Verified working using the provided `crash.png`

Fix handling of APNG with 0 delay_den

---

lib/extras/codec_psd.cc

Fixes loading of PSD files that have multiple layers, spot colors and a merged image without alpha (while the layers do of course have alpha).

fix psd decoder bug

---

CHANGELOG.md

Add these changes to the changelog for version 0.5.x

Add decoder API changes to changelog

---

lib/jxl/dec_modular.cc

Fuzz: Fix ModularImageToDecodedRect crop and add checks

---

tools/cjxl_main.cc

Fixes https://github.com/libjxl/libjxl/issues/354
Also makes cjxl return different exit codes for different error conditions.

cjxl exit codes

---

lib/jxl/dec_frame.cc

Instead of initializing only the padding in X for all the rows in the
extra channels this initializes the whole row for the rows that are
extra padding at the bottom of the channel.
This shouldn't be needed but the extra channels are processed up to the
upsampled padded size.
Using JXL_MEMORY_SANITIZER enables this in the oss-fuzz builds as well.

Initialize all X and Y padding on extra channels in msan and oss-fuzz.

---

lib/jxl/color_encoding_internal.cc

The division through zero was not the division through wy, but a value
that happened to be 0 after the bradford matrix multiplication.
Requiring the values to be in range 0-1, similar to skcms, should fix
this.
Also did this in the similar PrimariesToXYZD50.
Added TODO for also checking the r,g,b primaries like this: the ACES
P0 color space supports out of range values here.

Fix division through zero issue in AdaptToXYZD50

---

CHANGELOG.md

Added changelog entry for butteraugli changes and improved image quality
in the 0.5 release.

Changelog for improved encoding

---

lib/jxl/modular/transform/enc_palette.cc
lib/jxl/modular/transform/enc_palette.h
lib/jxl/modular/transform/enc_transform.cc

Before:
tools/benchmark_xl --input='/jyrki31/*.png' --codec=jxl:m:p0:lp:P0:9 --save_decompressed  --output_dir='output' --error_pnorm=1
benchmark_xl v0.5.0 [AVX2,SSE4,Scalar]
6 cores, 62 tasks, 6 threads, 0 inner threads
```
jxl:m:p0:lp:P0:9      16460  5347412    2.5989598   0.128   8.758   6.10237932   0.53296754  1.385161195009      0
Aggregate:            16460  5347412    2.5989598   0.128   8.758   6.10237932   0.53296754  1.385161195009      0
```
After:
tools/benchmark_xl --input='jyrki31/*.png' --codec=jxl:m:p0:lp:P0:9 --save_decompressed …

Add deltas to palette based on distance and frequency.

---

AUTHORS
debian/control
debian/jxl.install

* add build-depends: asciidoc, xmlto
- needed to build man pages
* add man pages to jxl package
* add libhwy-dev to depends for libjxl-dev
* update homepage to https://github.com/libjxl/libjxl

update debian packaging

---

.github/workflows/build_test.yml

At the moment i686 doesn't pass all the tests due to floating point
precision errors, so the tests are disabled there, but we still check
that it builds.

Cross compile targets for ARM and i686

---

lib/jxl/splines.cc

As discussed in https://github.com/libjxl/libjxl/issues/129

splines: prevent divide by zero in DrawGaussian

---

lib/jxl/dec_patch_dictionary.cc

Fixes #476. Two issues are fixed here:
- reserve() on a vector does not apply the usual doubling trick, making
the loop quadratic
- checking separately for kMaxPatches for the total number of distinct
patches and the number of occurrences of a patch effectively squares
the actual bound on # of patches, bringing it to 1<<48, which is not
OK.

Fix patch decoding fuzzer-found slow behaviour.

---

lib/jxl/color_encoding_internal.cc

Primaries and WhitePoint custom values should only be used when the enum
values are the `*_CUSTOM` ones, otherwise those values can be undefined.
This patch fixes handling those cases and cases where the enum values
are unknown (invalid) to help with forward ABI compatibility if new enum
values are added in the future.

Fix importing external JxlColorEncoding with custom cases.

---

plugins/gimp/file-jxl.cc

plugins/gimp: adjust gimp_register_magic_load_handler magic

---

lib/include/jxl/decode.h

Typos in decode.h

---

lib/include/jxl/encode.h
lib/jxl/encode.cc
lib/jxl/encode_test.cc

Fixes https://github.com/libjxl/libjxl/issues/522

allow effort 1,2 in encode api

---

tools/jxl_from_tree.cc

Adds a way to set the blendmode to kReplace and to use a custom tick duration.

add kReplace and animation FPS setting

---

lib/extras/codec_test.cc
lib/jxl/ans_common_test.cc
lib/jxl/bit_reader_test.cc
lib/jxl/bits_test.cc
lib/jxl/decode_test.cc
lib/jxl/encode_test.cc
lib/jxl/entropy_coder_test.cc
lib/jxl/fields_test.cc
lib/jxl/filters_internal_test.cc
lib/jxl/image_ops_test.cc
lib/jxl/jxl_test.cc
lib/jxl/lehmer_code_test.cc
lib/jxl/modular_test.cc
lib/jxl/optimize_test.cc
lib/jxl/padded_bytes_test.cc
lib/jxl/passes_test.cc
lib/jxl/patch_dictionary_test.cc
lib/jxl/preview_test.cc
lib/jxl/quantizer_test.cc
lib/jxl/toc_test.cc
lib/jxl/xorshift128plus_test.cc
tools/box/box_test.cc

Suddenly discovered that libjxl does not build on my macbook.

Fix signed-unsigned comparison warnings (errors)

---

README.md
doc/developing_in_debian.md
doc/developing_in_docker.md
doc/developing_in_windows_msys.md
doc/developing_with_crossroad.md

* Readme: typo, other minor changes
* Crossroad: change formatting
* Debian: minor wording changes
* Docker: improve clarity
* MSYS2: typo, change formatting

Edit Some Documents

---

plugins/gdk-pixbuf/pixbufloader-jxl.c

Implement animation support in the GDK plugin.

---

README.md
doc/software_support.md

add list of applications that use libjxl

---

third_party/skcms.cmake

Fix MSVC skcms Windows build

---

plugins/gimp/file-jxl-load.cc
plugins/gimp/file-jxl-save.cc

* Reorganize save dialog
* Rename functions, modify messages
* Use JxlEncoderSetBasicInfo
* Use float as intermediary format
* Fix float image alpha channels
* Fix grayscale ICC profile loading
* Fix distance/quality conversion

GIMP Plugin Updates and Fixes

---

lib/jxl/modular_test.cc

Improves test coverage by having a test for some cases that apparently don't occur naturally in other tests:
- an RCT that only does a permute (there's a special code path for that)
- custom (non-default) Weighted Predictor parameters (only used in slower-than-default encode settings)

add a test for permute-only RCT and custom WP

---

lib/jxl/modular_test.cc

There was no test for encode/decode of delta palette yet.

add test for delta-palette

---

lib/jxl/modular/encoding/enc_ma.cc

It gives slightly different results in MSAN.
No significant changes in bitrate or encoding time.

Do not use std::geometric_distribution.

---

lib/jxl/modular/transform/enc_palette.cc

tools/benchmark_xl --input='jyrki31-depth16/*.png' --codec=jxl:m:p0:lp:9 --error_pnorm=1 
benchmark_xl v0.7.0 e0f4c38 [AVX2,SSE4,Scalar]
6 cores, 61 tasks, 6 threads, 0 inner threads
Before:
```
Encoding         kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
---------------------------------------------------------------------------------------------------------------
jxl:m:p0:lp:9      16443  5346967    2.6013328   0.077   8.516   2.28837752   0.53577100  1.393718668969      0
Aggregate:         16443  5346967    2.6013328   0.077   8.516   2.28837752   0.53577100  1.393718668969      0
```
After:
```
Encoding         kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs …
```

Allow delta palette in >8-bit images.

---

lib/jxl/decode_test.cc

Adds a test for the tricky combination of progressive decode, lossy with alpha (so both VarDCT and Modular), with the color image needing 2x upsampling and the alpha needing 4x upsampling.

add test for (progressive) decode of image using upsampling

---

lib/include/jxl/encode.h
lib/jxl/encode.cc

Add several options to the encoder api

---

lib/jxl/enc_bit_writer.h

Fixes a stale comment and removes a function that wasn't used anymore.

some more enc_bit_writer cleanup

---

lib/jxl/modular_test.cc

Adds a test for lossless encoding of custom floats (in this case, 18 bits with 6 exponent bits).

add test for lossless modular handling of custom float data

---

lib/jxl/modular/transform/enc_palette.cc

Parameters optimised via grid search with parameters {0.35, 0.45, ... 0.75}.
BEFORE:
8-bit jyrki31:
```
Encoding         kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
---------------------------------------------------------------------------------------------------------------
jxl:m:p0:lp:9      16443  5383220    2.6189701   0.054   7.259   2.17182755   0.52790631  1.382570824960      0
Aggregate:         16443  5383220    2.6189701   0.054   7.259   2.17182755   0.52790631  1.382570824960      0
```
16-bit jyrki31:
```
Encoding         kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
--------------------------------------------------------------------------------------------------------------- …
```

Add diffusion parameters.

---

lib/jxl/decode.cc

Fixes issue discovered in https://github.com/libjxl/libjxl/pull/651/:
It was saving previous box data to the codestream buffer when a next
partial codestream box is encountered. However, if there were other
unrelated boxes in between, it already updated position pointers and no
longer included the previous box data.
Now it instead saves the codestream data to the internal buffer
immediately if it's a partial codestream, rather than waiting for the
next one. It has to do this anyway to concatenate the separate buffers,
so the memory usage is about the same.
Also removed variable box_begin that was never read from.

Fix issue with partial codestream boxes

---

lib/jxl/dec_group.cc
lib/jxl/dec_reconstruct.cc
lib/jxl/dec_reconstruct.h
lib/jxl/jxl_test.cc

Fixes https://github.com/libjxl/libjxl/issues/673
Also adds a test.

Fix progressive previews with chroma subsampling.

---

CHANGELOG.md

(cherry picked from commit 5a77302bf9aa04913d40303523fc4be20b5023e9)
(cherry picked from PR #686)

Mark release v0.6 in the CHANGELOG (#686)

---

lib/include/jxl/decode.h
lib/jxl/decode.cc
lib/jxl/decode_test.cc

This MR does not yet implement box contents, and no output buffer can be
set yet. However, box type and size can be requested.

Implement JXL_DEC_BOX event and getting box info

---

CHANGELOG.md

(cherry picked from commit 2b5e77c79ba0b5c30681810438f49076d6e500b9)
(cherry picked from PR #801)

Update CHANGELOG.md for v0.6.1 (#801)

---

lib/jxl/decode.cc

Check if the ftyp box is present, at the correct position, and only
once, and the major brand matches "jxl "
This makes the decoder more stringent about this, which aids in
conformance.

Check ftyp validity

---

tools/conformance/djxl_conformance.cc

Builds on https://github.com/libjxl/libjxl/pull/791.
Makes djxl_conformance produce a npy array that contains all extra channels, not just alpha like it is now.

make djxl_conformance return all extra channels

---

lib/jxl/modular/encoding/enc_debug_tree.cc
lib/jxl/modular/encoding/enc_debug_tree.h

These can be used for printing the tree in different ways from other
tools.

Expose PredictorName and PropertyName

---

lib/include/jxl/encode.h

Header only change, implementation to follow.
Pair with Lode.

encoder api: function headers for extra channels

---

SECURITY.md
doc/vuln_playbook.md

Publish the playbook and security policy for handling these bugs.

Update libjxl security policy

---

AUTHORS
tools/check_author.py

In addition to checking if the author of the commit is in AUTHORS we
also check the orderof the individual authors.

check alphabetic order in AUTHORS

---

tools/cjxl_main.cc

See https://github.com/libjxl/libjxl/issues/346
When for whatever reason, the `jbrd` could not be created, instead of silently failing, it will now still encode a jxl file (without `jbrd`) and produce a warning. The exit code returned is different from 0 in this case, so you can tell that something went wrong.

handle case when jbrd fails at encoding

---

lib/jxl/encode_test.cc

This fixes a memory leak by the test

Fix forgetting to destroy the decoder

---

lib/jxl/dec_patch_dictionary.cc

Fixes https://github.com/libjxl/libjxl/issues/877

fix shadow variable in dec_patch_dictionary.cc

---

lib/extras/codec_apng.cc
lib/jxl/enc_noise.cc
tools/jxl_emcc.cc

3 small cleanups as proposed by @maddin200:
fixes https://github.com/libjxl/libjxl/issues/536, https://github.com/libjxl/libjxl/issues/515 and https://github.com/libjxl/libjxl/issues/514

cleanups by maddin200

---

deps.sh

Use more portable to-uppercase in deps.sh

---

CMakeLists.txt
lib/jxl.cmake
third_party/CMakeLists.txt

Allow the use of system-wide lcms2

---

lib/include/jxl/encode.h
lib/jxl/encode.cc
lib/jxl/encode_test.cc

Also renamed the channel palette settings to what I now think are more clear names

Add remaining cjxl options to encoder api

---

.github/workflows/build_test.yml

Unblock commit queue.

---

lib/jxl/encode.cc

fixes https://github.com/libjxl/libjxl/issues/915
Also fixes the case where you set distance to 0.0001 or some other too-small-but-not-zero value.

fix JxlEncoderOptionsSetDistance

---

lib/include/jxl/cms_interface.h
lib/include/jxl/decode.h
lib/jxl/color_management_test.cc
lib/jxl/enc_color_management.cc
lib/jxl/enc_color_management.h
lib/jxl/enc_image_bundle.cc
lib/lib.gni

This will eventually allow other implementations of that interface to be
passed to the C encoding API. The actual plumbing is still to be done.

Refactor enc_color_management as the implementation of a C interface

---

lib/jxl/decode_test.cc
lib/jxl/test_utils.h

In order to use ComparePixels in #845, we move it to test_utils.h

move ComparePixels

---

lib/jxl/dec_modular.cc

Otherwise we might touch channels with not undone transforms.

Do not ignore fatal error on group decoding.

---

CHANGELOG.md
lib/include/jxl/encode.h
lib/jxl/enc_frame.cc
lib/jxl/encode.cc
lib/jxl/encode_internal.h
lib/jxl/encode_test.cc
lib/jxl/image_bundle.h

Writes the frame duration fields and frame name
Blending and cropping fields not yet implemented

Implement frame animation settings in encoder API

---

lib/extras/codec_apng.cc

Should fix at least some of the failing msan tests.

codec_apng: libpng unpoisoning fix and fix possibly not fully initialized color encoding

---

CHANGELOG.md

changelog update for extra channels

---

lib/jxl/encode.cc

Instead of setting the extra channel info via `SetAlphaBits`, we now use
`JxlEncoderSetExtraChannelInfo`.
Co-authored-by: Lode <lode@google.com>

Simplify handling of extra channels info.

---

tools/comparison_viewer/codec_comparison_window.cc
tools/comparison_viewer/codec_comparison_window.h
tools/comparison_viewer/compare_codecs.cc
tools/comparison_viewer/compare_images.cc
tools/comparison_viewer/image_loading.cc
tools/comparison_viewer/image_loading.h
tools/flicker_test/parameters.cc
tools/flicker_test/parameters.h
tools/flicker_test/setup.cc
tools/flicker_test/setup.ui
tools/flicker_test/test_window.cc

If set to the maximum luminance of the display, it allows proper
rendering of HLG images for that peak luminance.

Comparison tool: allow setting the intensity target

---

lib/jxl.cmake
lib/jxl/dec_frame.cc
lib/jxl/render_pipeline/render_pipeline_stage.h
lib/jxl/render_pipeline/render_pipeline_test.cc
lib/jxl/render_pipeline/stage_upsampling.cc
lib/jxl/render_pipeline/stage_upsampling.h
lib/lib.gni

Depends on https://github.com/libjxl/libjxl/pull/982

Upsampling stage

---

lib/jxl/modular/options.h
tools/args.h

allow virtual predictors 14 and 15 in cjxl -P

---

lib/jxl.cmake
lib/jxl/dec_frame.cc
lib/jxl/render_pipeline/render_pipeline_test.cc
lib/jxl/render_pipeline/stage_chroma_upsampling.cc
lib/jxl/render_pipeline/stage_chroma_upsampling.h
lib/lib.gni

Chroma upsampling stage

---

lib/jxl/render_pipeline/stage_upsampling.cc

Unpoison memory outside of image borders for upsampling.

---

lib/extras/codec_apng.cc

Not needed anymore now that we bundle libpng.

Remove Unpoison calls in codec_apng.cc.

---

lib/jxl/dec_frame.cc
lib/jxl/dec_group.cc
lib/jxl/dec_group.h
lib/jxl/dec_modular.cc
lib/jxl/dec_modular.h
lib/jxl/render_pipeline/render_pipeline.cc
lib/jxl/render_pipeline/render_pipeline.h
lib/jxl/render_pipeline/render_pipeline_test.cc

Wire up modular mode for outputting to the render pipeline.

---

lib/extras/codec_apng.cc

Fixes a bug in the new png encode code: when writing exif/xmp metadata, it was passing potentially already-expired string pointers to libpng (since push_back to the textstrings vector can cause a realloc which can cause the string.data() pointer to change, apparently). Doing it this way is safer.

fix png encode msan fail

---

lib/jxl/base/compiler_specific.h
lib/jxl/dec_reconstruct.cc
lib/jxl/dec_xyb.cc
lib/jxl/render_pipeline/stage_xyb.cc

It is likely that performace wins does not pay maintenance cost.

Remove JXL_COMPILER_FENCE

---

lib/jxl/encode.cc
lib/jxl/encode_test.cc

Adds support in the encode API to encode frames with have_crop.

add support for encoding cropped frames

---

tools/djxl_fuzzer.cc

Split from https://github.com/libjxl/libjxl/pull/888
Adds no-coalescing decoding to the fuzzer.

add no-coalescing to djxl_fuzzer

---

lib/jxl.cmake
lib/jxl/common.h
lib/jxl/dec_cache.h
lib/jxl/dec_frame.cc
lib/jxl/dec_noise.h
lib/jxl/render_pipeline/render_pipeline.cc
lib/jxl/render_pipeline/render_pipeline.h
lib/jxl/render_pipeline/render_pipeline_test.cc
lib/jxl/render_pipeline/simple_render_pipeline.cc
lib/jxl/render_pipeline/stage_noise.cc
lib/jxl/render_pipeline/stage_noise.h
lib/lib.gni

This also implements a box-filter stage for the noise generation, and
generating noise group by group at the time in which an AC group is
processed.

Implement a Noise stage.

---

lib/jxl/splines.cc

To avoid OOM/CPU bomb we have to limit intermediate array size as well.

Apply spline limits at intermediate stage.

---

lib/jxl.cmake
lib/jxl/blending.cc
lib/jxl/blending.h
lib/jxl/dec_frame.cc
lib/jxl/dec_patch_dictionary.cc
lib/jxl/dec_patch_dictionary.h
lib/jxl/dec_reconstruct.cc
lib/jxl/render_pipeline/render_pipeline_test.cc
lib/jxl/render_pipeline/stage_patches.cc
lib/jxl/render_pipeline/stage_patches.h
lib/lib.gni

Add a patches stage

---

lib/extras/dec/apng.cc
lib/extras/packed_image.h

Fixes https://github.com/libjxl/libjxl/issues/756.

Support DISPOSE_OP_BACKGROUND in APNG decoder.

---

lib/jxl.cmake
lib/jxl/dec_frame.cc
lib/jxl/image_metadata.cc
lib/jxl/render_pipeline/render_pipeline_test.cc
lib/jxl/render_pipeline/stage_spot.cc
lib/jxl/render_pipeline/stage_spot.h
lib/lib.gni

Also move the check for unknown extra channels to header parsing.

Add a spot color stage.

---

lib/jxl/splines.cc

Deal with division by zero in spline rasterization

---

.github/workflows/release.yaml

https://github.com/eustas/libjxl/runs/4668224839?check_suite_focus=true#logs

Make "Release linux x86_64 static" green

---

lib/extras/dec/apng.cc

Fix APNG decoding.

---

.github/workflows/conformance.yml

Currently level10 is failing:
- `bike` requires 4x error to pass
- `progressive` requires 1.2x error to pass

Add conformance testing to CI 

---

tools/upscaling_coefficients/generate_upscaling_coefficients.py

This is a fix to make it possible again to run
generate_upscaling_coefficients.py.

fix generation of upscaling coefficients

---

tools/djxl_ng_main.cc

Fixing reading the file twice and some little restructuring.

djxl_ng: read file outside

---

lib/jxl/decode_test.cc

After fixing the upsampling, those we can run more tests.

manual merge now the same

---

AUTHORS
doc/software_support.md

noted that "IrfanView Plugins" needs to be installed and enabled by the user

Add "IrfanView" to supported image viewers list

---

experimental/fast_lossless/fast_lossless.cc
experimental/fast_lossless/fast_lossless.h
experimental/fast_lossless/fast_lossless_main.cc

Makes it a bit slower in general, though not measurably in case of photo (which will have a palette collision early).
Significantly better density in case palette can actually be used.

add palette detection to fjxl

---

lib/jxl/enc_ans.cc

Minor impact at default speeds.
Before:
```
jxl:d0.7        13270  3400483    2.0499581   1.702  10.366   1.50473666   0.47348297  0.970620226409      0
jxl:d1          13270  2678703    1.6148379   1.779  10.567   1.68153656   0.60257544  0.973061663050      0
jxl:d2          13270  1683778    1.0150541   1.866  10.369   3.00312042   0.95243347  0.966771527011      0
jxl:d4          13270  1004942    0.6058225   1.734   7.013   4.85261440   1.50554379  0.912092235041      0
jxl:d6          13270   718857    0.4333581   1.658   7.644   7.34840679   1.97809701  0.857224277568 …
```

Fix ANS code generation at faster speeds.

---

lib/include/jxl/encode.h

This should fix failing doxygen.

no doc for empty return type

---

.github/workflows/build_test.yml
lib/jxl/encode_test.cc
lib/jxl/jxl_test.cc
lib/jxl/render_pipeline/render_pipeline_test.cc

Also fixes the tests with that flag enabled.

Test -DJXL_HIGH_PRECISION=0 in the CI

---

.github/workflows/build_test.yml
lib/jxl/dec_frame.cc
lib/jxl/dec_reconstruct.cc
lib/jxl/dec_xyb-inl.h
lib/jxl/dec_xyb.cc
lib/jxl/dec_xyb.h
lib/jxl/decode_test.cc
lib/jxl/encode_test.cc
lib/jxl/fast_math_test.cc
lib/jxl/jxl_test.cc
lib/jxl/render_pipeline/render_pipeline_test.cc
lib/jxl/render_pipeline/stage_xyb.cc
lib/jxl/render_pipeline/stage_xyb.h

Add a fast-XYB-to-sRGB8 stage.

---

lib/jxl.cmake
lib/jxl/dec_frame.cc
lib/jxl/dec_frame.h
lib/jxl/render_pipeline/render_pipeline.h
lib/jxl/render_pipeline/render_pipeline_stage.h
lib/jxl/render_pipeline/stage_blending.cc
lib/jxl/render_pipeline/stage_blending.h
lib/lib.gni

The stage only handles the part of the image corresponding to the current crop, and therefore the pipeline does not yet work for animations where not all frames have the same size.

Pipeline stage for blending

---

lib/jxl/dec_ans.h
lib/jxl/modular/encoding/encoding.cc

Special modular decode case for RLE-only huffman decoding with gradient predictor (i.e. what fjxl currently produces).
before:
1200 x 1400, geomean: 22.59 MP/s [14.46, 25.23], 100 reps, 0 threads.
after:
1200 x 1400, geomean: 34.35 MP/s [19.44, 37.91], 100 reps, 0 threads.
There's still a lot of room for further speed improvements by specializing for 16-bit modular buffers, avoiding copying (should be better with render-pipeline), SIMD'ing YCoCg, and avoiding conversion to float.

make decoding of fjxl-produced images a bit faster

---

lib/jxl/modular/encoding/encoding.cc

Since transforms list is incomplete - drop transforms list and pretend there are none.

ZF channels if group header is incomplete.

---

tools/djxl_ng_main.cc

We add a function fo decode compressed jxl data to a PackeDPixelFile.

decode to PackedPixelFile

---

lib/jxl/modular/transform/transform.cc

Follow-up on https://github.com/libjxl/libjxl/pull/1060#issuecomment-1012080914

Disallow palette for bit_depth > 24

---

lib/extras/codec.cc
lib/extras/enc/pnm.cc
lib/extras/enc/pnm.h

This prepares everything for djxl_ng to use the pnm encoder.

change pnm encoder to use ppf

---

.github/workflows/build_test.yml
lib/extras/dec/pgx.cc
lib/jxl/base/data_parallel.h
lib/jxl/enc_color_management.cc

clang-format --style=file -i lib/**/*.{h,cc}

---

lib/jxl/modular/transform/rct.cc

Small speedup for decoding e.g. jxl files produced with fjxl or cjxl -m -e 1-3.

SIMDify inverse YCoCg

---

tools/djxl_ng_main.cc

Fixes https://github.com/libjxl/libjxl/issues/1187

remove duplicate else if

---

lib/extras/dec/jpg.cc
lib/extras/dec/pnm.cc

Deal with unteminated c-strings in JXL messages

---

lib/jxl/base/span.h
lib/jxl/enc_bit_writer.cc
lib/jxl/enc_frame.cc
lib/jxl/encode_test.cc
tools/cjxl_ng_main.cc

RegExp: "(->|\.)size\(\) (!= 0|== 0|> 0)"

Fix remaining "used size instead of empty"

---

lib/jxl/encode.cc
lib/jxl/encode_internal.h

preparation for being able to index frame starts

access to byte position in a stream

---

lib/jxl/dec_modular.cc
lib/jxl/enc_modular.cc
lib/jxl/modular_test.cc

This makes the conversion from float to int or back use double precision multiplication when the bitdepth is 23 or more. Otherwise things don't roundtrip losslessly. When the bitdepth is at most 22, the SIMD conversion can still be used, so this is only slowing things down when the bitdepth is > 22.
For integer bitdepths of 25 and more, we can't roundtrip losslessly anyway because single-precision floats only have 24 mantissa bits, but we can roundtrip integer values representable in floats losslessly, up to 30-bit (or 29-bit when Squeeze is used).
Adds a test to see if an image (with artificial noise added in the lsb) roundtrips losslessly at bitdepths 1 to 30 without squeeze and 1 to 29 with squeeze.

fix accuracy of float2int / int2float and add test

---

lib/jxl/jpeg/enc_jpeg_data_reader.cc

Thanks to Jon Sneyers for clarification:
https://github.com/libjxl/libjxl/issues/1088#issuecomment-1073577246

Clarify requirement for 8bits precision.

---

lib/jxl/modular/transform/squeeze.cc

MSVC failed to digest #ifdef inside macro expansion.

Flatten unsqueeze code.

---

lib/jxl/common.h
lib/jxl/enc_icc_codec.cc
lib/jxl/icc_codec.cc

frame index box will also benefit from varint coding

Making varint coding accessible outside of ICC

---

lib/extras/dec/pgx.cc

Remove strict requirement for 16bits since we support 24bits losslessly

---

lib/jxl/dec_cache.cc
lib/jxl/render_pipeline/stage_write.cc
lib/jxl/render_pipeline/stage_write.h

"extra" should be the number of pixels to group boundary, not image edge.

Fix aarc64 write stage.

---

lib/jxl/aux_out.h
lib/jxl/dec_ans.cc

Small fix in a debug function that probably doesn't really get used (but I was using it in some WIP stuff).
Also remove a redundant test in dec_ans.cc (a uint8 plus 1 will never be zero).

minor cleanup/fix

---

tools/jxlinfo.c

Currently, `jxlinfo` produces rather verbose output that is somewhat hard to understand for anyone not very familiar with libjxl.
This makes the output a lot more compact and nicer to read for humans. "Unsurprising" information like e.g. intrinsic dimensions that are equal to the image dimensions is dropped, leaving only the info that is actually interesting to see.
Layers are now also shown (not just animation frames), including crop dimensions/offsets.
Some example outputs:
Before:
```
dimensions: 960x860
have_container: 0
uses_original_profile: 0
bits_per_sample: 8
have_preview: 0
have_animation: 0
intrinsic xsize: 960
intrinsic ysize: 860
orientation: 1 (Normal)
num_color_channels: 3
num_extra_channels: 1
extra channel 0:
type: Alpha
bits_per_sample: 8
alpha_premultiplied: 0 …
```

make jxlinfo output nicer for humans

---

lib/jxl/image.cc
lib/jxl/image_ops.h

These functions aren't used (anymore) by anything, so not much point in keeping them around.

remove some unused image_ops functions

---

lib/extras/dec/apng.cc

Previous assert was wrong: `sscanf(x, "%8lu", y);`
does not actually check that input is 8-digits long

APNG: consume only as much input as used when parsing deccimal

---

lib/jxl/encode.cc

Fixes https://github.com/libjxl/libjxl/issues/949.
Currently, AddJPEGFrame in the encode api silently strips Exif/XMP/JUMBF blobs that may exist in the JPEG bitstream. That causes JPEG reconstruction to fail, and is also just a bad thing to do even if JPEG reconstruction is not desired.
This PR makes it instead always preserve such metadata. It currently stores the metadata using `brob`, which seems to work fine with the decode api (e.g. `djxl_ng`), though it doesn't work when decoding with `djxl` (which has its own partial implementation of the container format, which does not include handling `brob`). It's probably not worth it to fix `djxl` at this point.
We could later add an option to strip the data instead (only useful when `jbrd` is stripped too), and/or to store it uncompressed.

jpeg recompression: preserve exif/xmp/jumbf

---

tools/box/box.cc

This prevents crashing for certain jxl files and thereby fixes https://github.com/libjxl/libjxl/issues/1396.

checking if xml empty

---

lib/include/jxl/decode.h
lib/include/jxl/types.h
lib/jxl/dec_frame.cc
lib/jxl/dec_frame.h
lib/jxl/decode.cc
lib/jxl/decode_test.cc

closes https://github.com/libjxl/libjxl/issues/1353
Co-authored-by: Luca Versari <veluca@google.com>

implement JxlDecoderSetProgressiveDetail

---

lib/jxl.cmake
lib/jxl/libjxl.pc.in
lib/jxl_threads.cmake
lib/threads/libjxl_threads.pc.in

This fixes https://github.com/libjxl/libjxl/issues/1400.

Allow adding prefix for pkg-config

---

.gitmodules
CMakeLists.txt
ci.sh
debian/copyright
plugins/gdk-pixbuf/CMakeLists.txt
tools/conformance/tooling_test.sh
tools/reference_zip.sh

testdata is not completely "third_party"

Move third_party/testdata to testdata/

---

lib/jxl/enc_adaptive_quantization.cc
lib/jxl/jxl_test.cc

Fix tile distmap size calculation in slow mode.

---

ci.sh

This makes it easier to iterate on a single or small group of tests
by running ci.sh in the following way.
TEST_SELECTOR="-R .*Resample.*" ./ci.sh

Add a test selector variable to ci.sh

---

lib/jxl/enc_cache.cc
lib/jxl/jxl_test.cc

This fixes the crash in #1448.

Fix level 2 progressive dc decoding inside encoder.

---

ci.sh

This was caused by the (fairly recent) change https://github.com/llvm/llvm-project/issues/53220

fix linting

---

debian/copyright
lib/extras/codec_test.cc
lib/jxl/jxl_test.cc
lib/jxl/modular_test.cc
lib/jxl/passes_test.cc
lib/jxl/preview_test.cc
lib/jxl/speed_tier_test.cc

Drive-by: fix wesaturate path in debian copyright

Move testdata/t_p to testdata/external

---

lib/jxl/decode.cc
lib/jxl/decode_test.cc

This fixes two cases in Issue #1079, the raw codestream case and the
unbounded jxlc/jxlp box at the end of the input case.

Stop consuming input in the decoder after codestream is finished.

---

lib/jxl/decode.cc
lib/jxl/decode_test.cc

Support image-out callback in JxlDecoderFlushImage().

---

lib/jxl/decode.cc
lib/jxl/decode_test.cc

If all the subscribed events are handled while processing a boxed
stream, we stop at the end of the last seen box.
If we detect a native codestream signature, or a jxl signature box,
we stop processing the current stream and release the rest of the
input.

Support concatenated native or boxed jxl streams in the decoder.

---

lib/jxl/decode.cc
lib/jxl/decode_test.cc

This enables a client to parse the boxed stream box by box, and can
stop at any JXL_DEC_BOX event, so that the input is consumed until
the end of the last box.
This fixes #1079, together with PR #1462.

Defer consuming box header until after DEC_BOX event was signaled.

---

lib/jxl/dec_frame.cc
lib/jxl/dec_frame.h
lib/jxl/decode.cc
lib/jxl/decode_test.cc

Define a progression detail level for each new frame right after
we decode the frame header and save the state of what progression
levels were already signaled in the internal JxlDecoderStruct.
Added byte-by-byte progression to the ProgressiveEventTest.

Fix progressive decoding for streaming input.

---

lib/CMakeLists.txt

only build extras when tools enabled

---

lib/jxl/decode.cc
tools/box/box.cc

correct extended box size handling

---

tools/CMakeLists.txt
tools/djxl_ng_main.cc
tools/roundtrip_test.sh

This change also wires up the --jpeg_quality and --use_sjpeg flags
and fixes --num_reps > 1 mode.
Added an end-to-end test for djxl_ng.

Implement --pixels_to_jpeg mode in djxl_ng.

---

lib/jxl/decode_test.cc

closes https://github.com/libjxl/libjxl/issues/1478

test for extended box size

---

lib/jxl/opsin_image_test.cc

leftover from https://github.com/libjxl/libjxl/pull/1500

removing empty test

---

tools/djxl_main.cc

This fixes the case where jpeg reconstruction box comes after basic info.

Fix jpeg reconstruction bug in djxl.

---

lib/extras/packed_image_convert.cc

was noticed in https://github.com/libjxl/libjxl/issues/492

newline in warning

---

lib/include/jxl/decode.h

Added documentation to each informative event as to where the
input processing stops and how many unprocessed bytes are
returned by JxlDecoderReleaseInput.

Document the new behaviour of JxlDecoderReleaseInput.

---

CMakeLists.txt

See: https://github.com/libjxl/libjxl/pull/1566#issuecomment-1172899590.

Lower the minimum required Clang version to 5

---

lib/include/jxl/decode.h

document rewind

---

.github/workflows/build_test.yml
CMakeLists.txt
deps.sh
tools/CMakeLists.txt

Update HWY to ToT
Disable SVE and RVV HWY targets
Also re-enable AVX targets and CLink tests

Add clang32/64 MSYS environments

---

CHANGELOG.md
lib/include/jxl/cms_interface.h
lib/include/jxl/codestream_header.h
lib/include/jxl/color_encoding.h
lib/include/jxl/decode.h
lib/include/jxl/encode.h

Drive-by: cleanup include/jxl includes

Fix changelog: new release, missing items, typos, formatting

---

tools/cjxl_main.cc

cjxl: spelling modular_lossy_palette

---

deps.sh

(likely fixes flaky scalar tests)

Update HWY to 1.0+

---

.github/workflows/build_test.yml
.github/workflows/conformance.yml
.github/workflows/release.yaml

Cache conformance ref objects

---

tools/cjxl_main.cc

Use modular lossless mode in cjxl when distance is implicit 0.

---

lib/jxl/dec_patch_dictionary.cc

Fix test failures when glibc assertions are enabled.

---

lib/extras/dec/apng.cc
lib/jxl/frame_header.cc
lib/jxl/frame_header.h

Fix frame infos of decoded apngs that have cropped frames.

---

lib/include/jxl/decode.h
lib/include/jxl/encode.h
lib/include/jxl/types.h

Fix placement of JXL_DEPRECATED macros.

---

third_party/CMakeLists.txt

Override brotli "no-install" policy.

---

tools/cjxl_main.cc

Fixes #1177
Drive-by: simplify --qprogressive_ac and --responsive flag handling.

Disable lossy palette in cjxl if progressive encoding is requested.

---

third_party/CMakeLists.txt

Do not exclude brotli from "all"

---

AUTHORS
CHANGELOG.md
deps.sh
lib/include/jxl/decode.h
lib/jxl.cmake
lib/jxl/version.h.in

export version information in headers (#834) 
update highway to version 1.0.1 (#1718)

Cherry picking v0.7.x

---

lib/jxl/color_management.cc

The profile is now 628 bytes instead of 920.

More compact XYB ICC profile

---

lib/extras/enc/jxl.cc
lib/extras/enc/jxl.h
lib/jxl/jxl_test.cc
lib/jxl/test_image.h
lib/jxl/test_utils.h

Start replacing CodecInOut based roundtrip tests in jxl_test.cc

Add a ppf based roundtrip test framework.

---

lib/extras/dec_group_jpeg.cc
lib/extras/dec_group_jpeg.h
lib/extras/decode_jpeg.cc
lib/jxl_extras.cmake
lib/lib.gni

Benchmark before (multithreaded):
```
Encoding           kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
-----------------------------------------------------------------------------------------------------------------
jpeg:q95             13270  7112433    4.2876819  17.743  47.052   1.72006321   0.48375988  2.074208483263      0
jpeg:q95:djxl8       13270  7112433    4.2876819  17.407  16.676   1.63743067   0.44661786  1.914955293952      0
jpeg:q95:djxl16      13270  7112433    4.2876819  17.885  15.183   1.61143291   0.43850905  1.880187337450      0
```
Benchmark after (multithreaded):
```
Encoding           kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs …
```

Simplify jpeg decoding and make it faster.

---

tools/cjxl_main.cc
tools/djxl_main.cc

cjxl/djxl: handle empty file out

---

plugins/gimp/file-jxl-save.cc
tools/benchmark/benchmark_stats.cc

two code analysis findings

---

AUTHORS
third_party/CMakeLists.txt

Set install_name properly when building brotli on macOS

---

lib/jxl/enc_cluster.h

fix uninitialized value in Histogram

---

ci.sh

changing three dots to two dots.

fix authors check

---

CMakeLists.txt

run a2x.exe directly on MinGW

---

lib/extras/decode_jpeg.cc

```
Encoding                 kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
-----------------------------------------------------------------------------------------------------------------------
jpeg:q90:djxl8             13270  4838710    2.9169834  54.059  96.219   2.15660810   0.61860242  1.804453005551      0
jpeg:q90:yuv420:djxl8      13270  3660915    2.2069577  81.060 132.376   6.06170416   0.91525017  2.019918444586      0
jpeg:libjxl:djxl8          13270  3197015    1.9272988  15.375  69.584   2.23333597   0.70076511  1.350583733701      0
```
```
Encoding                 kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs …
```

Compute dequant biases in a streaming manner.

---

lib/jxl/encode.cc

uses_original_profile typo

---

lib/extras/dec/jxl.cc
tools/roundtrip_test.sh

Choose output pixel format based on selected bit depth in djxl.

---

lib/jxl/jpeg/dec_jpeg_data_writer.cc
lib/jxl/jpeg/jpeg_data.cc

Fix JPEG reconstruction error.

---

lib/extras/dec_group_jpeg.cc
lib/extras/dec_group_jpeg.h

Add specialized 8x8 IDCT and transpose from jpeg xl.

Make jpeg decoder more self-contained.

---

AUTHORS
plugins/gimp/file-jxl-load.cc

plugins/gimp: Support for decoding animations

---

tools/ssimulacra2.cc

This makes two changes to the SSIMULACRA 2 algorithm:
- Downscaling (for the 1:2, 1:4 etc scales) is done in linear RGB. This is perceptually more correct, and allows the metric to notice any artifacts caused by codecs typically working in a gamma-compressed domain, causing e.g. the DC values to not actually correspond exactly to the correct color for a 1:8 image.
- The SSIM formula was fixed. There was a conceptual error in the original SSIM formula: it is effectively applying gamma correction twice: once by working in a gamma-compressed domain (with e.g. the sRGB transfer curve in typical SSIM implementations, or the XYB transfer curve in case of SSIMULACRA 2), and then again by having a division by mean luma which effectively penalizes errors in the darks more than in the brights, …

Ssimulacra2: linear downscaling and fixed SSIM

---

plugins/gimp/file-jxl-load.cc

```bash
$ cjxl --lossless_jpeg=0 -d 0.1 -p /tmp/FullMoon2010.jpg /tmp/FullMoon2010.jxl
```
```
JPEG XL encoder v0.8.0 3a4fd8a0 [AVX2,SSE4,SSSE3,Unknown]
Read 2580x2452 image, 6424806 bytes, 180.1 MP/s
Encoding [Container | VarDCT, d0.100, effort: 7 | 9298-byte Exif | 9066-byte XMP], 
Compressed to 2638053 bytes including container (3.336 bpp).
2580 x 2452, 5.84 MP/s [5.84, 5.84], 1 reps, 20 threads.
```
```bash
$ cp /tmp/FullMoon2010.jxl moon.jxl
$ truncate -s 500k moon.jxl
$ gimp -a !$
```
```bash
$ zip -Z store /tmp/Moons.jxl.zip /tmp/FullMoon2010.jxl /tmp/moon.jxl /tmp/FullMoon2010.jpg
```
[Moons.jxl.zip](https://github.com/libjxl/libjxl/files/9944572/Moons.jxl.zip)
- Closes #1845.
- Closes #638.

plugins/gimp: Fix progressive decoding (closes libjxl#1845 and libjxl#638)

---

plugins/gimp/file-jxl-save.cc

Goal: fix gcc-10 warning SetQuality is unused.

Use Set(Quality|Distance) where appropriate

---

doc/software_support.md

mention Pale Moon support

---

experimental/fast_lossless/build-android.sh
experimental/fast_lossless/cross_compile_aarch64.sh
experimental/fast_lossless/fast_lossless.cc

Also enable SIMD in build scripts.

Fix NEON SIMD implementation of fast_lossless

---

experimental/fast_lossless/fast_lossless.cc
experimental/fast_lossless/pam-input.h

>8 bit paths are not SIMDfied yet.

Refactor fast_lossless to support 16-bit data.

---

lib/extras/packed_image_convert.cc
lib/jxl/dec_external_image_gbench.cc
lib/jxl/decode_test.cc
lib/jxl/enc_external_image.cc
lib/jxl/enc_external_image.h
lib/jxl/enc_external_image_gbench.cc
lib/jxl/enc_external_image_test.cc
lib/jxl/enc_frame.cc
lib/jxl/encode.cc
lib/jxl/image_bundle.cc
lib/jxl/image_bundle.h
lib/jxl/roundtrip_test.cc
lib/jxl/test_utils.h
tools/benchmark/benchmark_codec_avif.cc
tools/benchmark/benchmark_codec_webp.cc
tools/fuzzer_corpus.cc
tools/jxl_from_tree.cc

premultiply alpha in BufferToImageBundle

---

lib/jxl/dec_noise.cc

don't generate unused noise

---

.github/workflows/conformance.yml
tools/conformance/conformance.py

Also update the conformance test set commit to make the tests pass.

Add an --update_on_failure flag to the conformance test runner.

---

experimental/fast_lossless/fast_lossless.cc

Tested on random noise & synthetic images at various bitdepths.
Benchmark on a A51, approximately a 10% speedup on a single core:
```
Before:
./fast_lossless artificial8.ppm x.jxl 2 100
63.178 MP/s
2.755 bits/pixel
./fast_lossless artificial13.ppm x.jxl 2 100
32.670 MP/s
6.994 bits/pixel
./fast_lossless artificial14.ppm x.jxl 2 100
32.285 MP/s
7.956 bits/pixel
./fast_lossless artificial16.ppm x.jxl 2 100
27.592 MP/s
10.411 bits/pixel
./fast_lossless bb8.ppm x.jxl 2 20
37.628 MP/s
11.895 bits/pixel
./fast_lossless bb13.ppm x.jxl 2 20
21.407 MP/s
26.594 bits/pixel
./fast_lossless bb14.ppm x.jxl 2 20
20.894 MP/s
29.654 bits/pixel
./fast_lossless bb16.ppm x.jxl 2 20
18.621 MP/s
35.989 bits/pixel
After:
./fast_lossless artificial8.ppm x.jxl 2 100
63.353 MP/s
2.755 bits/pixel
./fast_lossless …
```

SIMDfy >8-bit fjxl on ARM NEON.

---

tools/wasm_demo/index.html
tools/wasm_demo/no_png.cc
tools/wasm_demo/service_worker.js

Try to employ WASM compiled code caching; it works sometimes.

Do not calculate Adler32 (->faster)

---

experimental/fast_lossless/build-android.sh
experimental/fast_lossless/build.sh
experimental/fast_lossless/cross_compile_aarch64.sh
experimental/fast_lossless/fast_lossless_main.cc
lib/jxl/enc_fast_lossless.cc
lib/jxl/enc_fast_lossless.h

[fast-lossless] Do not require OpenMP for parallelism

---

lib/jpegli/render.cc

Benchmark before (using jpegli libjpeg.so):
```
Encoding                        kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
------------------------------------------------------------------------------------------------------------------------------
jpeg:cjpeg-static:q90             13270  4838710    2.9169834  20.116  84.572   2.17603207   0.62092407  1.811225220820      0
jpeg:cjpeg-static:yuv420:q90      13270  3660915    2.2069577  31.641 115.793   6.05725956   0.91959288  2.029502606507      0
jpeg:libjxl:d1.0                  13270  2999278    1.8080944  11.373  42.786   2.04391766   0.71183783  1.287069964681      0
```
```
Encoding                        kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm …
```

jpegli: fix bug in block statistics computation

---

lib/jxl/enc_fast_lossless.cc
lib/jxl/enc_fast_lossless.h

May also have caused a slight speedup.

[fast-lossless] Allow more advanced usage of the API.

---

tools/cjxl_main.cc

Currently, `cjxl input.jpg output.jxl` does lossless recompression, which is good. However, `cjxl input.jpg -d 10 output.jxl` also does lossless recompression, which is not expected/intuitive. This makes it only do lossless recompression by default or when specifying `-d 0` / `-q 100`; when any other distance/quality is specified, it does an implicit `--lossless_jpeg=0`. This was also the behavior previously in cjxl 0.6 back when it wasn't using the API yet.

make cjxl input.jpg -d 3 do lossy recompression

---

lib/extras/dec/jxl.cc
tools/djxl_main.cc

fix behavior for `--allow_partial_files`

---

lib/jxl/enc_frame.cc

don't allow chroma subsampling when YCbCr

---

lib/jxl/enc_fast_lossless.cc

At the cost of a slight slowdown (1-5%), this change:
- improves compression on RLE-heavy images (~2% in some cases; ~0.5% on the QOI test corpus)
- narrows the gap between wide-SIMD and narrow-SIMD (gap between AVX2 and AVX512 is ~5% in RLE-heavy images; before this change, it was ~10%)
- avoids the hack that was used to pad the image to a multiple of 16 in the frame header, unblocking the use of fast-lossless for animation.
```
Before:
build/fast_lossless /tmp/noise-4.ppm
242.731 MP/s
14.668 bits/pixel
build/fast_lossless /tmp/noise-6.ppm
235.825 MP/s
20.813 bits/pixel
build/fast_lossless /tmp/noise-8.ppm
231.766 MP/s
26.878 bits/pixel
build/fast_lossless /tmp/noise-10.ppm
167.014 MP/s
32.878 bits/pixel
build/fast_lossless /tmp/noise-11.ppm
161.748 MP/s
35.897 bits/pixel …
```

[fast-lossless] More flexible RLE; allow non-16-multiple frame width

---

lib/jxl/jxl_test.cc

remove TODO about SCALAR

---

lib/jxl/enc_fast_lossless.cc

clang-15 complains about kLanes not being defined.

Fix compilation for some compiler versions.

---

tools/cjxl_main.cc
tools/djxl_main.cc

harmonize `--num_threads` bewteen cjxl and djxl

---

tools/CMakeLists.txt

(cherry picked from commit 3b026cebd995c9e98b68fc295cac83613924eb38)
PR #2075

Fix MSYS2 build

---

lib/jxl/enc_frame.cc
lib/jxl/enc_params.h

fix non-lossless e10

---

lib/jpegli/encode.cc

With this change we can remove the dependence of the core jpegli library on the color management system.

jpegli encoder: lookup transfer function directly from CICP tag

---

lib/jpegli/color_transform.cc
lib/jpegli/color_transform.h
lib/jpegli/decode_api_test.cc
lib/jpegli/render.cc

- Added codepaths for 4 channels.
- Added YCCK to CMYK conversion support.

Added CMYK support.

---

lib/jxl/enc_fast_lossless.cc

fixes #2118
Co-authored-by: Luca Versari <veluca@google.com>

fix palette bug

---

lib/jpegli/encode.cc
lib/jpegli/encode.h
lib/jpegli/encode_api_test.cc
lib/jpegli/encode_internal.h
lib/jpegli/libjpeg_wrapper.cc

jpegli encoder: implement jpeg_write_marker API function

---

tools/CMakeLists.txt

not always build all fuzzer targets

---

doc/encode_effort.md

fixes https://github.com/libjxl/libjxl/issues/2196

Explain e10

---

lib/jpegli/encode.cc

File header is written in jpegli_start_compress() or jpegli_write_coefficients() while app markers are written in the methods where they are passed.

jpegli: write file header and app markers earlier

---

lib/jxl.cmake

remove libbrotlicommon from library requirements

---

lib/jpegli/bitstream.cc

Compute the number of nonzeros in the block first using SIMD, and then stop processing the block when we found all non-zeros.
```
jpeg:enc-jpegli:p0:q90           13270  3679250    2.2180109  43.503 201.934   2.26414490  86.30579721   0.68598112  1.521513573278      0
jpeg:enc-jpegli:p0:noaq:q90      13270  4054221    2.4440596  65.763 181.881   2.29879761  88.59588680   0.67347566  1.646014648716      0
jpeg:q90                         13270  4838710    2.9169834  66.564 167.835   2.40070152 …
```

Faster tokenization loop.

---

lib/jpegli/encode.cc

```
jpeg:enc-jpegli:p0:q90           13270  3679204    2.2179831  53.379 194.319   2.26414490  86.30231498   0.68598247  1.521497538051      0
jpeg:enc-jpegli:p0:noaq:q90      13270  4054257    2.4440813  75.418 176.274   2.29879761  88.59713846   0.67347830  1.646035711071      0
jpeg:q90                         13270  4838710    2.9169834  65.312 168.639   2.40070152  91.22219875   0.68663652  2.002907346332      0
Aggregate:                       13270  4163561    2.5099743  64.064 179.427 …
```

Faster input de-interleaving for RGB 8 bit input.

---

lib/jxl/enc_fast_lossless.cc

Channel ID was miscalculated.
Fixes #2281

Fix palette images larger than one group in -e 1.

---

tools/cjxl_main.cc

fixes https://github.com/libjxl/libjxl/issues/2304

simplify foo && foo to foo

---

examples/decode_progressive.cc
examples/encode_oneshot.cc
tools/file_io.cc

more fclose

---

.github/workflows/pull_request.yml
WORKSPACE
ci.sh
lib/jxl_vars.bzl

Drive-by: use newer clang-format in CI

Add bazel files linter

---

lib/jpegli/decode_marker.cc
lib/jpegli/decode_scan.cc
lib/jpegli/render.cc
lib/jpegli/test_utils.cc

Use the same {width,height}_in_block definition as in libjpeg.

---

lib/jpegli/decode.cc
lib/jpegli/decode_api_test.cc
lib/jpegli/decode_internal.h
lib/jpegli/decode_marker.cc
lib/jpegli/decode_marker.h
lib/jpegli/input_suspension_test.cc

Support custom marker parsers for suspending source managers.

Fix source manager input position for custom marker readers.

---

lib/jpegli/decode_api_test.cc
lib/jpegli/destination_manager.cc
lib/jpegli/encode_api_test.cc
lib/jpegli/test_utils.cc
lib/jpegli/test_utils.h

Fix initialization function of stdio destination manager.

Test reading from/writing to concatenated files/memory buffers.

---

.github/workflows/build_test.yml
debian/rules

the os is not supported anymore by github

remove ubuntu 18.04 build/test workflow

---

lib/jxl/splines.cc

fix ceil in spline calculation

---

lib/jxl/splines.cc
lib/jxl/splines.h
lib/jxl/splines_test.cc

Trying out if this fixes the the problem with clusterfuzz-testcase-minimized-djxl_fuzzer-6735607318052864

trigger spline limits earlier

---

lib/jpegli/decode_api_test.cc
lib/jpegli/encode_api_test.cc
lib/jpegli/input_suspension_test.cc
lib/jpegli/test_utils.cc
lib/jpegli/test_utils.h

* jpegli_write_m_header() and jpegli_write_m_byte()
* jpegli_simple_progression()
* jpegli_set_linear_quality()
* jpegli_quality_scaling()
* jpegli_default_colorspace()

Add tests for more jpegli API functions.

---

lib/jxl/splines.cc

The color value of the spline matters for the rendering effort, so it should be taken into account in the `width_estimate`.
This bumps up the estimates by a factor of ~10 for 'normal' values of the color, and larger factors like 20 for large values of the color, so the limits themselves are also bumped up (by a factor of 8 for level 5 and factor 16 for level 10).

take color into account in estimated area of splines

---

lib/include/jxl/codestream_header.h
lib/jxl/enc_patch_dictionary.cc
lib/jxl/encode.cc

Make patches use reference frame 3, and make it reserved in the API.

---

lib/jxl/enc_frame.cc
lib/jxl/enc_group.cc
lib/jxl/enc_progressive_split.cc
lib/jxl/enc_progressive_split.h
lib/jxl/encode_test.cc

fix progressive lossless JPEG recompression

---

lib/jpegli/memory_manager.cc

This wastes memory since the blocksize itself is multiple of alignment size.
Memory benchmark results:
```
cjpeg    per       djpeg    per
Input           Encode args          Pixels     peak mem  pixel    peak mem  pixel
----------------------------------------------------------------------------------
BEFORE:
tiny.ppm        -sample 2x2             256       295468             243923
tiny.ppm        -sample 2x2 -o          256       336785             243560
tiny.ppm        -sample 2x2 -p          256       598884             243708
stp2.ppm        -sample 2x2          960000      1574892   1.64      918424   0.96
stp2.ppm        -sample 2x2 -o       960000      7527369   7.84      918765   0.96
stp2.ppm        -sample 2x2 -p       960000      5947204   6.20     4869331   5.07
NC003.ppm …
```

Don't round up number of blocks to alignment size.

---

lib/jpegli/bitstream.cc
lib/jpegli/entropy_coding.cc

Benchmark results (encode speed only):
```
Encoding               kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2        pnorm       BPP*pnorm   Bugs
----------------------------------------------------------------------------------------------------------------------------------
BEFORE:
jpeg:enc-jpegli:q90      13270  3542281    2.1354400  21.446  72.245   0.99999997   0.00000000   0.00000000  0.000000000000      0
jpeg:enc-jpegli:q75      13270  2093148    1.2618400  25.097  90.460   0.99999997   0.00000000   0.00000000  0.000000000000      0
AFTER:
jpeg:enc-jpegli:q90      13270  3542281    2.1354400  24.638  71.903   0.99999997   0.00000000   0.00000000  0.000000000000      0
jpeg:enc-jpegli:q75      13270  2093148    1.2618400  29.740  92.955   0.99999997 …
```

Faster refinement scan processing.

---

lib/jxl/enc_fast_lossless.cc

Lossless e1 only detected palette on RGBA input, for no good reason.
This makes it detect palette also on RGB input.
For some random png8 image from discord:
Before:
```
JPEG XL encoder v0.9.0 c81a5a46 [SSE4,SSSE3,Unknown]
Read 3526x358 image, 627101 bytes, 277.8 MP/s
Encoding [Container | Modular, lossless, effort: 1 | 14-byte Exif], 
Compressed to 2800470 bytes including container (17.748 bpp).
3526 x 358, geomean: 206.82 MP/s [72.86, 233.42], 100 reps, 4 threads.
```
After:
```
JPEG XL encoder v0.9.0 c0cfd188 [SSE4,SSSE3,SSE2]
Read 3526x358 image, 627101 bytes, 313.6 MP/s
Encoding [Container | Modular, lossless, effort: 1 | 14-byte Exif], 
Compressed to 1194923 bytes including container (7.573 bpp).
3526 x 358, geomean: 65.45 MP/s [44.57, 69.96], 100 reps, 4 threads.
```

make e1 lossless also use palette for RGB images

---

lib/jxl/enc_adaptive_quantization.cc
lib/jxl/enc_adaptive_quantization.h

Fix the compression of cropped images at efforts 8/9

---

lib/jxl/base/status.h

This can be used i.e. to implement static methods that construct an Image3F with proper allocation failure handling.

Implement a StatusOr type.

---

AUTHORS
lib/jxl/dec_group.cc

Identified by coverity
`CID 1532936 (#1 of 1): Identical code for different branches (IDENTICAL_BRANCHES)`

Remove a duplicate declaration

---

examples/decode_progressive.cc

fix buffer size in in decode_progressive example

---

lib/jxl/base/float.h
lib/jxl/test_utils.cc

in tandem with https://github.com/google/highway/commit/5030a388acc3dcfada259217b9a1d387383b7a2c
[https://github.com/libjxl/libjxl/actions/runs/5482261062/jobs/9987420722?pr=2269](https://www.google.com/url?sa=D&q=https%3A%2F%2Fgithub.com%2Flibjxl%2Flibjxl%2Factions%2Fruns%2F5482261062%2Fjobs%2F9987420722%3Fpr%3D2269)

two static casts

---

lib/jxl/test_utils.cc
lib/jxl/test_utils.h

use the one from float.h instead

remove LoadFloat16

---

lib/jxl/splines.cc

Drive-by: avoid `abs(int_x) < 0` situations

Fix overflow when calculating spline area estimate.

---

tools/cjxl_main.cc

See https://github.com/libjxl/libjxl/issues/2645

fix cjxl help on --container

---

tools/fast_lossless/pam-input.h

fclose file

---

lib/jxl/fields.cc
lib/jxl/fields.h
lib/jxl/jpeg/jpeg_data.cc

We have to cheat here to avoid adding more methods to Visitor class

Avoid timeout in fuzzer

---

AUTHORS

make dependabot pass AUTHORS check

---

.github/workflows/build_test.yml
lib/jxl/ac_strategy_test.cc
lib/jxl/dct-inl.h
lib/jxl/dct_test.cc
lib/jxl/dec_cache.h
lib/jxl/dec_transforms-inl.h
lib/jxl/enc_ac_strategy.cc
lib/jxl/enc_chroma_from_luma.cc
lib/jxl/enc_chroma_from_luma.h
lib/jxl/enc_group.cc
lib/jxl/enc_transforms-inl.h
lib/jxl/fast_dct-inl.h
lib/jxl/quant_weights_test.cc
lib/jxl/simd_util.cc
lib/jxl/simd_util.h
lib/jxl_lists.bzl
lib/jxl_lists.cmake

And fix the remaining big frames

Unsilence max_stack error

---

lib/extras/dec/apng.cc

Fixes https://github.com/libjxl/libjxl/issues/2764
Improves handling of sBIT chunks in PNG input to cjxl.
When R,G,B bit depths are not the same (for example 5 6 5), instead of silently ignoring the sBIT chunk, give a warning and use the max of the three as the RGB bitdepth. So for example rgb565 becomes rgb666 now, with a warning, while before it would become rgb888 without a warning.
When Alpha bitdepth is different from RGB bitdepth, this is actually not a problem as far as I can tell — jxl requires RGB channels to have the same bitdepth but extra channels can have a different bitdepth. So I don't think there's any reason to refuse such input (and even if there would be a problem, it would be better to just ignore the sBIT info than to return failure).

better handling of PNG with sBIT chunk

---

examples/encode_oneshot.cc

add missing fclose

---

README.md

This links to something that looks nicer.

use link to nicer view for security score card

---

tools/cjxl_main.cc

mention default for --lossless_jpeg

---

lib/extras/alpha_blend.cc
lib/extras/alpha_blend.h
lib/extras/packed_image.h
lib/jxl_lists.bzl
lib/jxl_lists.cmake
tools/djxl_main.cc

Add options for alpha blending for djxl.

---

lib/extras/codec_test.cc
lib/extras/enc/jpegli.cc
lib/extras/packed_image_convert.cc
lib/jxl/base/span.h
lib/jxl/color_encoding_internal.cc
lib/jxl/color_encoding_internal.h
lib/jxl/color_management.cc
lib/jxl/color_management.h
lib/jxl/color_management_test.cc
lib/jxl/decode.cc
lib/jxl/decode_test.cc
lib/jxl/enc_icc_codec.cc
lib/jxl/enc_icc_codec.h
lib/jxl/encode.cc
lib/jxl/icc_codec_test.cc
lib/jxl/jpeg/enc_jpeg_data.cc
lib/jxl/jpeg/jpeg_data.cc
lib/jxl/jpeg/jpeg_data.h
lib/jxl/jxl_cms.cc
lib/jxl/render_pipeline/render_pipeline_test.cc
lib/jxl/roundtrip_test.cc
lib/jxl/test_image.cc
tools/benchmark/benchmark_codec_avif.cc
tools/comparison_viewer/image_loading.cc

Unlike other base/ utilities PaddedBytes require compilation unit.

Untie cms/ some icc utilities from PaddedBytes

---

lib/jxl/enc_fast_lossless.cc

Fix encoding of <256x256 images that have <4 channels.

---

.github/workflows/build_test.yml
.github/workflows/build_test_cross.yml
.github/workflows/conformance.yml
.github/workflows/debug_ci.yml
.github/workflows/fuzz.yml
.github/workflows/pull_request.yml
.github/workflows/release.yaml
ci.sh

see 
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions

add merge_group

---

lib/extras/enc/pnm.cc

allow decoding to pam when no alpha is present

---

lib/jxl/speed_tier_test.cc

The tests in `speed_tier_test.cc` were only testing lossy; also adding lossless.
The butteraugli bound was quite loose, tightened it.
Dropped the full-size e8 image to save some time, and only doing lossless on the small images. Also testing e10 (on a tiny image so it doesn't take too long).

add lossless and e10 to speed tier test

---

lib/jxl/encode.cc
lib/jxl/roundtrip_test.cc

There was a bug in the code to write the `jxli` box: it would always write an empty box since it was writing to a temporary buffer that never actually ended up being written to the bitstream.
Added a rudimentary test for encoding multiple frames, both with and without frame index. Only checks that the animation roundtrips in both cases, and that the encoded bitstream with frame index is a bit larger. Doesn't check yet that the `jxli` information is actually correct or gets used in any way by the decoder.
(flyby: tighten the butteraugli distance for another test since it has an unnecessarily high bound)

fix bug in frame index box writing and add rudimentary test

---

lib/extras/enc/encode.cc
lib/extras/enc/pnm.cc
lib/extras/enc/pnm.h
tools/djxl_main.cc

add PNM decoding

---

ci.sh

removing stuff that was only needed in the gitlab ci.

simplify ci.sh

---

lib/jxl/base/span.h
lib/jxl/cms/jxl_cms.h

Don't know why it does not give them all at once.

Two more clang-tidy findings

---

.github/workflows/build_test.yml
tools/scripts/build_stats.py

`build_stats.py` is somewhat fixed, but currently provides no useful data.

Add OSX workflow

---

lib/jxl/cms/color_management.cc
lib/jxl/render_pipeline/stage_tone_mapping.cc

Fix a few conditions

---

lib/jxl/enc_fast_lossless.cc
lib/jxl/enc_fast_lossless.h
tools/fast_lossless/build.sh

Fix standalone fast lossless build.

---

lib/CMakeLists.txt
lib/jxl.cmake

otherwise libjxl_cms.pc cflags is just "-I"

fix libjxl_cms.pc include/lib path

---

tools/jxlinfo.c

This allows the help and verbose flags to be place in any place, so for instance 
```
jxlinfo my_cool_image.jxl -v
```
also works.

jxlinfo: don't force order of flags

---

doc/software_support.md

Although it is more that a viewer, this seems to fit best as the category. The latest release has just added JPEG XL support: https://aspect.bildhuus.com/blog/posts/aspect-preview-33

Add Aspect to the list of image viewers

---

tools/djxl_main.cc

don't try to write files when --disable_output

---

lib/jxl/enc_adaptive_quantization.cc

(TSAN) Do not compute mask1x1 for tile padding

---

lib/jxl/coeff_order.cc
lib/jxl/dec_group.cc
lib/jxl/dec_patch_dictionary.cc
lib/jxl/modular/encoding/dec_ma.cc
lib/jxl/splines.cc

Fix #3025 and other potential overflows

---

WORKSPACE
lib/jpegli/dct-inl.h

Drive-by: fix maybe-unused warning

Fix bazel build with modern compilers

---

flake.nix
lib/jxl.cmake
lib/jxl/libjxl.pc.in
lib/jxl/libjxl_cms.pc.in
lib/jxl_cms.cmake
lib/jxl_threads.cmake
lib/threads/libjxl_threads.pc.in

Drive-by: add some system deps to flake.nix

Fix pkgconfig for linking to an installed static library.

---

.github/workflows/build_test.yml
CHANGELOG.md
flake.nix
lib/CMakeLists.txt
lib/extras/codec_test.cc
lib/extras/common.cc
lib/extras/common.h
lib/extras/dec/jxl.cc
lib/extras/enc/encode.cc
lib/extras/enc/encode.h
lib/jxl.cmake
lib/jxl/libjxl.pc.in
lib/jxl/libjxl_cms.pc.in
lib/jxl_cms.cmake
lib/jxl_lists.bzl
lib/jxl_lists.cmake
lib/jxl_threads.cmake
lib/threads/libjxl_threads.pc.in

do not squash, but rebase and merge

Cherry picking v0.9.x

---

deps.sh

All / and - should be substituted.
Fixes #3070.

Fix deps.sh

---

deps.sh

All / and - should be substituted.
Fixes #3070.

Fix deps.sh (#3071)

---

CMakeLists.txt

Set ENABLE_JPEGLI conditioned on the existence of the libjpeg-turbo submodule

---

lib/jxl/enc_cluster.cc

About 0.1% density improvement.
```
Before:
Encoding           kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm  SSIMULACRA2   PSNR        pnorm       BPP*pnorm   QABPP   Bugs
---------------------------------------------------------------------------------------------------------------------------------------------
jxl:d0.1:1          156870 125498985    6.4001323  10.481  25.622   0.33339046  93.97832386  55.04   0.11910776  0.762305449452   6.400      0
jxl:d0.1:3          156870 118196434    6.0277206   9.531  22.580   0.33339046  93.97832386  55.04   0.11910776  0.717948322403   6.028      0
jxl:d0.1:4          156870 117891989    6.0121947   8.962  22.995   0.33382919  93.98281550  55.04   0.11907582  0.715907017487   6.012      0
jxl:d0.1:5          156870 139407419 …
```

Improve histogram selection/clustering when in streaming mode.

---

lib/jxl/render_pipeline/stage_write.cc
lib/jxl/test_utils.cc

This should help mitigating banding.

Do 8-bit ordered dithering when decoding to 8-bit.

---

.gitmodules
deps.sh
lib/jxl/cms/color_encoding_cms.h
lib/jxl/encode_test.cc

Fix CMYK encoding

---

.github/workflows/build_test_cross.yml
.github/workflows/release.yaml
.gitmodules
BUILD.bazel
CMakeLists.txt
deps.sh
lib/extras/codec.cc
lib/extras/dec/decode.cc
lib/extras/dec/decode.h
lib/jxl/cms/color_encoding_cms.h
lib/jxl/cms/jxl_cms.cc
lib/jxl/enc_aux_out.cc
lib/jxl/encode_test.cc
lib/jxl_benchmark.cmake
lib/jxl_cms.cmake
third_party/skcms.cmake
tools/djxl_main.cc

Cherry pick v0.9.1

---

.github/workflows/release.yaml

Re-add jxl.dll asset

---

.github/workflows/release.yaml

(cherry picked from commit b26041c708d523ac53bb7d95d4f5c4a5d3b1ce30)

Re-add jxl.dll asset (#3117)

---

lib/jxl/encode_test.cc
lib/jxl/jxl_test.cc

Also fix the streaming encoder tests to not set the streaming flag in the non-streaming mode.

Add test for streaming and non-streaming pixel equivalence.

---

tools/conformance/CMakeLists.txt

disable tooling test when not JPEGXL_ENABLE_TOOLS

---

lib/jxl/encode.cc

remove superfluous return

---

lib/extras/dec/decode.cc

remove unused variable base

---

lib/CMakeLists.txt
lib/include/jxl/decode.h
lib/include/jxl/encode.h
lib/jxl.cmake
lib/jxl_threads.cmake

Drive-by: remove duplicate header installation
Partially resolves #3177

Temporarily re-add version.h include

---

lib/jxl/render_pipeline/stage_upsampling.cc

avoid false detection of buffer overrun

---

lib/jxl/enc_frame.cc
lib/jxl/enc_xyb.cc
lib/jxl/enc_xyb.h

Drive-by: Fix size of extra channels in streaming mode.

Do XYB color transform in-place.

---

lib/jxl/frame_header.cc

allow SkipProgressive be is_last

---

doc/software_support.md

I found that some tools capable of viewing & manipulating metadata such as ExifTool and others should be mentioned.
I signed the CLA, but since it's a small change to a readme I guess only the first point applies here.

Added metadata libraries to software_support.md

---

lib/jxl/enc_frame.cc
lib/jxl/enc_modular.cc
lib/jxl/jxl_test.cc

Different group sizes still TODO.

Enable streaming mode for modular mode. 

---

lib/jxl/gradient_test.cc
lib/jxl/image.cc
lib/jxl/image.h
lib/jxl/image_ops.cc
lib/jxl/image_ops.h
lib/jxl/image_ops_test.cc
lib/jxl/simd_util.cc
lib/jxl/simd_util.h
lib/jxl_lists.bzl
lib/jxl_lists.cmake
lib/lib.gni
tools/gauss_blur_test.cc

Move loosely related code from image.cc

---

lib/jxl.cmake
lib/nothing.cc
tools/scripts/build_cleaner.py

Make jxl_export OBJECT library non-empty

---

lib/extras/dec/jpegli.cc
lib/extras/dec/jpg.cc

make cast explicit

---

debian/libjxl-gdk-pixbuf.install
plugins/CMakeLists.txt
plugins/mime/CMakeLists.txt
plugins/mime/README.md

disable installation of MIME file

---

lib/extras/enc/jpg.cc

explicit cast 

---

lib/jxl/dec_group.cc
plugins/gdk-pixbuf/pixbufloader-jxl.c

cherry pick for v0.9.2

---

lib/jxl/enc_frame.cc

Fix jxl_from_tree.

---

lib/jxl/enc_modular.cc
lib/jxl/enc_params.h
tools/jxl_from_tree.cc

Also fix multiple frames. Fixes #3264

Add support for up to 8 hidden channels before RGB channels to jxl_from_tree.

---

lib/jxl/enc_ans.cc

Also replace the size upper limit of the allottment for WriteTokens with a more conservative bound.

Avoid accessing out-of-bounds tokens in WriteTokens.

---

lib/jxl/enc_cache.h
lib/jxl/enc_frame.cc

Fix streaming encoding with more than 255 DC groups.

---

lib/jxl/enc_modular.cc

Cap the number of reference properties to the # of extra channels.

---

lib/jxl/enc_modular.cc

This is enabled for efforts 8 and up.
Benchmark results for imagecompression.info
```
BEFORE:
jxl:d0:9       156870 190086925    9.6939547   0.886  31.690         -nan 100.00000000  99.99   0.00000000  0.000000000000   9.694      0
AFTER:
jxl:d0:9       156870 189042902    9.6407121   0.859  29.633         -nan 100.00000000  99.99   0.00000000  0.000000000000   9.641      0
```

Revert palette transforms if they don't reduce size.

---

debian/libjxl-gdk-pixbuf.install
plugins/CMakeLists.txt
plugins/mime/CMakeLists.txt
plugins/mime/README.md

fixes #3358, fixes #3370, fixes #3371, fixes #3372

Revert "disable installion of MIME file (#2259)"

---

lib/jpegli/decode.cc
lib/jpegli/decode_api_test.cc

Fix jpegli_has_multiple_scans precondition check.

---

lib/extras/enc/jpegli.cc
lib/jxl/cms/jxl_cms.cc

Fix cjpegli xyb mode for grayscale and RGBA images.

---

lib/extras/dec/apng.cc

Drive-by: fix overflow in image size calculation.

Return JXL_FAILURE in png reader in case of OOM.

---

lib/extras/alpha_blend.cc
lib/extras/codec_test.cc
lib/extras/dec/apng.cc
lib/extras/dec/exr.cc
lib/extras/dec/gif.cc
lib/extras/dec/jpegli.cc
lib/extras/dec/jpg.cc
lib/extras/dec/jxl.cc
lib/extras/dec/pgx.cc
lib/extras/dec/pnm.cc
lib/extras/packed_image.h
lib/extras/packed_image_convert.cc
lib/jxl/decode_test.cc
lib/jxl/test_image.cc
tools/benchmark/benchmark_codec_jxl.cc
tools/djxl_fuzzer_corpus.cc

This way we can detect OOM and return JXL_FAILURE instead of crashing.

Use StatusOr Create function for PackedImage and PackedFrame.

---

tools/cjxl_main.cc

This makes --streaming_input flag best effort and prints a warning if streaming file reading failed.
Fixes #3403

Always try non-streaming file reading for non PPM/PGM inputs.

---

lib/extras/dec/pnm.cc

Fix chunked PNM size check.

---

lib/extras/dec/pnm.cc
lib/extras/enc/jxl.cc
lib/extras/enc/jxl.h
lib/extras/packed_image.h
lib/extras/packed_image_convert.cc
lib/jxl/jxl_test.cc
tools/cjxl_main.cc

Fix handling of 1-bit images in benchmark_xl.

---

lib/extras/enc/apng.cc
tools/djxl_main.cc

extra channels for decoding to png

---

examples/decode_progressive.cc

Follow-up fix.
See also https://github.com/libjxl/libjxl/commit/d047b2347a56ffcfa12d1d19a862f64f20348549 and https://github.com/libjxl/libjxl/commit/97ec970d06ad04254f2cdcbe0bf8bba3166372b6
@mo271 Now need one more of this :) 

decode_progressive.cc: define __STDC_FORMAT_MACROS if undefined

---

lib/jxl/encode_test.cc

Minor comment typo

---

lib/extras/dec/apng.cc
lib/extras/dec/apng.h
lib/jxl/base/span.h

modernize language; in the next part decoding logic will be reorganized

Refactor apng.cc, part 1 of 2:

---

lib/extras/enc/jpegli.cc
lib/jpegli/decode_api_test.cc
lib/jpegli/encode.cc
lib/jpegli/encode_api_test.cc
lib/jpegli/output_suspension_test.cc
tools/scripts/jpegli_tools_test.sh

The default remains YUV444 in the cjpegli binary.

Use YUV420 chroma subsampling in jpegli_set_defaults().

---

lib/jxl/enc_frame.cc

Set the flag --keep_invisible to default to 1 for lossless processing, and 0 for lossy.

Fixed --keep_invisible defaults, closes #3514

---

lib/jxl/enc_frame.cc

introduced by https://github.com/libjxl/libjxl/pull/3534

fix RoundtripLargeEmptyModular

---

lib/jxl/encode.cc

Add note on some other missing fields "reset"

Fix uninitialized memory access; 

---

lib/jxl/enc_adaptive_quantization.cc

no-op in quality, just a small cleanup

faster and simpler adaptive quantization calc

---

deps.sh

add googletest to deps.sh

---

lib/extras/enc/apng.cc

Replace manual bit shifting with the corresponding function from libpng

Simplify cLLi chunk writing

---

lib/jxl/modular/encoding/encoding.cc

Fixes https://github.com/libjxl/libjxl/issues/3659
This was a regression introduced in https://github.com/libjxl/libjxl/pull/1046 when making a specialized decode path for RLE-only Huffman decoding as in bitstreams produced by lossless effort 1 (fast lossless).
The bug was that at the end of a decoded channel, there could still be a run going that goes into the next channel. The code assumed that there would be no runs crossing channel boundaries (i.e. run == 0 at the end of every channel), which is a valid assumption for bitstreams produced by fast_lossless, but it is not a valid assumption in general.
The cases where libjxl happens to produce RLE-only Huffman bitstreams outside the fast_lossless code path are pretty rare (otherwise we would have noticed this regression way earlier), but …

fix bug in huffman-rle-gradient (e1) specialized decode path

---

WORKSPACE
lib/BUILD
lib/jxl/modular/encoding/encoding.cc

(cherry picked from commit 5c99f5300858a83badd92b2f3024374999416961)
rebase, not squash!

cherry pick for v0.10.3

---

WORKSPACE
lib/BUILD
lib/jxl/modular/encoding/encoding.cc

(cherry picked from commit 5c99f5300858a83badd92b2f3024374999416961) 
(cherry picked from commit f138eb30e4715b551effed727379a9938d7707db)

cherry pick v0.9.3

---

lib/jxl/modular/encoding/encoding.cc

(cherry picked from commit 5c99f5300858a83badd92b2f3024374999416961)
(cherry picked from commit f138eb30e4715b551effed727379a9938d7707db)

cherry-pick v0.8.3

---

lib/jxl/modular/encoding/encoding.cc

(cherry picked from commit 5c99f5300858a83badd92b2f3024374999416961)
(cherry picked from commit f138eb30e4715b551effed727379a9938d7707db) 
(cherry picked from commit bad72ed87c748a65e71ed03aef905564ce110ef9)

cherry-pick v0.7.1

---

lib/jxl/modular/encoding/enc_encoding.cc

Fix modular context tree lookup in the encoder.

---

tools/CMakeLists.txt
tools/benchmark/benchmark_xl.cc
tools/tracking_memory_manager.cc
tools/tracking_memory_manager.h

Add "cap" parameter - it will be used for "soft OOM" in fuzzers

Extract TrackingMemoryManager

---

lib/jxl/ac_strategy_test.cc
lib/jxl/base/random.h
lib/jxl/butteraugli/butteraugli_test.cc
lib/jxl/enc_modular.cc
lib/jxl/image_test_utils.h
lib/jxl/lehmer_code_test.cc
lib/jxl/modular/encoding/enc_ma.cc
lib/jxl/modular/encoding/enc_ma.h
tools/gauss_blur_test.cc
tools/tracking_memory_manager.cc
tools/tracking_memory_manager.h

(this will make transform_fuzzer corpora more cross-pollinating)

Make sure Rng is seeded the same way on 32/64-bit

---

bash_test.sh
ci.sh
deps.sh
doc/fuzzing.md
tools/benchmark/hm/decode.sh
tools/benchmark/hm/encode.sh
tools/benchmark/metrics/hdr_plots.sh
tools/benchmark/metrics/hdrvdp.sh
tools/benchmark/metrics/iqa_wrapper.sh
tools/benchmark/metrics/mrse.sh
tools/benchmark/metrics/prepare_metrics.sh
tools/benchmark/metrics/pupsnr.sh
tools/benchmark/metrics/pussim.sh
tools/benchmark/metrics/run_all_hdr_metrics.sh
tools/benchmark/metrics/run_all_sdr_metrics.sh
tools/benchmark/metrics/sdr_plots.sh
tools/benchmark/metrics/ssimulacra.sh
tools/benchmark/metrics/vmaf.sh
tools/conformance/tooling_test.sh
tools/demo_vardct_select.sh
tools/fast_lossless/build-android.sh
tools/fast_lossless/build.sh
tools/fast_lossless/cross_compile_aarch64.sh
tools/scripts/cjxl_bisect_bpp
tools/scripts/cjxl_bisect_size
tools/scripts/jpegli_tools_test.sh
tools/scripts/ossfuzz-build.sh
tools/scripts/progressive_sizes.sh
tools/scripts/reference_zip.sh
tools/scripts/roundtrip_test.sh

Scripts that were not prone to this problem were updated also, to make it more homogeneous.

Fix "space in script path" problem in all scripts.

---

lib/jxl/enc_modular.cc

Fix incorrect encoding behaviour in some cases in Modular mode.

---

tools/benchmark/benchmark_codec_avif.cc

Several libavif functions require us to check the result. This commit wraps these calls in the existing JXL_RETURN_IF_AVIF_ERROR macro to properly check these calls for failure.

tools/benchmark_codec_avif.cc: fix discarded avifResult warnings

---

lib/extras/enc/apng.cc

This fixes `benchmark_xl --save_decompressed`.

Make enc/apng support float input

---

doc/software_support.md

Added a line to software_support.md describing RawTherapee's current support of jxl

Update software_support.md adding RawTherapee

---

tools/example_tree.txt
tools/example_tree2.txt
tools/jxl_from_tree.cc

Allows making jxl art in HDR, because why not :)

add way to signal Rec2100 PQ/HLG in jxl_from_tree

---

tools/jxlinfo.c

check realloc in basicinfo

---

lib/jxl/convolve-inl.h

Add a couple of missing HWY_ATTR

---

lib/jxl/convolve-inl.h
tools/benchmark/benchmark_codec_avif.cc
tools/streaming_fuzzer.cc

cherry picking for  v0.11.0

---

lib/jxl/encode.cc
lib/jxl/jpeg/enc_jpeg_data.cc
lib/jxl/jpeg/enc_jpeg_data.h

detect broken ICC when encoding jpg

---

lib/jxl/encode_test.cc
lib/jxl/modular_test.cc
lib/jxl/roundtrip_test.cc

Remove some usages of CodecInOut

---

doc/software_support.md

Added in https://immich.app/docs/features/supported-formats/
https://github.com/immich-app/immich/commit/80d02e8a8d62b0b0738d25d9dd1b6987c1b5725d

Add Immich to supported software

---

lib/jxl/enc_ans.cc

add guard clause for alphabet size

---

tools/streaming_fuzzer.cc

Follow-up for https://github.com/libjxl/libjxl/pull/3822

Streaming fuzzer: allow lower effort attempts to have some diff as well

---

lib/jxl/modular/encoding/dec_ma.cc

Also rewrite the implementation to use iterative checking instead of recursive checking of tree property values, to ensure stack usage is low.
Before, it was possible for appropriately-crafted files to use a significant amount of stack (in the order of hundreds of MB).

Check height limit in modular trees.

---

lib/jxl/enc_fast_lossless.cc

```
2000 x 3008,  geomean: 123.866 MP/s [108.75, 129.53], , 100 reps, 1 threads.
3072 x 2048,  geomean: 211.124 MP/s [188.20, 221.33], , 100 reps, 1 threads.
->
2000 x 3008,  geomean: 132.063 MP/s [111.09, 137.27], , 100 reps, 1 threads.
3072 x 2048,  geomean: 225.402 MP/s [183.71, 236.48], , 100 reps, 1 threads.
```

Speedup 14+ bit e1 using AVX2 by ~6.6%.

---

lib/jpegli/huffman.h
lib/jxl/jpeg/enc_jpeg_huffman_decode.h
lib/jxl/modular/encoding/dec_ma.cc

cherry-pick for version 0.8.4

---

lib/jpegli/huffman.h
lib/jxl/jpeg/enc_jpeg_huffman_decode.h
lib/jxl/modular/encoding/dec_ma.cc

cherry-pick for v0.9.4

---

lib/jpegli/huffman.h
lib/jxl/jpeg/enc_jpeg_huffman_decode.h
lib/jxl/modular/encoding/dec_ma.cc

cherry-pick for v0.10.4

---

CMakeLists.txt
cmake_uninstall.cmake.in

add `make uninstall`

---

lib/jxl/dec_patch_dictionary.cc
lib/jxl/modular/encoding/encoding.cc
lib/jxl/pack_signed.h
lib/jxl/splines.cc

And check that range input is sane (32-bit).

Turn UnpackSigned to return int32_t

---

tools/gauss_blur.cc
tools/gauss_blur.h
tools/gauss_blur_gbench.cc
tools/gauss_blur_test.cc
tools/ssimulacra.cc
tools/ssimulacra2.cc

This is preparation for fixing SVE build

Do not use MaxLanes in gauss_blur

---

lib/jxl/color_management_test.cc
lib/jxl/enc_xyb.cc
lib/jxl/enc_xyb.h
lib/jxl/opsin_image_test.cc
lib/jxl/opsin_inverse_test.cc
tools/ssimulacra2.cc
tools/xyb_range.cc

In most cases it was just adding an extra image alloc + copy, and wrapping code on top.

Remove ToXYB(ImageBundle)

---

doc/software_support.md

Adding Okino software to the list in software_support.md

Add Okino products to software_support.md

---

lib/jxl/enc_fast_lossless.cc

Fix bug in BitWriter::WriteMultiple.

---

bash_test.sh
lib/jpegli/decode.cc
lib/jxl/convolve_test.cc
lib/jxl/icc_codec.cc
lib/jxl/jpeg/jpeg_data.cc
lib/jxl/modular/encoding/context_predict.h
tools/scripts/fix_headers.sh

Drive-by: minor readability fixes

Fix internal build

---

lib/jpegli/common_internal.h
lib/jpegli/huffman.cc
lib/jxl/enc_coeff_order.cc
lib/jxl/enc_huffman_tree.cc

It is fragile (does not work on my Arm + SVE instance / Clang).
Use other means to make results "stable".

Don't use hack for stable_sort

---

ci.sh

This makes repeated runs against different versions of binary easier

Add ability to save corpus after benchmark

---

lib/extras/codec_test.cc
lib/extras/dec/apng.cc
lib/extras/dec/apng.h
lib/extras/dec/exr.cc
lib/extras/dec/exr.h
lib/extras/dec/gif.cc
lib/extras/dec/gif.h
lib/extras/dec/jpegli.h
lib/extras/dec/jpg.cc
lib/extras/dec/jpg.h
lib/extras/dec/jxl.h
lib/extras/dec/pgx.h
lib/extras/dec/pnm.cc
lib/extras/dec/pnm.h
lib/extras/enc/apng.cc
lib/extras/enc/exr.cc
lib/extras/enc/jpegli.h
lib/extras/enc/jpg.cc
lib/extras/enc/jxl.h
lib/jxl/decode_test.cc
lib/jxl/test_utils.cc
lib/jxl/testing.h
tools/scripts/fix_headers.sh

(to aid automatic include fixes)

De-spaghettize extras codecs

---

.github/workflows/build_test.yml
.github/workflows/build_test_msys2.yml
.github/workflows/build_test_wasm.yml
bash_test.sh

Also skip bash_test in non-PR pipelines; it only makes noise

Split "magic" test in bash_test

---

tools/streaming_fuzzer.cc

Namely, dump image size and settings.

Tweak straming_fuzzer to make it easy to understand the testcase

---

lib/jxl/encode.cc
lib/jxl/memory_manager_internal.h

And refine return code for other

Deal with unhandled OOM case

---

.github/workflows/conformance.yml
lib/jxl/dec_noise.cc
tools/conformance/conformance.py
tools/scripts/install_deps.sh

Same compiler problem as seen in tests (surprise!)
Simplify conformance CI matrix and add all ARM variants.
Refactor conformance script - reduce nesting + report failed tests at the end
Bad news: SVE_256 conformance fails

Fix SVE2_128

---

AUTHORS
tools/jxltran.cc

jxltran: Add support for extracting the codestream from jxlp boxes

---

CHANGELOG.md
examples/encode_oneshot.cc
lib/extras/enc/jxl.cc
lib/include/jxl/encode.h
lib/jxl/encode_test.cc
lib/jxl/roundtrip_test.cc
plugins/gdk-pixbuf/pixbufloader-jxl.c
plugins/gimp/file-jxl-save.cc
tools/cjxl_fuzzer.cc
tools/streaming_fuzzer.cc

Clarify JxlEncoderFrameSettingsCreate can return NULL

---

tools/jxltran.cc

If the --extract option is used, the codestream is extracted without the container. However, raw JPEG XL codestreams cannot be higher than level 5, so we produce a warning if a jxll box was read first that indicates a higher level codestream is present.

tools/jxltran: warn if extracting raw codestream that is not level 5

---

lib/jxl/alpha.cc
lib/jxl/dec_group_border.cc
lib/jxl/enc_ans.cc
lib/jxl/enc_modular.cc
lib/jxl/jxl_test.cc
lib/jxl/memory_manager_internal.h
lib/jxl/modular/encoding/enc_encoding.cc
lib/jxl/modular/encoding/enc_ma.cc
lib/threads/thread_parallel_runner_internal.h
tools/streaming_fuzzer.cc

Run the formatter, which is causing linting failure with CI.

lint: run clang-format ./cl.sh lint | patch -p1

---

lib/jxl/enc_coeff_order.cc

Extracted from https://github.com/libjxl/libjxl/pull/4130
For large JPEG files, the number of blocks of a single type (dct8x8) can exceed 2^16 so the assumptions in the code break.

use enough integer width for counters in coefficient ordering

---

tools/jxltran.cc

Implement the `--pack` option for packing raw codestreams in a container.

jxltran: Add support for packing the codestream in a jxlc box

---

lib/jxl/enc_coeff_order.cc

See https://github.com/libjxl/libjxl/pull/4195#issuecomment-2820168638

Type fix for extended counters test

---

.github/workflows/conformance.yml

See https://github.com/libjxl/libjxl/pull/4200 — forgot to remove it there in the github runner script too

remove SVE256 from conformance runner matrix too

---

lib/jxl/alpha.cc
lib/jxl/butteraugli/butteraugli.cc
lib/jxl/enc_frame.cc
lib/jxl/enc_modular.cc
lib/jxl/enc_noise.cc
lib/jxl/image_ops.h
lib/jxl/modular/encoding/enc_encoding.cc
lib/jxl/modular/encoding/enc_ma.cc
lib/jxl/modular/encoding/enc_ma.h
lib/jxl/modular/encoding/encoding.cc

Also rewrite std::min(std::min and std::max(std::max

Use jxl::Clamp1 instead of std::min(std::max

---

lib/jxl/splines.cc

Subtracted row x0 from pixel to render to avoid rendering outside the row buffer.
Bug found in Rust translation jxl-rs, see https://github.com/libjxl/jxl-rs/pull/158.

Fixed spline offset.

---

lib/jxl/enc_heuristics.cc

27 log1p()s instead of one log1p for every 64 pixels

minor speed improvement for encoding

---

lib/jxl/modular/encoding/enc_ma.cc
lib/jxl/modular/encoding/enc_ma.h

Namely, it makes sense to have more granular group_id.

Give more room for static properties quantization

---

tools/streaming_fuzzer.cc

Also give more memory "volume" in case of narrow images. It is consumed by lightly used temporary arrays.
This will cause fuzzer to find problems at effort 8..9, but I don't want to tune threshold any further.
Later going to rework threshold system to display more precisely the problems. And explore why there are such big differences at higher efforts and `DECODING_SPEED > 2`.

Tune threshold for effort 5..7

---

lib/jxl/enc_modular.cc
lib/jxl/enc_modular_simd.cc
lib/jxl/enc_modular_simd.h
lib/jxl/jxl_test.cc
lib/jxl_lists.bzl
lib/jxl_lists.cmake
lib/lib.gni
tools/streaming_fuzzer.cc

While on release build it is ~+5% performance, on ASAN build it is ~30x speedup.
Why: std::min/max are tracked by ASAN as branch / decision point, and cost a lot...

SIMDify EstimateCost

---

lib/jxl/enc_modular.cc
lib/jxl/modular/encoding/enc_ma.cc

Q: perhaps we need to update it conditionally

Update predictor when setting ModularOptions::TreeMode::kNoWP

---

lib/jxl/enc_ans.cc

Drive-by: simplify allowed_counts generation; avoid `sort`.

Fix linear search in RebalanceHistogram

---

lib/jxl/enc_patch_dictionary.cc

That makes particular fuzzing sample to finish 1.4x faster

Massage FindTextLikePatches

---

.github/workflows/release.yaml

Try to fix vcpkg release workflow

Ramp up vcpkg version

---

.github/workflows/conformance.yml
CMakeLists.txt

And more friendly options to control that.

Report enabled/disabled HWY targets

---

.github/workflows/build_test.yml

Fix workflow
