- .github/workflows/pull_request.yml
The pull request workflow runs on a merge request which confuses our ci.sh lint on what to run the linter on.
> Disable clang-format on PR Actions

- .gitlab-ci.yml
gitlab.com/wg1/jpeg-xl is a mirror of github.com/libjxl/libjxl and it is
still running all the pipelines. This updates them to run on main branch
and on release branches.
Tested by pushing to a v0.999.x branch in gitlab.
> Update GitLab CI to run on main and release branches.

- .github/workflows/pull_request.yml
- ci.sh
- tools/check_author.py
Pull Request checks should only run on pull_request events, and not
needed to run on pull_request_review. This gets the feedback to the PR
as soon as possible. This was also causing issues in the PR with the
way we get the SHA values from the current environment.
This patch fixes the pull request workflow which was needed for the
AUTHORS check and adds this new check to update the AUTHORS file when
new contributors send patches.
> Check for AUTHORS file updates and re-enable PR checks.

- tools/benchmark/benchmark_xl.cc
- tools/cjxl_main.cc
- tools/codec_config.cc
- tools/djxl.cc
- tools/djxl_main.cc
Addresses https://gitlab.com/wg1/jpeg-xl/-/issues/183
Simplifies the cjxl banner (ascii art is fun, but not very good for a11y etc), and adds a banner to djxl and benchmark_xl so the version number can be seen in all tools, not only the encoder.
> simpler cjxl banner, also one for djxl

- lib/extras/codec_pnm.cc
- lib/jxl/enc_frame.cc
Adds decode support for `.y4m` (see https://wiki.multimedia.cx/index.php/YUV4MPEG2) which is convenient for source material that happens to be YCbCr 4:4:4, 4:2:2 or 4:2:0. Such images can be created using e.g. `ffmpeg -i input.png -pix_fmt yuv420p input.y4m`.
Only single-frame input works for now.
I used this to test lossless encoding of subsampled ycbcr and it works.
Trying vardct with this kind of input doesn't work (I suppose we could upsample and convert to RGB in that case).
There's no encode support for `.y4m` yet; that would involve having a way to skip the upsampling and color conversion, so the data stays in the original yuv4xx format.
If multi-frame and .y4m write support would later be added, it would be useful for lossless archival of uncompressed video in a way that also …
> add (still-only) y4m input support

- lib/jxl/enc_color_management.cc
- lib/jxl/enc_color_management.h
`cmsFLAGS_NOCACHE` disables the 1-pixel cache and makes calling `cmsDoTransform()` thread-safe. So instead of creating an LCMS transform for each thread, one can pass this flag and share a single transform across all threads.
I made an attempt to benchmark this, but the benefits (in terms of performance) are minimal, and I'm not sure whether it can be properly measured. Therefore, this should be considered as a general improvement.
<details>
<summary>Benchmark results</summary>
Benchmarked with a [photo of Wat Arun](https://commons.wikimedia.org/wiki/File:The_sculptures_of_two_mythical_giant_demons,_Thotsakan_and_Sahatsadecha,_guarding_the_eastern_gate_of_the_main_chapel_of_Wat_Arun,_Bangkok.jpg) (JPEG, 7360x4912, 29MB) containing the common sRGB IEC61966-2.1 profile.
Run with:
```bash
$ …
```
> Share LCMS transform across threads

- lib/extras/codec_psd.cc
decode_layer assumes that chan_id.size() == invert.size().
On one callsite (where invert is actually used) this is true.
On the other callsite invert is just an "all-false" stub, but
its size is set to be `real_nb_channels` which might be not enough.
>  Fuzz: fix heap-buffer-overflow in codec_psd

- .gitlab-ci.yml
- docker/scripts/jpegxl_builder.sh
This reverts commit 22ab730343a5ff0ed041359cee972f94e94e9a52.
It seems that EMCC uses improper closure-compiler version.
> Revert "Install JDK into docker image (for testing JNI wrapper). (#27)"

- .gitlab-ci.yml
This allows deprecating the (potentially disruptive) build-only-scalar
option, which may conflict with the desired build policy for tests.
> Use disabled-targets instead of build-only-scalar

- lib/include/jxl/decode.h
- lib/jxl/color_encoding_internal.cc
- lib/jxl/color_encoding_internal.h
- lib/jxl/dec_file.cc
- lib/jxl/dec_xyb.cc
- lib/jxl/dec_xyb.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_cache.cc
- lib/jxl/enc_patch_dictionary.cc
- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
For decoding a XYB-encoded image with ICC profile as original color
profile, allow configuring the decoder to decode to a color encoding of
your choosing, rather than the decoder always converting xyb to srgb.
Reason for this: the decoder is able to convert xyb to all supported
color encoding values (srgb, pq, hlg, linear, p3, ...). It does this
when it knows the color encoding, but not when an ICC profile is used
(since the libjxl decoder does not have color management system to parse
it, nor would all icc profiles be representable as a jxl color encoding)
If the decoder does not know the color encoding, it default to linear
srgb.
However, if you have a system, like the chrome browser, that can
determine form the ICC profile what the color encoding is, then it is
better to be able to let …
> Allow alternative to linear srgb when xyb with ICC

- README.md
After updating repo link in PR #41 the repo name changed too, so `cd jpeg-xl` doesn't work anymore if one wanted to use that link.
> Update build command in README.md

- lib/jxl/modular/transform/palette.h
Fixes https://github.com/libjxl/libjxl/issues/29
Inverse palette of multiple channels resetted hshift/vshift of the non-first restored channel to zero, which is incorrect.
In weird combinations with Squeeze, this can lead to negative shift values.
This does (probably) not happen in any bitstream created by cjxl.
> inverse palette bugfix: preserve hshift/vshift

- lib/jxl/dec_cache.h
- lib/jxl/dec_group.cc
- lib/jxl/dec_reconstruct.cc
- lib/jxl/dec_upsample.cc
- lib/jxl/dec_upsample.h
```
+------------+--------+--------+--------+
| cycles     |   2x   |   4x   |   8x   |
+------------+--------+--------+--------+
| Baseline   | 249948 | 377275 | 523975 |
+------------+--------+--------+--------+
| Scalar (1) | 111383 | 162607 | 299005 |
+------------+--------+--------+--------+
| SSE4 (4)   |  48596 |  47257 |  72677 |
+------------+--------+--------+--------+
| AVX2 (8)   |  38341 |  39268 |  45655 |
+------------+--------+--------+--------+
| AVX3 (16)  |  36736 |  44514 |  41769 |
+------------+--------+--------+--------+
```
BEFORE
```
Compr                            Input    Compr            Compr       Compr  Decomp  Butteraugli
Method                          Pixels     Size              BPP   #    MP/s    MP/s     Distance    Error p norm           BPP*pnorm …
```
> SIMDify upsampling

- AUTHORS
- tools/cpu/os_specific.cc
Building was failing because `CPU_ZERO` and `CPU_SET` in `os_specific.cc` were unused on HaikuOS.
This change makes HaikuOS follow example of MacOS: call them even though in the end thread will not be pinned anyway.
HaikuOS build could use `JXL_DISABLE_PINNING`, but then it would have to add some defines to exclude declaring `CPU_SET` and `CPU_ZERO`, which would lessen code readability for everyone.
> fix: unused CPU_[ZERO|SET] on HaikuOS

- tools/djxl_fuzzer.cc
In documentation it is said that preview is always after color profile,
in fuzzer code the expectation was inverted.
> Fuzz: fix expectation

- doc/developing_in_github.md
These instructions were for GitLab, but the reference in GitHub is a
different.
> Update instructions to fetch a pull request

- tools/cjxl.cc
Fixes https://github.com/libjxl/libjxl/issues/44
Default encoding from GIF was setting some encoder params that aren't necessarily a good idea anymore, causing -q 100 (which doesn't set those params) to often be better than default.
Default encoding from JPEG was not setting -d 0, which apparently caused it to do something slightly different (also lossless recompression, but the DC was somehow slightly less dense because of this).
> make default encode from gif/jpg do the same as -d 0 / -q 100

- README.Haiku.md
This adds `giflib_devel` (same as libgif on Linux) to list of dependencies to install on HaikuOS.
It's not strictly necessary for libjxl to work, but `RoundtripAnimationPatches` test fails without it.
> docs: add `giflib_devel` as dependency on HaikuOS

- .github/workflows/build_test.yml
- .github/workflows/pull_request.yml
- .gitlab-ci.yml
- bash_test.sh
This new build_test.yml workflow builds and tests for release, debug,
asan, msan and release with scalar-only modes in the the main and
release branches.
This patch now also builds all these targets but only tests release in
the pull request, unless it is labeled with "CI:full" label which will
cause it to test all the modes as well.
> New GitHub workflow to build and test several modes.

- .github/workflows/build_test.yml
AVX3 runs require at least 1800 kB as the limit, so bump this value up
to 2048.
> Increase stack limit on debug builds.

- lib/jxl/decode.cc
This is not supported in the current implementation, so skip outputting DC in this case
> Fuzz: Don't support DC output if pixel callback

- lib/jxl/modular/transform/palette.h
MetaPalette erases channels with non-zero h-/v-shift; when this transform is undone,
channels with zero h-/v-shift are added; un-squeeze of those will create channels
with negative h-/v-shift; repeated un-squeeze causes assertion failure.
Check h-/v-shift in MetaPalette.
> Fuzz: Undefined-shift in jxl::ModularFrameDecoder::FinalizeDecoding

- tools/cjxl.cc
This fixes a recent breakage in the handling of `--distance`.
> Only make `jpeg_transcode` set `butteraugli_distance` to 0 after it itself receives its correct value

- lib/jxl/common.h
- lib/jxl/dec_cache.h
- lib/jxl/dec_frame.cc
- lib/jxl/dec_reconstruct.cc
- lib/jxl/filters.h
- lib/jxl/image.cc
This should make it more evident when actually using "uninitialized"
padding memory in sanitizer builds.
> Use a sentinel value instead of 0 for memory sanitizer.

- README.md
- doc/benchmarking.md
Put the `benchmark_xl` in a separate file under `doc/` to avoid having a too intimidating main README.md / github frontpage.
Added `lightning` and `thunder` there, other than that it's just a copy/paste of what was in the README.md.
> split off the benchmarking section to a separate doc

- lib/jxl/image_metadata.cc
- lib/jxl/image_metadata.h
This header field wasn't actually set by the encoder.
For now, set it conservatively: if the RGB or A has a bit depth that is > 12, set the field to false.
Note that this may set it to false unnecessarily (e.g. if everything is VarDCT, the bit depth doesn't really matter; also 15-bit modular could be fine if no Squeeze or RCT is done and there are no out-of-range values), but that's better than nothing.
For now misses the cases where extra channels are manually added and have a higher bit depth than the main image (but I don't think there's any way that can happen at the moment in cjxl or in the encode api).
> set modular_16_bit_buffer_sufficient header field

- lib/jxl/color_encoding_internal.cc
These global static variables don't need to be non-const.
> Make kBradford and kBradfordInv const.

- lib/jxl/enc_file.cc
- tools/cjxl.cc
Disable progressive_dc with -p, and remove a 4x downsampled pass that
can look worse than just upsampling DC.
> Progressive steps

- tools/benchmark/benchmark_codec_jxl.cc
When running benchmark_xl on JPEG with exif orientation, or a PNG with
exif orientation in a text chunk identified as exif, the benchmark
compared the images with the mismatching orientation
> Fix benchmark on image with exif orientation

- lib/include/jxl/color_encoding.h
- lib/jxl/decode.cc
The function JxlDecoderGetInverseOpsinMatrix was defined but not
available in decode.h. It is not currently needed since the library
doesn't support outputting the internal xyb color values, and could be
restored (and added to the header) if such feature is added.
> Remove unused JxlInverseOpsinMatrix

- lib/jxl/enc_modular.cc
Fixes https://github.com/libjxl/libjxl/issues/75
It doesn't make sense to do lossy palette in combination with other lossy modular encode methods.
> don't do lossy palette when also doing lossy

- lib/jxl/modular/transform/palette.h
When bit_depth == 31, then intermediate value becomes MIN_INT...
> Fuzz: Integer-overflow in jxl::palette_internal::GetPaletteValue

- lib/jxl/base/status.h
Defining JXL_DEBUG_ON_ABORT to 0 will disable the abort messages in
JXL_ABORT, JXL_ASSERT and JXL_CHECK, removing the need to include those
strings in the final binary, as well as the __FILE__ strings.
This reduces libjxl.so in x86 by ~15 kB when compiling with
-DJXL_DEBUG_ON_ABORT=0.
> Build time flag to disable abort() messages.

- .github/workflows/build_test.yml
In Pull Requests, this uses the cache from the parent commit from main the first time, and re-uses its own cache in case of a rebuild of the same commit.
In main this uses the previous commit as a starting point as well. There's a 200MB ccache limit so old objects are evicted before we use up too much space in the per-repo GitHub cache, so multiple build targets can have space for their caches.
> Add ccache to the pipeline to speed it up

- lib/jxl/dec_frame.h
Blending check in MaybeSetFloatCallback was not quite correct, possibly causing segfaults.
Since the conditions are / should be the same between the two MaybeSet* functions, better to factor them out and avoid the duplication.
> fix check in MaybeSetFloatCallback, factor out duplicate code

- lib/jxl.cmake
- lib/jxl/decode.cc
- lib/jxl/decode_to_jpeg.cc
- lib/jxl/decode_to_jpeg.h
- lib/lib.gni
This patch groups most of the JPEG reconstruction decoder logic out of
the JxlDecoder to a new class JxlToJpegDecoder that is included in the
JxlDecoder struct. This clears a little bit the JxlDecoder but more
importantly makes it easier to remove the dependency on jxl::jpeg::
functions with a flag at build time which will be added later.
> Refactor decoding Jxl to JPEG out of decode.cc

- lib/jxl/dec_external_image.cc
- lib/jxl/dec_frame.h
Partially fixes https://github.com/libjxl/libjxl/issues/81
In the cases where ConvertToExternal is called to get an RGBA buffer, it will now always be unassociated alpha (which is what most applications will expect, including e.g. the png encoder in djxl).
If there is a need to also have the option of not doing the unpremultiply and getting the original, premultiplied values, this can be added later; for now it is important to get things right in decoders/viewers that are not looking at the premultiplied field and assuming things to be non-premultiplied.
This doesn't yet fix code paths that do not involve ConvertToExternal.
> do unpremultiply if needed in ConvertToExternal

- .gitlab-ci.yml
- docker/scripts/emsdk_install.sh
- docker/scripts/jpegxl_builder.sh
Do not land until HWY is updated past 376176136.
> Install JDK into docker image (for testing JNI wrapper).

- lib/jxl/dec_reconstruct.cc
Similar to recent fix, but for EC: upsampler takes care of mirroring,
so it should be fed with physical image size.
> Fuzz: fix DASSERT in FinalizeFrameDecoding

- ci.sh
- tools/CMakeLists.txt
The new ci.sh commands "asanfuzz" and "msanfuzz" are like "asan" and
"msan" but building all the code with -fsanitize=fuzzer-no-link.
This also allows to use a different set of flags when building the
fuzzers since the new JPEGXL_FUZZER_LINK_FLAGS cmake variable can be
changed to something else to use a different fuzzer driver.
Manually tested asanfuzz and msanfuzz.
> Split fuzzer builds to "asanfuzz" and "msanfuzz".

- lib/jxl/base/status.h
This is useful to force JXL_DASSERT() when NDEBUG is defined.
> Make `JXL_IS_DEBUG_BUILD` overridable

- examples/decode_oneshot.cc
- lib/include/jxl/resizable_parallel_runner.h
- lib/include/jxl/resizable_parallel_runner_cxx.h
- lib/jxl/decode_test.cc
- lib/jxl_threads.cmake
- lib/lib.gni
- lib/threads/resizable_parallel_runner.cc
This parallel runner is also tuned for running on systems with
non-uniform computation capabilities, such as arm's big.LITTLE CPUs that
are often found in phones.
> Add a resizable parallel runner.

- deps.sh
A fix for Windows.h filename case landed after that release.
This update is required for GCC builds on ARM, and Wasm.
> Update Highway to 0.12.2 +1

- lib/jxl/enc_modular.cc
This fixes a speed regression introduced in bdde644b9.
> Do not try LZ77ing DC in VarDCT mode.

- lib/include/jxl/decode.h
Add proposed API for rewinding the decoder with the purpose of
efficiently skipping to a frame
The goal of this is as follows: if you are rendering a looping animated JXL
image, but do not keep all frames in memory, and need to render an
arbitrary frame in the animation again (which may be beyond the start,
and may be at any point in time, e.g. due to not rendering frames when
not looking at the animation), how can we decode that frame as
efficiently as possible again, given the encoded jxl input data:
Decoding every frame from the beginning is very inefficient if you only
need to display frame N, and the SkipFrames function helps with that.
Even then it may be doing too much work though, since a decoder reset to
the beginning doesn't know which patches / to-be-blended frames affect
the …
> Header only: rewinding API

- lib/jxl/dec_modular.cc
- lib/jxl/enc_modular.cc
- lib/jxl/modular/encoding/encoding.cc
- lib/jxl/modular/encoding/encoding.h
- lib/jxl/modular/options.h
If group_rect gets squeezed to 0, it causes the situation when non-empty channel
is not decoded.
Validate channel configuration after MetaApply.
> Fuzz: accessing undefined values

- lib/jxl/codec_in_out.h
- lib/jxl/image_bundle.cc
- lib/jxl/image_bundle.h
- lib/jxl/jxl_test.cc
- tools/cjxl.cc
- tools/cjxl.h
Addresses one of the two feature requests in https://github.com/libjxl/libjxl/issues/76 :
Adds an option `--premultiply` to cjxl which will store the image in a premultiplied-alpha way (converting non-premultiplied to premultiplied).
Note: until https://github.com/libjxl/libjxl/issues/81 is resolved, this option will cause image to be rendered incorrectly.
> Add --premultiply option to cjxl

- bash_test.sh
When bash_test fails in the test_deps_version() print instructions on
how to revert the change if it was unintended.
> Add instructions to revert unintended submodule changes.

- lib/jxl.cmake
- lib/jxl_tests.cmake
- tools/CMakeLists.txt
This fixes the post-submit checks for the v0.4.x branch.
> Silence deprecation warnings when building with gcc

- lib/jxl/dec_ans.cc
Otherwise general ReadSymbol could read outside of vector
(and what worse, return wrong values).
> Fuzz: Initialize "0-symbol" Huffman tables.

- lib/include/jxl/decode.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
Implements SkipFrames and Rewind in a non-optimized way: makes the API
behave correctly and adds test, but does not yet implement optimizations
to prevent internally decoding unneeded frames
> Non-optimized SkipFrames implementation

- lib/jxl/enc_cache.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_params.h
- tools/cjxl.cc
- tools/cjxl.h
Allows preserving the color of invisible pixels in lossy mode (`--keep_invisible=1`) or forgetting the color of invisible pixels in lossless mode (`--keep_invisible=0`). For now just sets invisible pixels to black in lossless mode (probably something better is possible, but the smearing we're doing in lossy mode is not it).
> add cjxl option --keep_invisible

- lib/jxl/dec_reconstruct.cc
When vs > 0 and image is too short there might occur intermediate negative value.
Right shift is incorrect for that value and implementation-defined for signed
type.
Just do integer division instead and hope compiler will turn it to arithmetic shift.
> Fuzz: do proper division for negative values.

- deps.sh
This works around an internal compiler error specific to gcc 8.3 that did not trigger in 8.4.
> Highway update to 0.12.2+2

- lib/lib.gni
- tools/build_cleaner.py
This will help with build systems that require the public headers to be
explicitly listed in the build targets, like with bazel.
> Include the public include/ headers in the .gni file.

- .github/workflows/fuzz.yml
oss-fuzz provides a GitHub CI integration that would run the fuzzer on a
given pull request for a period of time. The minimum recommended time is
600 seconds, which is the value included in this commit.
See the following link for details:
https://google.github.io/oss-fuzz/getting-started/continuous-integration/
> Run CIFuzz continuous integration on PRs.

- lib/jxl/modular/transform/palette.h
- lib/jxl/modular/transform/subtractgreen.h
- lib/jxl/modular/transform/transform.cc
- lib/jxl/modular/transform/transform.h
RCT could be applied to channels of different hshift/vshift. If they have different dimensions, this got caught when trying to undo the RCT (which is rather late), but if they have the same dimensions (which can happen in weird/fuzzer cases), it was caught nowhere. When doing a permute-only RCT, that would lead to hshift/vshift values becoming invalid, and in combination with Squeeze it could lead to negative hshift/vshift.
This cleans up the checking a bit, doing the same check as in Palette also as a "Meta-RCT" check.
> check earlier and better if RCT operates on valid channels

- lib/jxl/common.h
- lib/jxl/modular/encoding/context_predict.h
- lib/jxl/modular/transform/squeeze.h
- lib/jxl/modular/transform/subtractgreen.h
Don't do unnecessary clamping and use of wider types in modular transforms and in the weighted predictor.
Small speedup of 1-4%, for example:
Modular falcon:
before: 4064 x 2704, geomean: 24.53 MP/s [21.31, 24.99], 30 reps, 4 threads.
after: 4064 x 2704, geomean: 24.77 MP/s [21.54, 25.62], 30 reps, 4 threads.
Modular default speed:
before: 4064 x 2704, geomean: 14.51 MP/s [13.62, 14.76], 30 reps, 4 threads.
after: 4064 x 2704, geomean: 14.61 MP/s [13.73, 14.99], 30 reps, 4 threads.
Modular default speed -Q 80:
before: 4064 x 2704, geomean: 17.86 MP/s [15.21, 18.50], 30 reps, 4 threads.
after: 4064 x 2704, geomean: 18.13 MP/s [14.79, 18.53], 30 reps, 4 threads.
Modular thunder:
before: 4064 x 2704, geomean: 49.24 MP/s [40.27, 51.04], 30 reps, 4 threads.
after: 4064 x 2704, geomean: 51.29 …
> don't use ClampToRange in modular

- tools/fuzzer_corpus.cc
The output of the fuzzer_corpus is too spammy and can fill up the logs
when generating the corpus. This new -q option makes it quiet.
Small fix to the logs to print the spec.orientation as a number instead
of a char is included here too.
> fuzzer_corpus: Add parameter to run quiet.

- lib/include/jxl/decode.h
- lib/jxl/decode.cc
Absolute values for skip frames don't work because when calling it you
may not know how many were already skipped internally. In addition, the
ability to make the amount smaller could cause a frame to have been
skipped that now would have been required anyway.
SkipFrames can instead increment the existing skip amount.
> Let skip frames add to existing amount

- lib/jxl/modular/transform/palette.h
- lib/jxl/modular/transform/subtractgreen.h
This allows to compile headers as standalone units.
> Add missing header includes.

- lib/jxl/enc_file.cc
- lib/jxl/enc_frame.cc
Overriding the color transform in enc_frame can an xyb_encoded <->
xyb mismatch assert to fail.
However, overriding color transform is still necessary to encode other
images correctly with correct color, such as y4m. Do this earlier, in
enc_file, now.
> Fix for https://github.com/libjxl/libjxl/issues/150

- tools/CMakeLists.txt
- tools/jni/org/jpeg/jpegxl/wrapper/Decoder.java
- tools/jni/org/jpeg/jpegxl/wrapper/DecoderJni.java
- tools/jni/org/jpeg/jpegxl/wrapper/DecoderTest.java
- tools/jni/org/jpeg/jpegxl/wrapper/ImageData.java
- tools/jni/org/jpeg/jpegxl/wrapper/PixelFormat.java
- tools/jni/org/jpeg/jpegxl/wrapper/decoder_jni.cc
- tools/jni/org/jpeg/jpegxl/wrapper/decoder_jni.h
Both RGBA_8888 and RGBA_F16 are tested in test_jxl_jni_wrapper unit test.
> Add F16 support to JNI wrapper.

- lib/jxl/modular/encoding/encoding.cc
- lib/jxl/modular/encoding/encoding.h
Get rid of unnecessary includes (I think most of those are for things that are now in enc_encoding.cc), some other minor cleanups.
> some minor code cleanup in modular decode

- lib/jxl/blending.cc
- lib/jxl/frame_header.cc
The latter appear to be more widely supported.
> Replace <cinttypes> macros with casts

- lib/jxl/dec_modular.cc
- lib/jxl/enc_modular.cc
- lib/jxl/modular/encoding/enc_encoding.cc
- lib/jxl/modular/modular_image.cc
- lib/jxl/modular/modular_image.h
- lib/jxl/modular/transform/palette.h
Some more cleanup, also theoretically fixing a (non-important) decoder bug.
Minval/maxval in modular Image were only used for two things:
- clamping after undoing all transforms
- defining the default out-of-bounds colors in palette
The spec says the image bitdepth is used to define these default palette colors. So the value that gets used in palette needs to correspond to that number. Palette computed the bitdepth from the minval and maxval, but it's a bit silly to first compute maxval from bitdepth and then bitdepth from maxval. In the DC groups, minval and maxval were set to some safe bound on how large these numbers can actually get, and then undo transform was done with clamping — it's better just not to do clamping and to pass the image bitdepth. Theoretically there could be a …
> replace modular image minval maxval with bitdepth

- lib/jxl/enc_modular.cc
Asan/msan tests fail because `1u << 32` has a too large shift. This only happens iff the result is not used anyway, but let's keep asan/msan happy.
> fix *san complaining about 1 << 32

- lib/jxl/dec_modular.cc
Factor is only used when bitdepth < 32 anyway, but *san complains about it so...
> avoid << 32 also in decoder

- lib/jxl/modular/encoding/encoding.cc
Image "size" for DC tile is 2048x2048. If there is e.g. 13 channels,
then tree is allowed to grow to 50M nodes. But when tree reaches 32M nodes,
for resizing it would temporarlily require ~4GiB...
> Limit tree size for DC tiles

- tools/cjxl_main.cc
Fixes https://github.com/libjxl/libjxl/issues/99
(first shows size of codestream, then if container is used, also shows total size)
> when using container, also show total size

- lib/jxl/decode.cc
- lib/jxl/image_metadata.h
Otherwise, mismatches in computed strides can result in memory
corruption and/or OOB writes.
> Properly consider orientation in *OutBufferSize.

- lib/jxl/dec_frame.cc
Otherwise spot-color rendering will fail.
> Fuzz: do not (re)move color planes before spot-colors are rendered

- CHANGELOG.md
- debian/changelog
The debian/changelog file is for the Debian package, which should list
changes made to the debian package, like changed flags or dependencies,
added patches to fix existing versions, etc. In our case, we normally
only just bump the version of the library and make no changes to the
package, so "Bump JPEG XL version to ..." is an appropriate message
there.
This patch moves all the available Changelog information to a new
CHANGELOG.md file following the guidelines from
https://keepachangelog.com/en/1.0.0/ . This will allow us to keep track
of notable changes when they land and make the release process easier.
> Move changelog to a CHANGELOG.md

- lib/jxl/dec_modular.cc
- lib/jxl/enc_modular.cc
- lib/jxl/modular/encoding/enc_encoding.cc
- lib/jxl/modular/encoding/encoding.cc
- lib/jxl/modular/modular_image.cc
- lib/jxl/modular/modular_image.h
- lib/jxl/modular/transform/enc_palette.cc
- lib/jxl/modular/transform/enc_transform.cc
- lib/jxl/modular/transform/enc_transform.h
Minor stuff, slightly decreases libjxl_dec size (probably not really when good lto is done), infinitesimally reduces memory use.
> compute_minmax is encode-only, real_nb_channels is not needed

- lib/jxl/dec_modular.cc
- lib/jxl/enc_modular.cc
- lib/jxl/modular/encoding/encoding.cc
- lib/jxl/modular/modular_image.h
- lib/jxl/modular/transform/squeeze.cc
The modular channel resize() function was copying and/or initializing pixels, for no good reason really. In the encoder there was one spot where copying was needed, the other instances of resize() were either just doing a shrinking of the dimensions with no need to initialize things, or a way to make sure the channel plane is actually allocated (in case of Squeeze, that wasn't always the case).
Reorganized things so this complicated resize() function is no longer needed. Channel planes are now always allocated immediately (change in MetaSqueeze), and explicit zeroing is only done when needed (when a modular decode is interrupted because of progressive: the not-yet-decoded channels all need to be zeroed then, not just the ones that weren't allocated yet — this fixes a potential …
> simplify modular channel resize()

- ci.sh
- tools/ossfuzz-build.sh
oss-fuzz.com uses a set of docker containers to build and run the fuzzer
targets. In oss-fuzz.com these are build from libjxl's main branch or
from a given branch in CIFuzz. However building requires a few steps to
set up the docker container and doesn't support fast incremental builds.
This patch adds ossfuzz_asan, ossfuzz_msan and ossfuzz_ubsan to build
libjxl in a similar way than what oss-fuzz does in their build.sh file.
A new ossfuzz_ninja will run "ninja" with the supplied args inside the
docker container to help rebuilding the project quickly after adding
local modifications.
The source code built is always taken from the current checkout (the
ci.sh directory) and the build files are stored in the BUILD_DIR as
usual. The BUILD_DIR is in a different path inside the container and …
> Add "ci.sh ossfuzz_*" commands to help repro oss-fuzz bugs

- lib/jxl/dec_frame.cc
- lib/jxl/dec_frame.h
- lib/jxl/dec_patch_dictionary.cc
- lib/jxl/dec_patch_dictionary.h
- lib/jxl/decode_test.cc
Add getters for which frame storage locations are referenced, and
referencable by, frames. This is for use for more optimal rewinding in
the API, but it is not implemented yet there.
Also added a test for a jxl image with patches to decode_test, to
prepare for when this feature is added to the API.
> Add reference getters to dec_frame

- tools/CMakeLists.txt
For proper xSAN run JVM needs to be driven by special wrapper.
There are no out-of-the box solutions, so currently test
is disabled to avoid unnecessary complexity.
> Disable JNI test on xSAN builds

- ci.sh
Summer is here, and with it an increased room temperature when
benchmarking JPEG XL on the ARM board, making it never reach the
internal CPU temp threshold to start the test. This workarounds the
issue by limiting the temperature waiting time to 5 seconds and
increasing the threshold to 38 C.
Tested with:
```
echo 42000 > fake_temp
THERMAL_FILE=fake_temp SKIP_CPUSET=1 ./ci.sh arm_benchmark
```
> Workaround the effects of global warming in ARM benchmarks.

- lib/jxl/jxl_test.cc
Adds a test that would have caught the regression fixed in https://github.com/libjxl/libjxl/pull/181
> add test for multi-threaded upsampling

- lib/jxl/enc_ac_strategy.cc
- lib/jxl/enc_heuristics.cc
This removes a non-linearity in bitrate for lower qualities, and makes
testing and figuring out more linear heuristics for the ac decision tree
reversal easier.
Before:
```
Compr              Input    Compr            Compr       Compr  Decomp  Butteraugli
Method            Pixels     Size              BPP   #    MP/s    MP/s     Distance    Error p norm   PSNR   QABPP     DCT2     DCT4   DCT4X8      AFV     DCT8  DCT8X16  DCT8X32    DCT16 DCT16X32    DCT32           BPP*pnorm   Errors
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
jxl:3           17448577  3687783    1.69081203585   1   6.678  16.907 …
```
> Simplifying speed heuristics

- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
When there were internal frames, SkipFrames counted them as externally
displayed frames, but it shouldn't: only user-visible frames that are
output by the API should be counted (and internal ones belonging to
that external frame skipped without decrementing the counter)
Also added a test for this. Also removed the test that used the traffic
light image: I wrongly thought this image had patches (internal
non-rendered frames), but it does not. The new test generates such
frames programatically instead.
> Fix SkipFrame in case of internal frames

- lib/jxl/jxl_test.cc
See https://github.com/libjxl/libjxl/commit/6e16ef746f2fcc68e0d7bd29bdaa9fedcde7a9b8#commitcomment-52246195
> bump up test target to not fail when high_precision=0

- lib/jxl/modular/transform/squeeze.cc
The default squeeze parameters were not exactly set according to spec. It doesn't make any difference for the bitstreams produced by the current encoder, but it would make a difference if a hypothetical encoder would do two or more squeeze transforms on the same modular image, where the second or later squeeze is a default squeeze. (this would likely not be a very useful thing for a hypothetical future encoder to do, but still...)
> fix default squeeze params

- lib/jxl/dec_modular.cc
- lib/jxl/enc_modular.cc
- lib/jxl/modular/encoding/enc_encoding.cc
- lib/jxl/modular/encoding/encoding.cc
- lib/jxl/modular/modular_image.cc
- lib/jxl/modular/modular_image.h
- lib/jxl/modular/transform/enc_palette.cc
- lib/jxl/modular/transform/palette.h
- lib/jxl/modular/transform/squeeze.cc
Get rid of `Image.nb_channels`, since it had become redundant, especially in the decoder.
Also fixes https://github.com/libjxl/libjxl/issues/184, removes/updates some stale comments, and removes a check that is already implied by an earlier check (so the condition will always fail).
> remove another unnecessary modular image field

- lib/jxl/modular/transform/enc_squeeze.cc
- lib/jxl/modular/transform/squeeze.cc
- lib/jxl/modular/transform/squeeze.h
Squeeze params were checked before the loop, which wasn't quite correct, since the number of channels changes during the loop that came after the check. This meant that custom squeeze params that would do squeezes on channels that don't exist yet before the loop would not be allowed (both in the encoder and in the decoder), while it could actually be a valid bitstream.
This PR puts the check inside the loop instead, so it checks things w.r.t. the actual channel vector at that point in the squeeze steps series.
The default squeeze params (which is the only thing the encoder currently uses) are not affected by this, because that always passes the too-strict check too. But valid custom squeeze params could lead to decode error.
> improve squeeze param check

- tools/cjxl_main.cc
Printing size_t with printf requires a different format string depending
on the library. Other projects use macros like PRIuS similar to PRIu32
and PRIu64.
To workaround the issue we print a long long unsigned instead in this
case.
> Avoid %zu in cjxl_main.cc

- lib/jxl/dec_frame.cc
- lib/jxl/dec_frame.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
This stores the dependency graph between frames on rewind, so that
decoding of more frames can be avoided when skipping to a later frame
after rewind.
Improved the SkipFrameWithBlendingTest to have true dependencies between
frames that use a blending mode that depends on the pixels of both 
frames, to test this feature, and verified that making 
GetFrameDependencies return wrong output, breaks the test.
> Store frame dependency graph on rewind

- lib/jxl/decode.cc
The format must be checked for having a supported amount of channels,
pixel type, etc... This was done in the size check for the image output
buffer setters, but was not done in the callback because buffer size
works differently for those.
Now the full check is done here as well to fix that.
> Verify JxlPixelFormat validity when setting out callback

- lib/jxl/dec_modular.cc
- lib/jxl/dec_modular.h
- lib/jxl/modular/transform/rct.h
- lib/jxl/modular/transform/transform.cc
Makes global RCTs a bit faster (as e.g. used at fast modular speed settings like thunder and falcon).
Introduces a list of global transforms that are applied immediately after decoding each group instead of during finalization. For now only RCTs are moved from the global image to that list, could later add non-delta-palette transforms (channel palettes or simple color palettes) too. @veluca93 : this might be a start for a memory reduction by skipping the global image in case there are no global transforms left at that point.
In case there are still global RCTs left (e.g. when the global RCT is followed by a global squeeze or delta palette), use threads.
About 5% speedup of modular thunder decoding:
before: 4064 x 2704, geomean: 47.28 MP/s [38.06, 49.52], 30 reps, 4 threads.
after: 4064 x …
> push global RCT to groups if possible, parallelize otherwise

- lib/include/jxl/decode.h
- lib/jxl/dec_frame.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
In dec_frame, the low memory path was being disabled if the image has
exif orientation, even if the user wants to output as-is without
applying the orientation. This adds a new flag to indicate what is
intended, so the low memory path can be used if no orientation is
performed.
Also adds a test for orientation in decode_test (both with and without
keep_orientation).
Also fixes decoder rewind to keep the orientation setting around, since
settings are expected to stay after rewind.
> Support low memory if exif orientation is kept

- lib/jxl/decode_test.cc
- lib/jxl/enc_ac_strategy.cc
look first for best 8x8 transforms, then combine them until one cannot
this leads to much less ringing and much more agreeable low bpp
performance
About 1.5-1.7 % improvement in d1-d0.8, 3-3.5 % in d3-d8, images look
better
Before:
``` …
```
> Reversing the decision tree

- lib/jxl/butteraugli/butteraugli.cc
- lib/jxl/enc_ac_strategy.cc
- lib/jxl/enc_adaptive_quantization.cc
- tools/optimizer/simplex_fork.py
The reversal of the decision tree produces more stable decisions and now
we can do overall more aggressive optimization of the ac strategy
heuristics.
1.33 % improvement in BPP*pnorm
Images look to have less ringing in the d0.8 - d4 range, d8-d32 not
worse.
Particularly, both jxl:d3:epf0 looks and jxl:d2:epf3 look quite a lot better
while having a lower BPP.
Before:
```
------------------------------------------------------------------------------------------------------- …
```
> Tuning ac strategy heuristics

- lib/jxl/blending.cc
- lib/jxl/blending.h
- lib/jxl/blending_test.cc
- lib/jxl/dec_reconstruct.cc
This prevents the pointers that we keep in `extra_channels` from being
invalidated by reallocation.
> Pass `decoded->extra_channels()` and the corresponding Rects separately to PrepareBlending

- lib/jxl/dec_reconstruct.cc
Items are processed lane-wise and stored element-wise (for last vector).
> Fix another MSAN false-alarm.

- lib/jxl/enc_ac_strategy.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/jxl_test.cc
Before:
```
jxl:d0.8:epf0      17448577  3873678    1.77604305497   1   2.196  14.199   1.80286932   0.53070128796  41.92   2.141 0.000000 0.000000 0.190141 0.006345 0.066184 0.300542 0.000000 0.052862 0.220016 0.128700 …
```
> Try merging 16x8 and 8x16 fairly, not sequentially

- lib/extras/codec_png.cc
Otherwise assert fails at later stages.
> Fuzz: validate rendering intent

- lib/jxl/enc_heuristics.cc
Use more distinct AC block contexts for larger images / lower distance, fewer for smaller images / higher distance.
~0.1% density improvement, no quality changes (entropy coding change only)
Before:
```
Compr              Input    Compr            Compr       Compr  Decomp  Butteraugli                                             
Method            Pixels     Size              BPP   #    MP/s    MP/s     Distance    Error p norm           BPP*pnorm   Errors
--------------------------------------------------------------------------------------------------------------------------------
jxl:d0.5        41091840 12560903    2.44543013893   1   2.159  19.226   2.49855947   0.40187863846  0.9827661346725537        0
jxl:d1          41091840  8035952    1.56448618509   1   2.070  19.190 …
```
> minor ac block ctx tweak

- lib/jxl/enc_ac_strategy.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/jxl_test.cc
- tools/optimizer/simplex_fork.py
Slight improvement (0.44 %) on BPP * pnorm, visual inspection suggest images may
be a bit more vivid and have higher contrast. Ringing is not substantially
reduced in this change, but possibly a little. Sometimes there is more
ringing. Likely some additional improvement to counter that is possible.
Delightfully max butteraugli distance is greatly reduced (3.5 %), too.
Before:
```
--------------------------------------------------------------------------------------------- …
```
> Start using non-aligned 16x8, 8x16 and 16x16 dcts

- doc/developing_in_github.md
Other minor fixes of GitLab vs GitHub naming included here.
> Update git documentation to recommend set-url --push.

- lib/jxl/dec_bit_reader.h
While an unsigned integer overflow is well defined, advancing next_byte_
way too much past the end of the buffer might make the pointer wrap
around and pass tests like "next_byte_ < end_minus_8_" when it actually
is before the beginning of the buffer.
Found this looking at unsigned integer overflow messages.
> Fuzz: Prevent integer overflow in SkipBits()

- lib/jxl/jxl_test.cc
Making build green again.
Not sure if this is a good idea, but it will keep the wheels rolling.
Probably something not so good is done in the low precision mode given
that its butteraugli score is 3x worse than high precision mode.
> Relax low precision RoundtripResample2MT ba score

- lib/jxl/enc_frame.cc
- lib/jxl/enc_params.h
- tools/cjxl.cc
This adds command line parameters `center_x` and `center_y` allowing to
specify the first tile, i.e. the center for tile order.
When no value is given the geomemtric middle of the image is used as a
center, as it was before.
> Allow arbitrary center for group order

- lib/jxl/enc_frame.cc
- lib/jxl/enc_params.h
- tools/cjxl.cc
We rename `middleout` to `centerfirst`. This is more consistent with the
parameters `center_x` and `center_y`.
> Rename to centerfirst

- lib/jxl/modular/transform/squeeze.cc
- lib/jxl/modular/transform/transform.cc
The short-circuit for channels with no pixels was not updating the size
of the output channel, only updating the vshift/hshift. This caused the
channel sizes to get out of sync with the MetaApply ones. This patch
fixes that and also prints the squeeze transforms when debug is enabled
and only the default transform is used.
> Fuzz: Fix InvSqueeze when using channels with no pixels

- lib/jxl/enc_ac_strategy.cc
Surface area of ringing is reduced in anime drawings (improvements observed in d0.8 and d3 epf0).
0.16 % degradation in BPP*pnorm.
1.1 % improvement in butteraugli distance.
Before:
```
jxl:d0.8:epf0      17972865  3936138 …
```
> Less ringing. Use max, not 8 norm for small blocks

- lib/jxl/enc_frame.cc
We change the order of the groups from counter-clockwise to clockwise,
because subjective evaluation suggests that this yields a more natural
progressive image.
> Clockwise order for centerfirst group order

- lib/jxl/decode.cc
- tools/CMakeLists.txt
When JPEGXL_ENABLE_FUZZERS is off, we weren't defining any of the fuzzer
targets except in coverage builds (when JPEGXL_ENABLE_COVERAGE is on).
This patch instead defines the fuzzer targets as "djxl_fuzzer_runner"
when JPEGXL_ENABLE_FUZZERS is off but excluded from the "all" target.
There are no changes to the targets defined when JPEGXL_ENABLE_FUZZERS
is on, except that djxl_fuzzer depends on the decoder side only, helping
the fuzzer library with the coverage analysis by removing all the unused
encoder and extras library code.
> Always define the fuzzer build targets

- ci.sh
- deps.sh
- doc/developing_in_github.md
- docker/scripts/jpegxl_builder.sh
- lib/extras/codec_png.cc
- lib/include/jxl/decode.h
- lib/jxl/ans_common.h
- lib/jxl/butteraugli/butteraugli.cc
- lib/jxl/dct-inl.h
- lib/jxl/dec_ans.cc
- lib/jxl/dec_frame.cc
- lib/jxl/dec_patch_dictionary.h
- lib/jxl/dec_render_pipeline.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
- lib/jxl/enc_ans.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_modular.cc
- lib/jxl/encode_test.cc
- lib/jxl/image_test_utils.h
- lib/jxl_extras.cmake
- third_party/HEVCSoftware/cfg/encoder_intra_main_scc_10.cfg
- tools/benchmark/benchmark_codec_webp.cc
- tools/box/box.cc
- tools/check_author.py
- tools/cmdline.h
- tools/demo_progressive_saliency_encoding.py
- tools/djxl_fuzzer.cc
- tools/jni/org/jpeg/jpegxl/wrapper/decoder_jni.cc
The proccess was manually supervised, so there's no need to worry that meaningful code has been corrupted. There still might be some other typos not detected by [`codespell`](https://github.com/codespell-project/codespell), so watch out.
> Fix typos with codespell tool

- lib/jxl/enc_adaptive_quantization.cc
Find the four lowest masking areas without favoring the current area.
Reduces ringing on anime and elsewhere in a very subtle way.
Before:
```
jxl:d0.8:epf0      17972865  3950851    1.75858484443   1   2.429  14.353   1.65703654 …
```
> Don't favor 4x4 locality in visual masking

- lib/jxl/modular/transform/enc_palette.cc
When doing lossless pfm compression, and the pfm contains negative values, things can happen like
minval=-1149239296
maxval=1073709056
int lookup_table_size = -2072018943
while it should actually be 2222948353
> fix overflow in fwd palette

- ci.sh
Calling ninja directly doesn't work in the msan case because the
msan libraries need to be copied to the docker container every time.
Disable this option since there's otherwise no indication that
ninja built with the non-instrumented std libraries.
> Dissable ci.sh ossfuzz_ninja for msan.

- tools/djxl.cc
- tools/djxl_main.cc
Whenever return code is not 0, user should be informed why.
Fixes #265.
> Improve failure reporting in djxl

- lib/jxl/dec_file.cc
- lib/jxl/dec_xyb.cc
- lib/jxl/dec_xyb.h
- lib/jxl/decode.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_cache.cc
- lib/jxl/enc_patch_dictionary.cc
- lib/jxl/image_metadata.h
There were two independent copies of CustomTransformData in CodecMetadata:
one directly in CodecMetadata, the other in ImageMetadata (which is the
field m of CodecMetadata)
The one being saved in the file was the one from CodecMetadata, the one
used while decoding was instead the one from the ImageMetadata.
So it ignored the opsin inverse matrix from the jxl file, due to using
the other, default initialized, one for the actual decoding.
This removes the copy from ImageMetadata, so there's only one copy
left that's both saved and used.
> Use the correct CustomTransformData

- lib/extras/codec_png.cc
- lib/include/jxl/color_encoding.h
Currently, we are quick to convert the color information to an ICC profile (https://github.com/libjxl/libjxl/issues/266#issuecomment-873052852), which means that when decoding to PNG (with iCCP and gAMA), reencoding to JXL (reading iCCP but ignoring gAMA), and decoding to PNG again (writing iCCP only), the final PNG does not have the original gAMA tag, although it does have a functionally equivalent ICC profile. With this, its set of tags is closer to the original’s.
Because we recognized the sRGB primaries, we also used not to write them back, but now we do. We also include the recommended gAMA chunk for sRGB images.
> PNG: try to preserve the original color tags when writing

- lib/jxl/enc_ac_strategy.cc
- lib/jxl/enc_ac_strategy.h
- lib/jxl/enc_adaptive_quantization.cc
Adding some rms-optimization instead of only L1 optimization to
EstimateEntropy. Looks better with less ringing, although it is
a subtle change.
Max butteraugli reduced by 2.4 %.
Some more 'fidelity' in complex textures is likely the largest
outcome of this change.
Before:
```
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ …
```
> Less ringing, more fidelity through 'info loss'

- lib/jxl/decode_test.cc
msan needs a higher butteraugli score than non-msan
This is of course not ideal, the result should be the same.
PR 273 that surfaced this however did not introduce this discrepancy,
and rolling it back would not solve the root cause -- so 'fixing'
the problem with upping the limit. I have filed a bug about the
msan and non-msan not matching and we will discuss that later.
> Fixing the build in msan

- lib/jxl/jpeg/enc_jpeg_data.cc
Otherwise decoder puts all zeroes instead of gray channel.
> Encoder: override color_transform for grayscale JPEG images with AdobeRGB ICC.

- tools/jxl_from_tree.cc
@sboukortt reported on Discord that `jxl_from_tree` can overwrite its input if the provided output filename is the same as input; now it should throw an error and exit, just like in case of wrong number of args.
> Abort `jxl_from_tree` if output filename same as input

- lib/jxl/enc_ac_strategy.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/passes_test.cc
First, overnight simplex-fork optimization of heuristics.
Second, manual tweaking of heuristics related to ac-strategy.
All numbers with the exception QABPP get slightly worse, but there is
significantly less ringing at high distances and some less in lower
distances, too.
Most effective change here was to change the base entropy to 0 in
EstimateEntropy, possibly the second most effective is calculating
distance-weighting into dct32x16 entropies.
Before:
``` …
```
> Reduce ringing

- lib/extras/codec_gif.cc
- lib/extras/codec_jpg.cc
- lib/jxl/dec_cache.h
- lib/jxl/dec_external_image.cc
- lib/jxl/dec_frame.cc
- lib/jxl/dec_reconstruct.cc
- lib/jxl/dec_xyb.cc
- lib/jxl/filters.h
- lib/jxl/image.cc
- lib/jxl/sanitizers.h
- tools/benchmark/benchmark_codec_webp.cc
This adds two new Image-related msan helper functions: PoisonImage will
mark all the Image memory (including padding) as uninitialized while
CheckImageInitialized will check that the pixels inside a given Rect are
is initialized in an image.
When running a multi-thread step with per-thread temporary images we can
use PoisonImage to avoid leaking initialized memory from a previous run
in the same thread to the next run. This helps identifying where was the
uninitialized memory from.
Functions accepting images, specially those that take chunks of images
with a given rect should use CheckImageInitialized over the passed Rect
to trigger msan early when uninitialized memory bugs arise, otherwise
msan would only trigger when the uninitialized values are used in a
comparison (like NearestInt or …
> Add PoisonImage and CheckImageInitialized to sanitizers.h

- lib/jxl/enc_ac_strategy.cc
This makes a corpus test produce exactly same results as before 288.
I had falsely assumed that the minor changes were due to the subtle
differences in calculation order.
> fixing uninitialized read I introduced in #288

- lib/jxl/enc_params.h
To say that this flag is deprecated would be an understatement since it's been marked as such from the very first public commit ff09371267315c39fe0220082943c5834db04ab9 from 2019.
> Remove ancient encoder flag

- tools/flicker_test/test_window.cc
Each call to `...Folder.entryList()` returned a new temporary, so we
called `.begin()` on one and `.end()` on the other.
> Fix flicker test tool with recent Qt versions

- lib/jxl/sanitizers.h
On top of printing the failed expectation (what range should be
initialized and what pixel wasn't initialized) this patch now prints a
map of all the uninitialized pixel in the given image to better
understand what region is not initialized. For example, after adding
some poisoned values:
```
/src/libjxl/lib/jxl/sanitizers.h:179: Checking an image of 336 x 292, rect x0=40, y0=18, xsize=258, ysize=258
/src/libjxl/lib/jxl/sanitizers.h:182: CheckImageInitialized failed at x=0, y=61: im=*plane_out, r=Rect(x0, y0, x1 - x0, y1 - y0)
Uninitialized regions for image of size 336x292:
y=[0, 18): [0, 336)
y=[18, 61): [0, 40) [298, 336)
y=[61, 65): [0, 45) [298, 336)
y=[65, 276): [0, 40) [298, 336)
y=[276, 292): [0, 336)
Uninitialized bytes in __msan_check_mem_is_initialized at offset 0 inside …
```
> Print uninitialized ranges when failing JXL_CHECK_IMAGE_INITIALIZED

- lib/jxl/modular_test.cc
- tools/fuzzer_stub.cc
- tools/jni/org/jpeg/jpegxl/wrapper/decoder_jni.cc
The only actual bug fixed here is in modular_test which was passing
maxval instead of bitdepth.
> Fix clang-tidy bugprone-argument-comment errors

- lib/jxl/decode.cc
With ANS coding it is easy to make CPU-bomb.
In example discovered by fuzzer there were hundreds of frames,
each encoded with just 39 bytes. Nevertheless, this fires the
full image decoding / processing machinery.
> Fuzz: introduce CPU limit alongside memory limit.

- lib/extras/codec_apng.cc
On windows it was emulated by creating temporary file (which was never deleted).
Drive-by: remove local defines
Fixes #6
> Get rid of fmemopen in codec_apng.

- lib/jxl/modular/transform/enc_palette.cc
- lib/jxl/modular/transform/palette.h
- lib/jxl/modular/transform/transform.cc
See also the discussion in https://github.com/libjxl/libjxl/pull/209
Requires palette to operate on either all-meta or all-non-meta channels (the first being something the current encoder doesn't do), and fix the nb_meta_channels update in the all-meta case.
Also checks RCT validity at the MetaApply point instead of waiting for after decode (it would fail when doing InvRCT, but better to fail earlier).
> make modular transform checks tighter and fix nb_meta_channels bug

- lib/jxl/dec_reconstruct.cc
- lib/jxl/epf.cc
- lib/jxl/epf.h
- lib/jxl/filters.cc
- lib/jxl/filters.h
The FilterPipeline required that the x0 in all three input, output and
image rects be a multiple of kPaddingXRound. This has the issue that it
is 4 in ARM but 8 in x86, however Sigma is always an 8x8 downsampled
image.
This patch relaxes the requirement so that input, output and image rect
all have the same alignment % kPaddingXRound but it doesn't need to be
0, removing the logic that extends the filters ranges from
dec_reconstruct.
The EPF functions were receiving a image_x_mod_8 value as
image_rect.x0() % 8, which was always 0 in x86, but may be 4 in ARM.
This value now can be anything between 0 and 7 in both architectures
since it depends on the value of x0.
This patch overall reduces a tiny bit the total range of [x0, x1) where
we run intermediate filters since the FilterPipeline now …
> Relax x0 % kPaddingXRound requirement in FilterPipeline

- .gitlab-ci.yml
We run build and tests in different jobs, but cmake requires the build
directory to not move. gitlab-runner recently started making the
checkout directory depend on the job number, which changes between
stages. Each runner only runs one job at a time in one Pod so having
different build directories is not needed. Setting the GIT_CLONE_PATH
to a fixed value will make all the stages build/test from the same
directory path.
> Set custom GIT_CLONE_PATH to a fixed path.

- lib/jxl/base/compiler_specific.h
- lib/jxl/color_encoding_internal.cc
- lib/jxl/color_management.cc
- lib/jxl/common.h
When reading a gamma value, the largest value (1e7) overflow uint32_t
when multiplying by 8192, which would reject some specific but valid
values of gamma. This patch fixes that check and also silences the
unsigned-integer-overflow for a few functions that intentionally do
that.
> Fix and silence some unsigned integer overflow.

- lib/jxl/enc_photon_noise_test.cc
This does not rely on the tuple-matching version of `FloatNear` anymore.
> Fix `enc_photon_noise_test` with older versions of GoogleTest

- lib/include/jxl/decode.h
The JPEG functions were in-between the function go get size
of image buffer, and set the image buffer, making the header
harder to read
> Minor cleanup: function order in header

- ci.sh
- tools/ossfuzz-build.sh
When running `./ci.sh ossfuzz_msan ARGS` this patch now passes the extra
ARGS to the ninja command inside the docker run. This allows to rebuild
only djxl_fuzzer for example, without having to rebuild all the fuzzer
targets.
> Pass ossfuzz_msan args to the ninja command

- CMakeLists.txt
The project() cmake command defines the ${project_name}_VERSION variable
with the value passed in the VERSION parameter to this command. We are
currently not setting the VERSION parameter so this was defining
JPEGXL_VERSION as the empty string. Independent to this we where using
the JPEGXL_VERSION cmake variable to let integrators define a project
version to include in the tools (like the package version) which was not
working since cmake would override its value.
This patch renames the project() name to LIBJXL to workaround this
issue. We should eventually set up the version numbers in the project()
as well.
> Update cmake project() name

- lib/jxl/enc_ac_strategy.cc
- lib/jxl/enc_adaptive_quantization.cc
This reduces ringing by a very small amount. Also improves other quality
metrics (0.01 % BPP*pnorm win, i.e., by even less than impact on ringing).
This works by reducing a stabilization epsilon in converting visual
masking data from adaptive quantization into use by ac strategy
computation. The stabilization epsilon affects the balance of integral
transform, so that is compensated for in the respective constants.
A lower stabilization epsilon increases the importance of a fully flat area
in integral transform split, and makes it more likely not to be
connected with a block containing high visual activity.
Before:
```
Method               Pixels     Size              BPP   #    MP/s    MP/s     Distance …
```
> less ringing

- lib/jxl/aux_out.h
- lib/jxl/enc_ac_strategy.cc
- tools/benchmark/benchmark_stats.cc
- tools/benchmark/benchmark_stats.h
- tools/benchmark/benchmark_xl.cc
Cleanup the output of `benchmark_xl` a bit, to make it more compact (making it easier to share results in places with limited horizontal space - like here), and to show counts for 32x64 and 64x64 block selection while keeping counts for small blocks (2x2 and 4x4 are counted in the same column, and also Hornuss/'Idendity'). The two-line column labels have also been replaced by single line ones, and the `#` column (which was supposed to show number of threads, but wasn't actually doing that) has been dropped. Precision of some numbers has been reduced a bit where it made sense, and block selection is now in percentages.
Before: (output layout only, the numbers themselves are different just because that's an old version I had available)
```
i0aq8ybkquh41.png
Compr              Input    Compr …
```
> improve benchmark_xl output a bit

- examples/jxlinfo.c
- lib/include/jxl/codestream_header.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
- tools/conformance/djxl_conformance.cc
Fix name mismatch in the API. These are corresponding fields and
it was a historical error that they appeared independently with
a different name.
Also add to the comments that they match that of the main alpha
extra channel.
This renames a field in the API, but I believe that because the API
did not yet support outputting extra channels, usage of this field
should be extremely rare.
> Fix name mismatch "associated" and "premultiplied"

- .gitlab-ci.yml
- CMakeLists.txt
- lib/jxl_benchmark.cmake
This sets Threads::Threads to use -Wl,--whole-archive for -lpthread when
compiling with JPEGXL_STATIC=1 since otherwise weak symbols in libstdc++
would not be resolved to pthread's library. This is more of a workaround
for compiling static binaries. The fix modifies the link libraries
properties of Threads::Threads.
Also fixes the -lrt flag in benchmark::benchmark making the benchmark
also compile in static mode when JPEGXL_STATIC=1. There are no changes
to the build when JPEGXL_STATIC=0.
Fixes #332.
> Fix Threads::Threads definition when JPEGXL_STATIC=1

- lib/extras/codec_jpg.cc
Small cleanup since MEMORY_SANITIZER is not set in the ossfuzz builds.
> Use msan::UnpoisonMemory in codec_jpg

- .github/workflows/build_test.yml
- plugins/gdk-pixbuf/CMakeLists.txt
- plugins/gdk-pixbuf/loaders_test.cache
- plugins/gdk-pixbuf/pixbufloader-jxl.c
- plugins/gdk-pixbuf/pixbufloader_test.cc
The pixbufloader-jxl was not destroying the decoder object after
decoding and therefore leaking memory. This patch fixes that by adding
the missing call to `JxlDecoderDestroy`.
A new test will try to load a .jxl file from disk using the
pixbufloader-jxl plugin. This would detect leaks when running in asan
mode.
A drive by fix, the pixbufloader doesn't need the full library, only the
decoder side.
Fixes #299
> Fix pixbufloader-jxl and add a test

- lib/jxl/dec_external_image.cc
The new `ConvertChannelsToExternal` uses a list of channels (ImageF*)
instead of repeating the logic of deciding which channels to include
in every lambda. This should make it easier to include a function to
convert extra channels.
> Refactor ConvertToExternal to use an array of ImageF*

- lib/jxl/modular/transform/squeeze.cc
See also https://github.com/libjxl/libjxl/pull/323
The Modular Squeeze transform, with custom parameters, can do weird things, some of which can lead to trouble.
Squeeze can be applied to metachannels (i.e. palettes), which is fine, except for two things:
-  if it leads to the channel list becoming of the form `[meta channels]* [normal channels]* [meta channels]*`, that violates the implicit invariant that everything starting with `nb_meta_channels` are not meta channels. If that implicit invariant does not hold, there can be channels that never get decoded, leading to uninitialized memory getting read.
- it should update the `nb_meta_channels` counter because effectively the squeeze residuals of a meta channel should also be considered to be a meta channel.
The way to avoid trouble that …
> fuzz / bitstream bug: squeezing meta channnels

- lib/jxl/butteraugli/butteraugli.cc
- lib/jxl/jxl_test.cc
- lib/jxl/passes_test.cc
This may improve butteraugli's behaviour in neural compression.
Here, reflected on jpeg xl's butteraugli implementation. Manual review
shows little changes in quality, possibly some less ringing at very high
distances such as d24, reviewed at effort 9.
Before:
```
Encoding           kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm   PSNR   QABPP  SmallB  DCT4x8     AFV  DCT8x8    8x16    8x32      16   16x32      32   32x64      64       BPP*pnorm   Bugs
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
jxl:9:d0.8:epf0      18628  4039653    1.7348526   0.161  15.096   1.07709587   0.50579125  41.95 …
```
> Butteraugli changes for less visual masking

- lib/jxl/dec_frame.cc
- lib/jxl/dec_modular.cc
- lib/jxl/dec_modular.h
- lib/jxl/modular/transform/rct.h
- lib/jxl/modular/transform/transform.cc
In cases where there are no global modular transforms except RCT (as is the case at speed falcon and faster), avoid the unnecessary copy from decoded groups to the modular `full_image` (and then to the float `decoded`).
For `-m -e 2`:
Before:
4064 x 2704, geomean: 47.20 MP/s [38.94, 49.02], 30 reps, 4 threads.
Allocations: 21465 (max bytes in use: 4.360149E+08)
After:
4064 x 2704, geomean: 57.45 MP/s [46.70, 59.76], 30 reps, 4 threads.
Allocations: 21465 (max bytes in use: 3.020612E+08)
> avoid full modular image copy

- lib/jxl/decode_test.cc
For resizeable_runner wrong runner function was used.
NB: why this fires only on osx build?
> Fix decode_test

- lib/include/jxl/decode.h
- lib/include/jxl/types.h
- lib/jxl/dec_external_image.cc
- lib/jxl/dec_external_image.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
- tools/djxl_fuzzer.cc
Allows outputting extra channels to individual single-channel buffers,
similar to the main image output
Adds two new functions to the API: JxlDecoderExtraChannelBufferSize
and JxlDecoderSetExtraChannelBuffer
> Support extra channel output

- .github/workflows/build_test.yml
- tools/build_stats.py
Ideally we would enforce a smaller static size limit but at the moment
there are a few functions that require more than 1 kB of static stack.
> Limit the static stack size of all functions in release mode to 3 kB

- lib/jxl/image_ops_test.cc
This is just to check that the result was properly copied when using
CopyImageToWithPaddingTest().
> Add unittest for CopyImageToWithPaddingTest.

- tools/djxl_fuzzer.cc
SetSupportedTargetsForTest() expects a target mask, not an index in the
targets array.
> Fix setting the SIMD target in the djxl_fuzzer.

- lib/jxl/sanitizers.h
The compute x value is relative to the `row + r.x0()` pointer, so we
need to add back x0 when printing it.
> Fix error message in msan::CheckImageInitialized()

- lib/jxl/image_ops_test.cc
CopyImageToWithPadding only checks for the boundaries on the first image
(the source image). This fixes the test case so it doesn't hit the
JXL_DASSERT.
> Fix new CopyImageToWithPaddingTest.

- lib/jxl/dec_modular.cc
- lib/jxl/dec_reconstruct.cc
- lib/jxl/dec_upsample.cc
When using an upsampling factor > 1 for extra channels with an odd size
(or not a multiple of the upsampling factor) we need to round up the
Rect copied in ModularImageToDecodedRect().
This fixes an msan bug where some pixels near the right or bottom edge
can be uninitialized.
Added more msan checks to the extra channels to fail faster on this type
of errors.
> Fuzz: Fix Rect rounding error decoding extra channels.

- lib/jxl/dec_modular.cc
CopyImageTo() has JXL_DASSERT() to check for the boundaries of the image
and the passed rects, so size mismatch errors trigger more reliably in
debug builds.
> Use CopyImageTo() instead of loop in dec_modular

- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/jxl_test.cc
- tools/optimizer/simplex_fork.py
jyrki31-split:
0.4 % BPP*pnorm improvement at d0.8, 0.35 % at d1
1 % improvement in Max norm
jpeg-xl a-d corpus:
0.6 % improvement at d0.8
Improvement diminishes at higher distances
Improvement diminishes at higher distances.
Inspired by a problem reported by Lee on discord, will likely not fix it fully but may be a step in the right direction.
Manual viewing suggests that this is an improvement, particularly when there are red, blue or magenta backgrounds, and that the new heuristics are slightly more balanced overall.
*jyrki31-split corpus*
```
Before:
Encoding         kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm   PSNR   QABPP  SmallB  DCT4x8     AFV  DCT8x8    8x16    8x32      16   16x32      32   32x64      64       BPP*pnorm   Bugs …
```
> More bits for red and blue areas

- CMakeLists.txt
Completely static build would require building stdlib.
```bash
$ otool -L bin/*
bin/cjxl:
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
bin/djxl:
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
```
> Enaable mostly-static build on OSX.

- lib/jxl/dec_modular.cc
Some fixes to the case where the full modular image is skipped:
- don't assume that everything happens at the modular AC group level (`minShift==0`), there can also be upsampling causing channels to have nonzero shift even when there's no Squeeze
- for partial decodes (when `zerofill` is true), don't try to fill the full image when it's not used. Instead initialize the decoded image with zeroes and skip the decoding.
> fix use_full_image==false case

- lib/jxl/modular/transform/squeeze.cc
MetaSqueeze() started updating the nb_meta_channels value in #331, but
we also need to update the value back when applying the transform. This
was leading to the transforms getting out of sync with when
meta-applying versus inverse applying them later.
> Fuzz: Update the nb_meta_channels in squeeze when applying.

- lib/jxl/adaptive_reconstruction_test.cc
- lib/jxl/dec_cache.h
- lib/jxl/dec_frame.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/filters.cc
- lib/jxl/filters.h
- tools/epf.cc
Spec says that the coefficients of the kernel used in Gaborish are
normalized to sum 1, but if the sum is already near 0 this is undefined.
This patch catches that case and returns a JXL_FAILURE instead of
creating NaNs or infs in the output.
> Fuzz: Return error if Gaborish weights lead to invalid kernel.

- bash_test.sh
- lib/extras/codec_pgx.cc
- lib/extras/codec_png.cc
- lib/extras/codec_pnm.cc
%n is error prone and some environments start to complain about its
usage. Remove %n usage and add a check to avoid re-introducing it.
Tested that `cjxl third_party/sjpeg/tests/testdata/test_exif_xmp.png`
still parses the metadata correctly.
> Remove usage of %n.

- lib/jxl/quant_weights.cc
The checks for 0 should use an almost zero value to prevent divide by
zero errors.
> Fuzz: Prevent divide by zero in Interpolate.

- lib/jxl/modular/transform/squeeze.cc
squeeze in_place transforms use the residual channels from right after
the squeeze transform range, but that might be out of bounds if the
endc channel is near the end of the list. This patch checks for the
channel number before accessing it.
> Fuzz: Fix out of bounds access in squeeze channels

- tools/cjxl.cc
Not sure why I originally wrote 0. It likely doesn’t warrant it.
> Adjust the visibility of the `photon_noise` parameter

- lib/jxl/modular/transform/palette.h
- lib/jxl/modular/transform/transform.cc
Fuzzing hasn't found a problem case yet afaik, but in the palette transform there was a similar problem as in https://github.com/libjxl/libjxl/pull/370 : the nb_meta_channels counter was not properly decremented in the inverse transform.
Also now checking for doing transforms on an invalid mix of meta/nonmeta channels in CheckEqualChannels(), so it will also cause RCT to fail when tried to be applied to a mix of meta and nonmeta channels.
> fix modular nb_meta_channels counter

- lib/jxl/modular/transform/palette.h
Made a braino in the original assert here: the assert talks about the situation _after_ the inverse transform (checking that it is indeed a case where all affected channels were metachannels), so it has to use the updated `nb_meta_channels` and `begin_c` instead of `c0`.
> fuzz: fix assert in the exotic case of doing palette on palettes

- lib/jxl/dec_modular.cc
- lib/jxl/dec_modular.h
When a modular dc or ac group is empty, a 0-channel image gets decoded, and in the old flow that just meant that all of those 0 channels would get copied to the modular full_image.
In the new flow however (where full_image is avoided), it created trouble because a 0-channel image would still cause a call to ModularImageToDecodedRect(), which would then try to access non-existing channels.
Returning early when a 0-channel group image is about to get decoded solves that.
Still adding an assert to check for access to non-existing channels.
~~There could still be a remaining bug that can arise when a modular group e.g. contains data for some extrachannels but not for others (because they have a different dim_shift / upsampling factor). I haven't seen a fuzzcase for that yet, but it is …
> fuzz: return early when there is no modular data to decode

- tools/benchmark/benchmark_xl.cc
This can be convenient when comparing multiple benchmark reports
together. Before, it only showed the bpp, now also the butteraugli
scores.
> Add pnorm&maxdist to benchmark html report tooltip

- AUTHORS
- lib/jxl/splines.cc
This seems to be the preferred approach discussed in https://github.com/libjxl/libjxl/issues/129
(Name added to AUTHORS as per contributing checklist.)
> Splines: skip DrawGaussian when sigma is 0, prevents possible divide-by-zero

- lib/jxl/blending.cc
- lib/jxl/blending.h
- lib/jxl/splines.cc
When copying the background to the output in PrepareBlending, we now leave a hole where the foreground will be, in case it is in fact already there.
> Allow blending to work when the output is the foreground

- plugins/gdk-pixbuf/CMakeLists.txt
The gdk-pixbuf plugin only uses public API so it can be built against
the shared library.
Tested with: `./ci.sh test -R pixbuf`
> plugins/gdk-pixbuf: Link against the shared lib

- .gitmodules
- tools/benchmark/metrics/prepare_metrics.sh
The projects are now cloned when running prepare_metrics.sh, as they
were only used for running the metrics.
> Remove unnecessary submodules.

- plugins/gdk-pixbuf/CMakeLists.txt
We don't install the decoder shared library, only the full shared
library. We can't install both libraries since they share many symbols
and programs won't be able to link against both (either directly or
transitively).
Fixes #399.
> plugins/gdk-pixbuf: Use the shared full library.

- .github/workflows/pull_request.yml
- ci.sh
clang-format evolved over time and different versions don't exactly
agree on certain formatting, so we accept any formatting as valid. This
patch includes versions 10 and 11 to the list.
> Add clang-format 10 and 11 to the allowed list.

- tools/jni/org/jpeg/jpegxl/wrapper/DecoderTest.java
This allows compiling DecodeTest on JDK7 (and earlier).
> Avoid using java.util.Base64 introduced in 1.8

- lib/jxl/enc_adaptive_quantization.cc
The code before causes inf's to appear in the masking field, leading to
confusion and debug asserts to fail. Adding a small bias to both sides
of a / b to converge to 1.0 instead of inf for small values.
Before:
```
Encoding         kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm   PSNR   QABPP  SmallB  DCT4x8     AFV  DCT8x8    8x16    8x32      16   16x32      32   32x64      64       BPP*pnorm   Bugs
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
jxl:d0.8:epf0      29551  6554567    1.7744017   2.296  24.016   3.15145683   0.56864224  40.40   2.643  0.8420 19.9916  1.0484  5.4701 21.4274  0.0000 …
```
> Fix for division by zero in masking

- .github/workflows/release.yaml
Release binaries include the Debian packages for Ubuntu 18.04 and 20.04
and static linux binaries for x86_64.
The binaries are built from main and the release branches whenever a
new commit is pushed there, and the artifacts are automatically attached
to releases in GitHub when a release is created.
> Build release binaries on post-submit

- ci.sh
- tools/CMakeLists.txt
- tools/codec_config.cc
- tools/git_version.cmake
- tools/tool_version.cc
- tools/tool_version.h
This sets the JPEGXL_VERSION macro used in the tools from the short git
hash at build time, updating it only when needed to avoid rebuilding
every time. Unfortunately, ninja checks for the header timestamp before
running the target that generates it so when only updating the hash, the
tool_version.cc.o file is not regenerated. This doesn't affect make, or
when running `ci.sh release` or similar commands.
GitHub/GitLab builders use the hash of the built reference, so this code
doesn't run in the workflow/pipelines anyway.
Tested with:
- `./ci.sh release`
- `./ci.sh release -DJPEGXL_VERSION="foo bar"`
- `mkdir build; cd build; cmake ..`
Test rebuilt after amending a commit.
> Set JPEGXL_VERSION macro from git hash at build time.

- tools/CMakeLists.txt
INCLUDE_DIRECTORIES was not a Source File property in cmake 3.10, which
is the minimum we support and what ships with Ubuntu 18.04. This sets
the include directory on the library instead.
> Fix Ubuntu-18.04 build with git version.

- .github/workflows/release.yaml
In order to keep the tools as executable files upload a single .tar.gz
file instead of letting GitHub group them as a .zip file.
> Make linux-static artifact a .tar.gz

- .github/workflows/release.yaml
- lib/profiler/tsc_timer.h
This patch creates the static builds for Windows 32 and 64 bits from
main and attaches them to releases. The build uses vcpkg for
dependencies and the default msvc compiler from the GitHub image.
> Add msvc+vcpkg windows release builds

- lib/jxl/common.h
- lib/jxl/dec_upsample.cc
- lib/jxl/modular/encoding/context_predict.h
- lib/jxl/modular/encoding/dec_ma.cc
- lib/threads/thread_parallel_runner_internal.cc
All of these are harmless, but evaluating and silencing them makes it
easier to spot ones that can be problematic.
> Silence some unsigned-integer-overflow warnings

- lib/jxl.cmake
In the lcms2 case, the static library libjxl.a installed depends on
lcms2 symbols so linking the final application against lcms2 is
required.
> Include lcms2 in the .pc when building against lcms2

- lib/jxl_extras.cmake
We use `DGifCloseFile` which in version 5.1 got an extra parameter
`int *ErrorCode` not present in 5.0. This means that we need at least
version 5.1 to compile.
Fixes #420
> Bump GIF requirement to version 5.1

- CMakeLists.txt
- lib/jxl_extras.cmake
- third_party/lcms2.cmake
- third_party/lodepng.cmake
- third_party/skcms.cmake
- tools/CMakeLists.txt
- tools/box/CMakeLists.txt
New `JPEGXL_ENABLE_TOOLS` flags (default enabled) lets the user disable
cjxl/djxl tools and the new `JPEGXL_ENABLE_JNI` lets the user disable
building the JNI wrappers.
A few intermediate libraries that should  be only compiled if the tools
that need them are also compiled are now marked as EXCLUDE_FROM_ALL.
This allows user to only compile the jxl libraries.
Fixes #421
> New CMake flags to disable cjxl/djxl and JNI

- lib/jxl/decode.cc
ConvertImageInternal Used to have a much larger implementation and
be specific to the RGB output case, the assert then made sense.
Now ConvertImageInternal is a small wrapper around ConvertImageExternal
and is used for much more than just RGB: also preview image and extra channels.
The assert was checking that when calling this function, the slow code
path of the decoder (without internal RGB buffer) was being taken. However
now that this function is also used for preview image and extra channels,
such check does not belong here.
The cases where this function is used in the RGB context already have
a clear `HasRGBBuffer` if condition, so the assert does not need to
be moved there, it can just be removed.
This fixes a fuzzer-found DASSERT issue.
> Remove ConvertImageInternal HasRGBBuffer assert

- .github/workflows/release.yaml
The "ubuntu-18.04" GitHub environment is not exactly the same as
upstream's 18.04 from Ubuntu. In particular, the built libjxl .deb
package gets a dependency on libgcc-s1 which is not available in
Ubuntu 18.04.
This patch builds the Debian packages using upstream's Docker container
instead. This also allows to build for other Debian-based environments
not otherwise available in GitHub, such as debian:buster and
debian:bullseye which are now added to the list.
> Build .deb packages inside a Docker container

- .github/workflows/release.yaml
To provide .deb packages with increasing versions from main, this patch
updates the version on the package being built to include a suffix
with the date.
> Stamp .deb packages with the commit date.

- debian/rules
When running the cjxl/djxl tools we include two versions, the library
semantic version numbers (MAJOR.MINOR.PATCH) as reported by the library
and an arbitrary string that comes from the package. The arbitrary
string is normally the git hash or other version or build information.
For the Debian packages this now includes the Debian package version
string.
> Include Debian package version in the tool

- lib/jxl/modular/encoding/enc_ma.cc
Creating a geometric distribution with fraction 0 causes divisions by 0
and invalid float-to-int conversions. Fixed #409.
(cherry picked from commit f99f3395c197b00726dc1c1d4a64d81d9f704c9c, PR #410)
> Cherry-pick “Avoid UB in enc_ma.cc.” in 0.5.x

- CMakeLists.txt
- lib/jxl.cmake
- lib/jxl/enc_color_management.cc
- lib/jxl/enc_jxl_skcms.h
- lib/lib.gni
- third_party/skcms.cmake
skcms is only a single .cc file with a C API, but not widely available
as a standalone package or library. We currently require to use a CMS in
the encoder side of the library to convert from arbitrary color spaces
when encoding, among probably other things. The user can select from
either skcms (the default) or lcms2 for the CMS library. In the skcms
case libjxl.so was bundling the libskcms.a symbols (since skcms is built
as a static library) but libjxl.a wasn't, resulting in an unusable
static library being packaged and installed.
This patch adds a default-on setting to bundle skcms.cc into libjxl.a
when using skcms, however, we rename all the function from `skcms_` to
`jxl_skcms_` to avoid issues with potential projects that would
include skcms from elsewhere. Until there's a packaged …
> CMake setting to bundle libskcms.a into libjxl.a

- tools/benchmark/benchmark_stats.cc
- tools/benchmark/benchmark_stats.h
- tools/benchmark/benchmark_xl.cc
- tools/benchmark/metrics/prepare_metrics.sh
- tools/benchmark/metrics/vmaf.sh
Example output:
```
luca@desktop ~/libjxl/build extra_metrics_columns $ ninja tools/benchmark_xl && ./tools/benchmark_xl --codec jxl,jxl:d2,jxl:d4,jxl:d6,jxl:d8 --input "/data/jpeg_xl_data/jyrki31/*.png" --extra_metrics SSIMULACRA:../tools/benchmark/metrics/ssimulacra.sh 2>/dev/null
Encoding      kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs  SSIMULACRA
------------------------------------------------------------------------------------------------------------------------
jxl             13270  2682333    1.6170262   3.525  24.327   1.79344261   0.62184480  1.005539343779      0      0.0181
jxl:d2          13270  1693780    1.0210838   3.653  26.097   3.12266779   0.98560314  1.006383363499      0      0.0302
jxl:d4          13270  1020994 …
```
> Add columns with aggregate stats when using --extra_metrics.

- lib/jxl.cmake
- third_party/skcms.cmake
When bundling skcms into libjxl.a we want to include the object files
with `$<TARGET_OBJECTS:lib>` which is only supported for OBJECT
libraries in older versions of cmake. This patch makes a new skcms-obj
library similar to what we do with jxl_dec-obj and jxl_enc-obj.
This fixes the build for debian:buster.
In MSVC, the flag to include a header is /FI, this patch splits that
case which fixes the MSVC windows build.
> Make skcms-obj an OBJECT library

- .github/workflows/build_test.yml
- CMakeLists.txt
- examples/CMakeLists.txt
- examples/examples.cmake
Creates a new examples/CMakeLists.txt example project importing libjxl
with pkg-config and building against both the shared and static
libraries.
Added a new test step to the "./ci.sh release" builder checking that the
installed library can be used by the example tools both in static builds
and regular builds using the shared libraries.
> Build example projects against the installed library.

- lib/jxl/enc_heuristics.cc
- lib/jxl/jxl_test.cc
Uses a 12x12 downsampling kernel instead of the 2x2 box kernel for the
case of downsampling factor of 2.
Resulting rescaled images look sharper, and ringing is reduced by clamping pixels to be withing the colors of a small region around them. This clamping reduces ringing but also makes the result less sharp looking that it could be in other regions. This can be fixed in future pull requests
This helps improve the quality of using the --resampling=2 option when
targetting low bitrates, such as 0.1bpp.
```
Encoding                kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm   PSNR   QABPP  SmallB  DCT4x8     AFV  DCT8x8    8x16    8x32      16   16x32      32   32x64      64       BPP*pnorm   Bugs …
```
> Implement sharper 2x2 downsampling kernel

- lib/jxl.cmake
We only use lcms/skcms on the encoder side for now.
> Remove lcms/skcms from libjxl_dec deps.

- lib/jxl/jxl_test.cc
https://github.com/libjxl/libjxl/pull/445 increases butteraugli for downsampling case (visually the images look sharper as intended)
That PR increased the allowed score for the high precision case but not the other case, causing the test to fail for non high precision
Fixing here.
> Fix non-high precision test after PR 445

- CMakeLists.txt
asciidoc in debian:10 and ubuntu:18.04 uses python2 as an interpreter.
This patch detects the python version requested from the shebang in a2x
and looks for that Python interpreter version.
> Fix manpage generation on debian:10 / ubuntu:18.04

- .github/workflows/release.yaml
Add sjpeg, skcms, highway and brotli since those are linked into the
static binaries. Also renamed LICENSE.jxl to LICENSE.libjxl to avoid
confusing it with an image.
> Add missing licenses to the vcpkg static builds

- tools/jxl_from_tree.cc
> `jxl_from_tree`: always initialize `quantization_adjustment`

- lib/jxl/enc_heuristics.cc
- lib/jxl/jxl_test.cc
The 2x2 downsampling with 12x12 kernel is followed by a ringing
reduction. This ringing reduction also makes the image less
sharp than it could be in places where there is no visible ringing.
This MR implements a selective ringing reduction, in more noisy
areas it's less reduced.
Pair programmed with Jyrki.
The images look sharper, as intended. The benchmark results don't
show this, it can be visually checked, when using the --resampling=2
option in the encoder.
There are also less "jaggies" in diagonal lines after this MR. The
borders around sharp boundaries, such as letters of text, look sharper
with some overshoot, but no multiple-pixel-distance ringing.
```
Encoding                kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm   PSNR   QABPP …
```
> Improve ringing reduction balance of 2x2 downsampling

- lib/jxl/enc_heuristics.cc
The value of mask_multiplier was set too high compared to the intended change,
the current value gives too much ringing, 2 works well and was the intended
value.
> Fix too high mask_multiplier

- lib/jxl/jxl_test.cc
The downsampling changes affect butteraugli distance and bit rates (in either direction), increase value to prevent test failing in non-high-precision mode
> Fix non-high-precision test

- lib/jxl/enc_heuristics.cc
- lib/jxl/jxl_test.cc
Add iterative downsampling algorithm (designed by Jyrki) in addition to the sharper downsampling with fixed 12x12 kernel, which optimizes the result per-pixel.
Ringing reduction is done with a mask after the optimization. Future MR's can perform ringing reduction, as well as take clamping into account, during the iterations.
The results have less jagged edges, less ringing artefacts and look sharper than the fixed 12x12 kernel.
Before:
```
Encoding                kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm   PSNR   QABPP  SmallB  DCT4x8     AFV  DCT8x8    8x16    8x32      16   16x32      32   32x64      64       BPP*pnorm   Bugs …
```
> Iterative downsampling algorithm

- lib/jxl/enc_frame.cc
- lib/jxl/enc_modular.cc
- lib/jxl/enc_patch_dictionary.cc
- lib/jxl/enc_patch_dictionary.h
Refactors the patch frame encoding into a separate function (preparing for https://github.com/libjxl/libjxl/pull/466).
Also fixes a regression in patch frame encoding that caused the modular quality of patch frames to be set incorrectly: it was basically always (almost) lossless. Setting it correctly gives considerable bpp*pnorm savings. The heuristic that would skip correct subtraction of decoded patches at d >= 3 has to be disabled, because with lossy patches it is important to subtract the decoded patches at all distances (otherwise pnorm suffers a lot).
Also fixes a bug in modular non-squeeze lossy. It magically doesn't change anything in the case of 3-channel images, because uint overflow would make the condition fail anyway, but for images with > 3 channels it would incorrectly make …
> refactor and fix patch frame encoding

- lib/jxl/jxl_test.cc
scalar and arm32 builds produced a sligthly bigger file. This fixes the
failures for scalar and arm32.
> Increase RoundtripResample2 threshold

- lib/extras/codec_pgx.cc
- lib/extras/codec_png.cc
- lib/extras/codec_pnm.cc
- lib/include/jxl/encode.h
- lib/jxl/decode_test.cc
- lib/jxl/enc_external_image.cc
- lib/jxl/enc_external_image.h
- lib/jxl/enc_external_image_gbench.cc
- lib/jxl/enc_external_image_test.cc
- lib/jxl/encode.cc
- lib/jxl/roundtrip_test.cc
- lib/jxl/test_utils.h
- tools/benchmark/benchmark_codec_avif.cc
- tools/benchmark/benchmark_codec_webp.cc
- tools/fuzzer_corpus.cc
A parameter to flag whether the input is float or not was added to  ConvertFromExternal() so it can differentiate between uint16 and float16 images.  Existing calls to ConvertFromExternal were modified.  Checks to reject float16 in the external API were removed.
> Add float16 support to public API

- lib/extras/codec_jpg.cc
See https://github.com/libjxl/libjxl/issues/468
Corrupt JPEGs and CMYK JPEGs cannot be losslessly recompressed to jxl.
Instead of just saying "failed to read", write a more useful error message in this case.
> print error when encountering non-recompressable (cmyk or corrupt) JPEG

- lib/jxl_extras.cmake
- lib/lib.gni
- tools/build_cleaner.py
This includes the non-optional parts of libjxl_extras to avoid
forgetting those files in the lib.gni build files.
> Add libjxl_extras to lib.gni and build_cleaner.py

- tools/cmdline.cc
- tools/cmdline.h
See #433. If for whatever reason you need things to work on filenames that start with a dash, you can now do `cjxl -q 80 -- -myweirdfile.png -myweirdoutputfile.jxl`.
> flag to stop parsing options, fixes #433

- plugins/gimp/CMakeLists.txt
- plugins/gimp/common.cc
- plugins/gimp/common.h
- plugins/gimp/file-jxl-load.cc
- plugins/gimp/file-jxl-load.h
- plugins/gimp/file-jxl-save.cc
- plugins/gimp/file-jxl-save.h
- plugins/gimp/file-jxl.cc
* Remove libjxl internals
* Use multi-threaded parallel runner
* Allow saving without requiring compiler flag
* Load multiple frames as layers
* Save non-linear uint8/16 and linear float16/32
* Save alpha channel in uint8/16 formats
* Add save options dialog
The following issues are resolved: #100, #229, #417, [wg1#234](https://gitlab.com/wg1/jpeg-xl/-/issues/234), [wg1#184](https://gitlab.com/wg1/jpeg-xl/-/issues/184).
> Update GIMP plugin to use public API and add save dialog

- plugins/gimp/file-jxl-save.cc
`!gimp_color_profile_is_gray` was converting the address of the function
to bool instead of calling it and then using the result. New compilers
actually have a warning for this.
> Fix build for GIMP plugin with new compilers

- plugins/gdk-pixbuf/pixbufloader-jxl.c
- plugins/gimp/file-jxl.cc
Signature pattern cannot contain \x00 as that gets misinterpreted as null-terminator, so use z mask designed to work around that issue.
Updates #505.
> plugins/gdk-pixbuf: fix signature

- plugins/gdk-pixbuf/CMakeLists.txt
- plugins/gdk-pixbuf/README.md
- plugins/gdk-pixbuf/loaders_test.cache
- plugins/gdk-pixbuf/pixbufloader-jxl.c
- third_party/skcms.cmake
The new version supports ICC profiles in the input JXL file, real
incremental loading and multithreading.
Pair programmed with Moritz.
Still TODO are animation and saving.
Fixes #512.
> Rewrite the GDK-Pixbuf plugin.

- lib/jxl/headers.cc
Silly little tweak in the encoding of SizeHeader: in some cases, even if the width is > 256, we can still use the shorter `small` encoding because the width can be derived from the height using the aspect ratio encoding.
This can save 1 byte for a 512x256 image.
> tweak size header encoding (512x256 can be 'small' too)

- lib/jxl/dec_modular.cc
- lib/jxl/modular/encoding/ma_common.h
As discussed in and fixes #528
The reduction applies to both the per-pixel limit and the overall limit, which means the maximum memory consumption of a frame's decode tree will be ~0.3MB (previously ~5.2GB).
> Modular decode: reduce tree size limit by a factor of 16

- tools/CMakeLists.txt
- tools/ossfuzz-build.sh
- tools/transforms_fuzzer.cc
It simulates internal modular decoder workflow:
* create "output" image
* meta-apply transforms
* simulate decode (fill "transformed" channels with data)
* undo transforms
Drive-by: fix indentation in `tools/CMakeLists.txt`
> Add transforms fuzzer.

- lib/jxl/modular/transform/palette.h
Simplifying divisions to shifts in the stock palette value generation. 
Before:
```
Encoding          kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
----------------------------------------------------------------------------------------------------------------
jxl:m               18628 20623382    8.8568318   0.426   3.572   0.00004654   0.00000021  0.000001818792      0
jxl:d0.7            18628  4455150    1.9132902   2.301  14.336   1.59264278   0.47658482  0.911845053323      0
jxl:m:q95           18628  6402674    2.7496657   1.106   4.778   1.14431751   0.35536362  0.977131162284      0
jxl:m:p7:lp:P7      18628  7127590    3.0609851   0.084   6.182   6.79819155   0.61806553  1.891889392155      0
jxl:m:p0:lp:P0      18628 11385144 …
```
> Simplifying stock palette indexing

- lib/jxl/jxl.version
We already set the default visibility of all symbols to hidden
(CXX_VISIBILITY_PRESET) so this is not necessary. Having this was
causing the type_info weak objects to be also local, meaning that
programs would return a different typeid() pointer for the same
object depending on where was the function called from (what .so). In
particular, the `JxlParallelRunner` function type was different between
libjxl (where it is called) and libjxl_threads (where functions are
defined) cause an asan failure with clang-7. This patch solves that
issue since the loader is able to match the (now global) weak typeinfo
symbols when loading these libraries.
> Stop marking all other symbols as local in the .version file

- lib/jxl.cmake
- lib/jxl/jxl.version
- third_party/skcms.cmake
hwy is always linked in statically (even when installed) and skcms is
sometimes bundled with libjxl.a, however functions from those libraries
shouldn't be exposed in the libjxl library. For hwy, we use
`-Wl,--exclude-libs=ALL` at link time, which would also work for skcms
but in the latter case we build it locally so there's no reason to also
mark it as hidden at build time.
The std:: namespace includes a lot of header-only functions that are not
always inlined (like template ones) and thus create weak symbols with
the functions. The std namespace is marked explicitly as default
visibility because those symbols should be exposed in shared libraries
when using std types in the library interface (functions or exceptions)
but our API is C only so we don't need them there. Removing the …
> Remove most other symbols from the shared library.

- .github/workflows/debug_ci.yml
Those pipelines will build a release, debug, asan, msan or opt build
when pushed to a branch ci-{release, debug, ...}-debug name, and then
start a tmate session in the resulting environment that can be used to
access the CI environment for debugging purposes.
> Add pipeline executions that allow ssh access.

- lib/jxl/enc_file.cc
- lib/jxl/enc_params.h
- tools/cjxl.cc
By default, let cjxl choose resampling=2 if requested distance >= 20
This also increases the allowed --distance given to cjxl to go up to 20,
previously it only was allowed up to 15.
For these bit rates, using the 2x2 resampling looks better on most
images.
The distance itself is lowered to 6 (and slightly more for higher
original distance), which roughly ends up at similar bit rate. This
depends on the image but is relatively close overall.
While there are lower distances where rescaling works better as well, it
depends on the image, 20 is a conservative choice.
This only implements it for the cjxl binary tool for now, not for the encoder
API (which doesn't yet support the resampling option; to be added soon)
nor for the benchmark.
To force using no resampling anyway, you can still use …
> Auto resample for high distance

- lib/jxl/dec_patch_dictionary.cc
Small but significant speedup on Android fd4: ~21.2 MP/s -> 21.7 MP/s.
> Avoid allocations when no patches are present.

- lib/extras/codec.cc
- lib/extras/codec_apng.cc
- lib/extras/codec_apng.h
- lib/extras/codec_exr.cc
- lib/extras/codec_exr.h
- lib/extras/codec_gif.cc
- lib/extras/codec_gif.h
- lib/extras/codec_jpg.cc
- lib/extras/codec_jpg.h
- lib/extras/codec_pgx.cc
- lib/extras/codec_pgx.h
- lib/extras/codec_png.cc
- lib/extras/codec_png.h
- lib/extras/codec_pnm.cc
- lib/extras/codec_pnm.h
- lib/extras/codec_psd.cc
- lib/extras/codec_psd.h
- lib/extras/codec_test.cc
- lib/extras/color_hints.cc
- lib/extras/color_hints.h
- lib/jxl/decode_test.cc
- lib/jxl/jxl_test.cc
- tools/benchmark/benchmark_codec_custom.cc
- tools/benchmark/benchmark_codec_jpeg.cc
- tools/benchmark/benchmark_codec_png.cc
- tools/benchmark/benchmark_xl.cc
- tools/butteraugli_main.cc
- tools/djxl.cc
- tools/fuzzer_corpus.cc
This is in line with the coding style and makes it harder to depend on
extras/ code accidentally. codec.cc code will be moved at a later point.
> Move most of extras/ code to its own namespace jxl::extras

- lib/extras/codec_pgx.cc
- lib/extras/codec_pgx.h
- lib/extras/codec_pgx_test.cc
- lib/extras/codec_test.cc
- lib/jxl_tests.cmake
These codec-specific tests should use the existing testing mechanism
which also allows to convert them to gtest instead of relying on
ASSERTs.
> Move PGX test-only code to new codec_pgx_test.cc

- CHANGELOG.md
- examples/encode_oneshot.cc
- lib/include/jxl/codestream_header.h
- lib/include/jxl/encode.h
- lib/jxl/decode.cc
- lib/jxl/encode.cc
- lib/jxl/encode_test.cc
- lib/jxl/test_utils.h
Addresses one of the issues reported in https://github.com/libjxl/libjxl/issues/513: the encode api was not doing anything with the orientation field.
Also had to explicitly initialize JxlBasicInfo when it is used for encoding, otherwise, with uninitialized values for orientation, it does random orientations or has the value set to something out of range.
(making it so that initializing orientation to zero, as you would get with the `{}` initialization, makes it do the identity transform; I suggest we do the same when in the future more optional fields are passed to the encoder, like max_nits: let's use the zero value as acting like a sensible default value)
> make encode api not ignore orientation field

- lib/jxl/base/cache_aligned.cc
- lib/jxl/base/file_io.h
- tools/cmdline.cc
See https://github.com/libjxl/libjxl/issues/542
This makes a positional argument `-` correspond to stdin or stdout (whichever makes sense). It works for `cjxl`; for `djxl` it works to take the jxl input from stdin, but you cannot decode stdout because the output codec selection is done based on filename extension. We could change that and add an option to explicitly choose an output codec, but then there's also the issue that djxl can produce multiple output files (in case of animation), which doesn't make much sense when outputting to stdout.
> make "cjxl - -" encode stdin to stdout

- .gitlab-ci.yml
This removes from the GitLab CI/CD the following workflows:
* all release builders (now available and published in GitHub)
* asan, msan and debug builders for x86_86
* armhf cross compiled targets
* merge_request workflows.
aarch64 cross-compiled targets are not yet completely migrated.
> Remove GitLab CI/CD workflows already migrated

- lib/extras/codec.cc
- lib/extras/codec_jpg.cc
- lib/extras/codec_jpg.h
- lib/jxl/decode_test.cc
- lib/jxl/jxl_test.cc
- tools/djxl.cc
- tools/fuzzer_corpus.cc
DecodeTarget was telling DecodeImageJPG whether we should load the pixel
or the JPEG coefficients. To load the JPEG coefficients we were actually
using the library internal API. Loading the coefficients is used for
pixel-lossless (but not byte-lossless) encoding of JPEG files. This is
not currently supported in the public API, but it would certainly be
a different workflow than loading the pixels (either we pass an image
with coefficient values or we pass the JPEG file like in lossless
recompression).
This patch splits out this workflow from DecodeImageJPG and
EncodeImageJPG so we can start migrating those functions to use the
external types.
> Remove JPEG's DecodeTarget parameter.

- .gitlab-ci.yml
asan/msan build were already removed.
> Remove GitLab asan/msan fast_benchmarks

- .github/workflows/build_test.yml
Fast benchmark is just a quick validation of the codec running on a
small set of images. This patch runs it whenever we run the tests.
> Run fast_benchmark on GitHub.

- third_party/CMakeLists.txt
The gdk pixbuf loader plugin depends directly on skcms, regardless of
whether libjxl uses lcms or skcms. This patch builds skcms when the
plugins are enabled.
Fixes #563
> Fix building gdk pixbuf plugin with lcms

- plugins/gdk-pixbuf/CMakeLists.txt
This will prevent potential runtime conflicts with other libraries that
also use skcms.
> Hide all symbols in the gdk-pixbuf plugin.

- plugins/gimp/CMakeLists.txt
Now that the plugin only uses the external libjxl API we can link
against the shared library. This reduces the binary size from 3.9 MB to
49 KB (both after stripping) which is important from a distribution
point of view.
> GIMP plugin: Link against the shared library.

- lib/jxl/color_encoding_internal.cc
- lib/jxl/decode_test.cc
This fixes issue https://github.com/libjxl/libjxl/issues/580
Getting the pixel data ICC profile after changing preferred color
encoding could return an earlier ICC profile instead.
The ColorEncoding was caching an older ICC Profile, call CreateICC at
the appropriate time to fix this.
> Fix stale cached ICC profile gotten

- third_party/sjpeg.cmake
sjpeg is bundled into the tools and not installed. This patch builds
sjpeg as a static library even if libjxl is built as a shared library.
> Always build sjpeg as a static library.

- .github/workflows/release.yaml
hwy uses gtest-dev, but the cmake project there depends on gmock-dev
which is not installed as a dependency. Install it manually so hwy
compiles.
> Fix debian:sid build in the pipeline.

- AUTHORS
- lib/jxl.cmake
In 63a481a, linker flag `-Wl,--exclude-libs=ALL` is added. However, LLVM LLD does not support it. Building with LLVM toolchain would result in failure.
This PR check whether the linker support this flag. If it does not, the flag will not be added. A not-so-pretty method with `CheckCSourceCompiles` is used, because CMake 3.10 does not support `CheckLinkerFlag` or `CMAKE_REQUIRED_LINK_OPTIONS`.
> Fix building with LLVM LLD: check "-Wl,--exclude-libs=ALL"

- lib/jxl/decode.cc
The xyb_encoded flag must be set on the transform data before parsing
This fixes the opsin_inverse case in issue https://github.com/libjxl/libjxl/issues/584
> Fix transform data parsing in API

- lib/jxl/base/file_io.h
Reading from regular files is simple because we can obtain the size of
the file first and then read the whole file to a buffer at once, but
when the input is given as a pipe (like in `cat file | cjxl - foo.jxl`)
the size is unknown. We had a special case for reading from "-" one byte
at a time, which is unnecessarily slow and didn't cover all cases.
This patch uses a list of 16 KiB chunks when reading from a file whose
size is unknown. This includes both stdin and named pipes.
Fixes #591
> Fix reading other than regular files in file_io.h

- plugins/gimp/file-jxl-save.cc
glib 2.61 and earlier versions didn't have the helper function
`g_clear_signal_handler` now used by the GIMP plugin. This makes it
compile for older distributions like Debian buster.
> Support compiling GIMP plugin with glib < 2.62

- examples/jxlinfo.c
This allows to see if it's a grayscale image
Also print something if a frame has no name or animation info, otherwise
the output ends with "frame:" with nothing after it
> Print num color channels in jxlinfo

- .github/workflows/build_test.yml
- lib/jxl/ans_test.cc
- lib/jxl/encode_test.cc
This patch runs the coverage build and reports the results to Codecov
(codecov.io). Right now this is only done on push to main or releases
because the runtime of the tests is a bit slow.
Updated two tests to improve on the runtime a bit.
> Run and report unittest coverage.

- lib/extras/codec_jpg.cc
When calling `cjxl` on e.g. a broken GIF or on an OpenEXR file, it will say it's a `Corrupt or CMYK JPEG`. This fixes that and only shows that error message when it's actually a JPEG.
> silently fail on non-JPEGs

- lib/include/jxl/codestream_header.h
JxlBasicInfo was defined both as a struct and as a typedef:
```
typedef struct JxlBasicInfo {
...
} JxlBasicInfo;
```
Like with all other types we do the typedef so `JxlBasicInfo` can be
used as a type directly in C, so naming the struct is not necesary and
actually causes the JxlBasicInfo name to have two different meanings.
> API: remove duplicated `JxlBasicInfo` definition.

- lib/jxl/modular/transform/enc_palette.cc
BEFORE:
tools/benchmark_xl --input='jyrki31/*.png' --codec=jxl:m:p0:lp:P0:9 --save_decompressed  --error_pnorm=1 
benchmark_xl v0.7.0 c4df527 [AVX2,SSE4,Scalar]
6 cores, 62 tasks, 6 threads, 0 inner threads
```
jxl:m:p0:lp:P0:9      16460  5362973    2.6065227   0.076   9.016   6.48264694   0.52997204  1.381384171235      0
Aggregate:            16460  5362973    2.6065227   0.076   9.016   6.48264694   0.52997204  1.381384171235      0
```
AFTER:
tools/benchmark_xl --input='jyrki31/*.png' --codec=jxl:m:p0:lp:P0:9 --save_decompressed  --error_pnorm=1 …
> Improve penalty heuristic for palette delta selection.

- .github/workflows/build_test.yml
- .readthedocs.yaml
- CMakeLists.txt
- doc/api.txt
- doc/sphinx/api.rst
- doc/sphinx/api_butteraugli.rst
- doc/sphinx/api_common.rst
- doc/sphinx/api_decoder.rst
- doc/sphinx/api_encoder.rst
- doc/sphinx/api_threads.rst
- doc/sphinx/conf.py
- doc/sphinx/index.rst
- doc/sphinx/requirements.txt
- lib/include/jxl/butteraugli.h
- lib/include/jxl/butteraugli_cxx.h
- lib/include/jxl/codestream_header.h
- lib/include/jxl/color_encoding.h
- lib/include/jxl/decode.h
- lib/include/jxl/decode_cxx.h
- lib/include/jxl/encode.h
- lib/include/jxl/encode_cxx.h
- lib/include/jxl/memory_manager.h
- lib/include/jxl/parallel_runner.h
- lib/include/jxl/resizable_parallel_runner.h
- lib/include/jxl/resizable_parallel_runner_cxx.h
- lib/include/jxl/thread_parallel_runner.h
- lib/include/jxl/thread_parallel_runner_cxx.h
- lib/include/jxl/types.h
This is first step to generate the library API documentation in HTML
format for publication in readthedocs.io. At the moment only the
reference documentation is included (functions, symbols, enums, etc and
their definition) but no other introductory documentation.
Split things a bit between encoder, decoder, common structs, butteraugli
and threads for easier navigation of the documentation.
HTML pages are not automatically build with cmake on local builds, but
can be triggered locally with `ninja -C rtd-html`.
PR pipelines now check that `rtd-html` builds without errors and
readthedocs.io automatically triggers a build of the documentation
whenever we push to main.
> Generate readthedocs.io sphinx documentation for the C API reference.

- README.md
Added code coverage and documentation links to the README, and a row of
badges for these and the GitHub builds.
> Add status badges and links to the README

- lib/extras/codec_gif.cc
Apparently there are GIF images like this one:
https://cdn.discordapp.com/attachments/804324493420920833/888295777821130792/patrick.gif
that have an out-of-bounds background color. The GIF spec doesn't say what should be done if that happens. I suppose it only makes a difference anyway if there is any visible background, which often isn't the case (since the frames have the same size as the canvas).
Instead of erroring out, we can just define the background color to be black in this case and call it a day. All the viewers that I tried don't make a fuss about it, so it's probably best if cjxl also doesn't.
> allow gif with out-of-bounds bg color

- lib/extras/codec_pnm.cc
- lib/jxl/codec_y4m_testonly.cc
- lib/jxl/codec_y4m_testonly.h
- lib/jxl/jxl_test.cc
- lib/jxl_tests.cmake
- lib/lib.gni
The external API currently doesn't support encoding subsampled YUV
frames, so we can't support this mode in cjxl. This patch moves the .y4m
parsing to another test-only file that is used by jxl_test.cc so we can
continue to run the roundtrip test (which upsamples the data). This
removes the possibility to encode .y4m images in the cjxl tool.
> Move .y4m parser to a test-only file.

- lib/jxl/modular/encoding/dec_ma.cc
Should fix a fuzzer-found integer overflow when a corrupt MA tree has a wildly out-of-range property value.
> fuzzer: integer overflow in MA decoding

- README.md
- doc/format_overview.md
Adding some documentation to give a high-level overview of JPEG XL: codestream and file format, basic design rationale, features , etc.
This is likely useful as a starting point for anyone new to the codec who wants to start using the libjxl API, understand what the codec can do, or start contributing to the project.
> add format overview documentation

- lib/jxl/color_encoding_internal.h
- lib/jxl/dec_ans.h
- lib/jxl/field_encodings.h
- lib/jxl/fields.cc
- lib/jxl/fields_test.cc
- lib/jxl/frame_header.h
- lib/jxl/headers.h
- lib/jxl/image_metadata.h
- lib/jxl/jpeg/jpeg_data.h
- lib/jxl/loop_filter.h
- lib/jxl/modular/encoding/context_predict.h
- lib/jxl/modular/encoding/encoding.h
- lib/jxl/modular/modular_image.cc
- lib/jxl/modular/transform/transform.h
- lib/jxl/quantizer.h
The const string returned by Name() ends up in the library and it is
only used in debug builds when Fields tracing is enabled. This patch
removes the Name() virtual method and replaces it with an empty string
in non-debug build so these strings don't end up in the library.
> Remove Fields::Name() strings from non-debug builds.

- lib/include/jxl/decode.h
- lib/jxl/decode.cc
The decoder should not reset the parallel runner when using rewind, only
when using reset.
Improved the way code between rewind and reset is shared.
In addition, changed the behavior of JxlDecoderSetParallelRunner to
match the documentation: the documentation says "may only set before
starting decoding", while the implementation instead allowed setting at
any time, but only once. Now it allows setting it before decoding, after
reset, and after rewind. It's not required to do so after rewind since
it keeps it now.
This addresses https://github.com/libjxl/libjxl/issues/624, by changing
the behavior rather than the documentation
> Keep parallel runner on decoder rewind

- lib/jxl/enc_modular.cc
- lib/jxl/enc_params.h
- lib/jxl/modular_test.cc
Currently the encoder always uses the default squeeze parameters.
This adds an encode option (only in cparams, not exposed in cjxl or api) to use custom squeeze parameters instead.
At the moment, it just does some random fixed custom squeeze, just for testing (improving code coverage a bit, checking that things roundtrip also with custom params). Perhaps at some point alternatives to the default squeeze params can be explored, e.g. to achieve better trade-offs between density and progressiveness.
> add custom squeeze encode option (just for testing atm)

- lib/jxl.cmake
- lib/jxl/enc_modular.cc
- lib/jxl/modular/encoding/context_predict.h
- lib/jxl/modular/encoding/enc_debug_tree.cc
- lib/jxl/modular/encoding/enc_debug_tree.h
- lib/jxl/modular/encoding/enc_encoding.cc
- lib/jxl/modular/encoding/enc_encoding.h
- lib/jxl/modular/options.h
- lib/lib.gni
- tools/jxl_from_tree.cc
PrintTree was duplicated in jxl_from_tree.cc, and some debug stuff that is only used in the encoder was in common files. This moves things around to make more sense.
> deduplicate PrintTree and move enc-only debug stuff to a new file

- lib/jxl/enc_external_image.cc
- lib/jxl/enc_external_image_test.cc
When de-interleaving a RGBA or GA image to an ImageBundle object that
doesn't have an alpha channel the code was crashing. This patch ignores
the alpha channel in that case. This should help with situations like
issue #513 where passing RGBX data to an RGB image.
> Allow passing alpha channel to an ImageBundle without alpha.

- lib/jxl/modular_test.cc
For some reason, the msan build created a file that is slightly larger, possibly because of different rounding in entropy coding heuristics.
> adjust threshold to make msan test pass

- lib/jxl/enc_modular.cc
- lib/jxl/enc_modular.h
- lib/jxl/modular/transform/palette.h
- lib/jxl/modular_test.cc
Currently, the predictor used for delta palette (`cjxl --lossy-palette`) is hardcoded to `Average4` (which is the one that works best). This changes that to use that one by default, but allows changing it by setting `-P`. The predictor used to encode the indices themselves is now hardcoded to `Zero`, which is the one that should work best.
Before: (the predictor choice affects how the indices are encoded, not the predictor used in delta-palette)
```
bees.png
Encoding          kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
----------------------------------------------------------------------------------------------------------------
jxl:m:lp:p0           114    37800    2.6398492   0.084   7.107   1.32610476   0.63799224  1.684203267014 …
```
> allow changing predictor used in delta palette

- lib/jxl/adaptive_reconstruction_test.cc
- lib/jxl/dec_frame.cc
- lib/jxl/dec_reconstruct.cc
- lib/jxl/dec_reconstruct.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
- lib/jxl/enc_adaptive_quantization.cc
- tools/epf.cc
There was still a bug in progressive decoding: extra channels would be moved from the dec_state at the first flush, causing segfault (unallocated buffer) at the next/final flush. That causes trouble e.g. in case of images with alpha.
Added tests for the cases of VarDCT + Modular alpha and lossless RGBA, to check that progressive decode works in these cases (no crashes), and do a crude check of the pixel values (check that most pixels are close to what they should be, i.e. there is an actual progressive preview and not just a black image).
> fix and (better) test progressive decode

- lib/extras/codec_jpg.cc
jpeg::DecodeImageJPG() can return an error after modifying the
CodecInOut on invalid JPEG files (or non-JPEG files). This causes codecs
running after the call to DecodeImageJPGCoefficients() to fail to decode
unless -j is passed to cjxl. This solves the issue at least for valid
JPEG files and files that not start with a JPEG header. File that look
like a JPEG might trigger an error but those shouldn't be parsed by any
other codec on the chain.
This is not an issue when calling jpeg::DecodeImageJPG() from the API
because the CodecInOut is not reused afterwards.
> Move the check for JPG files earlier.

- lib/jxl/image_bundle.cc
- lib/jxl/image_bundle.h
The specific depth channel is never used in our code and it won't be
different than any other extra channel so it doesn't need special
treatment.
> Remove unused ImageBundle::depth().

- lib/jxl/base/data_parallel.h
- lib/jxl/data_parallel_test.cc
The `class Divider` implemented a unsigned 32-bit division that
accelerated dividing by the same divisor multiple times. This could be
of use in a libjxl_threads implementation (and that's why it was in
data_parallel.h) but this would be out of the scope of libjxl and it
hasn't been used in a long a time.
> Remove unused jxl::Divider()

- lib/jxl/dec_modular.cc
- lib/jxl/enc_modular.cc
- lib/jxl/modular/encoding/encoding.cc
- lib/jxl/modular/encoding/encoding.h
- lib/jxl/modular/modular_image.cc
- lib/jxl/modular/modular_image.h
- tools/transforms_fuzzer.cc
There was some dead code in `modular_image.cc`:
- Back in FUIF days, it used to be useful to not undo all transforms, but that was because e.g. YCbCr and DCT were transforms too (remember, FUIF could also do lossless jpeg recompression, though it wasn't as good at it as jxl is now), so there were cases when you wanted to keep those. This option (`keep > 0`) has never been used in the jxl decoder though.
- undo_transform used to also clamp values to their valid range (`keep == 0`), but we never used that option either, since clamping is done elsewhere now (much later) and it is undesirable to do it too early.
- so that left only two options that were actually used: `keep == -1` (undo all transforms and don't clamp) and `keep == -2` (don't undo any transform). 
Cleaned things up a bit to …
> cleanup undo_transforms

- lib/jxl/jxl_test.cc
- lib/jxl/modular/transform/enc_squeeze.cc
- lib/jxl/modular/transform/squeeze.cc
The normal decode flow is:
- input image has N channels
- it does Squeeze with default (empty) parameters
- at header decode, MetaSqueeze is called which will fill in the Squeeze params with default values, to get O(N log N) channels
- after channel decode, InvSqueeze is called which undoes the Squeezes (it now has actual parameters, since MetaSqueeze replaced the empty params with default params)
So there is no reason to set default squeeze params in InvSqueeze — if the params are still empty at that point, it's a bug.
> do not set default squeeze params in InvSqueeze

- lib/jxl/dec_patch_dictionary.h
- lib/jxl/enc_detect_dots.h
- lib/jxl/enc_dot_dictionary.h
- lib/jxl/enc_patch_dictionary.h
Like the title says: remove things from dec_patch_dictionary.h that are only used in the encoder.
> move encode-only code out of dec_patch_dictionary.h

- lib/jxl/image.cc
There was a function in `image.cc` to compute the dot product of two images. I have no clue why we ever had that function in the first place, but it looks like nothing is using it.
> remove unused function in image.cc

- tools/ssimulacra.cc
- tools/ssimulacra.h
- tools/ssimulacra_main.cc
Adds an option `-s` to `ssimulacra_main` to skip the edge/grid penalties, so it's basically just L*a*b* MS-SSIM with pooling being a weighted sum of the mean error and the max error.
> add option for simplified ssimulacra

- lib/include/jxl/decode.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
The box based container format doesn't indicate which box is the last
(having an unbounded size last box is possible but not required), so the
decoder cannot know for sure when the file finished.
If there would be metadata boxes after codestream boxes, the decoder
could return JXL_DEC_SUCCESS when it decoded all codestream boxes and
the user input happened to end exactly at the last codestream box
boundary.
The API did not allow calling JxlDecoderProcessInput again after it
returned success, so it would be impossible to decode those further
metadata boxes.
This MR changes that by allowing to call JxlDecoderSetInput and then
process the further input again.
It will still give errors when calling JxlDecoderProcessInput without
setting any new input, and also when it's not the container …
> Allow setting more boxes after decoder finished

- lib/jxl/dec_modular.cc
Fixes https://github.com/libjxl/libjxl/issues/650
In the case where there's only a global RCT, there's an optimization that skips the global modular image and does the transform undo at the group level, directly copying decoded groups to the output buffer.
This optimization is only implemented for the full float output buffer case, not for the 8-bit output case or the pixel callback. This caused buggy behavior when the global transform was moved out of the global modular image, but `use_full_image` was still true.
> fix case where the global modular image is used after all

- ci.sh
No need to report coverage of the test files themselves.
> exclude more test stuff from coverage report

- ci.sh
The test-only files are called `*_testonly.*`, not `*_test-only.*`. So they weren't actually excluded from the report yet.
> silly typo in excluding test-only stuff

- lib/jxl/dec_frame.cc
- lib/jxl/dec_frame.h
- lib/jxl/dec_group.cc
In some cases (progressive rendering with a flush at an unfortunate moment), the allocations done in InitForAC() were not yet done when they are already expected to be done to be able to render partial images, causing segfault. I think this could happen when DC is available but ACGlobal not yet, or something like that. This fixes that.
In general, we probably need to revisit what is allocated where and by whom, because the current situation of `FrameDecoder.decoded_` and `PassesDecoderState.decoded` both being used is quite confusing and probably unnecessary.
> fix allocation not being done before use in some cases

- lib/jxl/enc_bit_writer.cc
- lib/jxl/enc_bit_writer.h
Isn't used and looks like we wanted to get rid of it, so cleaning it up.
> cleanup deprecated += in BitWriter

- lib/jxl/base/byte_order.h
- lib/jxl/dec_external_image.cc
- lib/jxl/enc_external_image.cc
We have code to handle (big-endian and little-endian) uint24 buffers. Nobody will use that — you can use 32-bit if you need more than 16-bit, but handling 24-bit data will be inconvenient for anyone and we will not have it in the api either (also now the code does what the documentation says it does: bits_per_sample has to be 8, 16 or 32.
> remove uint24

- lib/jxl/enc_modular.cc
- lib/jxl/modular_test.cc
In the case that the whole image fits in the GlobalModular section, the encoder wasn't trying different RCTs and different WP params, since that code was only being run for the ModularDC and ModularAC sections. This fixes that, which should lead to slightly denser lossless compression of images smaller than 256x256.
A side effect of this change seems to be that a test related to partial codestream boxes (`jxlp`) is now failing — likely that is unrelated to this change, so for now I have manually disabled those tests.
@lvandeve PTAL at the failing test (see the change in `decode_test.cc` in this PR). I tried finding the problem but I'm not familiar with the relevant code.
> try RCTs and custom WP also for single-group images

- lib/CMakeLists.txt
0.y.z version can have API/ABI changes during development but we should
mark those in the shared library SOVERSION. This uses MAJOR.MINOR for
major version 0, and just MAJOR for version after 1.0.
> Update SOVERSION to reflect v0.6 API/ABI changes.

- lib/extras/codec_exr.cc
- lib/extras/codec_jpg.cc
- lib/extras/codec_pgx.cc
- lib/extras/codec_png.cc
- lib/extras/codec_pnm.cc
- lib/jxl/enc_butteraugli_comparator.cc
- lib/jxl/enc_comparator.cc
- lib/jxl/enc_image_bundle.cc
- lib/jxl/enc_xyb.cc
- lib/jxl/image_bundle.h
- tools/benchmark/benchmark_codec_webp.cc
The `CopyToSRGB()` function (and the associated code in CopyTtoT to convert to uint8) in `image_bundle.h` / `enc_image_bundle.cc` was only used by the webp codec in `benchmark_xl`. Cleaning some things up to reduce code duplication and unnecessary clutter in the lib/jxl code.
> cleanup image_bundle and enc_image_bundle

- lib/jxl/dec_params.h
- tools/benchmark/benchmark_codec_jxl.cc
The comparison operators for dec_params were only used in one spot in benchmark_xl, no need to have that in libjxl itself.
> drop ==, != from dec_params.h

- lib/include/jxl/decode.h
- lib/jxl/decode.cc
- lib/jxl/decode_to_jpeg.h
This simplifies the box handling loop, so that it will be possible to
implement support for decoder output of metadata boxes, and handling the
metadata of reconstructed jpeg
> Simplify box handling in decode.cc

- tools/cpu/cpu.cc
According to the comment this include was used for
`__ppc_get_timebase_freq` at some point in this file but nowadays that
function is not there, so we can remove the include. Fixes #677.
> Remove sys/platform/ppc.h include.

- lib/jxl/enc_cache.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_modular.cc
- lib/jxl/enc_modular.h
Some small tweaks to the lossless jpeg recompression encoder choices:
- slightly adjust AC context model (use fewer contexts for smaller images)
- allow more effort to be spent on DC at -e 8, -e 9
- don't call ClusterGroups() at -e 9, it makes -e 9 extremely slow for little benefit
Tested on a corpus of the (large) CTC images + jyrki's testset (of mostly smaller images), converted to jpeg with imagemagick -quality 70 and 90. Times and sizes are totals for the whole set. Speed was not measured very accurately, but it gives an idea.
At q70:
| effort | size before | size after | time before | time after |
|-------|------------|-----------|----------|--------|
| e3 | 7,464,028 | 7,460,659  | 2.4s | 2.4s | 
| e7 | 7,460,245 | 7,456,938 | 2.5s | 2.5s |
| e8 | 7,449,599 | 7,434,265  | 4.0s | …
> tweaks to lossless jpeg recompression

- lib/jxl/enc_cache.cc
`true` is not the same thing as `false`, as I noticed minutes after merging https://github.com/libjxl/libjxl/pull/679
Sorry about that.
> silly copy/paste error

- lib/jxl/fields.cc
- lib/jxl/fields.h
I don't think we still need these — and if we do, it currently requires manually enabling printing by editing the code anyway, so you can just as well just fetch a version of `fields.*` from before this commit.
Not all the printed strings are detected by the compiler to be in unreachable code, so they did end up in the binary. So this is a (very minor) binary size improvement.
This instrumentation was useful when debugging the (quite complicated) header field mechanism with its various visitors, but I think it's safe to say that it now just works and we don't need the debug instrumentation anymore.
> remove debug printing instrumentation on header fields

- .github/workflows/release.yaml
svenstaro/upload-release-action is triggering connection issues when
uploading artifacts to releases and there's no fix for it. Migrate to
a different action for uploading artifacts to releases.
Added `fail-fast: false` to increase the likelihood that other workflows
in the matrix upload their artifacts when one fails so we can retry
less jobs.
(cherry picked from commit 4f3daf864e603d22d9b4303e1c735d9d2c54189b)
(cherry picked from PR #795)
> Migrate to AButler/upload-release-assets action. (#795)

- lib/include/jxl/decode.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
Adds a decode option to disable spot color rendering. This is needed for conformance testing, and is also useful for printing applications where the spot colors should be kept separate from the main image.
> expose decode option to disable spot color rendering

- CMakeLists.txt
asciidoc in debian:sid is now a bash script to force it to run with
python3. This breaks our workarounds for older versions. This patch
extends the workarounds to support the new case.
> Fix build with latest asciidoc

- AUTHORS
- lib/profiler/tsc_timer.h
Fixes compilation with llvm-mingw targeting Windows i686 (when building with `-DJPEGXL_ENABLE_PROFILER=ON`).
Here's a simple Dockerfile to reproduce this issue:
<details>
<summary>Dockerfile</summary>
```Dockerfile
FROM mstorsjo/llvm-mingw:latest
RUN apt-get update -qq && \
apt-get install -qqy --no-install-recommends git && \
apt-get clean -y && \
rm -rf /var/lib/apt/lists/*
WORKDIR /build
RUN git clone --depth 1 --recursive https://github.com/libjxl/libjxl.git
ENV \
CFLAGS="-O3 -fdata-sections -ffunction-sections" \
CXXFLAGS="-O3 -fdata-sections -ffunction-sections" \
LDFLAGS="-Wl,--gc-sections -Wl,-s"
WORKDIR /build/libjxl/build-i686
RUN cmake \
-DCMAKE_BUILD_TYPE=Release \
-DBUILD_TESTING=OFF \
-DJPEGXL_ENABLE_PROFILER=ON \
-DCMAKE_INSTALL_PREFIX="/packaging" \ …
```
> tsc_timer: sync with highway

- lib/include/jxl/encode.h
- lib/jxl/encode.cc
- lib/jxl/encode_test.cc
- plugins/gimp/file-jxl-save.cc
All options use the enum now.
The JxlEncoderOptionsSetLossless will be handled in a different MR,
since it's actually a combination of a modular, quality_pair and
color_transform option that still need to be added. The
JxlEncoderUseContainer option may also need some rework when
API to add boxes is added.
EDIT: also did this for the forgotten JxlEncoderOptionsSetDecodingSpeed option
> Use enum for encoder distance and effort options

- lib/include/jxl/encode.h
- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
- lib/jxl/encode_test.cc
Since this is a global codestream setting, this can't use the option
enum.
Also tuned related encoder settings:
-add comments to JxlEncoderOptionsSetInteger and related structs that
these settings apply only to frames, since this now confused myself,
trying to add the level and force_container settings to the enum while
those are global codestream settings
-added JxlEncoderSetCodestreamLevel to choose level 5 or level 10
compatibility
-changed JxlEncoderUseContainer to no longer be required, it only
forces the container when it is not needed. Using
JxlEncoderStoreJPEGMetadata or JxlEncoderSetCodestreamLevel will
automatically let the encoder emit the container format, it doesn't
require setting JxlEncoderUseContainer.
-added requirement for all of JxlEncoderUseContainer, …
> Add codestream level setting to encoder

- lib/jxl/dct-inl.h
- lib/jxl/dct_test.cc
- lib/jxl/dec_transforms-inl.h
- lib/jxl/enc_transforms-inl.h
ComputeScaled(I)DCT with ROWS == COLUMNS is identical.
> Remove ComputeTransposedScaled(I)DCT.

- tools/CMakeLists.txt
- tools/README.cjpeg_hdr.md
- tools/cjpeg_hdr.cc
- tools/cjxl.cc
Results are odd:
encoding: hbit = this code, 8bit = mozjpeg
decoding: hbddec = cjxl + djxl, .jpg = libjpeg-turbo
mae: mean average error
pae: peak average error
```
8bit_hbddec.png
0.6284970045
3-norm: 0.247564
8bit.jpg
0.6567226052
3-norm: 0.255915
hbit_hbddec.png
0.8870159388
3-norm: 0.370683
hbit.jpg
1.0059230328
3-norm: 0.396879
8bit_hbddec.png
mae 174.236 (0.00265868)
pae 1492 (0.0227665)
8bit.jpg
mae 168.05 (0.00256428)
pae 1409 (0.0215)
hbit_hbddec.png
mae 151.448 (0.00231095)
pae 1218 (0.0185855)
hbit.jpg
mae 173.705 (0.00265057)
pae 1197 (0.018265)
```
> WIP: attempts at more precise JPEG encoder.

- tools/djxl_fuzzer.cc
- tools/flicker_test/split_view.cc
- tools/flicker_test/split_view.h
tools/ that use only the public API break if we try to also use internal
API (base/random.h) since those are not exposed. This particular header
happened to work in most cases because it was mostly header-only, except
when JXL_DEBUG_ON_ERROR is enabled.
> Partially revert "Remove (almost) all uses of C++ distributions/RNGs."

- lib/include/jxl/encode.h
- lib/jxl/encode.cc
Add setting to the encoder to force modular or vardct mode, or use the
default (where in future implementations, encoder is allowed to e.g. use
heuristics on pixel content to choose this)
Also lets the SetDistance option set the quality_pair setting for
modular too. As dicussed with Jon, it's ok to translate distance to
a quality_pair value and expose only one setting in the API, rather than
expose the distance setting for vardct, and the quality pair setting for
modular, separately. The conversion formulas come from cjxl.cc and can
be tweaked if necessary.
Also alters the documentation of the SetLossless setting to specify what
this setting actually does as implemented, and do not be as strict in the
documentation which settings exactly this overrides since this can be
future …
> Add modular setting to encoder

- doc/release.md
it is only relevant for < 1.0
after 1.0 the SOVERSION there is only the MAJOR number
> release.md: reminder to mention API/ABI changes

- CHANGELOG.md
- examples/decode_exif_metadata.cc
- examples/decode_oneshot.cc
- lib/include/jxl/decode.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
- tools/djxl_fuzzer.cc
This adds a function to mark input explicitely as closed.
This is required to be used for correctness when box metadata
is gotten, because from streaming input it is not possible to
determine whether the current box is the last box, or the
current bytes of an unbounded last box are the final bytes.
Before, the decoder could return success when the user still
had more input (when requesting box content only), which is
not entirely straightforward.
It should also be used in general from this point on for
consistency, though for backwards compatibility with the
previous released decoder API versions, is not required
to be used when JXL_DEC_BOX is not used.
> Add JxlDecoderCloseInput to decoder API

- tools/jxl_from_tree.cc
jxl_from_tree wasn't initializing its `cparams` before use. That caused some weird behavior when some params got random values...
> initialize cparams

- lib/include/jxl/encode.h
- lib/jxl/encode.cc
Also added TODO's for the others that cjxl supports that need to be
supported through the API, some of which require more thought.
> Addes more missing options to the encoder API

- lib/jxl/dec_modular.cc
- lib/jxl/modular/encoding/encoding.cc
The global MA tree limit was computed without taking extra channels into account. Also added a hard cap of 1<<22 for global trees and 1<<20 for local ones.
> adjust MA tree size limits

- lib/include/jxl/encode.h
- lib/jxl/encode.cc
- lib/jxl/encode_test.cc
Also adds comment that the other noise setting is not recommended, since
the photon noise works better in practice
> Add photon noise setting to encoder API

- lib/jxl/dec_frame.cc
- lib/jxl/jpeg/jpeg_data.cc
See https://github.com/libjxl/libjxl/issues/346
This changes the behavior of `jbrd` so that if there are quantization tables that are not actually used (so the jxl codestream will not actually contain the values), it does not throw an error but it assumes that the unused table is exactly equal to the previous table. At encode time it checks if this is true, at decode time it is assumed that it is true.
The spec (18181-2) is a bit vague on this — it only says
> Qk are corresponding quantization factors from the codestream (see ISO/IEC 18181-1 / C.6.2)
but it's not really clarified/specified what exactly "corresponding" means here. We could clarify/extend the spec later, and specify what a decoder is supposed to do when there are no "corresponding" quantization factors.
Since there do seem …
> allow redundant quant table in jbrd

- lib/jxl/fake_parallel_runner_testonly.h
- lib/jxl/image_test_utils.h
Make functions defined in the headers static inline to avoid potential
ODR violations.
> Fix potential ODR violations

- lib/jxl/dec_reconstruct.cc
- lib/jxl/decode_test.cc
Adds upsampling to decode_test. ~~This test currently fails for uint8 output, due to an actual bug in that codepath. I haven't tried fixing the bug yet, but at least there's now an easy way to check if it is fixed :)~~
Fixes the upsampling bug in the uint8 codepath, thanks to @veluca93.
> add test for upsampling and fix uint8 upsampling bug

- lib/include/jxl/encode.h
- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
- lib/jxl/encode_test.cc
Adds the function JxlEncoderAddBox, which can be used either before or
after encoding image frames.
Updates the JxlEncoderUseContainer documentation to noet say
"force" after all since for metadata boxes you need to call it
explicitely (the encoder cannot know on its own if boxes will be added
at the end only)
Adds documentation about the box format and individual box types so that
it is clear what types of metadata boxes this function can be used for
and which ones the encoder automatically adds.
Pair programmed with Jyrki, who also proposed to add good documentation
about the boxes and a prototype test.
> Add API to encode boxes, header only (no implementation)

- .github/workflows/build_test.yml
- lib/gbench_main.cc
- lib/jxl/dec_reconstruct.cc
- lib/jxl/dec_reconstruct_gbench.cc
- lib/jxl_benchmark.cmake
- lib/lib.gni
Run gbench in the PR release pipeline to make sure it runs and doesn't
crash. In some distributions benchmark_main doesn't actually export a
main() symbol. Workaround the problem by defining our own main()
function for gbench.
This patch adds a new gbench test for benchmarking UndoXYB.
> Add gbench for UndoXYB and run it

- .github/workflows/build_test.yml
Install libbenchmark-dev libbenchmark-tools so the jxl_gbench is built
in all modes, not just release.
> Build gbench in all modes

- .github/workflows/build_test.yml
benchmark library (gbench) is not instrumented with msan so running the
binary in msan mode fails. This patch skips it in the main pipeline.
> Skip gbench on msan since it is not instrumented.

- lib/include/jxl/encode.h
- lib/jxl/encode.cc
Filling in the functions:
- `JxlEncoderInitExtraChannelInfo`
- `JxlEncoderSetExtraChannelInfo`
- `JxlEncoderSetExtraChannelName`
Pair with Lode
> encoder api: functions to handle extra channels

- AUTHORS
- lib/jxl/encode.cc
- lib/jxl/encode_test.cc
The encoder will no longer refuse AddImageFrame if the
color encoding is set to XYB via JxlBasicInfo, even if it
is not set directly.
> lib/jxl/encode.cc: add XYB fallback check to AddImageFrame

- lib/jxl/dec_frame.cc
It is created on ProcessAcGlobal and not expected to be removed.
NB: it might be possible to swap it with  fresh image instead of copying; but it might be dangerous, in case unshrink is required.
Fixes #842
> Copy pre_color_transform image instead of moving.

- lib/include/jxl/encode.h
Add two new functions for boxes to the encoder API, to require user to
indicate they plan to add metadata boxes, and close boxes.
The reason is: it is more efficient for the encoder, if it knows no more
boxes will follow, to output a final codestream box of unbounded size.
On the other hand, if the possibility exists that the user wants to add
a box after the final codestream box, the encoder will have to output a
box with size indicated in the header, so it must hold on to the entire
output before passing it to the user to be able to write the size in the
box header.
Without the use-boxes and close-boxes functions, the encoder would
always have to operate under the assumption a box after the codestream
could follow.
In theory it's possible to have only JxlEncoderCloseBoxes, but then the …
> Add use-boxes and close-boxes functions to encoder API

- lib/include/jxl/encode.h
- lib/jxl/encode.cc
Edited MR description after Jon's idea to keep JxlEncoderCloseInput:
Adds the separate JxlEncoderCloseFrames to close only frames.
JxlEncoderCloseInput now closes both frames and boxes.
The individual closing can also be necessary as it helps user declare
encoder can be more efficient e.g. if more frames will be added but no
more metadata boxes.
The combined JxlEncoderCloseInput is both backwards compatible and
convenient.
(Old description below:
Rename JxlEncoderCloseInput to JxlEncoderCloseFrames
This to distinguish it from CloseBoxes. The encoder needs to know
separately when each type of input ends, to allow to correctly generate
the correct box header for the final box. The CloseInput name is quite
confusing when it only closes frames and other input like boxes can
still be added. …
> Add JxlEncoderCloseFrames

- lib/jxl/dec_reconstruct.cc
- lib/jxl/dec_upsample.cc
- lib/jxl/enc_ac_strategy.cc
- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_ar_control_field.cc
- lib/jxl/enc_butteraugli_pnorm.cc
- lib/jxl/enc_chroma_from_luma.cc
- lib/jxl/enc_cluster.cc
- lib/jxl/enc_entropy_coder.cc
- lib/jxl/enc_fast_heuristics.cc
- lib/jxl/gauss_blur.cc
- lib/jxl/modular/encoding/enc_ma.cc
- lib/jxl/rational_polynomial_test.cc
- lib/jxl/splines.cc
- lib/jxl/transpose-inl.h
Instead use the newer overloads with the extra d arg required to
support SVE/RISC-V.
> Avoid deprecated Highway functions

- examples/jxlinfo.c
Fixes https://github.com/libjxl/libjxl/issues/859
In principle, jxlinfo could return an error when the file ends with a not-until-eof box, since then the decoder would keep asking for more input (since there might be more boxes after that one).
@lvandeve could you check that it's calling JxlDecoderCloseInput at the correct time?
> call JxlDecoderCloseInput and fclose in jxlinfo

- lib/jxl/enc_modular.cc
- lib/jxl/enc_patch_dictionary.cc
- lib/jxl/jxl_test.cc
Get rid of unnecessary clamping of patches.
Also fix rounding in enc_modular when converting from negative floats to ints.
Small density improvement for lossless, e.g. on this set of 9 screenshots:
Before:
```
jxl:m           42351  9372482    1.7704171   0.560   4.682   0.00007111   0.00000944  0.000016714712      0
```
After:
```
jxl:m           42351 …
```
> remove unnecessary patch clamping

- ci.sh
- lib/jxl/aux_out.cc
- lib/jxl/aux_out.h
No need to have files in the coverage report that only contain verbose debug printing functions.
Also remove an unused function from `aux_out.cc`.
> don't report coverage of debug-printing code

- lib/include/jxl/encode.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
- lib/jxl/encode_test.cc
- lib/jxl/roundtrip_test.cc
Various refactorings in the encoder to prepare for adding the
implementation of the add-boxes functions.
This also makes the encoder support jxlp boxes (partial codestream
boxes): it'll now add each frame in its own jxlp box, and possibly
an as early as possible jxlp box with the basic info, because it's
much simpler in the encoder to insert other boxes between frames when
using jxlp rather than a single jxlc. This is more efficient for the
decoder too since no more boxes with unbounded size are used.
Also made the decoder more strict about final jxlp being indicated:
experimenting with this new encoder feature showed that the decoder
ignored the error of not having a jxlp box marked as last.
> Refector encoder for box output, and support jxlp

- CHANGELOG.md
- lib/include/jxl/encode.h
- lib/jxl/decode.cc
- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
- lib/jxl/encode_test.cc
This implemented the JxlEncoderAddBox function to add boxes and enables
the test for it.
Brotli compressed boxes are not yet supported in this MR
> Implement JxlEncoderAddBox in the encoder API

- lib/jxl/dec_modular.cc
- lib/jxl/modular/encoding/dec_ma.cc
Fixes https://github.com/libjxl/libjxl/issues/848
The MA tree size check was not counting the color channels in the VarDCT case, while it should (the DC is still using modular and might benefit from a tree larger than 1024 nodes).
This now conforms to the profile spec again.
(one could argue that the dimensions should be divided by 64 for the color channels in the VarDCT case, but that's not what we specced and probably it doesn't matter that much)
The encoder still doesn't verify that it isn't generating a tree that is too large; however it seems extremely unlikely that this would happen accidentally given that the (corrected) bounds are quite generous.
> fix MA tree size check

- lib/jxl/decode_test.cc
- lib/jxl/encode_test.cc
As encode_test and decode_test are testing more stuff, CI is becoming quite slow. Some tests are unnecessarily slow, e.g. because default lossless encode speed is used (while the compression density / coding tools don't really matter for that test), or because Butteraugli is used when a cheaper metric is sufficient.
This makes encode_test and decode_test about twice as fast, without really changing anything.
> make tests a bit faster

- lib/jxl/dec_frame.cc
- lib/jxl/dec_modular.cc
- lib/jxl/dec_modular.h
- lib/jxl/quant_weights.cc
- lib/jxl/toc.cc
Progressive decoding (`djxl --allow_partial_files --allow_more_progressive_steps`) was a bit broken:
- progressive modular didn't work anymore
- DC frames were only shown when the frame header of the main frame was available (which kind of defeats the purpose of progressive DC)
This makes things work better again in `djxl`. ~~However, I only tested things with `djxl`, which only has to do one 'paint'. This PR may break things in the API, where multiple paints can be done as the bitstream gets loaded. For testing that, it would be useful to have a version of `decode_oneshot` that emulates what happens if a bitstream becomes available in X kb chunks, writing each of the intermediate progressive steps to output images.~~
Things were meanwhile fixed in the API: …
> Make progressive decode work (better)

- lib/jxl/enc_frame.cc
- lib/jxl/enc_heuristics.cc
Partially addresses https://github.com/libjxl/libjxl/issues/665
Makes `--photon-noise` work also in modular mode.
> allow photon noise in modular mode

- doc/software_support.md
Adds official GIMP support, jpegxl.io, and also the suggestion by @zeroheure (see https://github.com/libjxl/libjxl/pull/578) to add a link to Can I Use.
(that PR cannot be merged because the author/CLA bot is complaining; since it's just a single sentence addition to the documentation I'm assuming @zeroheure is OK with it if I just include it in this PR and pretend I wrote that sentence)
> update software support list

- lib/jxl/color_management_test.cc
- lib/jxl/enc_color_management.cc
Those occur when using djxl’s `--color_space=` flag.
> Fix HLG<->HLG and PQ<->PQ conversions

- CHANGELOG.md
- lib/CMakeLists.txt
- lib/include/jxl/codestream_header.h
- lib/include/jxl/decode.h
- lib/jxl/dec_frame.cc
- lib/jxl/dec_frame.h
- lib/jxl/dec_params.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
Proposed new decode option to disable frame coalescing.
This allows extracting layers from a multi-layer image (in case of Gimp/Photoshop-like use cases), and also possibly to save memory when decoding animations with lots of small cropped frames — at the cost of having to do the blending in the application instead of having the decoder handle it.
Obviously, default behavior doesn't change and still returns coalesced frames as before.
It is partially implemented, but more checks need to be added, and tests and an example application should still be added. Also documentation needs to be improved. This option does significantly change the behavior, e.g. you can no longer set the output buffer immediately after decoding the image header, but you have to do it after decoding the frame header …
> API proposal: JxlDecoderSetCoalescing

- plugins/CMakeLists.txt
fixes https://github.com/libjxl/libjxl/issues/647
(at least I hope it does)
> build gdk-pixbuf plugin when building for MSYS

- lib/jxl/fast_dct-inl.h
Fixes #884.
Unfortunately clang doesn't even complain about these errors...
> Fix inverted order of _s16 and _s32 in vreinterpretq.

- lib/include/jxl/encode.h
- lib/jxl/enc_frame.cc
- lib/jxl/encode.cc
- lib/jxl/encode_test.cc
- lib/jxl/roundtrip_test.cc
Also added test for already_downsampled. Also added TODO for issue found
with already_downsampled on odd output sizes (something that you can do
through the API and should be possible, but cjxl can't do)
> Add color transform and already_downsampled enc options

- AUTHORS
- CMakeLists.txt
- cmake/FindHWY.cmake
- third_party/CMakeLists.txt
The module looks for hwy using pkg-config if available otherwise it will look for the library in the `CMAKE_PREFIX_PATH`. If found a target is created that mirrors the in source build of the library.
> Add find module for hwy

- CMakeLists.txt
Windows uses .lib files for its libraries so setting the suffix to .a prevents find_library from functioning. This value is already set on the platform level so there isn't any reason to override.
Also don't use unix libraries with MSVC.
> Fix configuration of a static MSVC build

- lib/jxl/decode.cc
- tools/djxl_fuzzer.cc
We still don't want it to be public, but have to "enable" it for fuzzing the wrapper libraries like libvips.
> Bake-in unpublished API.

- lib/jxl/encode.cc
- lib/jxl/encode_test.cc
This writes the animation settings to the main image header. This is
part of what is needed to fully support animation, but does not yet
allow setting the time of each individual frame.
This change inadvertedly ended up in the header-only pull request https://github.com/libjxl/libjxl/pull/909
Implemented in a separate pull request now, and added test for this (and
most other basic info as well)
> Write animation in basic info in encoder

- lib/include/jxl/encode.h
- lib/jxl/encode.cc
Splitting this off from https://github.com/libjxl/libjxl/pull/909
Rename the argument to make more obvious that it are frame settings,
not settings for the entire encoder
This is a backwards compatible change. If we decide to rename the struct
itself, that's not intended for this PR.
> Make clear JxlEncoderOptions are frame settings

- cmake/FindBrotli.cmake
- third_party/CMakeLists.txt
The module looks for brotli using pkg-config if available otherwise it will look for the library in the CMAKE_PREFIX_PATH. If found a target is created that mirrors the in source build of the library.
The brotli headers do not have versioning so a minimum version is not requested.
> Add find module for brotli

- lib/jxl/dec_ans.h
Note that this does not enable the flag yet.
> Use FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION to disable ANS checksums.

- lib/jxl/enc_color_management.cc
They are technically a C++20 feature and MSVC complains.
> Don’t use designated initializers

- lib/include/jxl/codestream_header.h
- lib/include/jxl/encode.h
Adds function for setting the frame header containing animation
duration. Header-only, no implementation yet.
This change is open for discussion: let's find the best way to add this
to the encoder.
In this proposal, this setting is set to the JxlEncoderOptions, because
JxlEncoderOptions ara in reality frame options. The frame header
belongs to a frame, so setting its information to JxlEncoderOptions looks more
logical than setting it to JxlEncoder directly. Other opinions are
welcome.
JxlEncoderOptions is a confusing, JxlFrameOptions or similar could have
been a better name, you cannot use it to set boxes-related options to
the encoder for example. To clear this up, I also renamed it "frame_options"
wherever it was called "options" before and improved its documentation where used.
> header only: proposed encoder animation API

- lib/jxl.cmake
- lib/jxl/render_pipeline/low_memory_render_pipeline.cc
- lib/jxl/render_pipeline/low_memory_render_pipeline.h
- lib/jxl/render_pipeline/render_pipeline.cc
- lib/jxl/render_pipeline/render_pipeline.h
- lib/jxl/render_pipeline/render_pipeline_stage.h
- lib/jxl/render_pipeline/render_pipeline_test.cc
- lib/jxl/render_pipeline/simple_render_pipeline.cc
- lib/jxl/render_pipeline/simple_render_pipeline.h
- lib/jxl/render_pipeline/test_render_pipeline_stages.h
- lib/lib.gni
The pipeline is single-threaded and uses a large amount of memory.
Also modify trivial stages to test the behaviour of the pipeline, by
checking that downsampled all-0 input is upsampled to all-0.
> Implement the simple render pipeline.

- CHANGELOG.md
- examples/encode_oneshot.cc
- lib/include/jxl/codestream_header.h
- lib/include/jxl/encode.h
- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
- lib/jxl/encode_test.cc
- lib/jxl/roundtrip_test.cc
- plugins/gimp/file-jxl-save.cc
As discussed in https://github.com/libjxl/libjxl/pull/909
The reason for this is that these settings only apply to a frame, they
include frame metadata, and the name encoder options could be taken to
mean global options of the encoder.
Identifiers that already existed in the 0.6 release have the old name
marked as deprecated: JxlEncoderOptions, JxlEncoderOptionsCreate,
JxlEncoderOptionsSetDistance, JxlEncoderOptionsSetLossless
Other functions that are already marked deprecated are kept as-is, e.g.
JxlEncoderOptionsSetDecodingSpeed
Other identifiers that changed name have not been part of a release yet
so can be renamed without keeping the old name as deprecated:
JxlEncoderSetIntegerOption, JxlEncoderFrameSettingId and the enum values
> Rename JxlEncoderOptions to JxlEncoderFrameSettings

- lib/extras/codec_apng.cc
- lib/jxl/sanitizers.h
As libpng is not compiled with msan, msan believes memory coming from it
is uninitialized. This patch fixes that.
> Properly unpoison memory in codec_apng.

- lib/include/jxl/encode.h
- lib/jxl/enc_external_image.cc
- lib/jxl/enc_external_image.h
- lib/jxl/encode.cc
- lib/jxl/roundtrip_test.cc
- lib/jxl/test_utils.h
This adds `JxlEncoderSetExtraChannelBuffer` and
modifies the a roundtrip test to test it.
Pair with Lode
> encoder api: extra channels

- lib/jxl/dec_cache.h
- lib/jxl/dec_frame.cc
- lib/jxl/dec_frame.h
- lib/jxl/dec_group.cc
- lib/jxl/dec_modular.cc
- lib/jxl/dec_params.h
- lib/jxl/dec_reconstruct.cc
- lib/jxl/decode.cc
- lib/jxl/image_test_utils.h
- lib/jxl/render_pipeline/render_pipeline.h
- lib/jxl/render_pipeline/render_pipeline_test.cc
- lib/jxl/render_pipeline/simple_render_pipeline.cc
- lib/jxl/render_pipeline/stage_write_to_ib.cc
This patch adds a (not exposed) option that uses the rendering pipeline,
giving an error for all stages that are not implemented, and uses this
flag to verify the same behaviour between the slow pipeline and the
current behaviour in new tests.
> Add a testing infrastructure for the rendering pipeline.

- lib/jxl/dec_frame.cc
- lib/jxl/render_pipeline/render_pipeline.cc
- lib/jxl/render_pipeline/render_pipeline.h
- lib/jxl/render_pipeline/render_pipeline_test.cc
- lib/jxl/render_pipeline/simple_render_pipeline.cc
As a side effect, this fixes test failures in coverage builds.
> Simplify RenderingPipeline's handling of shifts.

- CHANGELOG.md
- examples/jxlinfo.c
- lib/include/jxl/codestream_header.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
- lib/jxl/encode.cc
We add fields in the `JXLBasicInfo`: a boolean `have_intrinsic_size` and
a new `JXLIntrinsicSizeHeader` struct that contains the dimensions of
the intrinsic size.
We add a parameter in the parameterized decode tests, in order to test
the intrinsic size.
> expose intrinsic size in the API

- lib/include/jxl/cms_interface.h
- lib/jxl/color_encoding_internal.cc
- lib/jxl/color_encoding_internal.h
- lib/jxl/color_management_test.cc
- lib/jxl/dec_reconstruct.cc
- lib/jxl/dec_xyb.cc
- lib/jxl/dec_xyb.h
- lib/jxl/enc_color_management.cc
- lib/jxl/render_pipeline/stage_xyb.cc
This effectively makes VarDCT always display-referred, instead of being
display-referred if and only if the original colorspace did not happen
to be HLG. It means that the linear output of the decoder is now always
suitable for display at a peak luminance of `intensity_target`.
JxlCmsInterface now has the responsibility of converting between scene
and display light if HLG is involved on one side and not the other. The
default implementation, JxlCms, does it and can be used for inspiration.
Images previously encoded from HLG to VarDCT with the default HLG
`intensity_target` of 1000, having not had the OOTF applied, will now be
decoded to a HLG signal brighter than the original since the OOTF will
nevertheless still be unapplied. But arguably, it was a bug of previous
encoders, since the …
> Apply the HLG OOTF when encoding to VarDCT and unapply it when decoding to HLG

- lib/jxl/color_management.cc
- lib/jxl/enc_color_management.cc
- lib/jxl/enc_image_bundle.cc
Code outside of the CMS should not depend on whether JxlCms is built
with skcms or lcms2 as it could dynamically be set to an entirely
different CMS.
> Make the skcms version of JxlCms handle grayscale the way it should

- lib/include/jxl/decode.h
- lib/jxl/dec_frame.cc
- lib/jxl/dec_frame.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
This implements the progressive API event fo rthe DC image.
This is currently only supported for vardct without extra channels: for
modular and extra channels it's only supported if squeeze is used, and
it may not correctly work with Flush yet in that case.
> Support progressive event for DC

- lib/jxl/image_metadata.h
- lib/jxl/roundtrip_test.cc
Currently it is impossible to encode a `JXL_CHANNEL_THERMAL`, we fix
this by adding the corresponding `MakeBit`.
> allow thermal channels

- CHANGELOG.md
- lib/include/jxl/encode.h
- lib/jxl/encode.cc
Only use JXL_ENC_ERROR for errors. This prevents the user having to
distinguish between different error cases, and is similar to how the
decoder works. Also, JXL_ENC_NOT_SUPPORTED was not used for sufficiently
many cases to be worth its additional handling.
> Remove JXL_ENC_NOT_SUPPORTED

- lib/extras/codec.cc
- lib/extras/codec_exr.cc
- lib/extras/codec_exr.h
- lib/extras/codec_test.cc
- lib/jxl/codec_in_out.h
- lib/jxl/jpeg/enc_jpeg_data.cc
- lib/jxl/jxl_test.cc
- lib/jxl/luminance.cc
- tools/benchmark/benchmark_codec_custom.cc
- tools/benchmark/benchmark_xl.cc
- tools/cjxl.cc
Previously, target_nits served as a hint to set intensity_target in the
various codecs. It was set prior to decoding an image, and if non-zero,
codecs were to give it precedence over what they would have otherwise
set from the image itself (e.g. EXR would set it from the whiteLuminance
header, PQ images would get 10000 given that we have no other source of
mastering metadata than the user).
The reason for doing it this way was historical (it used to affect the
numerical pixel values that the codecs would return) and does not apply
anymore, so now we can simply let the codecs set it however they like it
and then override it if requested.
> Remove CodecInOut::target_nits

- lib/jxl/enc_color_management.cc
- tools/comparison_viewer/image_loading.cc
This fixes conversions between HLG/PQ and a non-sRGB/PQ/HLG transfer
function (e.g. gamma or a LUT profile), which would not occur during
typical use of cjxl/djxl but may occur e.g. when viewing HLG images
using the comparison tool. This now works properly although it is not
yet possible to set the peak luminance to use for the OOTF in this use
case.
> Split linear profile creation for source and destination

- examples/encode_oneshot.cc
- lib/include/jxl/encode.h
- lib/jxl/encode.cc
The encoder was marking all frames as last.
Also fixes the encode_oneshot example to close the input, it's required
to use close input, otherwise the encoder can't know what the last frame
is. The above fix revealed this error in the example.
Documented better in the header that closing input is required.
> Let API encoder correclty mark frames as last

- lib/include/jxl/codestream_header.h
- lib/jxl/encode.cc
- lib/jxl/encode_test.cc
- lib/jxl/image_bundle.h
Implement several of the frame blending options in the encoder (that
is, pass them on to the C++ encoder)
This also adds the have_crop field to JxlLayerInfo: for initialization
purposes, as well as for the documentation, it's easier to have a flag
to disable it, than to indicate no crop by setting the the layer info
sizes to the full image dimensions (making the way to indicate the
default depenent on other circumstances)
Does not yet support cropping, or multi values for save as reference.
> Save blending options in encoder

- lib/jxl/encode.cc
We add a function `CheckValidBitdepth` and use it for color channels and
for extra channels.
> Add check for valid bit depth.

- lib/jxl/jxl_test.cc
- tools/box/box.cc
- tools/box/box.h
- tools/box/box_test.cc
- tools/cjxl_main.cc
- tools/djxl.cc
- tools/djxl_main.cc
djxl could not handle partial jxl codestream boxes, which made it fail to decode files produced by the current api encoder.
This fixes that.
> make djxl handle jxlp

- lib/jxl/enc_frame.cc
- lib/jxl/enc_frame.h
- lib/jxl/encode.cc
- lib/jxl/encode_test.cc
Make it work correctly: support the correct source frame. Also remove
the check for source, as experimenting reveals all from 0 to 3 work for
composite stills. Also support passing on the clamp and alpha index
settings.
> Improve encoder API blending support

- CHANGELOG.md
- lib/include/jxl/encode.h
- lib/jxl/enc_frame.cc
- lib/jxl/enc_frame.h
- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
- lib/jxl/encode_test.cc
Note: the function name for setting extra channel info is very long and
I'm considering shortening this one and JxlEncoderFrameSettingsSetInfo
to match the decoder equivalents in an upcoming MR
> Allow setting extra channel blend info in enc API

- lib/include/jxl/codestream_header.h
- lib/include/jxl/encode.h
- lib/jxl/encode.cc
- lib/jxl/encode_test.cc
After https://github.com/libjxl/libjxl/pull/990, this funtion was
forgotten, rename to JxlEncoderSetFrameName to match the decoder's
JxlDecoderGetFrameName
> Also rename JxlEncoderFrameSettingsSetName

- examples/jxlinfo.c
Fix silly bug where names are first free'd and then printed instead of the other way around.
> fix name free before print

- lib/jxl/dec_external_image.cc
- lib/jxl/decode.cc
~~Couldn't find any fuzzerbugs running it locally for a short while, but still good to test both coalesced and non-coalesced decoding to find potential bugs.~~
Fixes a fuzzer-found bug in the uint8 buffer case (where stride was not computed correctly in the no-coalescing case).
Also adds an ASSERT in dec_external_image to hopefully find more such bugs and to turn buffer overruns into an abort.
> fix no-coalescing fuzzerbugs

- lib/jxl/decode.cc
> Allow smaller buffers for output when row_stride is requested.

- lib/jxl/ans_test.cc
- lib/jxl/jxl_test.cc
- lib/jxl/xorshift128plus_test.cc
Make some more tests faster, hopefully without really changing the test coverage.
A lot of the time spent by jxl_test was spent in computing Butteraugli scores, sometimes for no good reason (e.g. to check that an image is lossless), sometimes maybe with good reason but likely a simpler MSE is good enough to catch bugs.
In ans_test and xorshift128plus_test, we're doing quite a lot of iterations and I think it's fine to do fewer of them.
> make tests faster

- lib/jxl/ac_strategy_test.cc
- lib/jxl/coeff_order_test.cc
- lib/jxl/jxl_test.cc
- lib/jxl/lehmer_code_test.cc
Fix the test failing on MSYS2.
Also makes some tests faster by not doing unnecessary iterations or by doing sampling of the whole range instead of exhaustively doing (part of) it.
> fix MSYS test and speedup some more tests

- lib/jxl/encode.cc
Spec says the number of mantissa bits has to be in the range [2, 23] — so including the sign bit, there have to be at least 3 bits besides the exponent bits.
> ensure at least 2 mantissa bits

- AUTHORS
- lib/jxl_threads.cmake
> jxl_threads: Hide all the std namespace symbols.

- lib/jxl/enc_ans.cc
- lib/jxl/enc_ans.h
- lib/jxl/enc_modular.cc
- lib/jxl/modular/encoding/enc_encoding.cc
- lib/jxl/modular/transform/enc_rct.cc
- lib/jxl/modular/transform/enc_rct.h
- lib/jxl/modular/transform/enc_transform.cc
Some speed tweaks, mostly for lossless -e 1.
No change in density nor in quality.
Before:
```
Encoding [Modular, lossless, lightning], 4 threads.
Compressed to 16788658 bytes (12.222 bpp).
4064 x 2704, geomean: 25.72 MP/s [20.88, 26.89], 30 reps, 4 threads.
real	0m13.375s
user	0m28.461s
sys	0m1.183s
```
After:
```
Encoding [Modular, lossless, lightning], 4 threads.
Compressed to 16788658 bytes (12.222 bpp).
4064 x 2704, geomean: 35.07 MP/s [26.63, 40.60], 30 reps, 4 threads.
real	0m9.960s
user	0m23.619s
sys	0m1.411s
```
So with 4 threads in real time it's about 35% faster, in terms of cpu time it's about 20% faster.
For comparison: when I use ImageMagick's `convert` to encode the same image 30 times, it takes 137 seconds with default settings, and still 39 seconds with `-quality 10` …
> make modular encoding faster (mostly lightning)

- ci.sh
When building with msan, we disable `-Werror`, in order to fix tests for #999.
> disable -Werror

- CMakeLists.txt
For #999 we had trouble compiling abseil-cpp with msan and asan. Turning
off rtti fixes this.
> add -fno-rtti flag

- lib/extras/codec.cc
- lib/extras/codec.h
- lib/extras/codec_jpg.cc
- lib/extras/codec_jpg.h
- lib/extras/codec_test.cc
- lib/jxl/codec_in_out.h
- lib/jxl/encode.cc
- lib/jxl/jpeg/dec_jpeg_data_writer.cc
- lib/jxl/jpeg/dec_jpeg_data_writer.h
- lib/jxl/jpeg/enc_jpeg_data.cc
- lib/jxl/jpeg/enc_jpeg_data.h
- lib/jxl/jxl_test.cc
- lib/jxl/render_pipeline/render_pipeline_test.cc
- lib/jxl_extras.cmake
- lib/lib.gni
- tools/CMakeLists.txt
- tools/benchmark/benchmark_codec.cc
- tools/benchmark/benchmark_codec_jpeg.cc
- tools/benchmark/benchmark_xl.cc
- tools/build_cleaner.py
- tools/cjpeg_hdr.cc
- tools/cjxl.cc
- tools/djxl.cc
- tools/fuzzer_corpus.cc
This is a step towards making codec_* not depend on CodecInOut /
ImageBundle.
> Move {En,De}codeImageJPGCoefficients out of codec_jpg

- lib/extras/packed_image_convert.cc
This restores correct propagation of the whiteLuminance tag from EXR
input.
> In PackedPixelFile->CodecInOut conversions, respect intensity_target if present

- .github/workflows/debug_ci.yml
We allow underscores in the name of between `ci-` and `-debug`, so that
it is possible to also run `./ci.sh msan_install` and other targets that
include an underscore.
> more targets in debug_ci

- .github/workflows/build_test.yml
- plugins/gdk-pixbuf/CMakeLists.txt
- plugins/gdk-pixbuf/pixbufloader-jxl.c
Drive-by: install arch-dependent packaages for gdk-pixbuf for cross-compilation.
> Fix gdk-pixbuf installation path in cross-compilation

- lib/jxl/enc_external_image.cc
- lib/jxl/encode.cc
- lib/jxl/image_bundle.cc
Fixes two encoder bugs:
- Not enough extra channels were allocated when you have e.g. a kBlack channel while passing an RGBA buffer.
- JxlEncoderSetExtraChannelBuffer() was incorrectly using image dimensions instead of frame dimensions
> fix bugs in extra channel encoding

- .github/workflows/build_test.yml
- third_party/CMakeLists.txt
Disable HWY tests/examples/install.
Asan build: 25m -> 18m
Msan build:  31m -> 19m
> Try to make (A|M)San builds faster

- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
djxl_fuzzer expects that frame header layer_info contains dimensions
that correspond to what is passed to callback.
> Use upsampled dimensions in GetCurrentDimensions

- examples/CMakeLists.txt
- examples/decode_progressive.cc
- examples/examples.cmake
Adds an optional argument to `decode_oneshot` to do the decode in chunks of `N` bytes, saving the intermediate image when flushing after every chunk. This is useful to test/debug progressive decoding with the API (which is not quite the same thing as decoding a truncated image with `djxl --allow_partial_files --allow_more_progressive_steps`, since djxl doesn't use the API yet, and decoding a truncated image once is not really the same thing as doing multiple flushes during a single decode).
> decode_progressive: example application to demo/simulate/test progressive decoding

- lib/jxl/modular/transform/transform.cc
See https://github.com/libjxl/libjxl/issues/1057
> Prohibit Palette with nonzero predictor when bits_per_sample > 24

- lib/jxl/render_pipeline/render_pipeline_test.cc
- lib/jxl/render_pipeline/simple_render_pipeline.cc
This causes calling Row() with invalid values, which causes debug mode
failures in some conditions.
> Do not fill input rows for ignored channels.

- lib/jxl/dec_frame.cc
- lib/jxl/render_pipeline/render_pipeline.cc
- lib/jxl/render_pipeline/render_pipeline.h
- lib/jxl/render_pipeline/render_pipeline_test.cc
- lib/jxl/render_pipeline/simple_render_pipeline.cc
- lib/jxl/render_pipeline/simple_render_pipeline.h
This allows more tests to pass. Remaining failing tests under ASAN:
377 - BlendingTest.Crops (ILLEGAL)
1196 - DecodeTest.SkipFrameWithBlendingTest (ILLEGAL)
1197 - DecodeTest.SkipFrameWithAlphaBlendingTest (ILLEGAL)
1198 - DecodeTest.OrientedCroppedFrameTest (ILLEGAL)
1200 - DecodeTest.FlushTestLossyProgressiveAlpha (Failed)
1201 - DecodeTest.FlushTestLossyProgressiveAlphaUpsampling (ILLEGAL)
1596 - EncodeTest.frame_settingsTest (ILLEGAL)
1603 - EncodeTest.CroppedFrameTest (ILLEGAL)
1955 - JxlTest.RoundtripAlphaResamplingOnlyAlpha (ILLEGAL)
1970 - JxlTest.RoundtripAnimation (ILLEGAL)
1971 - JxlTest.RoundtripLosslessAnimation (ILLEGAL)
2200 - RoundtripTest.TestICCProfile (Failed)
2235 - SplinesTest.ClearedEveryFrame (ILLEGAL)
2257 - pixbufloader_test_jxl (ILLEGAL)
2259 - …
> Fix rendering pipeline with multiple passes.

- README.md
- deps.sh
Make shallow clones in order to prevent unnecessary downloading
during dependency fetching.
> submodules: make shallow clones

- experimental/fast_lossless/build-android.sh
- experimental/fast_lossless/build.sh
This cleans up the bash buildscripts so they should be more robust and work better cross-platform.
> fast_lossless: clean up Bash buildscripts

- .github/workflows/release.yaml
In the `windows_build` of "Release build/deploy" there is we get a
`LINK : fatal error LNK1181: cannot open input file 'gflags.lib'`
As a workaround we build our own gflags instead.
> bundle gflags for windows build

- AUTHORS
- third_party/CMakeLists.txt
Current CMakeFiles.txt looks for gflags unless it is bundled, as gflags is only required by the tools this breaks builds where the tools are disabled.
This change only does a search for gflags if tools is set to enabled
> GFLAGS is supposed to be used by tools only

- lib/jxl/render_pipeline/render_pipeline_stage.h
Warning is:
jxl/render_pipeline/render_pipeline_stage.h:124:24: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
124 |     JXL_DASSERT(offset <= 1 << settings_.shift_y);
|                 ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
> Fix a simple warning reported by gcc

- AUTHORS
- doc/building_wasm.md
The docker container does not build the wasm artifact normally using the provided commands.
The build commands need `CMAKE_FLAGS=-I/usr/wasm32/include` prefixed to them in order to actually build.
> Add info for compiling with docker container

- lib/jxl/ans_test.cc
This will solve the following warning reported by gcc:
libjxl/lib/jxl/dec_bit_reader.h: In function ‘void jxl::{anonymous}::TestCheckpointing(bool, bool)’:
libjxl/lib/jxl/dec_bit_reader.h:176:10: warning: ‘br_pos’ may be used uninitialized in this function [-Wmaybe-uninitialized]
176 |     skip -= bits_in_buf_;
|     ~~~~~^~~~~~~~~~~~~~~
libjxl/lib/jxl/ans_test.cc:232:12: note: ‘br_pos’ was declared here
232 |     size_t br_pos;
|            ^~~~~~
> Make sure to initialize `br_pos` to zero

- tools/bisector
- tools/cjxl_bisect_bpp
- tools/cjxl_bisect_size
This allows us to do generic 'bisect to
target-size/target-bits-per-pixel' searches without having bisection
in the JXL encoder. Picking target quality settings via bisection is
relevant for performance comparison of codecs (when encoding the same
image to a given size with different encoders), but it makes more
sense to not have support for this directly in the encoder due to
potential for confusion: It in general does not make much sense to
encode images of very different visual complexity in a corpus to
identical bits-per-pixel, since this would give very unhomogeneous
quality.
> Adding a general-purpose bisector tool

- lib/extras/dec/gif.cc
This fixes a problem with encoding certain gifs introduced by #634 and described in https://github.com/libjxl/libjxl/issues/980.
Fixes #980
> fix total_rect for gif

- lib/extras/packed_image_convert.cc
There are two identical functions converting JxlDataType to the number
of bits per channel. We remove one of them.
> Remove duplicate function converting JxlDataType

- experimental/fast_lossless/fast_lossless.cc
- experimental/fast_lossless/fast_lossless.h
- experimental/fast_lossless/fast_lossless_main.cc
- experimental/fast_lossless/pam-input.h
fjxl:
Generalizes 8-bit RGBA input to any bitdepth <= 12 and any number of channels <= 4.
Adds pgm/ppm/pam input support to the main file.
For now, SIMD is only used in the 8-bit codepath, since there are some assumptions/constraints in the SIMD code that are broken by having a larger range for the symbols than what is needed for 11-bit.
Compression of 8-bit images is not affected much, the only differences are:
- slightly less compact encoding of the huffman code itself because kNumRaw was bumped up (typically +2 or +3 bytes per file) — can be fixed later
- slightly better and faster compression when giving input as Grayscale, Gray+Alpha or RGB instead of as RGBA
- slightly denser when palette can be used (~0.2% smaller on my test set of palette images)
- significantly denser if input is …
> up to 12-bit Grayscale, Gray+Alpha, RGB and RGBA input via pgm/ppm/pam

- lib/extras/packed_image.h
When creating a `PackedPixelFile`, currently the `JxlBasicInfo` inside it is not initialized to meaningful defaults. We use `JxlEncoderInifBasicInfo` to do this. 
This is currently used in cjxl_ng and makes the code there more simple.
> Init basic info

- lib/extras/dec/apng.cc
It is assumed, that ppf.frames should not be empty.
> Add corner-case check in APNG decoding (no frames decoded)

- tools/djxl_ng_main.cc
because it is not needed for reconstructing jpeg.
> Remove info argument

- lib/extras/packed_image_convert.cc
- lib/jxl/decode_test.cc
- lib/jxl/enc_external_image.cc
- lib/jxl/enc_external_image.h
- lib/jxl/enc_external_image_gbench.cc
- lib/jxl/enc_external_image_test.cc
- lib/jxl/roundtrip_test.cc
- lib/jxl/test_utils.h
- tools/benchmark/benchmark_codec_avif.cc
- tools/benchmark/benchmark_codec_webp.cc
- tools/fuzzer_corpus.cc
Row alignment (stride) was ignored when passing an image buffer in JxlEncoderAddImageFrame. This should fix that.
Also check if the buffer size has the right size: currently it was only checking if it is large enough, but if it's too large then it's better to return an error than to just silently ignore the additional bytes — most likely this is API usage error.
Fix one of the tests where we had such an API usage error (interpreting a 16-bit input buffer as 8-bit), which didn't really matter for that particular test but still...
> don't ignore JxlPixelFormat.align when encoding

- lib/jxl/base/scope_guard.h
- lib/jxl/modular/encoding/encoding.cc
Before planes were zeroified only if the very late stage failed.
Now the scope guard is placed after meta-apply, so that there is no
escape path to leave planes uninitialized (if truncated groups are allowed).
> Add unified safeguard for truncated group decoding.

- lib/extras/enc/pnm.cc
Fixes ppm/pgm output when bitdepth is not 8 or 16.
> fix ppm output when bitdepth is not 8 or 16

- lib/jxl/dec_ans.h
This will fix the following warnings reported by gcc-10:
libjxl/lib/jxl/dec_ans.h:151:7: error: '<anonymous>.jxl::ANSSymbolReader::log_alpha_size_' may be used uninitialized [-Werror=maybe-uninitialized]
libjxl/lib/jxl/dec_ans.h:151:7: error: '<anonymous>.jxl::ANSSymbolReader::log_entry_size_' may be used uninitialized [-Werror=maybe-uninitialized]
libjxl/lib/jxl/dec_ans.h:151:7: error: '<anonymous>.jxl::ANSSymbolReader::entry_size_minus_1_' may be used uninitialized [-Werror=maybe-uninitialized]
libjxl/lib/jxl/dec_ans.h:151:7: error: '<anonymous>.jxl::ANSSymbolReader::num_special_distances_' may be used uninitialized [-Werror=maybe-uninitialized]
libjxl/lib/jxl/dec_ans.h:151:7: error: '*(unsigned char (*)[480])((char*)&<unnamed> + offsetof(jxl::ANSSymbolReader, …
> Default initialize member variables of class ANSSymbolReader

- lib/jxl/dec_reconstruct.cc
Missing +y caused interesting decoding results.
> Fix the low-precision AARCH64 pipeline.

- lib/jxl/ac_strategy.cc
- lib/jxl/ac_strategy.h
- lib/jxl/coeff_order.cc
- lib/jxl/coeff_order.h
- lib/jxl/enc_coeff_order.cc
- lib/jxl/enc_coeff_order.h
- lib/jxl/enc_frame.cc
This cuts static memory usage by 1.5mb, with minor impact on speed:
```
Before:
jxl:d0.7        13270  3400483    2.0499581   5.592  48.001   1.50473666   0.47348297  0.970620226409      0
jxl:d1          13270  2678725    1.6148512   5.885  51.535   1.68153656   0.60257544  0.973069654737      0
jxl:d2          13270  1683788    1.0150602   6.256  54.283   3.00312042   0.95243347  0.966777268691      0
jxl:d4          13270  1004956    0.6058309   6.122  38.064   4.85261440   1.50554379  0.912104941537      0
jxl:d6          13270   718865    0.4333629   5.912  37.250 …
```
> Do not keep around copies of the natural coefficient order.

- lib/extras/packed_image_convert.cc
- lib/extras/packed_image_convert.h
Adding a new function fo convert a CodecInOut to a PackedPixelFile. The
idea is to use this for djxl when changing the encoder in `extras/enc/`
to use PackedPixelFile instead of CodecInOut.
> convert CodecInOut to PackedPixelFile

- lib/jxl/compressed_image_test.cc
- lib/jxl/dec_frame.cc
- lib/jxl/dec_group.cc
- lib/jxl/enc_ac_strategy.cc
- lib/jxl/enc_heuristics.cc
- lib/jxl/quant_weights.cc
- lib/jxl/quant_weights.h
- lib/jxl/quant_weights_test.cc
- lib/jxl/quantizer.h
This saves ~3Mb of static memory. Speed impact with multiple repetitions
is negligible, significant speed improvement for one-off decodes.
Slight variation in 6th digit of en/decoding results due to more
approximate quant matrix computation.
```
Before:
jxl:d0.7        13270  3400483    2.0499581   5.466  47.067   1.50473666   0.47348297  0.970620226409      0
jxl:d1          13270  2678725    1.6148512   5.750  50.382   1.68153656   0.60257544  0.973069654737      0
jxl:d2          13270  1683788    1.0150602   6.102  53.015   3.00312042   0.95243347  0.966777268691      0 …
```
> Do not keep around default quantization matrices

- tools/cjxl_ng_main.cc
cjxl_ng should now support animated gifs with and without alpha channel.
There still can be issues with variable-size frames.
This also completes missing modular-mode support flags.
> cjxl_ng: Fix encoding (some) animated gifs.

- lib/jxl/splines.cc
Internally splines are processed in floats.
For the first segment of spline a virtual mirrored point is added.
Lets take a look at spline with control points: (16777216, 0), (16777215, 0)
Mirrored point would be (16777217, 0), but alas, it is (16777217, 0) due to floating point precision.
Next, distance between points is calculated and at some point used as a divisor...
> Fix division by zero in spline caching

- lib/extras/enc/apng.cc
In the case of no-animation multi-frame images, the (a)png output was writing something weird that is basically a non-animated PNG that contains a sequence of frames (i.e. the first frame followed by a bunch of tail data). This fixes that: in the case of no animation, what needs to be encoded is the final frame (the result of merging all layers), not the first frame (the bottom layer).
> fix composite still png output

- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
Current behavior: when encoding a frame without setting buffers for all extra channels, uninitialized memory is used as input pixels for the extra channels.
This PR makes it an API usage error instead when that is attempted.
> check that all extra channels are initialized before encode

- lib/jxl/dec_reconstruct.cc
- lib/jxl/decode.cc
Why? djxl_fuzzer does not expect those:
`if (x + num_pixels > data->xsize) abort();`
> Shortcut: do not invoke callback with 0 pixels

- lib/jxl/base/padded_bytes.h
- lib/jxl/blending.cc
- lib/jxl/decode_to_jpeg.h
- lib/jxl/enc_bit_writer.cc
- lib/jxl/image_ops.h
Documentation for std::memcpy clearly states that:
> If either dest or src is an invalid or null pointer, the behavior is
> undefined, even if count is zero.
ref:
* https://en.cppreference.com/w/cpp/string/byte/memcpy
> Rework append implementation to avoid passing in NULL pointers

- lib/jxl/enc_frame.cc
- lib/jxl/jxl_test.cc
Remove the increase of x quantization below distance 0.65
Add a reduction of x quantization below distance 0.3
Seeking for community feedback for this.
> improve redness-greenness preservation at low dist

- lib/jxl/splines.cc
It was a missing path in defusing CPU-bomb.
The minimum possible cost for regular spline pixel is imputed.
> Account no-draws as regular pixels

- lib/jxl/color_encoding_internal.cc
E.g. wx = 0.080128, wy = 0.179394 -> w = [0.446659, 1.000000, 4.127663] ->
lms = [0.000000, 1.529902, 4.198717] -> division by zero for a[0].
> Avoid division by zero in AdaptToXYZD50

- lib/jxl/enc_ans.cc
- lib/jxl/enc_ans_params.h
- lib/jxl/enc_modular.cc
- lib/jxl/modular/options.h
```
Before:
jyrki31:
Encoding                              kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm       BPP*pnorm   Bugs
------------------------------------------------------------------------------------------------------------------------------------
jxl:m:squirrel:faster_decoding=1:R      13270 21392160   12.8961183   2.443   7.117  -1.00000000   0.00000000  0.000000000000      0
jxl:m:cheetah:faster_decoding=1:R       13270 19474130   11.7398469   3.239   7.292  -1.00000000   0.00000000  0.000000000000      0
jxl:m:squirrel:faster_decoding=2:R      13270 22843671   13.7711518   2.958  14.900  -1.00000000   0.00000000  0.000000000000      0
jxl:m:cheetah:faster_decoding=2:R       13270 19320457   11.6472062   4.039  15.534  -1.00000000   0.00000000 …
```
> Improve --faster_decoding for progressive lossless.

- lib/extras/enc/apng.cc
In case of no-animation multi-frame (composite still), the end chunk wasn't getting written.
> write png end for composite still

- lib/jxl/dec_file.cc
- lib/jxl/dec_frame.cc
- lib/jxl/dec_frame.h
- lib/jxl/dec_params.h
- lib/jxl/decode.cc
- lib/jxl/preview_test.cc
They were basically only used in tests - the C API implements this
differently.
> Remove DecodePreview and SkipFrame.

- lib/jxl/dec_ans.h
- lib/jxl/dec_huffman.cc
- lib/jxl/dec_huffman.h
- lib/jxl/modular/encoding/context_predict.h
- lib/jxl/modular/encoding/encoding.cc
- lib/jxl/modular_test.cc
This breaks conformance test “lossless_pfm”.
> Revert "more speedups for fjxl decoding (#1149)"

- lib/include/jxl/codestream_header.h
- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
- lib/jxl/luminance.cc
- lib/jxl/luminance.h
- tools/cjxl_ng_main.cc
On the C side, leaving JxlBasicInfo::intensity_target to its initial value of 0 lets the implementation choose a reasonable value based on the color encoding (1000 for HLG, 10000 for PQ, kDefaultIntensityTarget otherwise).
This also restores that behavior in cjxl, since ConvertPackedPixelFileToCodecInOut only calls SetIntensityTarget if ppf.info.intensity_target is 0, but starting in #1129, it was initialized to 255.
> Intensity target defaults in the C API

- lib/jxl/enc_adaptive_quantization.cc
- lib/jxl/enc_group.cc
- lib/jxl/jxl_test.cc
Don't attempt to do energy preserving corrections for AFV0,1,2,3 transforms.
This affects quantization decisions 2 % of the surface area.
Elsewhere, use 2nd norm of dct coefficients as a decision criteria for
energy preservation.
0.23 % improvement in BPP*pnorm, doesn't look worse
Before:
```
Encoding        kPixels    Bytes          BPP  E MP/s  D MP/s     Max norm        pnorm   PSNR   QABPP  SmallB  DCT4x8     AFV  DCT8x8    8x16    8x32      16   16x32      32   32x64      64       BPP*pnorm   Bugs
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
jxl:d1:epf3       18628  3526882    1.5146401   1.505   8.358   1.98383951 …
```
> AFV transform -- no special quantization

- lib/jxl/enc_file.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_params.h
- lib/jxl/encode.cc
- tools/cjxl.cc
Fixes #1210 so it does the correct thing when setting resampling to -1 in the API.
> fix default resampling in encode api

- lib/jxl/color_management.cc
This commit will fix the following warning reported by gcc-10:
lib/jxl/color_management.cc:502:9: error: 'void* memset(void*, int, size_t)' offset [0, 3] is out of the bounds [0, 0] [-Werror=array-bounds]
502 |   memset(icc_sum.data() + 44, 0, 4);
|   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
libjxl/lib/jxl/color_management.cc:503:9: error: 'void* memset(void*, int, size_t)' offset [0, 3] is out of the bounds [0, 0] [-Werror=array-bounds]
503 |   memset(icc_sum.data() + 64, 0, 4);
|   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
> Prevent a potential out of bounds write access

- tools/cjxl.cc
- tools/cjxl.h
- tools/cjxl_main.cc
it suppresses generating "jbrd" chunk in output. it is no-op if not in
jpeg transcode mode.
dunno if this is really that useful. i tested it and it seems to work, and seems like minimal added maintenance burden. i don't mind if you don't merge it though because cjxl_ng.
> cjxl: add --strip_jpeg_metadata option

- lib/extras/packed_image_convert.cc
- lib/jxl/decode_test.cc
- lib/jxl/enc_external_image.cc
- lib/jxl/enc_external_image.h
- lib/jxl/enc_external_image_gbench.cc
- lib/jxl/enc_external_image_test.cc
- lib/jxl/roundtrip_test.cc
- lib/jxl/test_utils.h
- tools/benchmark/benchmark_codec_avif.cc
- tools/benchmark/benchmark_codec_webp.cc
- tools/fuzzer_corpus.cc
Fixes #1198 
When an RGB(A) buffer is passed while the image is grayscale, use R and A instead of misinterpreting the buffer as Y(A) and ignoring the bottom part. G and B just get ignored in this case and G and B get copied from R (we could instead check that R==G==B in the input, but that comes at a small overhead just to catch potential wrong API usage; I think it will be sufficiently easy to debug for application developers if they see their color image gets incorrectly grayscaled when they accidentally incorrectly set the color encoding to grayscale).
When a Y(A) buffer is passed while the image is color, return a relevant error instead of just saying that the buffer is too small.
> use actual num_channels instead of guessing from color encoding

- lib/jxl/enc_file.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_frame.h
- lib/jxl/enc_modular.cc
- lib/jxl/enc_params.h
- tools/jxl_from_tree.cc
Adds three new options to `jxl_from_tree` to manually specify:
- Noise lookup table: `Noise [8 floats in [0.0,1.0) range]`
- custom XYB quantization factors: `XYBFactors [3 floats]`
- Delta Palette: `DeltaPalette` (signals a default zero-color delta palette transform)
This allows setting XYB factors to their defaults `4096 512 256`, which makes the LfChannelDequantization bundle 1 bit instead of 49 bits, and using different factors than the default ones for modular to get different 'bit depths' in XYB too. In particular, this enables producing the currently known smallest jxl file as follows:
```
XYB
XYBFactors 4096 512 256
Gaborish
EPF 2
Width 512
Height 256
- Set 0
```
For noise this helps to produce test bitstreams to debug noise seeding.
Delta Palette is just to explore jxl art :)
> add Noise and XYBFactors options to jxl_from_tree

- lib/jxl/enc_params.h
Forgot to remove the PostInit() function which is no longer in enc_params but in enc_frame.
> Cleanup enc params

- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
might help when a client has a small output buffer
looks like O(n**2) writing would happen with vector erasing a small number of bytes in the beginning
> change vector to deque

- lib/include/jxl/encode.h
- lib/jxl/enc_external_image.cc
Follow-up on https://github.com/libjxl/libjxl/pull/1020: check that the buffer size matches what is expected, don't just check if it's large enough. If the size doesn't match, it's likely an API usage error (e.g. interpreting an RGBA buffer as RGB) so it's more useful to return a meaningful error in this case than to cause head scratching for the application developer.
Also updating documentation to clarify that the size has to match.
The only degree of freedom this check is leaving, is the padding at the end of the last row in case `align` is being used. You can choose whether to pass a buffer with or without that padding.
> enc buffer api: check if buffer size matches

- lib/extras/dec/apng.cc
Sometimes proflen contains garbage (non-initialized).
When png_get_iCCP fails, then we would memcpy from garbage address (or from nullptr)...
> Do not ignore png_get_iCCP result.

- lib/extras/dec/pnm.cc
[...]
In the raster, the sample values are "nonlinear." They are proportional
to the intensity of the ITU-R Recommendation BT.709 red, green, and blue
in the pixel, adjusted by the BT.709 gamma transfer function. (That
transfer function specifies a gamma number of 2.2 and has a linear
section for small intensities). A value of Maxval for all three samples
represents CIE D65 white and the most intense color in the color
universe of which the image is part (the color universe is all the
colors in all images to which this image might be compared).
[...]
* http://netpbm.sourceforge.net/doc/ppm.html
> Deviate from upstream ppm specification and assume color space is sRGB

- lib/jxl/render_pipeline/stage_blending.cc
In particular, noise will cause 3 additional channels to be present in
the RP.
> Do not assume that the RP has as many channels as the image.

- lib/extras/packed_image_convert.cc
- lib/include/jxl/encode.h
- lib/jxl/enc_external_image.cc
Fixes #1026.
I think it is reasonable to allow passing RGB data to the encoder if the image is actually RGBA, and make the assumption that the alpha channel is all-opaque. This is symmetric to what we do in the decoder when requesting RGBA data from an RGB image.
An alternative could be to make it an error to not explicitly pass alpha if the image has alpha.
Theoretically you could first set the RGB with AddImageFrame and then set the A with SetExtraChannelBuffer, which should still work but it will unnecessarily set the A to all-opaque first. If you do it the other way around, it's a bigger problem: then with this change you'll end up overwriting the A with all-opaque. In any case we should make a choice here and document the behavior.
More generally: it looks like we currently silently …
> assume RGB pixels are all-opaque (if there's alpha)

- lib/jxl/decode.cc
- lib/jxl/render_pipeline/stage_write.cc
Currently we do not populate image bundle when callback used.
This means that there is no EC planes to copy data from.
Does not seem to be a (popular) use-case.
> Fix access to non-existing EC plane

- lib/jxl/render_pipeline/low_memory_render_pipeline.cc
- lib/jxl/render_pipeline/low_memory_render_pipeline.h
E.g. 1x2M image would require 32x2M storage for vertical borders.
This CL cuts-off top-,bottom-,left-,right-most borders that are not
actually used.
> Reduce memory usage for tall or wide images

- lib/jxl/decode.cc
Before: 1x2M image accounted as 2MPx image
In reality, its representation alone is 32x bigger,
because of image row extension / padding
(see CacheAligned::kAlignment == 128 bytes)
> Fix fuzzer memory accounting

- lib/jxl/modular/transform/enc_palette.cc
For some reason, the pre-processing pass (made for lossy palette) was also done in case of lossless (multi-channel) palette. This causes spurious errors when no lossless palette transform can actually be done (which is usually the case), and unnecessarily does the fwd palette transform twice if it can be done (causing slowdown).
> fix #1244 (spurious error messages doing non-lossy palette)

- lib/include/jxl/encode.h
- lib/jxl/decode_test.cc
- lib/jxl/enc_params.h
- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
- lib/jxl/jpeg/enc_jpeg_data.cc
- lib/jxl/jpeg/enc_jpeg_data.h
- lib/jxl/jxl_test.cc
- tools/cjxl.cc
- tools/cjxl_main.cc
- tools/cjxl_ng_main.cc
- tools/fuzzer_corpus.cc
Currently, when doing JPEG recompression, the `jbrd` is brotli-compressed with effort 11 (hardcoded), and when `brob` boxes are created, they are brotli-compressed with effort 9 (also hardcoded). This adds an encoder option to set a custom brotli effort for the uses of brotli in the JPEG XL file format.
> add brotli_effort option

- lib/jxl/dec_file.cc
- lib/jxl/enc_modular.cc
- lib/jxl/enc_params.h
- lib/jxl/encode.cc
- lib/jxl/encode_test.cc
- lib/jxl/roundtrip_test.cc
Fixes some stuff related to levels and the `modular_16bit_buffers` header field.
- Set the `modular_16bit_buffers` field correctly in the encode api, i.e. only make it false if there is a reason for it (there is a modular channel that will not fit in int16_t).
- Check that field in VerifyLevelSettings, i.e. don't allow e.g. lossless uint16 to be encoded as level 5.
- Add a cparam option to set the level to conform to. E.g. if the level is 5 and the data is lossless 14-bit, then that's fine, but there are not enough spare bits to do RCTs + Squeeze, so disable those if we have to conform to level 5. However if we only have to conform to level 10, we can still do those things.
- In particular, don't do modular transforms that will potentially cause trouble even in level 10: e.g. when the …
> modular_16 and a cparam to conform to level restrictions

- lib/jxl/encode.cc
- lib/jxl/encode_test.cc
Fixes https://github.com/libjxl/libjxl/issues/1237.
Return error earlier when attempting to encode an image that does not meet the level requirements. In particular: if it has more extra channels than what level 5 allows, return error already at `JxlEncoderSetBasicInfo`, and when trying to add a CMYK channel, return error already at `JxlEncoderSetExtraChannelInfo`. Currently these cases will cause error only when the actual encode of the first frame is started, which is unnecessarily late.
> fail earlier when level is too low

- lib/extras/enc/apng.cc
- lib/extras/enc/jpg.cc
- lib/jxl.cmake
- lib/jxl/enc_file.cc
- lib/jxl/exif.cc
- lib/jxl/exif.h
- lib/lib.gni
There were some issues with Exif metadata handling in cjxl/djxl (see also https://github.com/libjxl/libjxl/issues/540):
- `djxl foo.jxl bar.jpg -j --use_sjpeg` wrote no exif metadata
- `djxl foo.jxl bar.jpg -j` (using libjpeg) wrote malformed exif metadata
- `djxl foo.jxl bar.jpg -j` did not orient the image, which is not good (it would maybe be OK if we always wrote exif metadata that does the appropriate orientation, but there could also just not be any exif, e.g. when you do `cjxl oriented.jpg foo.jxl --strip`.
- `djxl foo.jxl bar.png` orients the image (which is good), but also writes exif metadata which might lead to repeated orientation (most viewers ignore exif orientation in png files, but some don't, and also cjxl doesn't)
This PR attempts to fix those issues in the following …
> better handling of exif (in particular orientation)

- lib/jxl/decode.cc
Tests that use "flower" picture failed because it is 3Mpx+ and limit was 2MPx.
> Raise memory limit for xSAN

- lib/jxl/decode_test.cc
- lib/jxl/enc_cache.cc
- lib/jxl/enc_file.cc
- lib/jxl/enc_frame.cc
- lib/jxl/enc_modular.cc
- lib/jxl/enc_modular.h
- lib/jxl/enc_params.h
- lib/jxl/enc_patch_dictionary.cc
- lib/jxl/encode.cc
- lib/jxl/jxl_test.cc
- lib/jxl/modular_test.cc
- lib/jxl/patch_dictionary_test.cc
- lib/jxl/render_pipeline/render_pipeline_test.cc
- lib/jxl/roundtrip_test.cc
- tools/benchmark/benchmark_codec.cc
- tools/benchmark/benchmark_codec_jxl.cc
- tools/cjxl.cc
- tools/fuzzer_corpus.cc
Get rid of the separate cparams.quality_pair for modular quality, instead use cparams.butteraugli_distance also in modular mode as the main setting that controls lossy quality.
Also taking the opportunity to better calibrate modular and vardct quality and to tweak the quality settings chosen for alpha, dc frames, and patch frames.
Test corpus: jyrki31.
Before:
```
jxl:d0.5        13270  4225280    2.5471813   3.049  22.687   1.12016439   0.37185960  0.947193828701      0
jxl:d1          13270  2680279    1.6157880   3.333  24.225   1.68695998   0.60068375  0.970577588663 …
```
> remove modular quality

- lib/extras/dec/pnm.cc
- lib/extras/packed_image.h
- lib/extras/packed_image_convert.cc
Currently, e.g. 10-bit ppm files are loaded incorrectly: while the range of values in the ppm is 0..1023, they get interpreted as UINT16 so basically everything becomes very dark.
This solves that.
> fix ppm input where bitdepth is not 8 or 16

- lib/jxl/dec_frame.cc
In the `jxli` box as defined in 18181-2, we don't include zero-duration non-last frames in the frame count. If we want to be able to correctly do the noise seeding when doing `jxli` seeking, we have to match that.
> noise seeding: match frame index of jxli box

- CMakeLists.txt
- cmake/FindAtomics.cmake
- lib/jxl.cmake
It turns out that GCC requires explicitly linking to a library `atomic`
in order to support c11/atomics. gcc spec file will not handle it
directly at least not on the following Debian archs: armel, mipsel,
powerpc and riscv64.
Introduce a new cmake module to detect usage of gcc/atomic and add
missing library to the link step.
For reference:
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104248
> libjxl implementation rely on c11 atomics (cache_aligned.cc)

- lib/jxl/modular/encoding/context_predict.h
- lib/jxl/modular/encoding/encoding.cc
- lib/jxl/modular/transform/squeeze.cc
- lib/jxl/modular/transform/squeeze.h
- lib/jxl/simd_util-inl.h
Some more specialization for the slower modular decode paths.
~~Vectorizeable unsqueeze.
Alas, my clang (12.0.1) requires a `pragma` to be convinced to vectorize the inner loop. Not sure how to proceed with that...~~
SIMDified unsqueeze.
Good decode speedup for images where this applies (lossy modular, lossless progressive modular, also should help a little for DC frames and VarDCT mode alpha channels).
Decoding a lossy modular image (produced with cjxl -m -q 80 -e 2), with AVX2:
Before:
2749 x 4049, geomean: 9.90 MP/s [8.67, 10.66], 10 reps, 0 threads.
2749 x 4049, geomean: 18.35 MP/s [15.42, 18.81], 10 reps, 2 threads.
2749 x 4049, geomean: 29.92 MP/s [23.30, 31.61], 10 reps, 4 threads.
After:
~~2749 x 4049, geomean: 14.94 MP/s [12.36, 15.50], 10 reps, 0 threads.
2749 x 4049, geomean: …
> Faster unsqueeze / lossy modular

- lib/extras/packed_image_convert.cc
AdoptWhitePoint error is silenced in ConvertExternalToInternalColorEncoding ->
-> ConvertPackedPixelFileToCodecInOut did not notice ICC was not set ->
-> CHECK triggered.
> Fix crash in set_from_bytes fuzzer

- lib/jxl/modular/transform/squeeze.cc
For MSVC 2019 being just a constexpr is not enough.
> Try to fix "error C2131: expression did not evaluate to a constant"

- lib/jxl/blending.cc
Fixes test JxlTest.RoundtripAnimationPatches (using ubsan)
libjxl/lib/jxl/blending.cc:81:13: runtime error: null pointer passed as argument 1, which is declared to never be null
> Make sure to only call memcpy when not nullptr

- lib/extras/dec/apng.cc
- tools/cjxl_ng_main.cc
Fixing an issue introduced in #1223. Drive-by: don't assume cropping by default.
> cjxl_ng: fixing single-frame pngs

- tools/djxl.cc
Fixes https://github.com/libjxl/libjxl/issues/258. The problem was that the frames don't get the jpeg_quality set correctly, which resulted in horrible quality/or non-working jpeg when decoding animated jxls to a sequence of jpgs
> pass jpeg_quality to frames

- lib/jxl/enc_modular.cc
- lib/jxl/enc_patch_dictionary.cc
- lib/jxl/jxl_test.cc
In the case of lossy non-squeeze modular, XYB color quantization was done twice: once with big factors to go to integers, then again by applying integer quantization as if the values are the final squeeze residuals.
This changes it to do XYB color quantization directly by using different LF quant weights.
For the B channel, the quantization that was done before was too aggressive since it ended up using the large factors that make sense for the final (highest freq) squeeze residuals but not when done on every pixel. This instead uses twice the effective quantization for B (or rather B-Y) as for Y, which makes more sense.
Note: of course `-m -R 0` is not a good way to do lossy compression, but it does still make sense to have the distance parameter roughly make sense at this setting too. …
> Patch frame quant

- tools/djxl.cc
Same as `jpeg_quality`, https://github.com/libjxl/libjxl/pull/1307, this is used later in the call to `EncodeImageJPG` in `lib/extras/codec.cc`.
> pass use_sjpeg to frames

- lib/jxl/image.h
- lib/jxl/render_pipeline/low_memory_render_pipeline.cc
Drive-by: generalise Rect to use with ssize_t (negative origin).
> Refactor padding calculation to improve readability.

- lib/jxl_extras.cmake
This should fix libvips' CIFuzz and OSS-Fuzz integration.
https://github.com/libvips/libvips/runs/5799006301
https://oss-fuzz-build-logs.storage.googleapis.com/index.html#libvips
Alternatively, we could avoid building `jxl_extras_dec` as a shared
library, since it's not being linked against.
(The logic is derived from `jxl_threads.cmake`)
> Build `jxl_extras_dec` only as a shared library if necessary

- lib/jxl/frame_header.h
On most arches `char` is a signed integer type. Make sure to cast to a
unsigned char first, so that all values are within range [0, 255]
This should fix the following error:
[...]
./lib/jxl/fields.h:44: JXL_FAILURE: Value 4294967235 too large for 8 bits
[...]
When calling API:
```
JxlEncoderSetFrameName(jxl_encoder_frame_settings, u8"é");
```
> Prevent a signed wrap-around when processing utf-8 strings

- plugins/gdk-pixbuf/CMakeLists.txt
```
xvfb-run -a ./build/plugins/gdk-pixbuf/pixbufloader_test ./plugins/gdk-pixbuf/loaders_test.cache ./third_party/testdata/jxl/blending/cropped_traffic_light.jxl
Uninitialized bytes in __interceptor_strlen at offset 10 inside [0x701000000810, 11)
==3746300==WARNING: MemorySanitizer: use-of-uninitialized-value
#0 0x7f09809c906e in _XlcAddCT (/lib/x86_64-linux-gnu/libX11.so.6+0x5306e)
#1 0x7f09809c92f7 in _XlcInitCTInfo (/lib/x86_64-linux-gnu/libX11.so.6+0x532f7)
#2 0x7f09809cf482  (/lib/x86_64-linux-gnu/libX11.so.6+0x59482)
#3 0x7f09809ceb62  (/lib/x86_64-linux-gnu/libX11.so.6+0x58b62)
#4 0x7f09809cf378 in _XlcCreateLC (/lib/x86_64-linux-gnu/libX11.so.6+0x59378)
#5 0x7f09809f0070 in _XlcUtf8Loader (/lib/x86_64-linux-gnu/libX11.so.6+0x7a070)
#6 0x7f09809d690d in _XOpenLC …
```
> Disable pixbuf test under MSAN.

- lib/extras/dec/pnm.cc
The parser was confusing a whitespace character with the actual first
pixel value.
Fixes the following test cases:
```
% convert -size 512x512 xc:#090909 tab.pam
% convert -size 512x512 xc:#202020 space.pam
% convert -size 512x512 xc:#0A0A0A lf.pam
% convert -size 512x512 xc:#0D0D0D cr.pam
```
```
% for i in tab.pam space.pam lf.pam cr.pam; do cjxl $i $i.jxl; done
Failed to read image tab.pam.
Failed to read image space.pam.
Failed to read image lf.pam.
Failed to read image cr.pam.
```
> PAM: Do not skip multiple whitespaces after `ENDHDR`

- lib/jxl/encode.cc
- lib/jxl/encode_internal.h
Frame index box needs the count of bytes in codestream box(es),
not the absolute byte position in the resulting file.
> Change position bytes to codestream bytes

- CMakeLists.txt
- lib/jxl_benchmark.cmake
- lib/jxl_tests.cmake
- tools/conformance/CMakeLists.txt
- tools/conformance/tooling_test.sh
This will allow user to configure libjxl using an existing testdata
location:
```
% cmake -DJPEGXL_TEST_DATA_PATH:PATH=/usr/share/libjxl-testdata .
```
> Provide a mechanism to override default testdata location

- lib/extras/packed_image_convert.cc
Fixes https://github.com/libjxl/libjxl/issues/1335
PNM output was always writing 8 or 16 bit data, which is of course wrong when putting a maxval in the PNM header that is not 255 or 65535.
> fix pnm output for the non-multiple-of-8 bitdepth cases

- tools/CMakeLists.txt
This will make sure that cjxl_ng is installed after a call to `make
install`.
This reverts partially commit 775d010700bc8bb752f8db3753e9e7246093758f
> Properly list `cjxl_ng` as part of the tools to be installed

- lib/jxl/encode.cc
Even if the API clearly document that the user input should be a
c-string (UTF-8), remove an undefined behavior from
JxlEncoderSetFrameName. The implementation does not make any
difference in between a NULL comment and an empty comment anyway.
[...]
Some standard library vendors, such as libstdc++, throw a
std::logic_error when a null pointer is used in the above function
calls, though not when calling std::char_traits::length(). However,
std::logic_error is not a requirement of the C++ Standard, and some
vendors (e.g., libc++ and the Microsoft Visual Studio STL) do not
implement this behavior. For portability, you should not rely on this
behavior.
[...]
Ref:
* https://wiki.sei.cmu.edu/confluence/display/cplusplus/STR51-CPP.+Do+not+attempt+to+create+a+std%3A%3Astring+from+a+null+pointer
> Do not attempt to create a std::string from a null pointer

- lib/jxl/butteraugli_wrapper.cc
- lib/jxl/decode.cc
- lib/jxl/encode.cc
- lib/threads/thread_parallel_runner.cc
While there is no reason for compiler to do something extraordinary, MSAN has concerns...
> Avoid use-after-destructor

- .github/workflows/release.yaml
Attempt to fix the failing Ubuntu 20.04 and debian sid package builds.
See also: https://github.com/actions/checkout/issues/760
> attempt to fix release build

- .github/workflows/build_test.yml
- ci.sh
The `coverage` run was running the 'fast' benchmark after uploading the coverage report, which is just taking a lot of time (the code instrumented for coverage analysis is really slow) and doesn't do anything useful.
Also updating the benchmark_xl call in fast_benchmark to take into account that the modular `q` parameter is replaced by `d` now.
> don't run fast_benchmark after coverage

- AUTHORS
- third_party/CMakeLists.txt
See:
- https://github.com/microsoft/vcpkg/pull/20011
- https://stackoverflow.com/questions/45401212/how-to-make-imported-target-global-afterwards/48390363#48390363
Fixes #1197
> Make gflags an IMPORTED GLOBAL library

- lib/extras/dec/apng.cc
Fixes https://github.com/libjxl/libjxl/issues/1330
Bumps up the maximum png chunk size from 100 MB to 1 GB.
> allow bigger png chunks

- lib/jxl/modular/transform/squeeze.cc
Drive-by: simplify division by 2:
https://godbolt.org/z/sq91EMKT8
> Avoid (temporary?) integer overflow

- lib/extras/dec/pgx.cc
- lib/extras/dec/pnm.cc
- lib/extras/packed_image.h
- lib/include/jxl/encode.h
- lib/include/jxl/types.h
- lib/jxl/butteraugli_wrapper.cc
- lib/jxl/dec_external_image.cc
- lib/jxl/dec_external_image.h
- lib/jxl/decode.cc
- lib/jxl/decode_test.cc
- lib/jxl/enc_external_image.cc
- lib/jxl/roundtrip_test.cc
- lib/jxl/test_utils.h
These two sample types are in the enum but were never fully implemented so they couldn't actually be used by applications. It probably is not a great idea to implement them either, for the following reasons:
- Supporting UINT32 as a sample type at the API boundary can give the misleading impression that JPEG XL can losslessly store uint32 samples, which is not true. The spec limits integer bitdepths to what fits in int32 (so 31-bit uint), and the current libjxl implementation uses internal float representations so it is in practice limited to 24-bit uint.
- Saving memory for 1-bit images by having a bit-packed representation at the API boundary is a somewhat futile exercise when we're still internally using 32-bit floats to represent each bit. It's also somewhat arbitrary to support bit …
> deprecate JXL_TYPE_BOOLEAN and JXL_TYPE_UINT32

- lib/jxl/quantizer-inl.h
It is one of the sketchier optimizations, as it completely ignores some
bitstream parameters, and the performance benefit is at best
questionable (<1%):
Before:
```
geomean: 9.45908 MP/s [9.41058, 9.52119]
```
After:
```
geomean: 9.37787 MP/s [9.31414, 9.45261]
```
> Remove the non-high-precision special behaviour of dequantization.

- lib/include/jxl/decode.h
The documentation was saying the opposite of how the parameter actually behaves.
> fix documentation bug in brob API

- tools/jxlinfo.c
For consistency with the usage message, make sure to check for the
trailing null byte in argv[1].
> Make sure that verbose flag is exactly `-v`

- lib/jxl/modular/transform/squeeze.cc
Same simplification as in https://github.com/libjxl/libjxl/pull/1358, but in the SIMD unsqueeze path.
It's a very tiny little bit faster this way, almost not measurable.
Before:
4064 x 2704, geomean: 17.34 MP/s [15.22, 18.43], 30 reps, 0 threads.
After:
4064 x 2704, geomean: 17.40 MP/s [15.29, 18.57], 30 reps, 0 threads.
> simplify simd unsqueeze

- lib/extras/packed_image_convert.cc
It is not reasonable to check that in image decoder - this would require
repeated ICC parsing.
> Do not crash when color type does not match ICC

- lib/jxl/dec_patch_dictionary.cc
The jxl codestream allows setting the kPatches flag to `true`, so patches will get decoded, and then signaling that num_patches = 0. This is of course silly — it's better to set the kPatches flag to `false` and not waste some bits on signaling an explicit zero — but there's nothing in the spec that forbids it, so the decoder shouldn't fail if this happens.
Of course the current libjxl encoder will not produce silly bitstreams where kPatches=true and num_patches=0, so it's not a practical problem at all at the moment.
(the alternative is explicitly disallowing this in the spec, but I don't see why that would be needed)
> don't fail to decode when num_patches is explicitly zero

- .github/workflows/build_test.yml
- lib/CMakeLists.txt
Coverage reports currently don't include jxl_test and slow tests because of some philosophical distinction between "unit tests" and "roundtrip tests" which I don't think really makes sense.
Also, when not pushing to main, no coverage report is produced (which is intended) but the instrumented code still gets built (which is a waste of time if no report is going to be produced).
> make coverage run all tests, and only build it if it's going to make a report

- tools/jxlinfo.c
~~Calling "jxlinfo --help" should provide the default help
message rather than failing with "failed to read file --help."
This fixes that behavior to work as expected.~~
This patch adds --help, --verbose, and other convenience
features, such as the ability to read multiple files with
jxlinfo.
> tools/jxlinfo: improve CLI option parsing

- lib/include/jxl/decode.h
- lib/include/jxl/encode.h
Documentation had `"XML "` while it should be `"xml "`.
Moved the description of box types you can encounter to the decode api documentation, since that is a more relevant place. In the encode api, you don't really need to know about the jxl* boxes.
Simplified/improved some descriptions.
> simplify/improve/correct box API documentation
